Repository contao/contao, pull requests merged in 2019-07, with the labels that each got.

#539 Group image sizes by theme
  core-bundle/src/Image/ImageSizes.php
  core-bundle/src/Resources/contao/controllers/BackendHelp.php
  core-bundle/src/Resources/contao/widgets/ImageSize.php
  core-bundle/tests/Image/ImageSizesTest.php
Labels: feature

#537 [RTM] Provide a configuration option to define the predefined image sizes
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/ImageSizes.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/ImageSizesTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: feature

#529 Autorotate images based on EXIF metadata
  composer.json
  core-bundle/composer.json
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/ImageFactoryInterface.php
  core-bundle/src/Image/LegacyResizer.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/languages/en/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/en/tl_layout.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Resources/contao/models/ImageSizeModel.php
  core-bundle/src/Resources/contao/templates/backend/be_popup.html5
  core-bundle/tests/Image/ImageFactoryTest.php
Labels: depends on other, feature

#540 Use annotations to tag services
  composer.json
  core-bundle/composer.json
  core-bundle/src/ContaoManager/Plugin.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/ServiceAnnotation/AbstractFragmentAnnotation.php
  core-bundle/src/ServiceAnnotation/Callback.php
  core-bundle/src/ServiceAnnotation/ContentElement.php
  core-bundle/src/ServiceAnnotation/FrontendModule.php
  core-bundle/src/ServiceAnnotation/Hook.php
  core-bundle/src/ServiceAnnotation/PickerProvider.php
  core-bundle/tests/ContaoManager/PluginTest.php
  core-bundle/tests/ServiceAnnotation/CallbackTest.php
  core-bundle/tests/ServiceAnnotation/ContentElementTest.php
  core-bundle/tests/ServiceAnnotation/FrontendModuleTest.php
  core-bundle/tests/ServiceAnnotation/HookTest.php
  core-bundle/tests/ServiceAnnotation/PickerProviderTest.php
Labels: feature

#553 Also strip the blackfire cookie
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
Labels: defect

#450 Make the insert tags in picker providers configurable
  calendar-bundle/src/Picker/EventPickerProvider.php
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/src/Picker/AbstractInsertTagPickerProvider.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/FilePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Picker/PickerConfig.php
  core-bundle/tests/Picker/ArticlePickerProviderTest.php
  core-bundle/tests/Picker/FilePickerProviderTest.php
  core-bundle/tests/Picker/PagePickerProviderTest.php
  core-bundle/tests/Picker/PickerConfigTest.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  news-bundle/src/Picker/NewsPickerProvider.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
Labels: feature

#552 Add support for image format conversion
  composer.json
  core-bundle/composer.json
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/languages/en/tl_image_size.xlf
  core-bundle/src/Resources/contao/library/Contao/Image.php
  core-bundle/src/Resources/contao/library/Contao/Picture.php
  core-bundle/src/Resources/contao/models/ImageSizeModel.php
  core-bundle/src/Resources/contao/templates/picture/picture_default.html5
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: feature

#560 Detect if WEBP is supported
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/languages/en/tl_image_size.xlf
Labels: feature

#363 [RTM] 2FA for frontend scope
  core-bundle/README.md
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/EventListener/TwoFactorFrontendListener.php
  core-bundle/src/HttpKernel/JwtManager.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/languages/en/modules.xlf
  core-bundle/src/Resources/contao/languages/en/tl_member.xlf
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/modules/ModuleTwoFactor.php
  core-bundle/src/Resources/contao/templates/modules/mod_login.html5
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
  core-bundle/src/Resources/contao/themes/flexible/icons/member_two_factor.svg
  core-bundle/src/Resources/contao/themes/flexible/icons/member_two_factor_.svg
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Logout/LogoutHandler.php
  core-bundle/src/Security/TwoFactor/BackendFormRenderer.php
  core-bundle/src/Security/TwoFactor/Provider.php
  core-bundle/tests/Controller/FrontendControllerTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/TwoFactorFrontendListenerTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/TwoFactor/BackendFormRendererTest.php
  core-bundle/tests/Security/TwoFactor/ProviderTest.php
  manager-bundle/src/Resources/skeleton/app/security.yml
Labels: feature

#562 Add css class to link insert tag (#547)
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: defect

#565 Do not use session to store the last visited page
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/modules/ModuleLogout.php
  core-bundle/src/Resources/contao/pages/PageLogout.php
Labels: defect

#568 [RFC] Fix endless redirect
  core-bundle/src/EventListener/TwoFactorFrontendListener.php
  core-bundle/tests/EventListener/TwoFactorFrontendListenerTest.php
Labels: defect

#561 Add lightboxPicture in addition to imageHref
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: feature

#570 Fix redirect behaviour without 401 autoforward page
  core-bundle/src/EventListener/TwoFactorFrontendListener.php
  core-bundle/tests/EventListener/TwoFactorFrontendListenerTest.php
Labels: defect

#544 Track profiler messages in the Contao translator
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/TranslationDataCollectorPass.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Translation/DataCollectorTranslator.php
  core-bundle/src/Translation/Translator.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/TranslationDataCollectorPassTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Translation/DataCollectorTranslatorTest.php
Labels: feature, tests missing

#566 Config directory should be in root instead of app folder
  core-bundle/README.md
  installation-bundle/src/Config/ParameterDumper.php
  installation-bundle/src/DependencyInjection/ContaoInstallationExtension.php
  installation-bundle/src/Resources/translations/messages.en.xlf
  manager-bundle/src/Api/ManagerConfig.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  manager-bundle/src/Resources/skeleton/config/config_dev.yml
  manager-bundle/src/Resources/skeleton/config/config_prod.yml
  manager-bundle/src/Resources/skeleton/config/parameters.yml
  manager-bundle/src/Resources/skeleton/config/security.yml
  manager-bundle/src/Routing/RouteLoader.php
  manager-bundle/tests/Api/ManagerConfigTest.php
  manager-bundle/tests/Fixtures/Api/config/contao-manager.yml
  manager-bundle/tests/Fixtures/HttpKernel/WithConfigDevYml/config/config_dev.yml
  manager-bundle/tests/Fixtures/HttpKernel/WithConfigYml/config/config.yml
  manager-bundle/tests/Fixtures/HttpKernel/WithConfigsYml/config/config.yml
  manager-bundle/tests/Fixtures/HttpKernel/WithConfigsYml/config/config_prod.yml
  manager-bundle/tests/Fixtures/HttpKernel/WithParametersYml/config/parameters.yml
Labels: feature

#525 Handle exceptions in the initialize.php
  core-bundle/src/Controller/InitializeController.php
Labels: defect

#489 Changed wrong table name in comment on permissions
  faq-bundle/src/Resources/contao/dca/tl_faq_category.php
Labels: defect

#472 Remove a page's search index entries when its alias is changed
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: defect

#571 Use the jumpTo value from post data if set
  core-bundle/src/Resources/contao/dca/tl_form.php
Labels: defect

#594 Also make response private if an Authorization header is present
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/tests/EventListener/MakeResponsePrivateListenerTest.php
Labels: defect

#591 Prevent unnecessary DB query to fetch frontend preview username
  core-bundle/src/Resources/contao/classes/RebuildIndex.php
Labels: defect

#590 Disallow config folder as upload path
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: defect

#595 Use Symfony Security to check user access
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
Labels: defect

#596 Do not show pretty error screens for admin exceptions
  core-bundle/src/EventListener/ExceptionConverterListener.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/Exception/IncompleteInstallationException.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/languages/en/exception.xlf
  core-bundle/src/Resources/views/Error/forward_page_not_found.html.twig
  core-bundle/src/Resources/views/Error/incomplete_installation.html.twig
  core-bundle/src/Resources/views/Error/insecure_installation.html.twig
  core-bundle/src/Resources/views/Error/no_active_page_found.html.twig
  core-bundle/src/Resources/views/Error/no_layout_specified.html.twig
  core-bundle/src/Resources/views/Error/no_root_page_found.html.twig
  core-bundle/tests/EventListener/ExceptionConverterListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Functional/RoutingTest.php
Labels: defect

#611 Optimize http cache configuration
  manager-bundle/src/HttpKernel/ContaoCache.php
Labels: defect

#609 Use the security helper
  calendar-bundle/src/Picker/EventPickerProvider.php
  calendar-bundle/src/Resources/config/services.yml
  calendar-bundle/tests/DependencyInjection/ContaoCalendarExtensionTest.php
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/src/EventListener/BackendLocaleListener.php
  core-bundle/src/EventListener/BackendMenuListener.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/EventListener/StoreRefererListener.php
  core-bundle/src/EventListener/SwitchUserListener.php
  core-bundle/src/EventListener/UserSessionListener.php
  core-bundle/src/Picker/AbstractPickerProvider.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/FilePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/BackendLocaleListenerTest.php
  core-bundle/tests/EventListener/BackendMenuListenerTest.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/EventListener/StoreRefererListenerTest.php
  core-bundle/tests/EventListener/SwitchUserListenerTest.php
  core-bundle/tests/EventListener/UserSessionListenerTest.php
  core-bundle/tests/Picker/ArticlePickerProviderTest.php
  core-bundle/tests/Picker/FilePickerProviderTest.php
  core-bundle/tests/Picker/PagePickerProviderTest.php
  core-bundle/tests/Picker/PickerBuilderTest.php
  core-bundle/tests/Picker/PickerTest.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  faq-bundle/src/Resources/config/services.yml
  faq-bundle/tests/DependencyInjection/ContaoFaqExtensionTest.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/src/Resources/config/listener.yml
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
  news-bundle/src/Picker/NewsPickerProvider.php
  news-bundle/src/Resources/config/services.yml
  news-bundle/tests/DependencyInjection/ContaoNewsExtensionTest.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
Labels: defect

#602 Use custom console application to optimize arguments
  manager-bundle/bin/contao-console
  manager-bundle/src/Console/ContaoApplication.php
Labels: defect

#613 Do not use sqlite during read operations for performance reasons
  manager-bundle/src/HttpKernel/ContaoCache.php
Labels: defect

#612 Remove interfaces according to contao/image#57
  composer.json
  core-bundle/composer.json
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/ImageFactoryInterface.php
  core-bundle/src/Image/LegacyResizer.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Image/PictureFactoryInterface.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: defect

#615 Fix time sensitive unit test
  core-bundle/tests/Command/ResizeImagesCommandTest.php
Labels: defect

#616 Disable zlib.output_compression on CLI
  manager-bundle/bin/contao-api
  manager-bundle/bin/contao-console
Labels: defect
