Repository contao/contao, pull requests merged in 2020-03, with the labels that each got.

#1451 Add a conflict for PhpStan 0.12.12
  composer.json
Labels: CI

#1447 Re-add folderUrl setting to the root page
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/config/default.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_settings.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/languages/en/tl_settings.xlf
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Routing/Matcher/LegacyMatcher.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Contao/RoutingTest.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Routing/Matcher/LegacyMatcherTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: feature

#1453 Fix length of alias fields
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
Labels: defect

#1445 Retry failed schema diff migrations
  core-bundle/src/Command/MigrateCommand.php
Labels: defect

#1444 Make sure log messages are in proper CSV format
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/tests/Crawl/Monolog/CrawlCsvLogHandlerTest.php
Labels: defect

#1439 Fix missing image sizes with numeric theme names
  core-bundle/src/Image/ImageSizes.php
Labels: defect

#1458 Always set host and language when generating navigation
  core-bundle/src/Resources/contao/modules/ModuleNavigation.php
  core-bundle/src/Resources/contao/modules/ModuleSitemap.php
Labels: defect

#1450 Use native font stack in layout.html.twig
  core-bundle/src/Resources/views/Error/layout.html.twig
Labels: defect

#1460 Flex is now a tool of setup-php
  .github/workflows/ci.yml
Labels: CI

#1462 Flex is now a tool of setup-php
  .github/workflows/ci.yml
Labels: CI

#1455 Do not expose page ID in JSON LD context
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: defect

#1457 Use context prefix for json-ld schema
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Search/Document.php
  core-bundle/tests/Search/DocumentTest.php
Labels: defect

#1464 Do not allow slashes at the beginning and end of a folder alias
  core-bundle/src/Resources/contao/library/Contao/Validator.php
Labels: defect

#1424 Revert the document.write() changes
  core-bundle/src/Resources/contao/templates/backend/be_ace.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyFlash.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
Labels: defect

#1437 Translate the "show preview toolbar" title
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
Labels: defect

#1477 Remove the PhpStan conflict again
  composer.json
Labels: CI

#1478 Fix PHPStan issue in combination with functional tests (see #1475)
  core-bundle/tests/Functional/app/config/config_phpstan.yml
Labels: defect

#1476 Enable PHPStan level 4
  composer.json
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/src/Cron/Cron.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/HttpKernel/Header/HeaderStorageInterface.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/src/Security/Authentication/Provider/AuthenticationProvider.php
  core-bundle/tests/DependencyInjection/Compiler/DataContainerCallbackPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterHookListenersPassTest.php
  core-bundle/tests/Event/ImageSizesEventTest.php
  core-bundle/tests/Session/LazySessionAccessTest.php
  phpstan.neon.dist
Labels: feature

#1475 Register custom types in functional tests
  core-bundle/tests/Functional/app/config/config_test.yml
Labels: defect

#1481 Update the GitHub issue templates
  .github/ISSUE_TEMPLATE/1_Bug_report.md
  .github/ISSUE_TEMPLATE/2_Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CI

#1482 Merge branch '4.9' into master
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Image/ImageSizes.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/views/Error/layout.html.twig
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
  core-bundle/src/Search/Document.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/Crawl/Monolog/CrawlCsvLogHandlerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Functional/app/config/config_phpstan.yml
  core-bundle/tests/Functional/app/config/config_test.yml
  core-bundle/tests/Search/DocumentTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
Labels: release

#1485 Run PHPStan on level 4 in CI
  .github/workflows/ci.yml
Labels: feature

#1480 Deprecate helper functions
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/classes/Events.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/classes/StyleSheets.php
  core-bundle/src/Resources/contao/classes/Theme.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/controllers/BackendConfirm.php
  core-bundle/src/Resources/contao/controllers/BackendFile.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/controllers/BackendPage.php
  core-bundle/src/Resources/contao/controllers/BackendPopup.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/elements/ContentGallery.php
  core-bundle/src/Resources/contao/elements/ContentHyperlink.php
  core-bundle/src/Resources/contao/elements/ContentToplink.php
  core-bundle/src/Resources/contao/forms/FormFileUpload.php
  core-bundle/src/Resources/contao/helper/functions.php
  core-bundle/src/Resources/contao/library/Contao/ArrayUtil.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Database.php
  core-bundle/src/Resources/contao/library/Contao/Database/Updater.php
  core-bundle/src/Resources/contao/library/Contao/Files.php
  core-bundle/src/Resources/contao/library/Contao/Folder.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Pagination.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/modules/ModuleNavigation.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/templates/backend/be_csv_import.html5
  core-bundle/src/Resources/contao/widgets/FileSelector.php
  core-bundle/src/Resources/contao/widgets/FileTree.php
  core-bundle/src/Resources/contao/widgets/PageTree.php
  core-bundle/src/Resources/contao/widgets/Picker.php
  core-bundle/tests/Contao/ArrayUtilTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqList.php
  installation-bundle/src/Database/Version330Update.php
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterList.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
Labels: feature

#1494 Remove the codecov token again
  .github/workflows/ci.yml
Labels: CI

#1495 Remove the codecov token again
  .github/workflows/ci.yml
Labels: CI

#1496 Remove the codecov token again
  .github/workflows/ci.yml
Labels: CI

#1483 [RFC] Add Psalm, fixed errorLevel 7
  .github/workflows/ci.yml
  README.md
  composer.json
  core-bundle/src/EventListener/DataContainerCallbackListener.php
  core-bundle/src/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServices.php
  monorepo.yml
  psalm.xml
Labels: feature

#1493 Adjust the JSON-LD data in the default indexer test
  core-bundle/src/Search/Document.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: defect

#1468 Sorting for fileTree and pageTree without orderField
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Migration/Version410/OrderFieldMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/models/LayoutModel.php
  core-bundle/src/Resources/contao/models/ModuleModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/widgets/FileTree.php
  core-bundle/src/Resources/contao/widgets/PageTree.php
  core-bundle/src/Resources/contao/widgets/Picker.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: feature

#1501 Rename the routing.yml to routes.yml
  core-bundle/README.md
  core-bundle/src/ContaoManager/Plugin.php
  core-bundle/src/Resources/config/routes.yml
  core-bundle/tests/Functional/app/config/config_test.yml
  installation-bundle/src/ContaoManager/Plugin.php
  installation-bundle/src/Resources/config/routes.yml
Labels: feature

#1514 Ignore the routing test in Psalm
  psalm.xml
Labels: defect

#1513 Fix permission check for toggle element
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: defect

#1506 Convert functional test SQL to YAML
  composer.json
  core-bundle/composer.json
  core-bundle/tests/Fixtures/Functional/routing.yml
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Functional/app/Resources/contao_test.sql
Labels: feature

#1520 Optimize MSC.twoFactorBackupCodesExplain
  core-bundle/src/Resources/contao/languages/en/default.xlf
Labels: defect

#1532 Fixed some Piwik/Matomo cookie regex
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
Labels: defect

#1526 Add id to filter box for tl_module (see #974)
  core-bundle/src/Resources/contao/dca/tl_module.php
Labels: feature

#1503 Correctly handle URL suffix when redirecting page IDs
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
Labels: defect

#1533 Correctly sort if both root pages are fallback
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: defect

#1534 Port the 'handle URL suffix when redirecting page IDs' changes
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
Labels: defect

#1182 Allow clearing the model registry
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/library/Contao/Model/Registry.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
Labels: defect

#1518 Split routing functional tests into separate YAML files
  core-bundle/tests/Fixtures/Functional/Routing/domain-with-port.yml
  core-bundle/tests/Fixtures/Functional/Routing/domain-without-hostname.yml
  core-bundle/tests/Fixtures/Functional/Routing/language-sorting.yml
  core-bundle/tests/Fixtures/Functional/Routing/news.yml
  core-bundle/tests/Fixtures/Functional/Routing/root-with-folder-urls.yml
  core-bundle/tests/Fixtures/Functional/Routing/root-with-home.yml
  core-bundle/tests/Fixtures/Functional/Routing/root-with-index.yml
  core-bundle/tests/Fixtures/Functional/Routing/root-with-special-chars.yml
  core-bundle/tests/Fixtures/Functional/Routing/root-without-fallback-language.yml
  core-bundle/tests/Fixtures/Functional/Routing/same-domain-root-with-index.yml
  core-bundle/tests/Fixtures/Functional/Routing/same-domain-root.yml
  core-bundle/tests/Fixtures/Functional/Routing/theme.yml
  core-bundle/tests/Fixtures/Functional/routing.yml
  core-bundle/tests/Functional/RoutingTest.php
Labels: feature

#1540 Only create the MySQL database after starting the service
  .github/workflows/ci.yml
Labels: CI

#1547 Check if DBAL connection is available from .env configuration
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/InstallTool.php
  installation-bundle/src/Resources/translations/messages.en.xlf
  installation-bundle/src/Resources/views/misconfigured_database_url.html.twig
Labels: defect

#1546 Widen typehint of argument
  installation-bundle/src/EventListener/InitializeApplicationListener.php
Labels: defect

#1525 Remove string type hint as there can be an array value
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
Labels: defect

#1541 Show label instead of ID in picker widget
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: defect

#1551 Allow svg in favicons
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: defect

#1562 Fix the CI tests on Windows
  .github/workflows/ci.yml
Labels: CI

#1555 Allow to compare against any template if a prefix is unknown
  core-bundle/src/Resources/contao/dca/tl_templates.php
Labels: defect

#1556 Do not call static methods via a child class
  core-bundle/src/Resources/contao/widgets/SectionWizard.php
Labels: defect

#1559 Only index successful responses
  core-bundle/src/EventListener/AddToSearchIndexListener.php
  core-bundle/tests/EventListener/AddToSearchIndexListenerTest.php
Labels: defect

#1561 Show "-" instead of "0" if no related record can be loaded
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: defect

#1564 Fix duplicate version numbers
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/dca/tl_version.php
Labels: defect

#1566 Correctly check the permissions to create new FAQs
  faq-bundle/src/Resources/contao/dca/tl_faq.php
Labels: defect

#1567 Consistently use "news feed" and "calendar feed" instead of "RSS feed"
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/en/tl_user.xlf
  news-bundle/src/Resources/contao/languages/en/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/en/tl_user.xlf
Labels: defect

#1568 Add a missing space when generating global buttons
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: defect

#1570 Use a fixed width for the Ajax loading box
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/src/main.css
Labels: defect

#1571 Hide unsynchronized folders in the picker
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: defect

#1572 Fix the "insert version" query
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: defect

#1554 Bugfix/favicon content type
  core-bundle/src/Controller/FaviconController.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Fixtures/images/favicon.svg
Labels: defect

#1574 Fixed xliff glitch
  core-bundle/src/Resources/contao/languages/en/tl_settings.xlf
Labels: defect

#1580 Fix the tl_content.listtype DCA definition
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: defect

#1581 Disable the "switch user" button if it would impersonate the original user
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/dca/tl_user.php
  manager-bundle/composer.json
Labels: defect

#1582 Remove the default preview bar datalist option
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
Labels: defect

#1584 Show "-" if the device family is "Other"
  core-bundle/src/Entity/TrustedDevice.php
Labels: defect

#1586 Correctly check for loaded languages when adding the default labels
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
Labels: defect

#1579 Fix the preview bar alignment
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: defect

#1591 Show all files in the template editor
  core-bundle/src/Resources/contao/dca/tl_templates.php
Labels: defect

#1593 Re-add the "edit meta" label in the news and calendar bundles
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar_events.xlf
  news-bundle/src/Resources/contao/languages/en/modules.xlf
  news-bundle/src/Resources/contao/languages/en/tl_news.xlf
Labels: defect

#1595 Use the correct page title on the back end dashboard page
  core-bundle/src/Resources/contao/controllers/BackendMain.php
Labels: defect

#1542 Keep the sorting of the selected IDs for actions
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: defect

#1597 Correctly check whether a group is allowed to import themes
  core-bundle/src/Resources/contao/dca/tl_user_group.php
Labels: defect

#1596 Handle the "toggle nodes" command in the main back end method
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
Labels: defect

#1592 Fix the picker in the meta wizard
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
Labels: defect

#1560 Add a 5 seconds timeout to the CAPTCHA widget
  core-bundle/src/Resources/contao/templates/forms/form_captcha.html5
Labels: defect

#1549 Dynamically configure the TokenChecker service
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: defect

#1598 Hide the metadata fields if a news/event points to an external source
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar_events.xlf
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/languages/en/tl_news.xlf
Labels: defect

#1602 Upgrade yamllint and adjust the YAML files
  .github/workflows/ci.yml
  .yamllint
  calendar-bundle/src/Resources/config/listener.yml
  core-bundle/.github/workflows/autoclose.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Functional/app/config/config_test.yml
  installation-bundle/src/Resources/config/listener.yml
  installation-bundle/src/Resources/config/services.yml
  manager-bundle/src/Resources/config/listener.yml
  manager-bundle/src/Resources/config/services.yml
  manager-bundle/src/Resources/skeleton/config/config.yml
  monorepo.yml
  news-bundle/src/Resources/config/listener.yml
Labels: CI

#1599 Fixed broken URIs not being reported as error in search index subscriber
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
Labels: defect

#1600 Correctly filter subscriber specific crawl logs
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/tests/Crawl/Monolog/CrawlCsvLogHandlerTest.php
Labels: defect
