Repository contao/contao, pull requests merged in 2020-02, with the labels that each got.

#1266 Allow underscores in the hostname in the Environment class
  core-bundle/src/Resources/contao/library/Contao/Environment.php
Labels: defect

#1268 Urlencode the path returned by the "file::uuid" insert tag
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: defect

#1284 Add z-index:1 to the paste hint
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/public/core.min.js
  package-lock.json
Labels: defect

#1283 Use wikimedia/less.php instead of oyejorge/less.php
  composer.json
  core-bundle/composer.json
Labels: defect

#1282 Correctly publish new folders
  core-bundle/src/Resources/contao/dca/tl_files.php
Labels: defect

#1289 Improve post update or install CLI hint
  manager-bundle/src/Composer/ScriptHandler.php
Labels: defect

#1257 DCA: allow definition of filter without placeholder values
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: defect

#1275 Move the PreviewAuthenticationListener to the core-bundle
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  manager-bundle/src/Resources/config/listener.yml
  manager-bundle/tests/DependencyInjection/ContaoManagerExtensionTest.php
Labels: defect

#1267 Fix possible null value in AuthenticationSuccessHandler
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
Labels: defect

#1286 Fix the front end preview URLs in the back end
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
Labels: defect

#1291 Hide the member widget if searching protected sites is disabled
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/templates/backend/be_crawl.html5
Labels: defect

#1293 Update the back end keyboard shortcuts link
  core-bundle/src/Resources/contao/languages/en/default.xlf
Labels: defect

#1296 Correctly find unactivated members
  core-bundle/src/Resources/contao/models/MemberModel.php
Labels: defect

#1294 Fix checking for binary strings in the version comparison
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: defect

#1140 Fix compatibility with knplabs/knp-time-bundle 1.11.0
  core-bundle/src/Translation/Translator.php
Labels: defect

#1304 Use GitHub actions for CI
  .appveyor.yml
  .gitattributes
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  README.md
  codecov.yml
  composer.json
  core-bundle/tests/HttpKernel/ControllerResolverTest.php
Labels: defect

#1215 Adjust the text line height
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: defect

#1305 Also test PHP 7.4
  .github/workflows/ci.yml
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Security/Authentication/Token/FrontendPreviewToken.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/AddToSearchIndexListenerTest.php
  core-bundle/tests/Security/Authentication/Token/FrontendPreviewTokenTest.php
  core-bundle/tests/Session/LazySessionAccessTest.php
Labels: defect

#1306 Remove the PHP 7.4 workaround in the ci.yml file
  .github/workflows/ci.yml
Labels: defect

#1251 Handle array SQL definitions in version comparison
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: defect

#1082 Check if token has proper roles
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
Labels: defect

#1292 Roll back "back end switch" route name
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
Labels: defect

#1308 Version 4.9.0-RC2
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/de/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/es/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/it/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/lv/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/ru/modules.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_member_group.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_user.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_user_group.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_maintenance.xlf
  newsletter-bundle/src/Resources/contao/languages/de/tl_newsletter.xlf
Labels: release

#1302 Fix the top navigation overflow
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/src/main.css
Labels: defect

#1316 Make the "preload" attribute optional
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/templates/elements/ce_player.html5
Labels: defect

#1317 Correctly show the field names in the diff view
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: defect

#1318 Correctly save unsynchronized files and folders
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: defect

#1319 Show the field name if there is no label
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: defect

#1295 Handle removed search indexers
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/CrawlerPass.php
  core-bundle/src/DependencyInjection/Compiler/SearchIndexerPass.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/CrawlerPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/SearchIndexerPassTest.php
Labels: defect

#1320 Replace "recovery codes" with "backup codes"
  core-bundle/src/Resources/contao/templates/backend/be_two_factor.html5
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: defect

#1322 Clear trusted devices when disabling 2fa
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
Labels: defect

#1324 Sort the back end menu items alphabetically by label
  core-bundle/src/Resources/contao/classes/BackendUser.php
Labels: defect

#1327 Fix rendering the picker preview
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: defect

#1299 Fix several trusted device issues
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/Entity/TrustedDevice.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/modules/ModuleTwoFactor.php
  core-bundle/src/Resources/contao/templates/backend/be_two_factor.html5
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Authentication/Provider/AuthenticationProvider.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  core-bundle/tests/Security/TwoFactor/TrustedDeviceManagerTest.php
Labels: defect

#1323 Adjust the SERP widget to the Google search results
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/SerpPreview.php
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
Labels: defect

#1287 Don’t use fetchAll and enable initialization from array
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Fixtures/Database/DoctrineArrayStatement.php
Labels: defect

#1315 Fix the initial table sorting in the "table" content element
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/elements/ContentTable.php
  core-bundle/src/Resources/contao/templates/elements/ce_table.html5
  core-bundle/src/Resources/contao/templates/jquery/j_tablesort.html5
Labels: defect

#1329 Replace document.write() in the back end templates
  core-bundle/src/Resources/contao/templates/backend/be_ace.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyFlash.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
Labels: defect

#1332 Replace document.write() in the back end templates
  core-bundle/src/Resources/contao/templates/backend/be_ace.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
Labels: defect

#1331 Correctly set predefined image sizes in the news and calendar bundle
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: defect

#1335 Correctly highlight phrases in the search results
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Fixtures/Database/DoctrineArrayStatement.php
Labels: defect

#1250 Use correct schema.org data for search indexing meta data
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Search/Document.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: defect, up for discussion

#1336 Make the contao.search.indexer service public
  core-bundle/src/DependencyInjection/Compiler/SearchIndexerPass.php
  core-bundle/tests/DependencyInjection/Compiler/SearchIndexerPassTest.php
Labels: defect

#1333 Remove the setTimeout() wrapper from the be_tiny* templates
  core-bundle/src/Resources/contao/templates/backend/be_tinyFlash.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
Labels: defect

#1340 Fix issues found by the PhpStorm code inspector
  .github/workflows/ci.yml
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/DependencyInjection/Compiler/SearchIndexerPass.php
  installation-bundle/src/InstallTool.php
Labels: CI

#1321 Generate catch all routes for 404 pages
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Routing/Matcher/PublishedFilter.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Routing/Matcher/PublishedFilterTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
Labels: defect

#1342 Merge branch '4.8' into 4.9
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/templates/backend/be_ace.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
  core-bundle/src/Resources/contao/templates/elements/ce_player.html5
  core-bundle/src/Resources/contao/templates/jquery/j_tablesort.html5
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Routing/Matcher/PublishedFilter.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Routing/Matcher/PublishedFilterTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: release

#1348 Correctly align the wizard icon
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: defect

#1349 Version 4.9.0
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/de/tl_maintenance.xlf
Labels: release

#1354 Hide the 2FA fields in the back end info modal
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_user.php
Labels: defect

#1364 Fix the login screen CSS
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/login.min.css
Labels: defect

#1359 Fix the PictureFactoryInterface::create() type hint
  core-bundle/src/Image/PictureFactoryInterface.php
Labels: defect

#1372 Correctly save new template folders
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: defect

#1373 Fix the Ajax visibility toggle in the site structure
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: defect

#1374 Show the correct help text for the 2FA verification field
  core-bundle/src/Resources/contao/templates/backend/be_two_factor.html5
Labels: defect

#1375 Simulate active state of the debug button in debug mode
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
Labels: defect

#1376 Adjust the login screen again
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/login.min.css
Labels: defect

#1377 Fix the getAttributesFromDca() type hint
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: defect

#1370 Make sure the subdirectory in the tmp folder exists
  core-bundle/src/Resources/contao/classes/Crawl.php
Labels: defect

#1369 Clear dev cache
  manager-bundle/src/Composer/ScriptHandler.php
Labels: defect

#1385 Bugfix/show dns warning on crawl cli
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/tests/Command/CrawlCommandTest.php
Labels: defect

#1396 Do not show the current URI in progress bar title on crawl command
  core-bundle/src/Command/CrawlCommand.php
Labels: defect

#1412 Start the MySQL service before running the functional tests
  .github/workflows/ci.yml
Labels: CI

#1413 Correctly calculate the crawler progress
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: defect

#1418 Add a better DNS check in the site structure
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: defect

#1417 Fix uploading files into mounted folders for regular users
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: defect

#1416 Correctly check if a folder has been renamed
  core-bundle/src/Resources/contao/dca/tl_files.php
Labels: defect

#1419 Always append the current URL on redirect
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/tests/Security/Authentication/AuthenticationEntryPointTest.php
Labels: defect

#1411 Skip orphan pages in the route provider
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: defect

#1421 Update the composer run documentation in the README.md file
  README.md
  composer.json
Labels: defect

#1420 Handle the "no JSON-LD found" case separately from the "noSearch" case
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: defect

#1423 Revert the document.write() changes
  core-bundle/src/Resources/contao/templates/backend/be_ace.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
Labels: defect

#1427 Merge branch '4.9' into master
  .github/workflows/ci.yml
  README.md
  composer.json
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Image/PictureFactoryInterface.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/templates/backend/be_ace.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
  core-bundle/src/Resources/contao/templates/backend/be_two_factor.html5
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/login.min.css
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
  core-bundle/tests/Security/Authentication/AuthenticationEntryPointTest.php
  manager-bundle/src/Composer/ScriptHandler.php
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
Labels: release
