Repository contao/contao, pull requests merged in 2020-04, with the labels that each got.

#1609 Remove the pullreminders badge from the README file
  README.md
Labels: CI

#1610 Remove the pullreminders badge from the README file
  README.md
Labels: CI

#1589 Explanation text tl_page.guests.1
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
Labels: defect

#1611 Ensure that the login icons are always visible in Firefox
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/src/login.css
Labels: defect

#1410 Correctly execute kernel events for initialize.php
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/EventListener/InitializeControllerListener.php
  core-bundle/src/EventListener/MergeHttpHeadersListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/Controller/InitializeControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/MergeHttpHeadersListenerTest.php
Labels: defect

#1619 Upstream/4.4 4.9
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/en/tl_user.xlf
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/EventListener/InitializeControllerListener.php
  core-bundle/src/EventListener/MergeHttpHeadersListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/dca/tl_version.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/templates/backend/be_ace.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
  core-bundle/src/Resources/contao/templates/forms/form_captcha.html5
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/login.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/SectionWizard.php
  core-bundle/tests/Controller/InitializeControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/MergeHttpHeadersListenerTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  installation-bundle/src/Resources/translations/messages.cs.xlf
  installation-bundle/src/Resources/translations/messages.de.xlf
  installation-bundle/src/Resources/translations/messages.es.xlf
  installation-bundle/src/Resources/translations/messages.fr.xlf
  installation-bundle/src/Resources/translations/messages.it.xlf
  installation-bundle/src/Resources/translations/messages.ja.xlf
  installation-bundle/src/Resources/translations/messages.nl.xlf
  installation-bundle/src/Resources/translations/messages.ru.xlf
  installation-bundle/src/Resources/translations/messages.zh.xlf
  news-bundle/src/Resources/contao/languages/en/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/en/tl_user.xlf
Labels: release

#1608 Increase the split button breakpoint
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
Labels: defect

#1613 Fix the Contao toolbar labels
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
Labels: defect

#1614 Fix comment in MakeResponsePrivateListener
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
Labels: defect

#1615 Add additional Google Analytics Cookies to StripCookiesSubscriber
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
Labels: defect

#1590 Change how to count records in RobotsTxtListener
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
Labels: defect

#1623 Also add z-index to the .cto-toolbar__open element
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: defect

#1634 Verify TOTP with a window of 1 for better UX
  core-bundle/src/Security/TwoFactor/Authenticator.php
  core-bundle/tests/Security/TwoFactor/AuthenticatorTest.php
Labels: defect

#1640 Return the request argument if it's of the correct type
  core-bundle/src/HttpKernel/ModelArgumentResolver.php
  core-bundle/tests/HttpKernel/ModelArgumentResolverTest.php
Labels: defect

#1642 Amend explanation tl_maintenance_jobs.crawl_queue
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
Labels: defect

#1647 Suppress undefined docblock class errors for the Stringable interface
  psalm.xml
Labels: CI

#1653 Use psalm/plugin-symfony instead of seferov/symfony-psalm-plugin
  .github/workflows/ci.yml
  composer.json
  psalm.xml
Labels: CI

#1683 Fix the CI chain
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Picker/PickerTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/Fixtures/HttpKernel/WithAppNamespace/.gitignore
  manager-bundle/tests/Fixtures/HttpKernel/WithInvalidNamespace/.gitignore
  manager-bundle/tests/Fixtures/HttpKernel/WithInvalidNamespace/src/EventListener/FoobarListener.php
  manager-bundle/tests/Fixtures/HttpKernel/WithMixedNamespace/.gitignore
  manager-bundle/tests/Fixtures/HttpKernel/WithMixedNamespace/src/EventListener/FoobarListener.php
  manager-bundle/tests/Fixtures/HttpKernel/WithMixedNamespace/src/EventListener/InvalidListener.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
Labels: CI

#1681 Also analyze the YAML files in the CI chain
  .github/workflows/ci.yml
  calendar-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  faq-bundle/src/Resources/config/services.yml
  installation-bundle/src/Resources/config/listener.yml
  manager-bundle/src/Resources/skeleton/config/config_dev.yml
  news-bundle/src/Resources/config/services.yml
Labels: CI

#1415 add 'rel="noreferrer noopener"' to external targets
  calendar-bundle/src/Resources/contao/classes/Events.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  comments-bundle/src/Resources/contao/templates/comments/com_default.html5
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
  core-bundle/src/Resources/contao/elements/ContentHyperlink.php
  core-bundle/src/Resources/contao/elements/ContentVimeo.php
  core-bundle/src/Resources/contao/elements/ContentYouTube.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/exception.xlf
  core-bundle/src/Resources/contao/languages/en/explain.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/templates/rss/rss_default.html5
  core-bundle/src/Resources/contao/templates/rss/rss_items_only.html5
  core-bundle/src/Resources/views/Collector/contao.html.twig
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: defect

#1686 Fix the CI chain
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Monolog/ContaoTableHandlerTest.php
Labels: CI

#1678 Improve search query performance
  core-bundle/src/Resources/contao/library/Contao/Search.php
Labels: defect

#1687 Do not randomly encode email addresses
  core-bundle/src/Resources/contao/forms/FormCaptcha.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
Labels: defect
