Repository contao/contao, pull requests merged in 2020-12, with the labels that each got.

#2532 Trigger the onload_callback when featuring news/events
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: bug

#2534 Backport the doctrine-cache-bundle changes
  composer.json
  core-bundle/composer.json
  core-bundle/src/ContaoManager/Plugin.php
  core-bundle/tests/ContaoManager/PluginTest.php
  manager-bundle/composer.json
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  manager-bundle/src/Resources/skeleton/config/services.yml
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#2535 Add compatibility with PHP 8
  .github/workflows/ci.yml
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/library/Contao/GdImage.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Contao/GdImageTest.php
  core-bundle/tests/Functional/RoutingTest.php
  faq-bundle/composer.json
  installation-bundle/composer.json
  listing-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  newsletter-bundle/composer.json
Labels: bug

#2541 Update the changelog and the language files
  CHANGELOG.md
  calendar-bundle/src/Resources/contao/languages/fr/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  comments-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/fr/countries.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/exception.xlf
  core-bundle/src/Resources/contao/languages/fr/explain.xlf
  core-bundle/src/Resources/contao/languages/fr/modules.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_settings.xlf
  faq-bundle/src/Resources/contao/languages/fr/tl_faq_category.xlf
  installation-bundle/src/Resources/translations/messages.fr.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter.xlf
Labels: release

#2543 Add a missing PHPStan dependency
  composer.json
  monorepo.yml
Labels: CI

#2542 Merge branch '4.4' into 4.9
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: release

#2544 Fix issues found by the PhpStorm code inspector
  calendar-bundle/src/DependencyInjection/ContaoCalendarExtension.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/README.md
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/Config/Loader/PhpFileLoader.php
  core-bundle/src/Config/Loader/XliffFileLoader.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/src/Doctrine/DBAL/Types/BinaryStringType.php
  core-bundle/src/Monolog/ContaoTableProcessor.php
  core-bundle/src/Resources/contao/classes/BackendModule.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/forms/FormTextArea.php
  core-bundle/src/Resources/contao/forms/FormTextField.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/library/Contao/Email.php
  core-bundle/src/Resources/contao/library/Contao/GdImage.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/Request.php
  core-bundle/src/Resources/contao/library/Contao/SortedIterator.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Routing/Matcher/UrlMatcher.php
  core-bundle/src/Session/Attribute/ArrayAttributeBag.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Contao/GdImageTest.php
  core-bundle/tests/Contao/SearchTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
  core-bundle/tests/Fixtures/Database/DoctrineArrayStatement.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/ImageSizesTest.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Search/DocumentTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Authentication/ContaoLoginAuthenticationListenerTest.php
  core-bundle/tests/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServicesTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  faq-bundle/src/DependencyInjection/ContaoFaqExtension.php
  installation-bundle/src/ContaoManager/Plugin.php
  listing-bundle/README.md
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  news-bundle/src/DependencyInjection/ContaoNewsExtension.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
Labels: CI

#2506 Add global page model for fragments
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/HttpKernel/ModelArgumentResolver.php
  core-bundle/tests/HttpKernel/ModelArgumentResolverTest.php
Labels: bug

#2521 Do not try to generate fragments for generated fragments
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
Labels: bug

#2527 Allow caption to be a textarea rather than a text field
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
Labels: bug

#2545 Move migrations to core bundle
  core-bundle/src/Migration/Version400/Version400Update.php
  core-bundle/src/Migration/Version401/Version410Update.php
  core-bundle/src/Migration/Version403/Version430Update.php
  core-bundle/src/Migration/Version404/Version440Update.php
  core-bundle/src/Migration/Version404/Version447Update.php
  core-bundle/src/Migration/Version405/Version450Update.php
  core-bundle/src/Migration/Version406/Version460Update.php
  core-bundle/src/Migration/Version407/Version470Update.php
  core-bundle/src/Migration/Version408/Version480Update.php
  core-bundle/src/Resources/config/migrations.yml
  installation-bundle/src/Database/Version330Update.php
  installation-bundle/src/Database/Version350Update.php
  installation-bundle/src/DependencyInjection/ContaoInstallationExtension.php
  installation-bundle/src/Resources/config/migrations.yml
  installation-bundle/src/Resources/config/services.yml
Labels: bug

#2547 Fix compatibility with scssphp 1.4
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
Labels: bug

#2548 Run the CS fixer
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
Labels: CI

#2550 Do not index preview URLs for searching
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
  manager-bundle/src/Resources/skeleton/web/preview.php
Labels: bug

#2540 Correctly load the DCA labels
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
Labels: bug

#2551 Fix the cache tag invalidation
  calendar-bundle/src/Resources/contao/classes/Events.php
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqList.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
  news-bundle/src/Resources/contao/modules/ModuleNewsArchive.php
  news-bundle/src/Resources/contao/modules/ModuleNewsList.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterList.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
Labels: bug

#2553 Strip port numbers from root page domains
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#2560 Clean up before the release
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Resources/contao/classes/StyleSheets.php
  core-bundle/src/Resources/contao/classes/Theme.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Image.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Translation/DataCollectorTranslator.php
  core-bundle/tests/Contao/SearchTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Functional/RoutingTest.php
  manager-bundle/src/HttpKernel/JwtManager.php
  manager-bundle/tests/ContaoManager/PluginTest.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: CI

#2561 Update the changelog and the language files
  CHANGELOG.md
  calendar-bundle/src/Resources/contao/languages/da/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_calendar_events.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_calendar_feed.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_article.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  faq-bundle/src/Resources/contao/languages/da/tl_faq_category.xlf
  faq-bundle/src/Resources/contao/languages/fr/tl_faq.xlf
  faq-bundle/src/Resources/contao/languages/fr/tl_faq_category.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_news.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_news_feed.xlf
  newsletter-bundle/src/Resources/contao/languages/da/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter_channel.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter_recipients.xlf
Labels: release

#2564 Clean up after the upstream merge
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
  core-bundle/src/EventListener/DataContainer/PageTypeOptionsListener.php
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/src/ServiceAnnotation/Page.php
  core-bundle/src/Util/SimpleTokenParser.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Command/ResizeImagesCommandTest.php
  core-bundle/tests/EventListener/FilterPageTypeListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/ImageResultTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  newsletter-bundle/src/DependencyInjection/ContaoNewsletterExtension.php
Labels: CI

#2565 Update the changelog and the language files
  CHANGELOG.md
  calendar-bundle/src/Resources/contao/languages/da/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/fr/modules.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_calendar_feed.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_layout.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_user_group.xlf
  comments-bundle/src/Resources/contao/languages/fr/modules.xlf
  comments-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/fr/languages.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_article.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_image_size_item.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_log.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_member.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_member_group.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_style_sheet.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_theme.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_user_group.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_page.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_page.xlf
  faq-bundle/src/Resources/contao/languages/da/tl_faq_category.xlf
  listing-bundle/src/Resources/contao/languages/fr/modules.xlf
  news-bundle/src/Resources/contao/languages/fr/default.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_layout.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_news_feed.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_user_group.xlf
  newsletter-bundle/src/Resources/contao/languages/da/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/default.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/modules.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_member.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_user_group.xlf
Labels: release

#2572 Revert #2476 + work around for PHPStan
  core-bundle/src/ServiceAnnotation/Callback.php
  core-bundle/src/ServiceAnnotation/Hook.php
  core-bundle/src/ServiceAnnotation/PickerProvider.php
  core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php
  core-bundle/tests/EventListener/InsertTags/DateListenerTest.php
Labels: bug

#2581 Symfony\...\InvalidArgumentException in commands
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/tests/Command/CrawlCommandTest.php
Labels: bug

#2583 Combine multiple substr() calls
  calendar-bundle/src/Resources/contao/modules/ModuleEventMenu.php
Labels: CI

#2584 Use composer-bin-plugin to isolate the dev dependencies
  .github/workflows/ci.yml
  .gitignore
  .yamllint
  README.md
  calendar-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  manager-bundle/composer.json
  monorepo.yml
  news-bundle/composer.json
  phpstan.neon.dist
  tools/ecs/composer.json
  tools/monorepo/composer.json
  tools/phpstan/composer.json
Labels: CI

#2582 Use composer-bin-plugin to isolate the dev dependencies
  .github/workflows/ci.yml
  .gitignore
  .yamllint
  README.md
  calendar-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  installation-bundle/composer.json
  manager-bundle/composer.json
  monorepo.yml
  news-bundle/composer.json
  phpstan.neon.dist
  psalm.xml
  tools/ecs/composer.json
  tools/monorepo/composer.json
  tools/phpstan/composer.json
  tools/psalm/composer.json
Labels: CI

#2588 Do not use SQL default for empty value
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#2594 Fix two more E_WARNING issues
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/widgets/ModuleWizard.php
Labels: bug

#2595 Fix the OrderFieldMigration class
  core-bundle/src/Migration/Version410/OrderFieldMigration.php
Labels: bug

#2599 Fix more E_WARNING issues
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/widgets/ModuleWizard.php
  core-bundle/src/Resources/contao/widgets/SectionWizard.php
  core-bundle/src/Resources/contao/widgets/TableWizard.php
  installation-bundle/src/EventListener/InitializeApplicationListener.php
Labels: bug

#2593 Replace highlight.js with highlight.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/Migration/Version411/RemoveJsHighlightMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/elements/ContentCode.php
  core-bundle/src/Resources/contao/templates/js/js_highlight.html5
Labels: feature

#2602 Update the CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: bug

#2603 Update the CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: bug

#2601 Cast numeric identifier in FigureBuilder
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#2604 Update the CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: bug

#2600 Remove the Composer script handler
  core-bundle/composer.json
  core-bundle/src/Composer/ScriptHandler.php
  core-bundle/tests/Composer/ScriptHandlerTest.php
  manager-bundle/composer.json
Labels: feature
