Repository contao/contao, pull requests merged in 2020-10, with the labels that each got.

#2360 Correctly detect unknown options
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/widgets/CheckBox.php
  core-bundle/src/Resources/contao/widgets/CheckBoxWizard.php
  core-bundle/src/Resources/contao/widgets/ImageSize.php
  core-bundle/src/Resources/contao/widgets/RadioButton.php
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
Labels: bug

#2385 Check submitInput() again after validation
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#2361 Prevent using page aliases that could be page IDs
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
Labels: bug

#2376 Add a title tag callback to the SERP preview
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/widgets/SerpPreview.php
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: bug

#2388 Ignore logout URL if no user is present
  core-bundle/src/Resources/contao/pages/PageLogout.php
Labels: bug

#2400 Update contao/easy-coding-standard to version 3
  .github/workflows/ci.yml
  composer.json
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/EventListener/InsecureInstallationListenerTest.php
  core-bundle/tests/EventListener/UserSessionListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/ImageSizesTest.php
  core-bundle/tests/Security/User/UserCheckerTest.php
  monorepo.yml
Labels: CI

#2363 Reset the KEY_BLOCK_SIZE when migrating mysql engine and row format
  installation-bundle/src/Database/Installer.php
  installation-bundle/tests/Database/InstallerTest.php
Labels: bug

#2372 Remove existing tags from annotations that could be arrays
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/ServiceAnnotation/Page.php
Labels: bug

#2265 Purge the search tables directly
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
Labels: bug

#2337 Fix asset url handling in image studio
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Image/Studio/ImageResult.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  core-bundle/tests/Image/Studio/ImageResultTest.php
Labels: bug

#2379 Add image_container class to default figure template
  core-bundle/src/Resources/views/Image/Studio/figure.html.twig
Labels: feature

#2399 Remove last username from session after use
  core-bundle/src/EventListener/ClearSessionDataListener.php
Labels: bug

#2397 Check allowed page types
  core-bundle/src/EventListener/FilterPageTypeListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/FilterPageTypeListenerTest.php
Labels: bug

#2284 Replace phpunit/token-stream with nikic/php-parser
  composer.json
  core-bundle/composer.json
  core-bundle/src/Config/Loader/PhpFileLoader.php
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
  core-bundle/tests/Config/Loader/PhpFileLoaderTest.php
Labels: bug

#2403 Resolve private services in the ContaoCoreExtensionTest class
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#2406 Update the changelog
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
Labels: release

#2407 Merge branch '4.4' into 4.9
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/widgets/CheckBox.php
  core-bundle/src/Resources/contao/widgets/CheckBoxWizard.php
  core-bundle/src/Resources/contao/widgets/ImageSize.php
  core-bundle/src/Resources/contao/widgets/RadioButton.php
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
Labels: release

#2408 Update the changelog and the language files
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
Labels: release

#2341 Fix SimpleTokenParser BC
  core-bundle/src/Util/SimpleTokenParser.php
  core-bundle/tests/Util/SimpleTokenParserTest.php
Labels: bug

#2409 Merge branch '4.9' into 4.10
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/EventListener/ClearSessionDataListener.php
  core-bundle/src/Image/LegacyResizer.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/elements/ContentMedia.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/pages/PageLogout.php
  core-bundle/src/Resources/contao/templates/image/image.html5
  core-bundle/src/Resources/contao/widgets/CheckBox.php
  core-bundle/src/Resources/contao/widgets/CheckBoxWizard.php
  core-bundle/src/Resources/contao/widgets/ImageSize.php
  core-bundle/src/Resources/contao/widgets/RadioButton.php
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
  core-bundle/src/Resources/contao/widgets/SerpPreview.php
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  installation-bundle/src/Database/Installer.php
  installation-bundle/tests/Database/InstallerTest.php
  manager-bundle/src/Resources/skeleton/system/initialize.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
Labels: release

#2410 Port the numeric alias changes to the PageUrlListener class
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
Labels: bug

#2411 Update the changelog and the language files
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
Labels: release

#2412 Merge branch '4.10' into master
  .github/workflows/ci.yml
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  composer.json
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/EventListener/ClearSessionDataListener.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/EventListener/FilterPageTypeListener.php
  core-bundle/src/Image/LegacyResizer.php
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Image/Studio/ImageResult.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/elements/ContentMedia.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/pages/PageLogout.php
  core-bundle/src/Resources/contao/templates/image/image.html5
  core-bundle/src/Resources/contao/widgets/CheckBox.php
  core-bundle/src/Resources/contao/widgets/CheckBoxWizard.php
  core-bundle/src/Resources/contao/widgets/ImageSize.php
  core-bundle/src/Resources/contao/widgets/RadioButton.php
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
  core-bundle/src/Resources/contao/widgets/SerpPreview.php
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
  core-bundle/src/Resources/views/Image/Studio/figure.html.twig
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/ServiceAnnotation/Page.php
  core-bundle/src/Util/SimpleTokenParser.php
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/EventListener/FilterPageTypeListenerTest.php
  core-bundle/tests/EventListener/InsecureInstallationListenerTest.php
  core-bundle/tests/EventListener/UserSessionListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/ImageSizesTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  core-bundle/tests/Image/Studio/ImageResultTest.php
  core-bundle/tests/Security/User/UserCheckerTest.php
  core-bundle/tests/Util/SimpleTokenParserTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  installation-bundle/src/Database/Installer.php
  installation-bundle/tests/Database/InstallerTest.php
  manager-bundle/src/Resources/skeleton/system/initialize.php
  monorepo.yml
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
Labels: release

#2416 Remove the Content-Length header when modifying the response
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
Labels: bug

#2404 Remove the "add language" menu from the meta wizard
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_files.xlf
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: feature

#2420 Fix issues found by the PhpStorm code inspector
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Util/SimpleTokenParser.php
  core-bundle/tests/Contao/SearchTest.php
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
Labels: CI

#2423 Correctly show the xlabel in the checkbox wizard
  core-bundle/src/Resources/contao/widgets/CheckBox.php
Labels: bug

#2368 Add createIfDeferred to ImageResult
  core-bundle/src/Image/Studio/ImageResult.php
  core-bundle/src/Image/Studio/Studio.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Image/Studio/ImageResultTest.php
  core-bundle/tests/Image/Studio/StudioTest.php
Labels: feature

#2051 Allow editing Twig files in template editor
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: feature

#2419 Fix unknown option when creating or editing error pages
  core-bundle/src/EventListener/FilterPageTypeListener.php
  core-bundle/tests/EventListener/FilterPageTypeListenerTest.php
Labels: bug

#2417 Register globals in fragment pass
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/MapFragmentsToGlobalsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/Fragment/Reference/ContentElementReference.php
  core-bundle/src/Fragment/Reference/FrontendModuleReference.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/MapFragmentsToGlobalsPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
Labels: bug

#2431 Remove the Google web fonts field from the page layout
  core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/languages/en/tl_layout.xlf
  core-bundle/src/Resources/contao/models/LayoutModel.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
Labels: feature

#2430 Correctly generate the HTML module
  core-bundle/src/Resources/contao/modules/ModuleHtml.php
Labels: bug

#2434 Correctly move root level pages to the top
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#2432 Use meaningful values for the "autocomplete" attributes
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/forms/FormPassword.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/src/Resources/contao/templates/backend/be_login_two_factor.html5
  core-bundle/src/Resources/contao/templates/backend/be_password.html5
  core-bundle/src/Resources/contao/templates/backend/be_two_factor.html5
  core-bundle/src/Resources/contao/templates/forms/form_password.html5
  core-bundle/src/Resources/contao/templates/modules/mod_login.html5
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
  core-bundle/src/Resources/contao/widgets/Password.php
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
  installation-bundle/src/Resources/views/login.html.twig
  installation-bundle/src/Resources/views/password.html.twig
Labels: feature

#2295 Dynamically fetch the sitemap XML files
  calendar-bundle/src/Resources/contao/dca/tl_calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  calendar-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/Event/ContaoCoreEvents.php
  core-bundle/src/Event/SitemapEvent.php
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/dca/tl_content.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/dca/tl_news_archive.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
Labels: feature

#2427 Use binary comparison when looking for aliases in the database
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  faq-bundle/src/Resources/contao/models/FaqModel.php
  news-bundle/src/Resources/contao/models/NewsModel.php
  newsletter-bundle/src/Resources/contao/models/NewsletterModel.php
Labels: bug

#2442 Update the changelog and the language files
  CHANGELOG.md
  calendar-bundle/src/Resources/contao/languages/fr/default.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_calendar_events.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  comments-bundle/src/Resources/contao/languages/fr/default.xlf
  comments-bundle/src/Resources/contao/languages/fr/tl_comments.xlf
  comments-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/fr/countries.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/exception.xlf
  core-bundle/src/Resources/contao/languages/fr/explain.xlf
  core-bundle/src/Resources/contao/languages/fr/modules.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_article.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_files.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_image_size_item.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_member.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_member_group.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_opt_in.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_opt_in_related.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_style.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_style_sheet.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_templates.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_theme.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_undo.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_user_group.xlf
  faq-bundle/src/Resources/contao/languages/fr/tl_faq.xlf
  faq-bundle/src/Resources/contao/languages/fr/tl_faq_category.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.fr.xlf
  listing-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.fr.xlf
  news-bundle/src/Resources/contao/languages/fr/modules.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_news.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter_channel.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter_recipients.xlf
Labels: release

#2443 Merge branch '4.9' into 4.10
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/MapFragmentsToGlobalsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/Fragment/Reference/ContentElementReference.php
  core-bundle/src/Fragment/Reference/FrontendModuleReference.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleHtml.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/MapFragmentsToGlobalsPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
  faq-bundle/src/Resources/contao/models/FaqModel.php
  news-bundle/src/Resources/contao/models/NewsModel.php
  newsletter-bundle/src/Resources/contao/models/NewsletterModel.php
Labels: release

#2444 Update the changelog and the language files
  CHANGELOG.md
  calendar-bundle/src/Resources/contao/languages/fr/default.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_calendar_events.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  calendar-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  comments-bundle/src/Resources/contao/languages/fr/default.xlf
  comments-bundle/src/Resources/contao/languages/fr/tl_comments.xlf
  comments-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/fr/countries.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/exception.xlf
  core-bundle/src/Resources/contao/languages/fr/explain.xlf
  core-bundle/src/Resources/contao/languages/fr/modules.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_article.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_files.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_image_size_item.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_member.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_member_group.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_opt_in.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_opt_in_related.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_style.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_style_sheet.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_templates.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_theme.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_undo.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_user_group.xlf
  faq-bundle/src/Resources/contao/languages/fr/tl_faq.xlf
  faq-bundle/src/Resources/contao/languages/fr/tl_faq_category.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.fr.xlf
  listing-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.fr.xlf
  news-bundle/src/Resources/contao/languages/fr/modules.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_news.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/fr/tl_user.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter_channel.xlf
  newsletter-bundle/src/Resources/contao/languages/fr/tl_newsletter_recipients.xlf
Labels: release

#2445 Merge branch '4.10' into master
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/MapFragmentsToGlobalsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/EventListener/FilterPageTypeListener.php
  core-bundle/src/Fragment/Reference/ContentElementReference.php
  core-bundle/src/Fragment/Reference/FrontendModuleReference.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleHtml.php
  core-bundle/src/Resources/contao/widgets/CheckBox.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/MapFragmentsToGlobalsPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
  core-bundle/tests/EventListener/FilterPageTypeListenerTest.php
  faq-bundle/src/Resources/contao/models/FaqModel.php
  news-bundle/src/Resources/contao/models/NewsModel.php
  newsletter-bundle/src/Resources/contao/models/NewsletterModel.php
Labels: release

#2433 Do not use all:unset with the preview toolbar
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: bug

#2453 Evaluate unknown simple tokens
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug

#2321 Open doctrine/* constraints for 4.9
  composer.json
  core-bundle/composer.json
  core-bundle/src/Doctrine/Schema/MigrationsSchemaProvider.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/src/Repository/RememberMeRepository.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  manager-bundle/composer.json
Labels: bug

#2462 Remove hard dependency on PDO (4.4)
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/Resources/contao-manager/doctrine.yml
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#2469 Remove the FormModel type hint in the Hybrid class
  core-bundle/src/Resources/contao/classes/Hybrid.php
Labels: bug

#2470 Handle Composer 2 when reading the installed.json file
  core-bundle/src/DependencyInjection/Compiler/AddPackagesPass.php
  core-bundle/tests/DependencyInjection/Compiler/AddPackagesPassTest.php
  core-bundle/tests/Fixtures/vendor/composer/installedv2.json
Labels: bug

#2465 Fix routing issue with multiple domains and languages
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Functional/app/Resources/issue-2465.sql
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: bug

#2472 Fix the CI chain
  composer.json
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
  monorepo.yml
Labels: CI

#2463 Remove hard dependency on PDO
  .github/workflows/ci.yml
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#2471 Call the onload_callback in the "password" and "change password" modules
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
Labels: bug

#2473 Add a Cache-Control header to the back end response
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
Labels: bug

#2476 Fix the CI chain
  core-bundle/src/ServiceAnnotation/Callback.php
  core-bundle/src/ServiceAnnotation/Hook.php
  core-bundle/src/ServiceAnnotation/PickerProvider.php
Labels: CI

#2314 Add missing ResizeOptions to the studio classes
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Image/Studio/ImageResult.php
  core-bundle/src/Image/Studio/LightboxResult.php
  core-bundle/src/Image/Studio/Studio.php
  core-bundle/tests/Fixtures/Image/PictureFactoryWithRandomArgumentStub.php
  core-bundle/tests/Fixtures/Image/PictureFactoryWithResizeOptionsStub.php
  core-bundle/tests/Fixtures/Image/PictureFactoryWithoutResizeOptionsStub.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/ImageResultTest.php
  core-bundle/tests/Image/Studio/LightboxResultTest.php
Labels: bug

#2474 Correctly apply the CSS classes in the content module
  core-bundle/src/Resources/contao/elements/ContentModule.php
Labels: bug
