Repository contao/contao, pull requests merged in 2020-05, with the labels that each got.

#1685 Skip the initializeSystem hook if the temp folder does not yet exist
  core-bundle/src/Framework/ContaoFramework.php
Labels: defect

#1688 Remove the X-Mailer header
  core-bundle/src/Resources/contao/library/Contao/Email.php
Labels: defect

#1673 Do not update the search index if contao itself is crawling
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/tests/Crawl/Escargot/FactoryTest.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
Labels: defect

#1670 Fix the search indexer page detection
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: defect

#1668 Fix broken link checker
  core-bundle/src/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriber.php
  core-bundle/tests/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
Labels: defect

#1663 Fix playerAspect default value
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/tests/Functional/app/Resources/contao_test.sql
Labels: defect

#1658 Add Contao Manager cookie to the cookie blacklist
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
Labels: defect

#1638 Correctly check if search panel is active
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: defect

#1628 Update comment of FrontendController::checkCookiesAction
  core-bundle/src/Controller/FrontendController.php
Labels: defect

#1625 Fixed wrong CSRF token storage being wired
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: defect

#1693 Fix the CI chain
  core-bundle/src/Resources/config/services.yml
Labels: CI

#1691 Add the translation domain in the installation controller
  installation-bundle/src/Controller/InstallationController.php
Labels: defect

#1692 Skip the preview redirect if the preview script is not set
  core-bundle/src/Controller/BackendPreviewController.php
Labels: defect

#1694 Handle invalid language codes in the meta wizard
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: defect

#1651 Execute schema diff queries in the correct order
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/tests/Command/MigrateCommandTest.php
  installation-bundle/src/Database/Installer.php
Labels: defect

#1690 Skip the temp folder check if there is no initialization hook
  core-bundle/src/Framework/ContaoFramework.php
Labels: defect

#1689 Use array_key_exists() in the Database\Result class
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
Labels: defect

#1698 Fetch tables to check the database connection
  manager-bundle/src/ContaoManager/Plugin.php
Labels: defect

#1700 Set "information_schema_stats_expiry=0" in MySQL 8
  core-bundle/src/Resources/contao/library/Contao/Database.php
Labels: defect

#1704 Deprecate the "group" option in the query builder
  core-bundle/src/Resources/contao/library/Contao/Model/QueryBuilder.php
Labels: defect

#1713 Ignore the /var folder in the core bundle
  core-bundle/.gitignore
Labels: defect

#1714 Add a "rawValue" property to the TextArea class
  core-bundle/src/Resources/contao/forms/FormTextArea.php
Labels: defect

#1711 Fix fixed position of toolbar elements
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: defect

#1712 Remove the broken storeFrontendReferer() method
  core-bundle/src/EventListener/StoreRefererListener.php
  core-bundle/tests/EventListener/StoreRefererListenerTest.php
Labels: defect

#1715 Re-add the redirect in the BackendUser::authenticate() method
  core-bundle/src/Resources/contao/classes/BackendUser.php
Labels: defect

#1717 Update the PHPStan configuration
  composer.json
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Command/DebugFragmentsCommand.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Composer/ScriptHandlerTest.php
  core-bundle/tests/Contao/CombinerTest.php
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/Contao/PictureTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  monorepo.yml
  phpstan.neon.dist
Labels: CI

#1726 Fix the links to contao.org in the exceptions.xlf file
  core-bundle/src/Resources/contao/languages/en/exception.xlf
Labels: defect

#1727 Move the meta data fields back up in the news/events module
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar_events.xlf
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/languages/en/tl_news.xlf
Labels: defect

#1728 Do not flush the template output buffer
  core-bundle/src/Resources/contao/library/Contao/Template.php
Labels: defect

#1732 Redirect if a news/event has an external target and is called via the default URL
  calendar-bundle/src/Resources/contao/classes/Events.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/templates/events/event_full.html5
  calendar-bundle/src/Resources/contao/templates/events/event_list.html5
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
Labels: defect

#1733 Fix the indentation in the event_list.html5 template
  calendar-bundle/src/Resources/contao/templates/events/event_list.html5
Labels: defect

#1701 Change deprecated-message to a more clearer sentence
  core-bundle/src/Command/AbstractLockedCommand.php
Labels: defect

#1729 Always show the default template in the drop-down menu
  calendar-bundle/src/Resources/contao/languages/en/tl_module.xlf
  comments-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/languages/en/tl_article.xlf
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_form.xlf
  core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  listing-bundle/src/Resources/contao/languages/en/tl_module.xlf
  news-bundle/src/Resources/contao/languages/en/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/en/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/en/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/en/tl_newsletter_channel.xlf
Labels: defect

#1736 Fix a double "rel" tag in the com_default.htm5 template
  comments-bundle/src/Resources/contao/templates/comments/com_default.html5
Labels: defect

#1737 Merge branch '4.4' into 4.9
  calendar-bundle/src/Resources/contao/classes/Events.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/forms/FormCaptcha.php
  core-bundle/src/Resources/contao/forms/FormTextArea.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/exception.xlf
  core-bundle/src/Resources/contao/languages/en/explain.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Database.php
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
  core-bundle/src/Resources/contao/library/Contao/Email.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Model/QueryBuilder.php
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/views/Collector/contao.html.twig
  manager-bundle/src/ContaoManager/Plugin.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: release

#1738 Re-add the page ID to the JSON-LD context
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: defect

#1699 Ignore minval/maxval in checkbox/radio/select fields
  core-bundle/src/Resources/contao/forms/FormCheckBox.php
  core-bundle/src/Resources/contao/forms/FormRadioButton.php
  core-bundle/src/Resources/contao/forms/FormSelectMenu.php
Labels: defect

#1740 Rename "security question" to "spam protection"
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar.xlf
  comments-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  faq-bundle/src/Resources/contao/languages/en/tl_faq_category.xlf
  news-bundle/src/Resources/contao/languages/en/tl_news_archive.xlf
Labels: defect

#1743 Correctly check for duplicate input parameters
  core-bundle/src/Routing/Enhancer/InputEnhancer.php
  core-bundle/tests/Routing/Enhancer/InputEnhancerTest.php
Labels: defect

#1742 Fix notices for empty database result sets
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
  core-bundle/tests/Contao/Database/ResultTest.php
Labels: defect

#1745 Replace ocramius/package-versions with composer/package-versions-deprecated
  composer.json
  core-bundle/composer.json
Labels: defect

#1741 Fix notices for empty database result sets
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
  core-bundle/tests/Contao/Database/ResultTest.php
Labels: bug

#1509 Support Symfony Expression Language in Simple Tokens
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: feature

#1650 Always use the regular icon if page type has no icon
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: feature

#1761 Use createResult method in CeAccessMigration
  core-bundle/src/Migration/Version409/CeAccessMigration.php
Labels: bug
