Repository contao/contao, pull requests merged in 2020-07, with the labels that each got.

#1824 Fix back end layout problems in various browsers
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/src/basic.css
  core-bundle/src/Resources/contao/themes/flexible/src/main.css
Labels: bug

#1829 Replace symfony/swiftmailer-bundle with symfony/mailer
  composer.json
  core-bundle/composer.json
  core-bundle/src/ContaoManager/Plugin.php
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
  core-bundle/src/Resources/contao/library/Contao/Email.php
  core-bundle/tests/ContaoManager/PluginTest.php
  core-bundle/tests/DependencyInjection/Compiler/MakeServicesPublicPassTest.php
  core-bundle/tests/Functional/app/AppKernel.php
  manager-bundle/composer.json
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  manager-bundle/tests/Command/DebugPluginsCommandTest.php
  manager-bundle/tests/ContaoManager/PluginTest.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: feature

#1891 Rename all occurrences of rootDir to projectDir
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/Config/Loader/XliffFileLoader.php
  core-bundle/src/DependencyInjection/Compiler/AddResourcesPathsPass.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/HttpKernel/Bundle/ContaoModuleBundle.php
  core-bundle/src/Image/LegacyResizer.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/FileUpload.php
  core-bundle/src/Resources/contao/classes/PurgeData.php
  core-bundle/src/Resources/contao/controllers/BackendPopup.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
  core-bundle/src/Resources/contao/forms/FormFileUpload.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/ClassLoader.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Database/Updater.php
  core-bundle/src/Resources/contao/library/Contao/Dbafs.php
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
  core-bundle/src/Resources/contao/library/Contao/Image.php
  core-bundle/src/Resources/contao/library/Contao/Picture.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php
  core-bundle/src/Resources/contao/models/FilesModel.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/widgets/FileSelector.php
  core-bundle/src/Resources/contao/widgets/FileTree.php
  core-bundle/src/Util/SymlinkUtil.php
  core-bundle/tests/Command/SymlinksCommandTest.php
  core-bundle/tests/Contao/EnvironmentTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  installation-bundle/src/Config/ParameterDumper.php
  installation-bundle/src/InstallTool.php
  manager-bundle/src/Command/InstallWebDirCommand.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/src/Routing/RouteLoader.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#1892 Fix the visibility of the EnvironmentTest ::$projectDir property
  core-bundle/tests/Contao/EnvironmentTest.php
Labels: bug

#1798 Do not use blacklist and whitelist
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
  core-bundle/src/EventListener/HttpCache/StripQueryParametersSubscriber.php
  core-bundle/tests/EventListener/HttpCache/StripCookiesSubscriberTest.php
  core-bundle/tests/EventListener/HttpCache/StripQueryParametersSubscriberTest.php
  manager-bundle/src/HttpKernel/ContaoCache.php
  manager-bundle/tests/HttpKernel/ContaoCacheTest.php
  newsletter-bundle/src/DependencyInjection/ContaoNewsletterExtension.php
  newsletter-bundle/src/Migration/Version410/DenyListMigration.php
  newsletter-bundle/src/Resources/config/migrations.yml
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_deny_list.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
  newsletter-bundle/src/Resources/contao/languages/en/default.xlf
  newsletter-bundle/src/Resources/contao/models/NewsletterBlacklistModel.php
  newsletter-bundle/src/Resources/contao/models/NewsletterDenyListModel.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: feature

#1896 Allow ContainerBuilder with different configuration
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: feature

#1890 Allow more recent Doctrine versions in the composer.json
  composer.json
  core-bundle/composer.json
  core-bundle/src/Doctrine/Schema/MigrationsSchemaProvider.php
Labels: feature

#1895 Support project dir instead of root dir for ContaoModuleBundle
  core-bundle/src/HttpKernel/Bundle/ContaoModuleBundle.php
Labels: bug

#1897 Validate the composer.json files independently from the monorepo split
  .github/workflows/ci.yml
  core-bundle/composer.json
  manager-bundle/composer.json
Labels: CI

#1898 Validate the composer.json files independently from the monorepo split
  .github/workflows/ci.yml
Labels: CI

#1899 Validate the composer.json files independently from the monorepo split
  .github/workflows/ci.yml
Labels: CI

#1865 Store the crawl logs in a unique subfolder per installation
  core-bundle/src/Resources/contao/classes/Crawl.php
Labels: bug

#1900 Use createResult method in OrderFieldMigration
  core-bundle/src/Migration/Version410/OrderFieldMigration.php
Labels: bug

#1893 Allow new major versions of third-party packages
  composer.json
  core-bundle/composer.json
  manager-bundle/composer.json
Labels: feature

#1904 Remove id column from search index table
  core-bundle/src/Resources/contao/dca/tl_search_index.php
Labels: feature

#1911 Remove incorrect BC layer
  manager-bundle/src/HttpKernel/ContaoCache.php
Labels: bug

#1908 Renamed Piwik to Matomo + updated Tracking Code #690
  core-bundle/src/Resources/contao/languages/en/tl_layout.xlf
  core-bundle/src/Resources/contao/templates/analytics/analytics_matomo.html5
  core-bundle/src/Resources/contao/templates/analytics/analytics_piwik.html5
Labels: bug

#1915 Fix two left-over path util usages
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Composer/ScriptHandler.php
Labels: bug

#1917 Fix issues found by the PhpStorm code inspector
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/Composer/ScriptHandler.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/Util/SymlinkUtil.php
  core-bundle/tests/Composer/ScriptHandlerTest.php
  core-bundle/tests/Image/ImageSizesTest.php
  core-bundle/tests/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServicesTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  installation-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/Composer/ScriptHandler.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
Labels: CI

#1914 Remove symfony/monolog-bundle dependency from functional tests
  core-bundle/tests/Functional/app/AppKernel.php
Labels: bug

#1918 Revert old StringUtil logic (but compare on normalized strings)
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug

#1916 Replace the deprecated Doctrine cache bundle
  composer.json
  core-bundle/composer.json
  core-bundle/src/ContaoManager/Plugin.php
  core-bundle/tests/ContaoManager/PluginTest.php
  manager-bundle/composer.json
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  manager-bundle/src/Resources/skeleton/config/services.yml
  manager-bundle/tests/ContaoManager/PluginTest.php
  manager-bundle/tests/Fixtures/output/registered_bundles.out
Labels: bug

#1910 Use filesize units translation in search results
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/templates/search/search_default.html5
Labels: bug

#1601 Correct user to member or visitor
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar.xlf
  comments-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/modules.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  faq-bundle/src/Resources/contao/languages/en/tl_faq_category.xlf
  news-bundle/src/Resources/contao/languages/en/tl_news_archive.xlf
Labels: bug

#1667 Add SCSS Source Maps in Debug-Mode
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
Labels: bug

#1868 Fix tcpdf symlink for monorepo (backport of #158)
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/tests/Command/InstallCommandTest.php
Labels: bug

#1903 The security bundle may only be loaded after the framework bundle
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#1919 Revert the alphabetical sorting of the back end menu
  core-bundle/src/Resources/contao/classes/BackendUser.php
Labels: bug

#1894 Revert the $rootDir changes to the ContaoModuleBundle class
  core-bundle/src/HttpKernel/Bundle/ContaoModuleBundle.php
Labels: bug

#1920 Fix the toggle visibility checks
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_content.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_content.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: bug

#1922 Merge branch '4.4' into 4.9
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar.xlf
  comments-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/modules.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/templates/search/search_default.html5
  faq-bundle/src/Resources/contao/languages/en/tl_faq_category.xlf
  news-bundle/src/Resources/contao/languages/en/tl_news_archive.xlf
Labels: release

#1927 Fix the unit tests
  core-bundle/composer.json
  core-bundle/tests/Functional/app/AppKernel.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
Labels: bug

#1864 Extend voter for all backend user permissions
  calendar-bundle/src/Security/ContaoCalendarPermissions.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/tests/Security/Voter/BackendAccessVoterTest.php
  faq-bundle/src/Security/ContaoFaqPermissions.php
  news-bundle/src/Security/ContaoNewsPermissions.php
  newsletter-bundle/src/Security/ContaoNewsletterPermissions.php
Labels: feature

#1756 Simple token parser service
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Util/SimpleTokenExpressionLanguage.php
  core-bundle/src/Util/SimpleTokenParser.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Fixtures/IteratorAggregateStub.php
  core-bundle/tests/Util/SimpleTokenParserTest.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: feature

#1768 Provide format_date & convert_date insert tag
  core-bundle/src/EventListener/InsertTags/DateListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/InsertTags/DateListenerTest.php
Labels: feature

#1930 Replace lexik/maintenance-bundle with our Symfony 5 compatible fork
  composer.json
  core-bundle/composer.json
  manager-bundle/composer.json
Labels: bug

#1931 Fix merge error
  core-bundle/src/Controller/ImagesController.php
Labels: bug

#1932 Improve error message for unsupported image formats
  core-bundle/src/Image/LegacyResizer.php
Labels: bug

#1936 Remove @param Something&MockObject annotations
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Command/ResizeImagesCommandTest.php
  core-bundle/tests/Command/UserPasswordCommandTest.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/EventListener/UserSessionListenerTest.php
  core-bundle/tests/Fragment/FragmentHandlerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
  core-bundle/tests/OptIn/OptInTokenTest.php
  core-bundle/tests/Routing/Matcher/LanguageFilterTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  core-bundle/tests/Twig/Extension/ContaoTemplateExtensionTest.php
  core-bundle/tests/Util/SimpleTokenParserTest.php
Labels: bug

#1753 Image studio
  core-bundle/src/Exception/InvalidResourceException.php
  core-bundle/src/File/MetaData.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Image/Studio/ImageResult.php
  core-bundle/src/Image/Studio/LightBoxResult.php
  core-bundle/src/Image/Studio/Studio.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/FilesModel.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/File/MetaDataTest.php
  core-bundle/tests/Fixtures/files/public/bar.jpg
  core-bundle/tests/Fixtures/files/public/foo.jpg
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  core-bundle/tests/Image/Studio/ImageResultTest.php
  core-bundle/tests/Image/Studio/LightBoxResultTest.php
  core-bundle/tests/Image/Studio/StudioTest.php
Labels: feature

#1938 Fix comment
  faq-bundle/src/Resources/contao/dca/tl_user.php
  news-bundle/src/Resources/contao/dca/tl_user.php
  newsletter-bundle/src/Resources/contao/dca/tl_user.php
Labels: bug

#1463 Add user commands
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Command/UserListCommand.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/tests/Command/UserCreateCommandTest.php
  core-bundle/tests/Command/UserListCommandTest.php
Labels: feature

#1830 Make configured mailer transports selectable in the back end
  composer.json
  core-bundle/composer.json
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/AddAvailableTransportsPass.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Mailer/AvailableTransports.php
  core-bundle/src/Mailer/ContaoMailer.php
  core-bundle/src/Mailer/TransportConfig.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/languages/en/tl_form.xlf
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/models/FormModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddAvailableTransportsPassTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Mailer/AvailableTransportsTest.php
  core-bundle/tests/Mailer/ContaoMailerTest.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_channel.php
  newsletter-bundle/src/Resources/contao/languages/en/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/en/tl_newsletter_channel.xlf
  newsletter-bundle/src/Resources/contao/models/NewsletterChannelModel.php
  newsletter-bundle/src/Resources/contao/models/NewsletterModel.php
Labels: feature

#1924 Unlock phpstan level 5
  .github/workflows/ci.yml
  composer.json
  core-bundle/src/Composer/ScriptHandler.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/DependencyInjection/Compiler/MapFragmentsToGlobalsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/src/Resources/contao/library/Contao/Picture.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/src/Routing/UrlGenerator.php
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/EventListener/SubrequestCacheSubscriberTest.php
  core-bundle/tests/OptIn/OptInTest.php
  core-bundle/tests/Routing/UrlGeneratorTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  phpstan.neon.dist
Labels: bug

#1942 Fix a wrong return value in the back end locale listener test
  core-bundle/tests/EventListener/BackendLocaleListenerTest.php
Labels: bug

#1528 Twig helpers for rendering figures
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/views/Image/Studio/_macros.html.twig
  core-bundle/src/Resources/views/Image/Studio/figure.html.twig
  core-bundle/src/Twig/Extension/ImageExtension.php
  core-bundle/src/Twig/Runtime/FigureRendererRuntime.php
  core-bundle/src/Twig/Runtime/PictureConfigurationRuntime.php
  core-bundle/tests/Twig/Extension/ImageExtensionTest.php
  core-bundle/tests/Twig/Runtime/FigureRendererRuntimeTest.php
  core-bundle/tests/Twig/Runtime/PictureConfigurationRuntimeTest.php
Labels: feature

#1944 Fix light box group identifier description
  core-bundle/src/Image/Studio/FigureBuilder.php
Labels: bug

#1945 Fix issues found by the PhpStorm code inspector
  core-bundle/src/Resources/contao/classes/StyleSheets.php
  core-bundle/src/Resources/contao/classes/Theme.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
  core-bundle/src/Resources/contao/library/Contao/Image.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: bug

#1943 Revert 'Remove symfony/monolog-bundle dependency from functional tests'
  core-bundle/composer.json
  core-bundle/tests/Functional/app/AppKernel.php
Labels: bug

#1949 Add useful exception when hook class is invalid/missing
  core-bundle/src/Resources/contao/library/Contao/System.php
Labels: bug

#1950 Remove two left-over requirements
  composer.json
  installation-bundle/composer.json
Labels: bug

#1952 Fix missing ContentModel annotations
  core-bundle/src/Resources/contao/models/ContentModel.php
Labels: bug

#1953 Rename "light box" to "lightbox"
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Image/Studio/LightboxResult.php
  core-bundle/src/Image/Studio/Studio.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/views/Image/Studio/_macros.html.twig
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  core-bundle/tests/Image/Studio/LightboxResultTest.php
  core-bundle/tests/Twig/Runtime/FigureRendererRuntimeTest.php
Labels: bug

#1954 Clean up the routing changes
  core-bundle/src/DataCollector/ContaoDataCollector.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/elements/ContentDownload.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Controller/Page/RootPageControllerTest.php
  core-bundle/tests/DataCollector/ContaoDataCollectorTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Functional/Migration/RoutingMigrationTest.php
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#1948 Greatly simplify the PhpStan configuration
  composer.json
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/Session/LazySessionAccess.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Mailer/ContaoMailerTest.php
  core-bundle/tests/Routing/UrlGeneratorTest.php
  monorepo.yml
  phpstan.neon.dist
  psalm.xml
Labels: bug

#1951 Explicitly register the model classes
  calendar-bundle/src/Resources/contao/config/config.php
  comments-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  faq-bundle/src/Resources/contao/config/config.php
  news-bundle/src/Resources/contao/config/config.php
  newsletter-bundle/src/Resources/contao/config/config.php
Labels: bug

#1962 Fix PhpStan
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
  core-bundle/tests/Routing/Content/ArticleRouteProviderTest.php
  core-bundle/tests/Routing/Content/PageRouteProviderTest.php
  core-bundle/tests/Routing/Enhancer/InputEnhancerTest.php
  core-bundle/tests/Routing/Page/PageRouteTest.php
Labels: CI

#1960 Fix two MySQL 8 issues
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Resources/contao/classes/Crawl.php
Labels: bug

#1961 Convert non existing $_POST fields to an empty string
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
Labels: bug

#1967 Allow ResourceFinder in autowiring
  core-bundle/src/Resources/config/services.yml
Labels: bug

#1966 Do not run migration if tl_image_size table is missing
  installation-bundle/src/Database/Version410Update.php
Labels: bug

#1969 Fix order field migration missing where clause
  core-bundle/src/Migration/Version410/OrderFieldMigration.php
Labels: bug

#1971 Add a missing type-hint in the PageRoute constructor
  core-bundle/src/Routing/Page/PageRoute.php
Labels: bug

#1970 Prevent type errors in the button callback functions
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
Labels: bug

#1964 Fix the Composer script handlers
  core-bundle/src/Composer/ScriptHandler.php
  manager-bundle/src/Composer/ScriptHandler.php
Labels: bug

#1976 Fix search highlighting performance
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
Labels: bug

#1978 Reset the preview toolbar styles
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: bug

#1973 Rewrite the page annotation to follow the Route annotation
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/Page/RouteConfig.php
  core-bundle/src/ServiceAnnotation/Page.php
Labels: bug

#1975 Always include default value in the generated url
  core-bundle/src/Routing/RouteFactory.php
  core-bundle/tests/Routing/RouteFactoryTest.php
Labels: bug

#1972 Fix the front end preview
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/tests/Controller/BackendPreviewControllerTest.php
Labels: bug

#1992 Fix the unit tests
  composer.json
  core-bundle/composer.json
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/src/Repository/RememberMeRepository.php
  manager-bundle/composer.json
Labels: CI

#1988 Update terminal42/service-annotation-bundle
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Cron/LegacyCron.php
Labels: bug

#1990 Allow indexed tokens for SimpleTokenParser
  core-bundle/src/Util/SimpleTokenParser.php
  core-bundle/tests/Util/SimpleTokenParserTest.php
Labels: bug

#1987 Provide migration for folderUrl setting
  core-bundle/src/Migration/Version410/RoutingMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Functional/Migration/RoutingMigrationTest.php
Labels: bug

#1991 Fix warning in SearchIndexSubscriberTest
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
Labels: bug

#1986 Private properties in ImageResult + LightboxResult
  core-bundle/src/Image/Studio/ImageResult.php
  core-bundle/src/Image/Studio/LightboxResult.php
Labels: bug

#1996 Merge branch '4.4' into 4.9
  core-bundle/src/Resources/contao/library/Contao/System.php
  faq-bundle/src/Resources/contao/dca/tl_user.php
  news-bundle/src/Resources/contao/dca/tl_user.php
  newsletter-bundle/src/Resources/contao/dca/tl_user.php
Labels: release

#1997 Merge branch '4.9' into 4.10
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Cron/LegacyCron.php
  core-bundle/src/Image/LegacyResizer.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/EventListener/BackendLocaleListenerTest.php
  core-bundle/tests/Functional/app/AppKernel.php
  faq-bundle/src/Resources/contao/dca/tl_user.php
  installation-bundle/composer.json
  installation-bundle/src/Database/Version410Update.php
  news-bundle/src/Resources/contao/dca/tl_user.php
  newsletter-bundle/src/Resources/contao/dca/tl_user.php
Labels: release

#2001 Fix search highlighting performance
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
Labels: bug

#2000 Fix the search index subscriber test
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
Labels: bug

#2003 Fix the search index subscriber test
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
Labels: CI

#2002 Add a conflict with nikic/php-parser
  composer.json
  monorepo.yml
Labels: CI

#2004 Fix the textarea height
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/src/basic.css
Labels: bug

#2005 Fix the textarea height
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
Labels: bug

#2007 Require at least jQuery 3.5
  composer.json
  core-bundle/composer.json
Labels: bug

#1982 Added debugging information to the MakeResponsePrivateListener
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/tests/EventListener/MakeResponsePrivateListenerTest.php
Labels: bug

#2009 Upgrade to highlight.js 10
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/templates/js/js_highlight.html5
Labels: bug

#2008 Prevent installing jQuery <3.5
  composer.json
  core-bundle/composer.json
Labels: bug

#1985 Update terminal42/service-annotation-bundle and fix Page annotation
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
  core-bundle/src/EventListener/DataContainer/DisableAppConfiguredSettingsListener.php
  core-bundle/src/EventListener/DataContainer/LegacyRoutingListener.php
  core-bundle/src/EventListener/DataContainer/PageTypeOptionsListener.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/EventListener/InsertTags/DateListener.php
  core-bundle/src/Mailer/AvailableTransports.php
  core-bundle/src/ServiceAnnotation/Page.php
  core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php
Labels: bug

#2018 Ignore pages without alias when checking for duplicates
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
Labels: bug

#2021 Upgrade to TinyMCE 5
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: feature

#2024 Fix the .tox-menubar format definition
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#2026 Use escapeshellarg() in the symfony/process BC layer
  core-bundle/src/Composer/ScriptHandler.php
  manager-bundle/src/Composer/ScriptHandler.php
Labels: bug

#1984 Fix the SERP preview with mandatory route parameters
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/widgets/SerpPreview.php
Labels: bug

#2032 Do not reorder existing DROP INDEX queries to the end
  installation-bundle/src/Database/Installer.php
Labels: bug

#2020 Add CSV mime type and set Content-Type in File::sendToBrowser
  core-bundle/src/Resources/contao/config/mimetypes.php
  core-bundle/src/Resources/contao/library/Contao/File.php
Labels: bug

#2039 Fixed missing cache invalidations
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: bug

#2040 Remove redundant comments
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: bug

#1486 Fix/resize images memory leak
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/tests/Command/ResizeImagesCommandTest.php
Labels: bug

#2037 Always use the status code 307 for temporary redirects
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/EventListener/ToggleViewListener.php
  core-bundle/src/Exception/AjaxRedirectResponseException.php
  core-bundle/src/Exception/RedirectResponseException.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/controllers/FrontendShare.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
  core-bundle/tests/Controller/BackendControllerTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Exception/AjaxRedirectResponseExceptionTest.php
  core-bundle/tests/Exception/RedirectResponseExceptionTest.php
  installation-bundle/src/Controller/InstallationController.php
Labels: bug

#2035 Adjust the "admin e-mail" explanation
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/languages/en/tl_settings.xlf
Labels: bug

#2042 Add missing where condition for url prefix check
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
Labels: bug

#2041 Fix/resize images command
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/tests/Command/ResizeImagesCommandTest.php
Labels: bug
