Repository contao/contao, pull requests merged in 2020-06, with the labels that each got.

#1784 Fix the CI chain
  composer.json
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/Contao/RoutingTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/Controller/RobotsTxtControllerTest.php
  core-bundle/tests/Crawl/Escargot/FactoryTest.php
  core-bundle/tests/Cron/LegacyCronTest.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendPreviewListenerTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  core-bundle/tests/EventListener/TwoFactorFrontendListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/OptIn/OptInTest.php
  core-bundle/tests/OptIn/OptInTokenTest.php
  core-bundle/tests/Picker/FilePickerProviderTest.php
  core-bundle/tests/Routing/Enhancer/InputEnhancerTest.php
  core-bundle/tests/Routing/Matcher/LegacyMatcherTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  core-bundle/tests/Security/Logout/LogoutHandlerTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  core-bundle/tests/Slug/SlugTest.php
  core-bundle/tests/Translation/TranslatorTest.php
Labels: CI

#1789 Fix the CI chain
  composer.json
  core-bundle/composer.json
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/Contao/RoutingTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/Controller/RobotsTxtControllerTest.php
  core-bundle/tests/Crawl/Escargot/FactoryTest.php
  core-bundle/tests/Cron/LegacyCronTest.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendPreviewListenerTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  core-bundle/tests/EventListener/TwoFactorFrontendListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/OptIn/OptInTest.php
  core-bundle/tests/OptIn/OptInTokenTest.php
  core-bundle/tests/Picker/FilePickerProviderTest.php
  core-bundle/tests/Routing/Enhancer/InputEnhancerTest.php
  core-bundle/tests/Routing/Matcher/LegacyMatcherTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  core-bundle/tests/Security/Logout/LogoutHandlerTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  core-bundle/tests/Slug/SlugTest.php
  core-bundle/tests/Translation/TranslatorTest.php
Labels: CI

#1790 Ignore the Litespeed HTTP2 Smart Push cookie
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
Labels: bug

#1776 Correctly redirect to the preferred language if one does not have index alias
  core-bundle/src/Routing/RouteProvider.php
Labels: bug

#1794 Fix the CI chain
  composer.json
  core-bundle/composer.json
  core-bundle/tests/Contao/ImageTest.php
Labels: CI

#1772 Correctly track if container config files exist
  manager-bundle/src/HttpKernel/ContaoKernel.php
Labels: bug

#1583 Hide the crawler in maintenance mode
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
  core-bundle/src/Resources/contao/templates/backend/be_crawl.html5
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#1777 Unit tests for #1776
  core-bundle/src/Migration/Version409/CeAccessMigration.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Fixtures/Functional/Routing/language-index-mix.yml
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: bug

#1799 Remove the autoload_files option from the phpstan.neon.dist file
  phpstan.neon.dist
Labels: CI

#1801 Add a configuration for the Stale app on GitHub
  .github/stale.yml
Labels: CI

#1652 Let the pretty error screen handle unused arguments exception
  core-bundle/src/EventListener/ExceptionConverterListener.php
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/tests/EventListener/ExceptionConverterListenerTest.php
Labels: feature

#1800 Recreate sitemap xml, when regenerating news RSS
  news-bundle/src/Resources/contao/classes/News.php
Labels: bug

#1788 Fix/escargot 06 compat and skip broken link checker
  composer.json
  core-bundle/composer.json
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriber.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
  core-bundle/tests/Crawl/Monolog/CrawlCsvLogHandlerTest.php
Labels: bug

#1802 Also exempt "easy pick" and "help wanted" issues from going stale
  .github/stale.yml
Labels: CI

#1803 Correctly generate first and last class for articles and elements
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
Labels: bug

#1807 Improve the sizes attribute help text
  core-bundle/src/Resources/contao/languages/en/explain.xlf
  core-bundle/src/Resources/contao/languages/en/tl_image_size.xlf
Labels: bug

#1771 Explanation text tl_page.twoFactorJumpTo.1
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
Labels: bug

#1731 Prevent arbitrary column renaming in the schema update
  manager-bundle/src/EventListener/DoctrineAlterTableListener.php
  manager-bundle/src/Resources/config/listener.yml
  manager-bundle/tests/EventListener/DoctrineAlterTableListenerTest.php
Labels: bug

#1763 Add the Osano Cookie Consent cookie to the cookie deny list
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
Labels: bug

#1605 Try to fix the Codecov status report
  .github/workflows/ci.yml
Labels: CI

#1821 Use actions/checkout@v1
  .github/workflows/ci.yml
Labels: CI

#1822 Use actions/checkout@v1
  .github/workflows/ci.yml
Labels: CI

#1825 Skip invalid UTF-8 path names
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/library/Contao/Dbafs.php
Labels: bug

#1817 Ignore minlength/maxlength/minval/maxval in hidden fields
  core-bundle/src/Resources/contao/forms/FormHidden.php
Labels: bug

#1827 Add compatibility with imagine-svg 1.0
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/controllers/BackendPopup.php
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Resources/contao/templates/backend/be_popup.html5
Labels: bug

#1831 Fix PhpStan
  composer.json
  core-bundle/composer.json
  phpstan.neon.dist
Labels: CI

#1832 Fix the composer.json check in the monorepo split job
  .github/workflows/ci.yml
  monorepo.yml
Labels: CI

#1833 Fix PhpStan
  composer.json
  core-bundle/composer.json
Labels: CI

#1826 Improve disabled cookie deny list
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
  core-bundle/src/EventListener/HttpCache/StripQueryParametersSubscriber.php
  core-bundle/tests/EventListener/HttpCache/StripCookiesSubscriberTest.php
  core-bundle/tests/EventListener/HttpCache/StripQueryParametersSubscriberTest.php
Labels: feature

#1828 Fix "mail" DSN
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#1836 Use @mixin and @template for the Adapter class
  core-bundle/src/Framework/Adapter.php
  core-bundle/tests/Contao/RoutingTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/Controller/RobotsTxtControllerTest.php
  core-bundle/tests/Crawl/Escargot/FactoryTest.php
  core-bundle/tests/Cron/LegacyCronTest.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendPreviewListenerTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  core-bundle/tests/EventListener/TwoFactorFrontendListenerTest.php
  core-bundle/tests/Framework/Adapter/AdapterTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/OptIn/OptInTest.php
  core-bundle/tests/OptIn/OptInTokenTest.php
  core-bundle/tests/Picker/FilePickerProviderTest.php
  core-bundle/tests/Routing/Enhancer/InputEnhancerTest.php
  core-bundle/tests/Routing/Matcher/LegacyMatcherTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  core-bundle/tests/Security/Logout/LogoutHandlerTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  core-bundle/tests/Slug/SlugTest.php
  core-bundle/tests/Translation/TranslatorTest.php
  phpstan.neon.dist
Labels: CI

#1839 Improve performance of file manager
  core-bundle/src/Resources/contao/dca/tl_files.php
Labels: bug

#1840 Improved legacy class import statements for a massive performance improvement
  core-bundle/src/Resources/contao/library/Contao/System.php
Labels: bug

#1843 Added tideways profiler cookie to the list of cookies to ignore
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
Labels: bug

#1815 Show error 500 for unsupported image types
  core-bundle/src/Controller/ImagesController.php
Labels: bug

#1823 Fix back end layout problems in various browsers
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
Labels: bug

#1848 Remove sleep() from the password modules
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
Labels: bug

#1849 Update the PHPStan configuration
  phpstan.neon.dist
Labels: CI

#1863 Fix the ->import() calls
  calendar-bundle/src/Resources/contao/dca/tl_calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  calendar-bundle/src/Resources/contao/dca/tl_content.php
  news-bundle/src/Resources/contao/dca/tl_content.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/dca/tl_news_archive.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
Labels: CI

#1844 Lazy-load commands
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Command/CronCommand.php
  core-bundle/src/Command/DebugDcaCommand.php
  core-bundle/src/Command/FilesyncCommand.php
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/Command/UserPasswordCommand.php
  core-bundle/src/Command/VersionCommand.php
  core-bundle/src/Resources/contao/library/Contao/System.php
Labels: bug

#1465 Featured events
  calendar-bundle/src/Resources/contao/classes/Events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar_events.xlf
  calendar-bundle/src/Resources/contao/languages/en/tl_module.xlf
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventMenu.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
Labels: feature

#1869 Do not use the contao_root route
  core-bundle/README.md
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/tests/Controller/BackendPreviewControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Functional/app/config/security.yml
  manager-bundle/src/Resources/skeleton/config/security.yml
Labels: feature

#1870 Add csv_excel format to form generator
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/languages/en/tl_form.xlf
Labels: feature

#1872 Make the functional tests compatible with Symfony 5
  composer.json
  core-bundle/composer.json
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#1875 Fix the search field height in the back end
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
Labels: bug

#1778 Allow to override robots setting for news and events
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar_events.xlf
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/languages/en/tl_news.xlf
  news-bundle/src/Resources/contao/models/NewsModel.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
Labels: feature

#1877 Fix the widget headline and help wizard alignment
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#1446 Determine ptable dynamically
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
Labels: feature

#1881 Allow to define a default ptable
  calendar-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  news-bundle/src/Resources/contao/dca/tl_content.php
Labels: feature

#1382 Disable settings in the back end if defined in the container
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/DataContainer/DisableAppConfiguredSettingsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/languages/en/tl_settings.xlf
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php
Labels: feature

#1884 Get rid of more deprecations
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
  manager-bundle/src/Routing/RouteLoader.php
Labels: bug

#1879 Change back end layout yet again
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
Labels: bug

#1850 Optimize importing DB fixtures in the functional tests
  core-bundle/tests/Functional/RoutingTest.php
Labels: feature

#1886 Increase margin for TinyMCE
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
Labels: bug

#1880 Let the user disable 2FA if it is enforced
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
Labels: bug

#1883 Enable framework.assets by default in Managed Edition
  manager-bundle/src/Resources/skeleton/config/config.yml
Labels: bug

#1810 Remove redirect status type from 403
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/pages/PageError403.php
  core-bundle/src/Resources/contao/pages/PageError404.php
Labels: bug

#1871 Performance: Reduce file queries
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#1762 Remove redirect status type from 401 and 403
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/pages/PageError401.php
  core-bundle/src/Resources/contao/pages/PageError403.php
  core-bundle/src/Resources/contao/pages/PageError404.php
Labels: bug

#1754 Allow forcing password change on login in contao:user:password command
  core-bundle/src/Command/UserPasswordCommand.php
  core-bundle/tests/Command/UserPasswordCommandTest.php
Labels: bug
