Repository contao/contao, pull requests merged in 2020-08, with the labels that each got.

#2056 Use expectExceptionMessage() for non-deprecations
  core-bundle/tests/DependencyInjection/Compiler/DataContainerCallbackPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterHookListenersPassTest.php
Labels: bug

#2057 SingleSRC flags for youtube/vimeo splash screen
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#2048 Re-arrange the root page form layout
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
Labels: bug

#2036 Correctly generate the filter menu if the breadcrumb menu is active
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#2034 Show the filename in the versions overview
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: bug

#2059 Remove content routing
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/Page/RootPageController.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Exception/ContentRouteNotFoundException.php
  core-bundle/src/Exception/RouteParametersException.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/config/routing.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Routing/Content/ArticleRouteProvider.php
  core-bundle/src/Routing/Content/ContentRouteProviderInterface.php
  core-bundle/src/Routing/Content/PageRouteProvider.php
  core-bundle/src/Routing/ContentResolvingGenerator.php
  core-bundle/src/Routing/Matcher/UrlMatcher.php
  core-bundle/src/Routing/Page/DynamicRouteInterface.php
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/PageUrlGenerator.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteFactory.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Controller/Page/RootPageControllerTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterPagesPassTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Fixtures/src/Controller/Page/TestPageController.php
  core-bundle/tests/Routing/Content/ArticleRouteProviderTest.php
  core-bundle/tests/Routing/Content/PageRouteProviderTest.php
  core-bundle/tests/Routing/ContentResolvingGeneratorTest.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
  core-bundle/tests/Routing/Page/PageRouteTest.php
  core-bundle/tests/Routing/PageUrlGeneratorTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteFactoryTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: bug

#2061 Fix a case-sensitivity mismatch in the figure builder
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#2062 Correctly deprecate the ampersand() function
  core-bundle/src/Resources/contao/helper/functions.php
Labels: bug

#2055 Change the JSON-LD type "RegularPage" to "Page"
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
  core-bundle/tests/Search/DocumentTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: bug

#2060 getOverwriteMetadata() support for more models
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  core-bundle/src/File/ModelMetadataTrait.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  faq-bundle/src/Resources/contao/models/FaqModel.php
  news-bundle/src/Resources/contao/models/NewsModel.php
Labels: bug

#2063 Use the response constants for HTTP status codes
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/EventListener/ToggleViewListener.php
  core-bundle/src/Resources/contao/controllers/FrontendShare.php
  core-bundle/src/Resources/contao/pages/PageLogout.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
  installation-bundle/src/Controller/InstallationController.php
Labels: bug

#619 Fix a potential error if the URL has percentage in it
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: bug

#2066 Correctly handle empty manager config file
  manager-bundle/src/Api/ManagerConfig.php
  manager-bundle/tests/Api/ManagerConfigTest.php
Labels: bug

#2050 Harden table options lookup in Installer
  installation-bundle/src/Database/Installer.php
  installation-bundle/tests/Database/InstallerTest.php
Labels: bug

#2017 Allow to not redirect to a language
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Routing/RouteProvider.php
Labels: feature

#2068 Improve the PageUrlListener in "edit multiple" mode
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
Labels: bug

#2069 Correctly set the active record in the ContentCompositionListener
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
Labels: bug

#2064 Fix and improve route debugging
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/Routing/CandidatePagesTrait.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Routing/Route404ProviderTest.php
Labels: bug

#2065 Enable legacy routing by default
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Functional/app/config/config_legacy.yml
  core-bundle/tests/Functional/app/config/config_locale.yml
  core-bundle/tests/Functional/app/config/config_suffix.yml
  core-bundle/tests/Functional/app/config/config_test.yml
Labels: bug

#2073 Fix issues found by the PhpStorm code inspector
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/src/EventListener/DataContainer/LegacyRoutingListener.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/forms/FormTextArea.php
  core-bundle/src/Resources/contao/forms/FormTextField.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/library/Contao/Email.php
  core-bundle/src/Resources/contao/library/Contao/GdImage.php
  core-bundle/src/Resources/contao/library/Contao/Request.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
  core-bundle/src/Resources/contao/models/MemberGroupModel.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
Labels: bug

#2076 Pass the column to the getArticle() method in the ContentArticle class
  core-bundle/src/Resources/contao/elements/ContentArticle.php
Labels: bug

#2075 Use getClassFromTable() in the Model::createModelFromDbResult() method
  core-bundle/src/Resources/contao/library/Contao/Model.php
Labels: bug

#2078 Always render the "go to front end" link without preview fragment
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
Labels: bug

#2077 Correctly show the front end preview bar for non-admin users
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: bug

#2081 Correctly generate the news/events preview URL in multi-domain mode
  calendar-bundle/src/EventListener/PreviewUrlConvertListener.php
  calendar-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  news-bundle/src/EventListener/PreviewUrlConvertListener.php
  news-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
Labels: bug

#2085 Fix the tl_user_group.stop help text
  core-bundle/src/Resources/contao/languages/en/tl_user_group.xlf
Labels: bug

#2083 Update the Matomo tracking code
  core-bundle/src/Resources/contao/templates/analytics/analytics_matomo.html5
Labels: bug

#2090 Fix the yamllint CI job
  .github/workflows/ci.yml
Labels: CI

#2089 Use input instead of keyup event in the preview toolbar
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: bug

#2086 Also indicate default templates in the custom template menu
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#2088 Increase the z-index of the top menu overlay
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#2087 Show the picker menu even if there is only one tab
  core-bundle/src/Resources/contao/controllers/BackendMain.php
Labels: bug

#2091 Check if the username has been submitted in the registration module
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#2074 Fix order of CSRF and private response listeners
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#2093 Merge branch '4.4' into 4.9
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/EventListener/TwoFactorFrontendListener.php
  core-bundle/src/Exception/AjaxRedirectResponseException.php
  core-bundle/src/Exception/RedirectResponseException.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/config/mimetypes.php
  core-bundle/src/Resources/contao/controllers/FrontendShare.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentArticle.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/languages/en/tl_settings.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/pages/PageLogout.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/tests/Controller/BackendControllerTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Exception/AjaxRedirectResponseExceptionTest.php
  core-bundle/tests/Exception/RedirectResponseExceptionTest.php
  core-bundle/tests/Functional/RoutingTest.php
  installation-bundle/src/Controller/InstallationController.php
  manager-bundle/src/Controller/DebugController.php
Labels: release

#2028 Allow new major versions of two third-party packages
  composer.json
  core-bundle/composer.json
  manager-bundle/composer.json
Labels: bug

#2096 Use HTTP status code 303 instead of 307 for redirects
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/EventListener/ToggleViewListener.php
  core-bundle/src/Exception/AjaxRedirectResponseException.php
  core-bundle/src/Exception/RedirectResponseException.php
  core-bundle/src/Resources/contao/controllers/FrontendShare.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
  core-bundle/tests/Controller/BackendControllerTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Exception/AjaxRedirectResponseExceptionTest.php
  core-bundle/tests/Exception/RedirectResponseExceptionTest.php
  installation-bundle/src/Controller/InstallationController.php
Labels: bug

#2097 Use HTTP status code 303 instead of 307 for redirects
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/EventListener/TwoFactorFrontendListener.php
  core-bundle/src/Exception/AjaxRedirectResponseException.php
  core-bundle/src/Exception/RedirectResponseException.php
  core-bundle/src/Resources/contao/controllers/FrontendShare.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/tests/Controller/BackendControllerTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Exception/AjaxRedirectResponseExceptionTest.php
  core-bundle/tests/Exception/RedirectResponseExceptionTest.php
  core-bundle/tests/Functional/RoutingTest.php
  installation-bundle/src/Controller/InstallationController.php
  manager-bundle/src/Controller/DebugController.php
Labels: bug

#2098 Use HTTP status code 303 instead of 307 for redirects
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/EventListener/TwoFactorFrontendListener.php
  core-bundle/src/Exception/AjaxRedirectResponseException.php
  core-bundle/src/Exception/RedirectResponseException.php
  core-bundle/src/Resources/contao/controllers/FrontendShare.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/tests/Controller/BackendControllerTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Exception/AjaxRedirectResponseExceptionTest.php
  core-bundle/tests/Exception/RedirectResponseExceptionTest.php
  core-bundle/tests/Functional/RoutingTest.php
  installation-bundle/src/Controller/InstallationController.php
  manager-bundle/src/Controller/DebugController.php
Labels: bug

#2071 Also add template options to legacy template data
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/tests/Image/Studio/FigureTest.php
Labels: bug

#2101 Fix a wrong merge in the ModuleSearch class
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
Labels: bug

#2019 Add custom exception to further handle route parameter errors
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/Resources/contao/languages/en/exception.xlf
  core-bundle/src/Resources/views/Error/layout.html.twig
  core-bundle/src/Resources/views/Error/missing_route_parameters.html.twig
Labels: bug

#2106 Correctly decode entities in the layout name
  core-bundle/src/DataCollector/ContaoDataCollector.php
Labels: bug

#2107 Show the module type if name is not available
  core-bundle/src/Resources/contao/widgets/ModuleWizard.php
Labels: bug

#2110 Fix the UPGRADE.md file
  UPGRADE.md
Labels: bug

#2115 Do not add empty CSS classes to template
  core-bundle/src/Controller/AbstractFragmentController.php
Labels: bug

#2118 Make cookies secure if the request is secure
  core-bundle/src/Resources/contao/library/Contao/System.php
  manager-bundle/src/Resources/skeleton/config/config.yml
Labels: bug

#2121 Correctly show the default text form field template
  core-bundle/src/Resources/contao/dca/tl_form_field.php
Labels: bug

#2122 Remove the Contao-Merge-Cache-Control header in the master request
  core-bundle/src/EventListener/SubrequestCacheSubscriber.php
  core-bundle/tests/EventListener/SubrequestCacheSubscriberTest.php
Labels: bug

#2105 Correctly merge the root IDs with the child record IDs
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#2117 Make cookies secure if the request is secure
  core-bundle/src/Resources/contao/library/Contao/System.php
  manager-bundle/src/Resources/web/app.php
  manager-bundle/src/Resources/web/app_dev.php
Labels: bug

#2082 Correctly apply custom CSS in the ContentModule class
  core-bundle/src/Resources/contao/elements/ContentModule.php
Labels: bug

#2128 Fix psalm InvalidCatch error
  core-bundle/src/Image/LegacyResizer.php
Labels: bug

#2134 Merge branch '4.4' into 4.9
  UPGRADE.md
  core-bundle/src/DataCollector/ContaoDataCollector.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/widgets/ModuleWizard.php
Labels: release

#2103 $this->ptable not available in the DataContainer class
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#2136 Decorate mailer.mailer instead of mailer
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#2139 Also invalidate the ptable cache tags in the DC_Table class
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#2141 Merge branch '4.9' into 4.10
  UPGRADE.md
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/DataCollector/ContaoDataCollector.php
  core-bundle/src/EventListener/SubrequestCacheSubscriber.php
  core-bundle/src/Image/LegacyResizer.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/widgets/ModuleWizard.php
  core-bundle/tests/EventListener/SubrequestCacheSubscriberTest.php
  manager-bundle/src/Resources/skeleton/config/config.yml
Labels: release

#2124 Adjust the Psalm configuration and work towards level 6
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Config/Loader/PhpFileLoader.php
  core-bundle/src/DataCollector/ContaoDataCollector.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/src/Migration/MigrationCollection.php
  core-bundle/src/Translation/Translator.php
  core-bundle/tests/Command/UserListCommandTest.php
  core-bundle/tests/Config/Loader/XliffFileLoaderTest.php
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/Image/Studio/LightboxResultTest.php
  core-bundle/tests/Routing/UrlGeneratorTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  psalm.xml
Labels: CI

#2144 Correctly handle multiple slashes in a path
  core-bundle/src/Resources/contao/pages/PageError404.php
  core-bundle/src/Routing/Candidates/AbstractCandidates.php
Labels: bug

#2148 Add support for HTTP cache subscribers
  manager-bundle/src/HttpKernel/ContaoKernel.php
Labels: feature

#2146 Add more cases to the functional routing test
  core-bundle/tests/Functional/RoutingTest.php
Labels: CI

#2145 Disable the no-language-redirect feature in legacy routing mode
  core-bundle/src/EventListener/DataContainer/LegacyRoutingListener.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/widgets/CheckBox.php
  core-bundle/src/Routing/RouteProvider.php
Labels: bug

#2150 Fix the checkbox height on mobile devices
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
Labels: bug

#2151 Correctly inherit the disableLanguageRedirect property
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#2120 Support multiple fragments on the same controller
  core-bundle/src/Command/DebugFragmentsCommand.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
Labels: bug

#2153 Use the class name as cache key in System::import()
  core-bundle/src/Resources/contao/library/Contao/System.php
Labels: bug

#2154 Merge branch '4.9' into 4.10
  core-bundle/src/Command/DebugFragmentsCommand.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
Labels: release

#2156 Update the changelog and language files
  CHANGELOG.md
  calendar-bundle/src/Resources/contao/languages/es/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/es/tl_calendar_events.xlf
  calendar-bundle/src/Resources/contao/languages/es/tl_module.xlf
  calendar-bundle/src/Resources/contao/languages/es/tl_user.xlf
  calendar-bundle/src/Resources/contao/languages/it/tl_calendar_events.xlf
  comments-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/tl_page.xlf
  core-bundle/src/Resources/contao/languages/de/tl_page.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/exception.xlf
  core-bundle/src/Resources/contao/languages/es/explain.xlf
  core-bundle/src/Resources/contao/languages/es/modules.xlf
  core-bundle/src/Resources/contao/languages/es/tl_article.xlf
  core-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/languages/es/tl_files.xlf
  core-bundle/src/Resources/contao/languages/es/tl_form.xlf
  core-bundle/src/Resources/contao/languages/es/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/es/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/es/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/es/tl_member.xlf
  core-bundle/src/Resources/contao/languages/es/tl_member_group.xlf
  core-bundle/src/Resources/contao/languages/es/tl_module.xlf
  core-bundle/src/Resources/contao/languages/es/tl_page.xlf
  core-bundle/src/Resources/contao/languages/es/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/es/tl_user.xlf
  core-bundle/src/Resources/contao/languages/es/tl_user_group.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_member_group.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_user_group.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/it/tl_files.xlf
  core-bundle/src/Resources/contao/languages/it/tl_page.xlf
  core-bundle/src/Resources/contao/languages/ja/exception.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_page.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_page.xlf
  core-bundle/src/Resources/contao/languages/ru/exception.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_page.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_page.xlf
  faq-bundle/src/Resources/contao/languages/es/tl_faq_category.xlf
  listing-bundle/src/Resources/contao/languages/es/modules.xlf
  listing-bundle/src/Resources/contao/languages/es/tl_module.xlf
  news-bundle/src/Resources/contao/languages/es/modules.xlf
  news-bundle/src/Resources/contao/languages/es/tl_module.xlf
  news-bundle/src/Resources/contao/languages/es/tl_news.xlf
  news-bundle/src/Resources/contao/languages/es/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/es/tl_user.xlf
  news-bundle/src/Resources/contao/languages/it/tl_news.xlf
  newsletter-bundle/src/Resources/contao/languages/es/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/es/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/es/tl_newsletter_channel.xlf
Labels: release

#2155 Support captcha input wrapped in DIV
  core-bundle/src/Resources/contao/templates/forms/form_captcha.html5
Labels: bug

#2161 Update the changelog and the language files
  CHANGELOG.md
  calendar-bundle/src/Resources/contao/languages/it/tl_calendar_events.xlf
  core-bundle/src/Config/Loader/PhpFileLoader.php
  core-bundle/src/Config/Loader/XliffFileLoader.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/src/Resources/contao/config/constants.php
  psalm.xml
Labels: release

#2167 Add a template block for "content_css"
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
Labels: bug

#2163 Show SQL import error message
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/Resources/views/main.html.twig
Labels: bug

#2166 Fix a potential wrong image dimensions being returned from cache
  core-bundle/src/Resources/contao/classes/FileUpload.php
  core-bundle/src/Resources/contao/library/Contao/File.php
Labels: bug

#2172 Prevent zero values for idf measure in search algorithm
  core-bundle/src/Resources/contao/library/Contao/Search.php
Labels: bug

#2180 Add missing assets URL to non-combined files
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
  core-bundle/tests/Contao/CombinerTest.php
Labels: bug

#2192 Added index to tl_form_field.invisible
  core-bundle/src/Resources/contao/dca/tl_form_field.php
Labels: bug

#2188 Revert the changes regarding the article CSS classes
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
Labels: bug

#2193 Use a multicolumn index for the tl_form_field table
  core-bundle/src/Resources/contao/dca/tl_form_field.php
Labels: bug

#2189 Add a List-Unsubscribe header to newsletters
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#2191 Handle the subject query string when encoding/decoding e-mails
  core-bundle/src/Resources/contao/library/Contao/Idna.php
  core-bundle/tests/Contao/IdnaTest.php
Labels: bug

#2181 Add missing assets URL to non-combined files
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
  core-bundle/tests/Contao/CombinerTest.php
Labels: bug

#2182 Catch exceptions to prevent the resize images command from failing
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/tests/Command/ResizeImagesCommandTest.php
Labels: bug

#2194 Use the active record in the protectFolder() callback
  core-bundle/src/Resources/contao/dca/tl_files.php
Labels: bug

#2184 Fix invalid "array to string conversion" in ScriptHandler exception message
  manager-bundle/src/Composer/ScriptHandler.php
Labels: bug

#2195 Adjust the composer.json description
  composer.json
  core-bundle/composer.json
  manager-bundle/composer.json
Labels: bug

#2200 Load default labels within loading DCA files
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
Labels: bug

#2207 Fix the unit tests
  core-bundle/tests/ContaoManager/PluginTest.php
  manager-bundle/tests/Command/DebugPluginsCommandTest.php
Labels: CI

#2208 Always load DotEnv files if they exist
  manager-bundle/src/HttpKernel/ContaoKernel.php
Labels: bug

#2211 Fix the unit tests
  core-bundle/tests/ContaoManager/PluginTest.php
Labels: CI

#2204 Only check request token for master requests
  core-bundle/src/EventListener/RequestTokenListener.php
  core-bundle/tests/EventListener/RequestTokenListenerTest.php
Labels: bug
