Repository contao/contao, pull requests merged in 2020-09, with the labels that each got.

#2215 Preserve unknown options in select and checkbox widgets
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#2216 Use a temporary redirect to redirect to the language root
  core-bundle/src/Resources/contao/classes/Frontend.php
Labels: bug

#2217 Correctly find published pages in the findSearchablePages() method
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#2219 Only update the comments notification URL in the front end
  comments-bundle/src/Resources/contao/classes/Comments.php
Labels: bug

#2129 Correctly generate nested folder URL aliases
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#2220 Simplify the tl_content header fields
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#2223 Merge branch '4.4' into 4.9
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/FileUpload.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Resources/contao/library/Contao/Idna.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/tests/Contao/IdnaTest.php
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/Resources/views/main.html.twig
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: release

#2226 Do not add the first/last classes to articles
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
Labels: bug

#2234 Review the composite indexes
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  comments-bundle/src/Resources/contao/dca/tl_comments_notify.php
  core-bundle/src/Resources/contao/classes/Messages.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/MemberModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/models/NewsModel.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
Labels: bug

#2173 Work towards psalm level 6 (part 2)
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Image/Studio/Figure.php
Labels: bug

#2247 Rename the SimpleTokenParser::parseTokens() method
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Util/SimpleTokenParser.php
  core-bundle/tests/Util/SimpleTokenParserTest.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
Labels: bug

#2227 Use a temporary redirect to redirect to the language root
  core-bundle/src/Resources/contao/pages/PageError404.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
Labels: bug

#2213 Do not add CSS class to multiple elements
  core-bundle/src/Resources/contao/elements/ContentModule.php
Labels: bug

#2244 Do not log 503 "errors"
  manager-bundle/src/Resources/skeleton/config/config_prod.yml
Labels: bug

#2241 Update ModuleRegistration.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#2248 Fix a type error in the back end menu listener
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
Labels: bug

#2251 Run the CS fixer
  core-bundle/tests/Framework/Adapter/AdapterTest.php
Labels: CI

#2249 Return early in the Search::indexPage() method if nothing has changed
  core-bundle/src/Resources/contao/library/Contao/Search.php
Labels: bug

#2253 Run the CS fixer
  core-bundle/src/Session/LazySessionAccess.php
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/Framework/Adapter/AdapterTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Routing/UrlGeneratorTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
Labels: CI

#2250 Skip indexing if a page has not changed
  core-bundle/src/Resources/contao/library/Contao/Search.php
Labels: bug

#2255 Fix the stop time in the DB queries
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/Messages.php
  core-bundle/src/Resources/contao/classes/RebuildIndex.php
  core-bundle/src/Resources/contao/controllers/BackendSwitch.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/MemberGroupModel.php
  core-bundle/src/Resources/contao/models/MemberModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  faq-bundle/src/Resources/contao/modules/ModuleFaq.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/models/NewsModel.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#2256 Merge branch '4.4' into 4.9
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/classes/Messages.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/MemberGroupModel.php
  core-bundle/src/Resources/contao/models/MemberModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Security/User/UserChecker.php
  faq-bundle/src/Resources/contao/modules/ModuleFaq.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/models/NewsModel.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: release

#2257 Only use floorToMinute() in DB queries
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Security/User/UserChecker.php
  faq-bundle/src/Resources/contao/modules/ModuleFaq.php
  news-bundle/src/Resources/contao/classes/News.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#2259 Merge branch '4.9' into 4.10
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/classes/Messages.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/MemberGroupModel.php
  core-bundle/src/Resources/contao/models/MemberModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Security/User/UserChecker.php
  faq-bundle/src/Resources/contao/modules/ModuleFaq.php
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/src/Resources/skeleton/config/config_prod.yml
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/models/NewsModel.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: release

#2261 Do not validate widgets that do not submit input
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#2267 Keep fileTree sorting order when changing selection
  core-bundle/src/Resources/contao/classes/Ajax.php
Labels: bug

#2272 Fixed missing apostrophe in SQL query
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#2268 Fix height limit toggler behavior in "select multiple" state
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#2273 Merge branch '4.4' into 4.9
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: release

#2260 Do not use floorToMinute() in the PageModel::loadDetails() method
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#2264 The contao.search.indexer service is optional
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
Labels: bug

#2274 Merge branch '4.9' into 4.10
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: release

#2270 Fix wrong typehint
  core-bundle/src/EventListener/DataContainerCallbackListener.php
Labels: bug

#2275 Correctly generate name for hidden field in select menu
  core-bundle/src/Resources/contao/templates/forms/form_select.html5
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
Labels: bug

#2280 Update the UPGRADE.md file
  DEPRECATED.md
  UPGRADE.md
Labels: bug

#2285 Merge branch '4.4' into 4.9
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/templates/forms/form_select.html5
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
  core-bundle/tests/Contao/SearchTest.php
Labels: release

#2286 Merge branch '4.9' into 4.10
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/templates/forms/form_select.html5
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
  core-bundle/tests/Contao/SearchTest.php
Labels: release

#2287 Merge branch '4.10' into master
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/templates/forms/form_select.html5
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
  core-bundle/tests/Contao/SearchTest.php
Labels: release

#2281 Update dependecies for PHP 8.0 compatibility
  composer.json
  core-bundle/composer.json
Labels: bug

#2252 Do not change CSRF token cookie, if response is not successful
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
Labels: bug

#2298 Do not predefine the number of Psalm threads
  composer.json
Labels: bug

#2311 Fix FigureTest paths
  core-bundle/tests/Image/Studio/FigureTest.php
Labels: bug

#2209 Consider symlink when saving localconfig.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
Labels: bug

#2296 Fix picker deselecting filtered elements
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#2290 Fix warnings and deprecations when running unit tests
  core-bundle/src/Image/ImageSizes.php
  core-bundle/src/Routing/Matcher/LegacyMatcher.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/Cron/LegacyCronTest.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  core-bundle/tests/Image/ImageSizesTest.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  core-bundle/tests/Routing/Matcher/LegacyMatcherTest.php
  core-bundle/tests/Translation/TranslatorTest.php
Labels: bug

#2300 Do not use default player size
  core-bundle/src/Resources/contao/elements/ContentMedia.php
Labels: bug

#2320 Do not prolong unconfirmed opt-in tokens
  core-bundle/src/OptIn/OptIn.php
  core-bundle/tests/OptIn/OptInTest.php
Labels: bug

#2323 Fix the routing SSL logic
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/tests/Routing/Page/PageRouteTest.php
Labels: bug

#2313 Fix PictureFactory ResizeOptions priority
  core-bundle/src/Image/PictureFactory.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: bug

#2328 Fix the popup button padding
  core-bundle/src/Resources/contao/themes/flexible/popup.css
  core-bundle/src/Resources/contao/themes/flexible/popup.min.css
Labels: bug

#2333 Update the changelog and the language files
  CHANGELOG.md
  calendar-bundle/src/Resources/contao/languages/es/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/es/tl_calendar_events.xlf
  calendar-bundle/src/Resources/contao/languages/es/tl_module.xlf
  calendar-bundle/src/Resources/contao/languages/es/tl_user.xlf
  calendar-bundle/src/Resources/contao/languages/it/tl_calendar_events.xlf
  comments-bundle/src/Resources/contao/languages/de/default.xlf
  comments-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/exception.xlf
  core-bundle/src/Resources/contao/languages/es/explain.xlf
  core-bundle/src/Resources/contao/languages/es/modules.xlf
  core-bundle/src/Resources/contao/languages/es/tl_article.xlf
  core-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/languages/es/tl_files.xlf
  core-bundle/src/Resources/contao/languages/es/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/es/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/es/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/es/tl_member.xlf
  core-bundle/src/Resources/contao/languages/es/tl_member_group.xlf
  core-bundle/src/Resources/contao/languages/es/tl_module.xlf
  core-bundle/src/Resources/contao/languages/es/tl_page.xlf
  core-bundle/src/Resources/contao/languages/es/tl_user.xlf
  core-bundle/src/Resources/contao/languages/es/tl_user_group.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_member_group.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_user_group.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/sl/countries.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/languages.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_image_size_item.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_log.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_style.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  faq-bundle/src/Resources/contao/languages/es/tl_faq_category.xlf
  listing-bundle/src/Resources/contao/languages/es/tl_module.xlf
  news-bundle/src/Resources/contao/languages/es/modules.xlf
  news-bundle/src/Resources/contao/languages/es/tl_module.xlf
  news-bundle/src/Resources/contao/languages/es/tl_news.xlf
  news-bundle/src/Resources/contao/languages/es/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/es/tl_user.xlf
  newsletter-bundle/src/Resources/contao/languages/de/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/es/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/es/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/es/tl_newsletter_channel.xlf
Labels: release

#2334 Merge branch '4.9' into 4.10
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: release

#2336 Update the changelog and the language files
  CHANGELOG.md
  comments-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_page.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/de/tl_page.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_page.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/it/exception.xlf
  core-bundle/src/Resources/contao/languages/it/tl_content.xlf
  core-bundle/src/Resources/contao/languages/it/tl_files.xlf
  core-bundle/src/Resources/contao/languages/it/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/it/tl_page.xlf
  core-bundle/src/Resources/contao/languages/it/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_page.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_page.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_page.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_page.xlf
  newsletter-bundle/src/Resources/contao/languages/de/tl_module.xlf
Labels: release

#2340 Correctly protect new folders
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#2343 Only use $dc->id in the protectFolder() method
  core-bundle/src/Resources/contao/dca/tl_files.php
Labels: bug

#2342 Fix entering 0 in the back end
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/helper/functions.php
  core-bundle/src/Resources/contao/library/Contao/SqlFileParser.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
Labels: bug

#2348 Merge branch '4.9' into 4.10
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/helper/functions.php
  core-bundle/src/Resources/contao/library/Contao/SqlFileParser.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
Labels: release

#2353 Fix picker for providers with insert tags
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#2354 Merge branch '4.4' into 4.9
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: release

#2355 Merge branch '4.9' into 4.10
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: release

#2344 Support legacy console scripts in the initialize.php
  manager-bundle/src/Resources/system/initialize.php
Labels: bug

#2345 Support legacy console scripts in the initialize.php
  manager-bundle/src/Resources/skeleton/system/initialize.php
Labels: bug

#2362 Correctly handle IDNA hostnames in the root page
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#2351 Always override size variable for ce_player template
  core-bundle/src/Resources/contao/elements/ContentMedia.php
Labels: bug

#2369 Correctly check for numeric page IDs
  core-bundle/src/Routing/RouteProvider.php
Labels: bug

#2366 Harden non-normalized file ext comparison in LegacyResizer
  core-bundle/src/Image/LegacyResizer.php
Labels: bug

#2339 Reduce check for inlined services
  core-bundle/src/Resources/contao/library/Contao/System.php
Labels: bug

#2365 Fix non-normalized file ext comparison when building lightboxes
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#2373 Use $this->imageHref in the image.html5 template
  core-bundle/src/Resources/contao/templates/image/image.html5
Labels: bug

#2380 Fix the popup button padding
  core-bundle/src/Resources/contao/themes/flexible/popup.css
  core-bundle/src/Resources/contao/themes/flexible/popup.min.css
Labels: bug
