Repository contao/contao, pull requests merged in 2020-01, with the labels that each got.

#1145 Re-add prestissimo to shivammathur/setup-php
  .github/workflows/ci.yml
Labels: defect

#1132 Turn event listeners with more than one method into to subscribers
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/EventListener/DoctrineSchemaListener.php
  core-bundle/src/EventListener/LocaleSubscriber.php
  core-bundle/src/EventListener/SubrequestCacheSubscriber.php
  core-bundle/src/EventListener/UserSessionListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
  core-bundle/tests/EventListener/DoctrineSchemaListenerTest.php
  core-bundle/tests/EventListener/LocaleSubscriberTest.php
  core-bundle/tests/EventListener/UserSessionListenerTest.php
Labels: feature

#1147 Add contao.editable_files to the configuration
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/contao/config/default.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
Labels: defect

#1148 Rename "File location" to "Path"
  core-bundle/src/Resources/contao/languages/en/tl_files.xlf
Labels: defect

#1150 Rename "Column" to "Layout section"
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
Labels: defect

#1149 Fix the tl_files.source label
  core-bundle/src/Resources/contao/languages/en/tl_files.xlf
Labels: defect

#1068 Implement a broken link checker
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Search/Escargot/Factory.php
  core-bundle/src/Search/Escargot/Subscriber/BrokenLinkCheckerSubscriber.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Search/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
Labels: feature

#860 Use the Knp menu for the back end header menu
  core-bundle/src/EventListener/BackendMenuListener.php
  core-bundle/src/EventListener/Menu/BackendLogoutListener.php
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/src/EventListener/Menu/BackendPreviewListener.php
  core-bundle/src/Menu/BackendMenuBuilder.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Resources/contao/themes/flexible/hover.js
  core-bundle/src/Resources/contao/themes/flexible/hover.min.js
  core-bundle/src/Resources/contao/themes/flexible/icons/burger.svg
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/views/Backend/be_header_menu.html.twig
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/BackendMenuListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendLogoutListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendPreviewListenerTest.php
  core-bundle/tests/Menu/BackendMenuBuilderTest.php
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/src/Resources/config/listener.yml
  manager-bundle/tests/DependencyInjection/ContaoManagerExtensionTest.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
Labels: feature

#1151 Fix the description of the contao:crawl command
  core-bundle/src/Command/CrawlCommand.php
Labels: defect

#581 Compile navigation row via own method
  core-bundle/src/Resources/contao/modules/Module.php
Labels: feature

#1153 Fix the user and user group filters
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
Labels: defect

#1157 Update the badges in the README.md file
  README.md
Labels: defect

#1155 Fix parameter names which are not in snake case
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: defect

#709 Add a migrations command
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/TaggedMigrationsPass.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Migration/AbstractMigration.php
  core-bundle/src/Migration/MigrationCollection.php
  core-bundle/src/Migration/MigrationInterface.php
  core-bundle/src/Migration/MigrationResult.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/TaggedMigrationsPassTest.php
  core-bundle/tests/Migration/AbstractMigrationTest.php
  core-bundle/tests/Migration/MigrationCollectionTest.php
  core-bundle/tests/Migration/MigrationResultTest.php
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/Database/AbstractVersionUpdate.php
  installation-bundle/src/Database/Installer.php
  installation-bundle/src/Database/Version330Update.php
  installation-bundle/src/Database/Version350Update.php
  installation-bundle/src/Database/Version400Update.php
  installation-bundle/src/Database/Version410Update.php
  installation-bundle/src/Database/Version430Update.php
  installation-bundle/src/Database/Version440Update.php
  installation-bundle/src/Database/Version447Update.php
  installation-bundle/src/Database/Version450Update.php
  installation-bundle/src/Database/Version460Update.php
  installation-bundle/src/Database/Version470Update.php
  installation-bundle/src/Database/Version480Update.php
  installation-bundle/src/InstallTool.php
  installation-bundle/src/Resources/config/services.yml
Labels: feature

#989 Rework the front end preview
  calendar-bundle/src/EventListener/PreviewUrlConvertListener.php
  calendar-bundle/src/Resources/config/listener.yml
  calendar-bundle/tests/DependencyInjection/ContaoCalendarExtensionTest.php
  calendar-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Event/PreviewUrlConvertEvent.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/controllers/BackendPreview.php
  core-bundle/src/Resources/contao/controllers/BackendSwitch.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/templates/backend/be_preview.html5
  core-bundle/src/Resources/contao/templates/backend/be_switch.html5
  core-bundle/src/Resources/views/Collector/contao.svg
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
  core-bundle/tests/Controller/BackendPreviewControllerTest.php
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Event/PreviewUrlConvertEventTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  news-bundle/src/EventListener/PreviewUrlConvertListener.php
  news-bundle/src/Resources/config/listener.yml
  news-bundle/tests/DependencyInjection/ContaoNewsExtensionTest.php
  news-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
Labels: feature

#1158 Use addArgument() and addOption() instead of setDefinition()
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  manager-bundle/src/Command/DebugPluginsCommand.php
  manager-bundle/src/Command/InstallWebDirCommand.php
Labels: defect

#1154 Get universal picker url parameters via own method
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: feature

#521 Add a range field and support step in text field
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/forms/FormRange.php
  core-bundle/src/Resources/contao/forms/FormTextField.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
  core-bundle/src/Resources/contao/templates/forms/form_range.html5
Labels: feature

#1159 Fix the contao.image.sizes keys
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: defect

#579 Get filetree picker url parameters via own method
  core-bundle/src/Resources/contao/widgets/FileTree.php
Labels: feature

#580 Get pagetree picker url parameters via own method
  core-bundle/src/Resources/contao/widgets/PageTree.php
Labels: feature

#1057 Back end implementation for the crawler
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Entity/CrawlQueue.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/classes/RebuildIndex.php
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/templates/backend/be_crawl.html5
  core-bundle/src/Resources/contao/templates/backend/be_rebuild_index.html5
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Search/Escargot/Factory.php
  core-bundle/src/Search/Escargot/Subscriber/BrokenLinkCheckerSubscriber.php
  core-bundle/src/Search/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Search/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
  core-bundle/tests/Search/Escargot/Subscriber/SearchIndexSubscriberTest.php
Labels: feature

#1168 Use actions/checkout@v2 in the CI workflow
  .github/workflows/ci.yml
Labels: CI

#1162 Remove obsolete parameters
  manager-bundle/src/ContaoManager/Plugin.php
Labels: defect

#1164 Redirect to FE preview page after login and ensure integrity of target links
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/Base64EncodedRedirectController.php
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/controllers/BackendIndex.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/pages/PageError401.php
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/tests/Controller/Base64EncodedRedirectControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Security/Authentication/AuthenticationEntryPointTest.php
  manager-bundle/src/EventListener/PreviewAuthenticationListener.php
  manager-bundle/src/Resources/config/listener.yml
  manager-bundle/tests/DependencyInjection/ContaoManagerExtensionTest.php
Labels: defect

#1169 Exception and incorrect SERP alias
  core-bundle/src/Resources/contao/widgets/SerpPreview.php
Labels: defect

#1118 Override the authentication listener to validate FORM_SUBMIT
  core-bundle/README.md
  core-bundle/src/Controller/Base64EncodedRedirectController.php
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/controllers/BackendIndex.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/pages/PageError401.php
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/src/Resources/contao/templates/backend/be_login_two_factor.html5
  core-bundle/src/Resources/contao/templates/modules/mod_login.html5
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php
  core-bundle/tests/Controller/Base64EncodedRedirectControllerTest.php
  core-bundle/tests/Controller/FrontendControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/DependencyInjection/Security/ContaoLoginFactoryTest.php
  core-bundle/tests/Fixtures/src/Page/PageError401.php
  core-bundle/tests/Functional/app/config/security.yml
  core-bundle/tests/Security/Authentication/AuthenticationEntryPointTest.php
  core-bundle/tests/Security/Authentication/AuthenticationFailureHandlerTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Authentication/ContaoLoginAuthenticationListenerTest.php
  manager-bundle/src/Resources/skeleton/config/security.yml
Labels: defect

#1171 Clean up the Escargot integration
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Controller/RobotsTxtController.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriber.php
  core-bundle/src/Crawl/Escargot/Subscriber/EscargotSubscriberInterface.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/Crawl/Escargot/Subscriber/SubscriberResult.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/src/DependencyInjection/Compiler/EscargotSubscriberPass.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Entity/CrawlQueue.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/Crawl/Escargot/FactoryTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SubscriberResultTest.php
  core-bundle/tests/Crawl/Monolog/CrawlCsvLogHandlerTest.php
  core-bundle/tests/DependencyInjection/Compiler/EscargotSubscriberPassTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: defect

#1048 Improved purge search results cache maintenance label
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
Labels: defect

#1176 Disable the MakeResponsePrivateListener for non-Contao requests
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/MakeResponsePrivateListenerTest.php
Labels: defect

#1175 Add the ce_access migration
  .github/workflows/ci.yml
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Migration/Version409/CeAccessMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Migration/Version409/CeAccessMigrationTest.php
Labels: defect

#1179 Do not decode entities in page names
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
Labels: defect

#1180 Use spl_object_id() instead of spl_object_hash()
  core-bundle/src/Resources/contao/library/Contao/Model/Registry.php
Labels: feature

#1173 Generate all languages when warming the cache
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: defect

#1181 Always set the connection in the RememberMeRepository class
  core-bundle/src/Repository/RememberMeRepository.php
Labels: defect

#1188 Remove superfluous argument for RememberMeRepository
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: defect

#1098 Add a cron service and command with cron expressions
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/CronCommand.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Cron/CronJob.php
  core-bundle/src/Cron/LegacyCron.php
  core-bundle/src/DependencyInjection/Compiler/AddCronJobsPass.php
  core-bundle/src/Entity/CronJob.php
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/controllers/FrontendCron.php
  core-bundle/src/Resources/contao/dca/tl_cron.php
  core-bundle/src/ServiceAnnotation/CronJob.php
  core-bundle/tests/Command/CronCommandTest.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/Controller/FrontendControllerTest.php
  core-bundle/tests/Cron/CronJobTest.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/Cron/LegacyCronTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddCronJobsPassTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
  core-bundle/tests/Fixtures/src/Cron/TestCronJob.php
  core-bundle/tests/Fixtures/src/Cron/TestInvokableCronJob.php
  core-bundle/tests/Functional/app/Resources/contao_test.sql
Labels: feature

#1194 Show the correct error message if a wrong 2FA token is entered
  core-bundle/src/Security/Authentication/Provider/AuthenticationProvider.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
Labels: defect

#1191 Do not pollute the session with a target path
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Logout/LogoutHandler.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Logout/LogoutHandlerTest.php
Labels: defect

#1190 Do not merge subrequests without Cache-Control
  core-bundle/src/EventListener/SubrequestCacheSubscriber.php
  core-bundle/tests/EventListener/SubrequestCacheSubscriberTest.php
Labels: defect

#1189 Remove the contao manager logout handler by default
  core-bundle/README.md
Labels: defect

#1195 Also use the two factor factory constants in the unit tests
  core-bundle/tests/DependencyInjection/Security/ContaoLoginFactoryTest.php
Labels: defect

#1200 Revert 'Check if reset method exists on DeferredImageStorageFilesystem'
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: defect

#1202 Always allow root pages in a custom navigation modules
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
Labels: defect

#1197 Rework the module labels
  core-bundle/src/Resources/contao/languages/en/modules.xlf
Labels: defect

#1196 Also warn if a user or user group has permission to import themes
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
Labels: defect

#1177 Toggle DCA legends on their legend text only
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: defect

#1203 Improve the clickable area of the fieldset legends
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: defect

#1201 Remove all form actions
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/templates/modules/mod_comment_form.html5
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Maintenance.php
  core-bundle/src/Resources/contao/classes/PurgeData.php
  core-bundle/src/Resources/contao/classes/StyleSheets.php
  core-bundle/src/Resources/contao/classes/Theme.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/controllers/BackendFile.php
  core-bundle/src/Resources/contao/controllers/BackendIndex.php
  core-bundle/src/Resources/contao/controllers/BackendPage.php
  core-bundle/src/Resources/contao/controllers/BackendPassword.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/drivers/DC_File.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/modules/ModuleTwoFactor.php
  core-bundle/src/Resources/contao/templates/backend/be_confirm.html5
  core-bundle/src/Resources/contao/templates/backend/be_crawl.html5
  core-bundle/src/Resources/contao/templates/backend/be_csv_import.html5
  core-bundle/src/Resources/contao/templates/backend/be_diff.html5
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/src/Resources/contao/templates/backend/be_login_two_factor.html5
  core-bundle/src/Resources/contao/templates/backend/be_maintenance_mode.html5
  core-bundle/src/Resources/contao/templates/backend/be_password.html5
  core-bundle/src/Resources/contao/templates/backend/be_picker.html5
  core-bundle/src/Resources/contao/templates/backend/be_purge_data.html5
  core-bundle/src/Resources/contao/templates/backend/be_two_factor.html5
  core-bundle/src/Resources/contao/templates/member/member_default.html5
  core-bundle/src/Resources/contao/templates/member/member_grouped.html5
  core-bundle/src/Resources/contao/templates/modules/mod_changePassword.html5
  core-bundle/src/Resources/contao/templates/modules/mod_password.html5
  core-bundle/src/Resources/contao/templates/modules/mod_quicklink.html5
  core-bundle/src/Resources/contao/templates/modules/mod_quicknav.html5
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
  listing-bundle/src/Resources/contao/templates/listing/list_default.html5
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
  newsletter-bundle/src/Resources/contao/templates/newsletter/nl_default.html5
Labels: defect

#1199 Support YAML config files and routes.yaml
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/src/Routing/RouteLoader.php
Labels: defect

#806 Add info for more configuration options
  core-bundle/src/DependencyInjection/Configuration.php
Labels: defect

#1209 Refine the new labels
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/en/tl_user.xlf
Labels: defect

#1211 Fix issues found by the PhpStorm code inspector
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/Exception/ServiceUnavailableException.php
  core-bundle/tests/DependencyInjection/Compiler/AddAssetsPackagesPassTest.php
  core-bundle/tests/Migration/MigrationCollectionTest.php
  installation-bundle/src/Database/AbstractVersionUpdate.php
Labels: defect

#1210 Show preview toolbar on error pages
  core-bundle/src/EventListener/PreviewToolbarListener.php
Labels: defect

#559 Add trusted devices for 2FA
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/Entity/TrustedDevice.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/modules/ModuleTwoFactor.php
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/src/Resources/contao/templates/backend/be_login_two_factor.html5
  core-bundle/src/Resources/contao/templates/backend/be_two_factor.html5
  core-bundle/src/Resources/contao/templates/modules/mod_login.html5
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/login.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Authentication/Provider/AuthenticationProvider.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  core-bundle/tests/Security/TwoFactor/TrustedDeviceManagerTest.php
Labels: feature

#1213 Change allowed status codes for preview bar injection
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
Labels: defect

#1212 Tag the old version update classes as migrations
  core-bundle/src/Migration/Version409/CeAccessMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  installation-bundle/src/Database/Version330Update.php
  installation-bundle/src/Database/Version350Update.php
  installation-bundle/src/Database/Version400Update.php
  installation-bundle/src/Database/Version410Update.php
  installation-bundle/src/Database/Version430Update.php
  installation-bundle/src/Database/Version440Update.php
  installation-bundle/src/Database/Version447Update.php
  installation-bundle/src/Database/Version450Update.php
  installation-bundle/src/Database/Version460Update.php
  installation-bundle/src/Database/Version470Update.php
  installation-bundle/src/Database/Version480Update.php
  installation-bundle/src/DependencyInjection/ContaoInstallationExtension.php
  installation-bundle/src/Resources/config/migrations.yml
Labels: defect

#1221 Set the row format in the default table options
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  installation-bundle/src/Resources/views/configuration_error.html.twig
  manager-bundle/src/Resources/skeleton/config/config.yml
Labels: defect

#1223 Fixed missing crawl queue maintenance job
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
  core-bundle/src/Resources/contao/library/Contao/Automator.php
Labels: defect

#1225 Correctly determine the Ajax URL now that our forms no longer have an action
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
Labels: defect

#1228 Use GitHub actions for CI
  .appveyor.yml
  .gitattributes
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  README.md
  codecov.yml
  composer.json
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/tests/Image/PictureFactoryTest.php
  manager-bundle/tests/Command/InstallWebDirCommandTest.php
  manager-bundle/tests/Composer/ScriptHandlerTest.php
Labels: defect

#1232 Add the "url" parameter in the DropZone init script
  core-bundle/src/Resources/contao/classes/DropZone.php
Labels: defect

#1217 Fix url encoding in DATABASE_URL
  installation-bundle/src/Config/ParameterDumper.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: defect

#1238 Only build branches and tags of version 4.9
  .github/workflows/ci.yml
Labels: CI, defect

#1237 Set the DB password to null if empty
  installation-bundle/src/Controller/InstallationController.php
Labels: defect

#1239 Only build the master branch
  .github/workflows/ci.yml
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: CI, defect

#1246 Fix possible null value access in BackupCodeManager
  core-bundle/src/Security/TwoFactor/BackupCodeManager.php
  core-bundle/tests/Security/TwoFactor/BackupCodeManagerTest.php
Labels: defect

#1222 Remove Contao 3 services if they cause errors
  manager-bundle/src/Resources/skeleton/config/services.php
Labels: defect

#1255 Do not use a relative font for the preview bar
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: defect

#1230 Add a "title" attribute to the debug mode menu item
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/src/Resources/config/listener.yml
  manager-bundle/tests/DependencyInjection/ContaoManagerExtensionTest.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
Labels: defect

#1204 Fix custom response status code in Symfony 3.4
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/EventListener/ResponseExceptionListener.php
  core-bundle/src/Exception/ResponseException.php
  core-bundle/tests/EventListener/ResponseExceptionListenerTest.php
Labels: defect
