Repository contao/contao, pull requests merged in 2021-08, with the labels that each got.

#3244 Merge branch '4.11' into 4.12
  composer.json
  core-bundle/composer.json
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/elements/ContentYouTube.php
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/modules/ModuleProxy.php
  core-bundle/src/Resources/contao/templates/elements/ce_youtube.html5
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/Picker.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
  core-bundle/src/Resources/views/Image/Studio/figure.html.twig
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  manager-bundle/src/Resources/skeleton/config/security.yml
  phpunit.xml.dist
Labels: release

#3243 Fix a func_get_arg() value error
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: bug

#3245 Fix a func_get_arg() value error
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: bug

#3247 Unify the "numberOfItems" translations
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
Labels: bug

#3213 Support dynamic Twig includes/extends
  core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/src/Twig/Inheritance/TokenParserHelper.php
  core-bundle/tests/Twig/Inheritance/DynamicExtendsTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/DynamicIncludeTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/TokenParserHelperTest.php
Labels: bug

#3248 Split the "Coding Style" CI job
  .github/workflows/ci.yml
Labels: CI

#3219 Track theme templates in the template hierarchy
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/Twig/Inheritance/TemplateHierarchyInterface.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php
  core-bundle/tests/Command/DebugContaoTwigCommandTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: bug

#3228 Require twig/extra-bundle in the managed edition
  composer.json
  manager-bundle/composer.json
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: feature

#3250 Add missing SchemaOrgRuntime service declaration
  core-bundle/src/Resources/config/services.yml
Labels: bug

#3146 Deprecate the insert tag flag "|absolute"
  calendar-bundle/src/EventListener/InsertTagsListener.php
  calendar-bundle/tests/EventListener/InsertTagsListenerTest.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  faq-bundle/src/EventListener/InsertTagsListener.php
  faq-bundle/tests/EventListener/InsertTagsListenerTest.php
  news-bundle/src/EventListener/InsertTagsListener.php
  news-bundle/tests/EventListener/InsertTagsListenerTest.php
Labels: bug

#3253 Fix more invalid array access and missing null checks
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#3251 Harden literal insert tag replacement
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/tests/Contao/TemplateTest.php
Labels: bug

#3214 Support request tokens in Symfony forms
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/EventListener/RequestTokenListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/RequestToken.php
  core-bundle/tests/Controller/FrontendControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/RequestTokenListenerTest.php
  installation-bundle/src/Controller/InstallationController.php
Labels: bug

#3256 Revert 'Lazy-load the `rootFallbackLanguage` property'
  .github/workflows/ci.yml
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#3259 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  calendar-bundle/src/Resources/contao/languages/lv/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/lv/tl_module.xlf
  calendar-bundle/src/Resources/contao/languages/lv/tl_user.xlf
  calendar-bundle/src/Resources/contao/languages/tr/tl_user.xlf
  comments-bundle/src/Resources/contao/languages/lv/tl_content.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_content.xlf
  core-bundle/src/Resources/contao/languages/de/countries.xlf
  core-bundle/src/Resources/contao/languages/de/tl_content.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/it/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_content.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_content.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_content.xlf
  faq-bundle/src/Resources/contao/languages/lv/tl_faq_category.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.es.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.pl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sv.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.tr.xlf
  listing-bundle/src/Resources/contao/languages/lv/tl_module.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.es.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.lv.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.pl.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.sv.xlf
  news-bundle/src/Resources/contao/languages/lv/modules.xlf
  news-bundle/src/Resources/contao/languages/lv/tl_module.xlf
  news-bundle/src/Resources/contao/languages/lv/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/lv/tl_user.xlf
  newsletter-bundle/src/Resources/contao/languages/lv/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/lv/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/lv/tl_newsletter_channel.xlf
Labels: release

#3260 Merge branch '4.9' into 4.11
  .github/workflows/ci.yml
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/EventListener/RequestTokenListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/library/Contao/RequestToken.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Controller/FrontendControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/RequestTokenListenerTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  installation-bundle/src/Controller/InstallationController.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: release

#3261 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  calendar-bundle/src/Resources/contao/languages/lv/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/lv/tl_calendar_events.xlf
  calendar-bundle/src/Resources/contao/languages/lv/tl_module.xlf
  calendar-bundle/src/Resources/contao/languages/lv/tl_user.xlf
  calendar-bundle/src/Resources/contao/languages/tr/tl_layout.xlf
  calendar-bundle/src/Resources/contao/languages/tr/tl_user.xlf
  comments-bundle/src/Resources/contao/languages/lv/tl_content.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_content.xlf
  core-bundle/src/Resources/contao/languages/de/tl_content.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/languages/es/tl_files.xlf
  core-bundle/src/Resources/contao/languages/es/tl_form.xlf
  core-bundle/src/Resources/contao/languages/es/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/es/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/es/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/es/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/es/tl_page.xlf
  core-bundle/src/Resources/contao/languages/es/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/it/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_content.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_content.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_content.xlf
  faq-bundle/src/Resources/contao/languages/es/tl_faq.xlf
  faq-bundle/src/Resources/contao/languages/lv/tl_faq.xlf
  faq-bundle/src/Resources/contao/languages/lv/tl_faq_category.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.es.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.pl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sv.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.tr.xlf
  listing-bundle/src/Resources/contao/languages/lv/modules.xlf
  listing-bundle/src/Resources/contao/languages/lv/tl_module.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.es.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.lv.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.pl.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.sv.xlf
  news-bundle/src/Resources/contao/languages/lv/modules.xlf
  news-bundle/src/Resources/contao/languages/lv/tl_module.xlf
  news-bundle/src/Resources/contao/languages/lv/tl_news.xlf
  news-bundle/src/Resources/contao/languages/lv/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/lv/tl_user.xlf
  newsletter-bundle/src/Resources/contao/languages/lv/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/lv/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/lv/tl_newsletter_channel.xlf
Labels: release

#3258 Deprecated the return of null response in fragments
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
Labels: bug

#3269 Show native language suffix only in user profile
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_user.php
Labels: bug

#3270 Always refresh the template hierarchy in the debug:contao-twig command
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/tests/Command/DebugContaoTwigCommandTest.php
Labels: bug

#3268 Fix a type error in the event list module
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#3276 Check catalogue for country or locale translations
  core-bundle/src/Intl/Countries.php
  core-bundle/src/Intl/Locales.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Translation/MessageCatalogue.php
  core-bundle/src/Translation/Translator.php
  core-bundle/tests/Intl/CountriesTest.php
  core-bundle/tests/Intl/LocalesTest.php
  core-bundle/tests/Translation/MessageCatalogueTest.php
  core-bundle/tests/Translation/TranslatorTest.php
Labels: bug

#3279 Run the CI tools and the code inspector
  core-bundle/src/Config/Loader/XliffFileLoader.php
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Crawl/Escargot/Subscriber/EscargotSubscriberInterface.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/Crawl/Escargot/Subscriber/SubscriberResult.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/EventListener/RequestTokenListener.php
  core-bundle/src/HttpKernel/Bundle/ContaoModuleBundle.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Image/Studio/ImageResult.php
  core-bundle/src/Migration/Version400/Version400Update.php
  core-bundle/src/Twig/Interop/ContextHelper.php
  core-bundle/src/Util/LocaleUtil.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextTest.php
  core-bundle/tests/Routing/UrlGeneratorTest.php
  installation-bundle/src/Controller/InstallationController.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI

#3284 Update the changelog
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
Labels: release

#3285 Update the changelog and the language files
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_form.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/de/tl_form.xlf
  core-bundle/src/Resources/contao/languages/de/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/tl_form.xlf
  core-bundle/src/Resources/contao/languages/es/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/it/tl_form.xlf
  core-bundle/src/Resources/contao/languages/it/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_form.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_form.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_form.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_form.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_settings.xlf
Labels: release

#3286 Update the changelog and the language files
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_form.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/de/tl_form.xlf
  core-bundle/src/Resources/contao/languages/de/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/tl_form.xlf
  core-bundle/src/Resources/contao/languages/es/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/it/tl_form.xlf
  core-bundle/src/Resources/contao/languages/it/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_form.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_form.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_form.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_form.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_settings.xlf
Labels: release

#3282 Fix compatibility with PHP 8.1
  .github/workflows/ci.yml
  core-bundle/src/Resources/contao/library/Contao/Model/Collection.php
  core-bundle/src/Resources/contao/library/Contao/Model/Registry.php
  core-bundle/src/Session/Attribute/ArrayAttributeBag.php
  core-bundle/src/Session/LazySessionAccess.php
  manager-bundle/src/ContaoManager/Plugin.php
  tools/ecs/composer.lock
Labels: CI

#3287 Add the security fixes to the changelog
  CHANGELOG.md
Labels: release

#3288 Merge branch '4.9' into 4.11
  .github/workflows/ci.yml
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/FrontendUser.php
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  core-bundle/src/Resources/contao/library/Contao/Model/Collection.php
  core-bundle/src/Resources/contao/library/Contao/Model/Registry.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
  core-bundle/src/Resources/contao/library/Contao/ZipWriter.php
  core-bundle/src/Routing/Candidates/AbstractCandidates.php
  core-bundle/src/Session/Attribute/ArrayAttributeBag.php
  core-bundle/src/Session/LazySessionAccess.php
  core-bundle/tests/Contao/ModuleTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: release

#3289 Merge branch '4.11' into 4.12
  .github/workflows/ci.yml
  calendar-bundle/src/EventListener/InsertTagsListener.php
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/config/default.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_settings.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/elements/ContentMarkdown.php
  core-bundle/src/Resources/contao/helper/functions.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_form.xlf
  core-bundle/src/Resources/contao/languages/en/tl_settings.xlf
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Model/Collection.php
  core-bundle/src/Resources/contao/library/Contao/Model/Registry.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/src/Session/Attribute/ArrayAttributeBag.php
  core-bundle/src/Session/LazySessionAccess.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Contao/TemplateTest.php
  faq-bundle/src/EventListener/InsertTagsListener.php
  manager-bundle/src/ContaoManager/Plugin.php
  news-bundle/src/EventListener/InsertTagsListener.php
  tools/ecs/composer.lock
Labels: release

#3275 Fix missing tooltips for widget help text
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
Labels: bug

#3291 Fix the "iflng" and "ifnlng" insert tags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#3293 Do not show the urlattr flag for rgxp url fields
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#3297 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_settings.xlf
Labels: release

#3298 Merge branch '4.9' into 4.11
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: release

#3299 Update the changelog and the language files
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_settings.xlf
Labels: release

#3295 Fix the "iflng" and "ifnlng" insert tags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#3278 Check if stopwatch is started before stopping
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#3311 Fix version creation for entries with dynamic ptable
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#3315 Do not encode special characters if no tags are allowed
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#3319 Correctly encode HTML comments, <script> and <style> tags
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#3323 Remove reference to other table from column classname in DC_Table
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3321 Correctly explode foreign keys in the DCA
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
Labels: bug

#3303 Warn if the DB server is not running in strict mode
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/InstallTool.php
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.en.xlf
  installation-bundle/src/Resources/views/main.html.twig
  installation-bundle/tests/InstallToolTest.php
Labels: bug

#3314 Add support for namespaced attributes
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#3335 Merge branch '4.9' into 4.11
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/InstallTool.php
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.en.xlf
  installation-bundle/src/Resources/views/main.html.twig
  installation-bundle/tests/InstallToolTest.php
Labels: release

#3308 Fix undefined array keys
  core-bundle/src/Resources/contao/classes/StyleSheets.php
Labels: bug

#3336 Merge branch '4.11' into 4.12
  core-bundle/src/Resources/contao/classes/StyleSheets.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: release

#3337 Strip attributes in markdown element
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
Labels: bug

#3340 Fix another undefined array key warning
  core-bundle/src/Resources/contao/library/Contao/Model/QueryBuilder.php
Labels: bug

#3341 Clarify contao.preview_script usage
  core-bundle/src/DependencyInjection/Configuration.php
Labels: bug

#3339 Allow Twig v3
  composer.json
  core-bundle/composer.json
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/Twig/Inheritance/DynamicIncludeTokenParserTest.php
  manager-bundle/composer.json
Labels: bug

#3343 Make the ContaoFilesystemLoader compatible with Symfony 4.4
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
Labels: bug

#3348 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_settings.xlf
Labels: release

#3189 Bump target versions in markdown docs
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/1_Bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CI

#3327 Do not encode special characters if no tags are allowed
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#3328 Improve compatibility with JSON in attributes
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#3331 Do not show the urlattr flag for rgxp url fields
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#3332 Fix the "iflng" and "ifnlng" insert tags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#3330 Add support for namespaced attributes
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#3333 Correctly encode HTML comments, <script> and <style> tags
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#3356 Make the metadata available in the download element
  core-bundle/src/Resources/contao/elements/ContentDownload.php
Labels: bug

#3346 Fix versioning condition in DC_Folder edit action
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#3359 Fix the media element migration
  core-bundle/src/Migration/Version408/Version480Update.php
Labels: bug

#3310 Add the "dry-run" and "format=ndjson" options to the migrate command
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: bug

#3367 Handle insert tag flags in the picker
  calendar-bundle/src/Picker/EventPickerProvider.php
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/src/Picker/AbstractInsertTagPickerProvider.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/FilePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/tests/Picker/ArticlePickerProviderTest.php
  core-bundle/tests/Picker/FilePickerProviderTest.php
  core-bundle/tests/Picker/PagePickerProviderTest.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  news-bundle/src/Picker/NewsPickerProvider.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
Labels: bug

#3360 Use intl for text direction
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
Labels: bug

#3369 Fix using insert tags in the page title
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#3372 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  calendar-bundle/src/Resources/contao/languages/sl/default.xlf
  calendar-bundle/src/Resources/contao/languages/sl/tl_calendar.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_user.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/exception.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_module.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  faq-bundle/src/Resources/contao/languages/sl/tl_faq_category.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.de.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.es.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.fr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.it.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ja.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.nl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.pl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ru.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sv.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.tr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.zh.xlf
  listing-bundle/src/Resources/contao/languages/sl/tl_module.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.sl.xlf
  news-bundle/src/Resources/contao/languages/sl/tl_module.xlf
  news-bundle/src/Resources/contao/languages/sl/tl_news_archive.xlf
  newsletter-bundle/src/Resources/contao/languages/sl/tl_module.xlf
Labels: release

#3373 Merge branch '4.9' into 4.11
  calendar-bundle/src/Picker/EventPickerProvider.php
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Migration/Version408/Version480Update.php
  core-bundle/src/Picker/AbstractInsertTagPickerProvider.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/FilePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/elements/ContentDownload.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Picker/ArticlePickerProviderTest.php
  core-bundle/tests/Picker/FilePickerProviderTest.php
  core-bundle/tests/Picker/PagePickerProviderTest.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  news-bundle/src/Picker/NewsPickerProvider.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
Labels: release

#3374 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_user.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_form.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/exception.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_module.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  faq-bundle/src/Resources/contao/languages/fa/tl_faq.xlf
  faq-bundle/src/Resources/contao/languages/sl/tl_faq_category.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.de.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.es.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.fr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.it.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ja.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.nl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.pl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ru.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sv.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.tr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.zh.xlf
  listing-bundle/src/Resources/contao/languages/sl/modules.xlf
  listing-bundle/src/Resources/contao/languages/sl/tl_module.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.sl.xlf
  news-bundle/src/Resources/contao/languages/sl/tl_module.xlf
  news-bundle/src/Resources/contao/languages/sl/tl_news_archive.xlf
  newsletter-bundle/src/Resources/contao/languages/sl/tl_module.xlf
Labels: release

#3375 Merge branch '4.11' into 4.12
  calendar-bundle/src/Picker/EventPickerProvider.php
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Migration/Version408/Version480Update.php
  core-bundle/src/Picker/AbstractInsertTagPickerProvider.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/FilePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/elements/ContentDownload.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Model/QueryBuilder.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Picker/ArticlePickerProviderTest.php
  core-bundle/tests/Picker/FilePickerProviderTest.php
  core-bundle/tests/Picker/PagePickerProviderTest.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  news-bundle/src/Picker/NewsPickerProvider.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
Labels: release

#3353 Fix dynamic debug mode for templates
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php
  core-bundle/tests/Contao/TemplateTest.php
Labels: bug

#3365 Use 4 spaces to indent the strict mode notice
  installation-bundle/src/Resources/views/main.html.twig
Labels: bug

#3368 Fix another invalid array access
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#3378 Pass contao.web_dir to the contao:install-web-dir command
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
Labels: bug

#3380 Also convert the page title to plain text in the response context
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
Labels: bug

#3296 Fix a phpDoc comment in the Pagination class
  core-bundle/src/Resources/contao/library/Contao/Pagination.php
Labels: bug

#3383 Fix the default quote style
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
Labels: bug

#3390 Fix simple token parsing in HTML
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug

#3352 Also pass the template object in the "parseFrontendTemplate" hook
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
Labels: feature

#3402 Fix the `Adapter::__call()` method signature
  core-bundle/src/Framework/Adapter.php
Labels: bug

#3404 Fix simple token parsing in HTML
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Util/SimpleTokenParser.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Util/SimpleTokenParserTest.php
Labels: bug
