Repository contao/contao, pull requests merged in 2021-07, with the labels that each got.

#3137 Fix the functional tests
  core-bundle/src/Resources/contao/library/Contao/ClassLoader.php
  core-bundle/tests/Functional/RoutingTest.php
Labels: CI

#3136 Make sure that deserialized groups are always an array
  calendar-bundle/src/Resources/contao/classes/Events.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#3140 Add @phpstan-var to an inline phpDoc comment
  core-bundle/src/Resources/contao/library/Contao/Model.php
Labels: CI

#3141 Deprecate using tabindex values greater than 0
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/widgets/ListWizard.php
Labels: bug

#3111 Fix the unit and functional tests on PHP 8.1
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/tests/Functional/app/config/config_test.yml
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: CI

#3147 Add back the "guests" checkbox
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  comments-bundle/src/Resources/contao/dca/tl_content.php
  comments-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Migration/Version412/MergeGuestsOnlyMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/languages/en/tl_article.xlf
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Database/Updater.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/ModuleModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  faq-bundle/src/Resources/contao/dca/tl_module.php
  listing-bundle/src/Resources/contao/dca/tl_module.php
  news-bundle/src/Resources/contao/dca/tl_module.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
Labels: bug

#3149 Update the CI tools
  calendar-bundle/composer.json
  composer.json
  core-bundle/composer.json
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/FigureRendererTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  faq-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI

#3124 Use a security voter to check the member groups
  calendar-bundle/src/Resources/contao/classes/Events.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/tests/Security/Voter/MemberGroupVoterTest.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: feature

#3148 Filter "guests only" pages to restore backwards compatibility
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
Labels: bug

#3103 Allow to exclude fields in the file manager
  core-bundle/src/Migration/Version412/AllowedExcludedFieldsMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_files.php
Labels: feature

#3152 Fix the CI
  core-bundle/src/Monolog/ContaoTableProcessor.php
  core-bundle/tests/Crawl/Monolog/CrawlCsvLogHandlerTest.php
  core-bundle/tests/Monolog/ContaoTableHandlerTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI

#3153 Fix the remaining deprecated DBAL methods and some other issues
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/Migration/Version404/Version447Update.php
  core-bundle/src/Migration/Version411/TwoFactorBackupCodesMigration.php
  core-bundle/src/Monolog/ContaoTableProcessor.php
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/Database/ConnectionFactory.php
  installation-bundle/src/InstallTool.php
Labels: CI

#2305 Use Locale IDs for tl_page.language
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/EventListener/BackendLocaleListener.php
  core-bundle/src/EventListener/DataContainer/LegacyRoutingListener.php
  core-bundle/src/EventListener/LocaleSubscriber.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Migration/Version412/PageLanguageMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/controllers/BackendIndex.php
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/elements/ContentMedia.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/pages/PageError404.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/Routing/Enhancer/InputEnhancer.php
  core-bundle/src/Routing/Matcher/LanguageFilter.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/UrlGenerator.php
  core-bundle/src/Util/LocaleUtil.php
  core-bundle/tests/EventListener/LocaleSubscriberTest.php
  core-bundle/tests/Fixtures/Functional/Routing/issue-2819.yml
  core-bundle/tests/Fixtures/Functional/Routing/language-and-region.yml
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Routing/AbstractPageRouteProviderTest.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
  core-bundle/tests/Routing/PageUrlGeneratorTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: feature

#3154 Do not override the global language in some front end modules
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#3156 Use schema.org JSON-LD in the breadcrumb module
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Resources/contao/templates/modules/mod_breadcrumb.html5
Labels: feature

#3158 Undeprecate the "importUser" hook
  core-bundle/src/Resources/contao/library/Contao/User.php
Labels: bug

#3155 Use schema.org JSON-LD in the calendar-bundle
  calendar-bundle/src/Resources/contao/classes/Events.php
  calendar-bundle/src/Resources/contao/languages/en/default.xlf
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  calendar-bundle/src/Resources/contao/templates/calendar/cal_default.html5
  calendar-bundle/src/Resources/contao/templates/events/event_full.html5
  calendar-bundle/src/Resources/contao/templates/events/event_list.html5
  calendar-bundle/src/Resources/contao/templates/events/event_teaser.html5
  calendar-bundle/src/Resources/contao/templates/events/event_upcoming.html5
Labels: feature

#3162 Remove two left-over itemprop attributes
  calendar-bundle/src/Resources/contao/templates/events/event_full.html5
  core-bundle/src/Resources/contao/templates/picture/picture_default.html5
Labels: bug

#3165 Prevent an "undefined property" error in the Model class
  core-bundle/src/Resources/contao/library/Contao/Model.php
Labels: bug

#3161 Unify the schema.org helper methods
  calendar-bundle/src/Resources/contao/classes/Events.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  calendar-bundle/src/Resources/contao/templates/events/event_full.html5
  calendar-bundle/src/Resources/contao/templates/events/event_list.html5
  calendar-bundle/src/Resources/contao/templates/events/event_teaser.html5
  calendar-bundle/src/Resources/contao/templates/events/event_upcoming.html5
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Resources/contao/templates/modules/mod_breadcrumb.html5
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
  news-bundle/src/Resources/contao/templates/news/news_full.html5
  news-bundle/src/Resources/contao/templates/news/news_latest.html5
  news-bundle/src/Resources/contao/templates/news/news_short.html5
  news-bundle/src/Resources/contao/templates/news/news_simple.html5
Labels: bug

#3150 Always use the security voter to check member groups
  core-bundle/src/Resources/contao/classes/FrontendUser.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/tests/Security/Voter/MemberGroupVoterTest.php
Labels: bug

#3163 Remove left-over itemprop usages
  UPGRADE.md
  core-bundle/src/Resources/contao/templates/gallery/gallery_default.html5
  core-bundle/src/Resources/contao/templates/modules/mod_navigation.html5
  core-bundle/src/Resources/contao/templates/navigation/nav_default.html5
Labels: bug

#3168 CS
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: CI

#3166 Revert 'Lazy-load the `rootFallbackLanguage` property'
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#3164 Deprecate the getSearchablePages() method
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: bug

#3169 Code inspector cleanup
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/controllers/BackendFile.php
  core-bundle/src/Resources/contao/controllers/BackendPage.php
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Picture.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/library/Contao/Validator.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/widgets/TableWizard.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: CI

#3167 Use schema.org JSON-LD in the faq-bundle
  faq-bundle/src/Resources/contao/modules/ModuleFaq.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  faq-bundle/src/Resources/contao/templates/modules/mod_faqpage.html5
  faq-bundle/src/Resources/contao/templates/modules/mod_faqreader.html5
Labels: feature

#3171 Code inspector cleanup
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/controllers/BackendFile.php
  core-bundle/src/Resources/contao/controllers/BackendPage.php
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Picture.php
  core-bundle/src/Resources/contao/library/Contao/Validator.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/widgets/TableWizard.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: CI

#3047 Update the YouTube options
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/elements/ContentYouTube.php
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/templates/elements/ce_youtube.html5
Labels: bug

#3173 Fix the PHP 8.1 CI job
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/tests/Functional/app/config/config_test.yml
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: CI

#3174 Correctly handle form fields in DC_Folder in "editAll" mode
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#3151 Enforce the MySQL strict mode
  installation-bundle/src/InstallTool.php
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.en.xlf
  installation-bundle/src/Resources/views/configuration_error.html.twig
  installation-bundle/tests/InstallToolTest.php
Labels: feature

#3175 Only warn if the DB server is not running in strict mode
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/InstallTool.php
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.en.xlf
  installation-bundle/src/Resources/views/configuration_error.html.twig
  installation-bundle/src/Resources/views/main.html.twig
  installation-bundle/tests/InstallToolTest.php
Labels: bug

#3170 JSON-LD support for Twig
  core-bundle/src/Resources/views/Image/Studio/_macros.html.twig
  core-bundle/src/Twig/Extension/ContaoTemplateExtension.php
  core-bundle/src/Twig/Runtime/SchemaOrgRuntime.php
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/Twig/Runtime/SchemaOrgRuntimeTest.php
Labels: bug

#3176 Remove the service definition tests
  calendar-bundle/tests/DependencyInjection/ContaoCalendarExtensionTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  faq-bundle/tests/DependencyInjection/ContaoFaqExtensionTest.php
  manager-bundle/tests/DependencyInjection/ContaoManagerExtensionTest.php
  news-bundle/tests/DependencyInjection/ContaoNewsExtensionTest.php
Labels: CI

#3177 Exclude the migrations from coverage
  phpunit.xml.dist
Labels: CI

#3181 CS fixes that went unnoticed
  calendar-bundle/src/Resources/contao/templates/events/event_full.html5
  calendar-bundle/src/Resources/contao/templates/events/event_teaser.html5
  calendar-bundle/src/Resources/contao/templates/events/event_upcoming.html5
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/templates/modules/mod_breadcrumb.html5
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  tools/ecs/composer.lock
Labels: CI

#3179 Backport support for namespaced DC drivers
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/controllers/BackendFile.php
  core-bundle/src/Resources/contao/controllers/BackendPage.php
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug

#3183 Also exempt entities from coverage
  core-bundle/phpunit.xml.dist
  phpunit.xml.dist
Labels: CI

#3182 Simplify Controller::addImageToTemplate tests
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
Labels: bug

#3138 Use intl for languages and countries
  composer.json
  core-bundle/composer.json
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPass.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/LocaleSubscriber.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Intl/Countries.php
  core-bundle/src/Intl/Locales.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/config/countries.php
  core-bundle/src/Resources/contao/config/languages.php
  core-bundle/src/Resources/contao/controllers/BackendIndex.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/languages/en/countries.xlf
  core-bundle/src/Resources/contao/languages/en/languages.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
  core-bundle/tests/Command/UserCreateCommandTest.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPassTest.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/EventListener/LocaleSubscriberTest.php
  core-bundle/tests/Intl/CountriesTest.php
  core-bundle/tests/Intl/LocalesTest.php
  monorepo.yml
Labels: feature

#3193 Update the tools
  core-bundle/src/Intl/Locales.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Intl/CountriesTest.php
  core-bundle/tests/Intl/LocalesTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
Labels: CI

#3194 Fix the prefer-lowest tests
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: CI

#3195 Do not prefix our JSON-LD context
  core-bundle/src/Routing/ResponseContext/JsonLd/ContaoPageSchema.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Search/DocumentTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: bug

#3196 Support multiple JSON+LD objects in the search document
  core-bundle/src/Search/Document.php
  core-bundle/tests/Search/DocumentTest.php
Labels: bug

#3202 Sanity check template names in FigureRenderer
  core-bundle/src/Image/Studio/FigureRenderer.php
  core-bundle/tests/Image/Studio/FigureRendererTest.php
Labels: bug

#3206 Fix deprecations in test suite
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Contao/RoutingTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/PhpunitExtension/DeprecatedClasses.php
  core-bundle/tests/Routing/FrontendLoaderTest.php
  core-bundle/tests/Routing/LegacyRouteProviderTest.php
  core-bundle/tests/Routing/UrlGeneratorTest.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
Labels: CI

#3216 Add Google Conversion Linker cookie to deny list
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
Labels: bug

#3210 Ensure the numberOfItems label does refer to items only
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
Labels: bug

#3217 Allow robots setting for redirect pages
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#3203 Fix extending multiple levels of Contao templates
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Fixtures/Twig/legacy/templates/bar.html5
  core-bundle/tests/Fixtures/Twig/legacy/templates/baz.html5
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: bug

#3208 Always concatenate the 'image_container' class in figure.html.twig
  core-bundle/src/Resources/views/Image/Studio/figure.html.twig
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
Labels: bug

#3204 Implement a contao_ variant of the html_attr escaper
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Interop/ContaoEscaper.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperTest.php
Labels: bug

#3221 Remove the dev firewall
  manager-bundle/src/Resources/skeleton/config/security.yml
Labels: bug

#3201 Only create proxy templates for '@Contao' namespaced templates
  core-bundle/src/Twig/ContaoTwigUtil.php
  core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/src/Twig/Inheritance/TokenParserHelper.php
  core-bundle/src/Twig/Interop/PhpTemplateProxyNodeVisitor.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Twig/ContaoTwigUtilTest.php
  core-bundle/tests/Twig/Inheritance/TokenParserHelperTest.php
  core-bundle/tests/Twig/Interop/PhpTemplateProxyNodeVisitorTest.php
Labels: bug

#3223 Fix the CI chain
  core-bundle/tests/EventListener/MakeResponsePrivateListenerTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI

#3222 Backport CI fixes from #3152 and #3137
  core-bundle/src/Monolog/ContaoTableProcessor.php
  core-bundle/src/Resources/contao/library/Contao/ClassLoader.php
  core-bundle/tests/Crawl/Monolog/CrawlCsvLogHandlerTest.php
  core-bundle/tests/Monolog/ContaoTableHandlerTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
  tools/phpstan/composer.lock
Labels: CI

#3229 Add note that Figure will be final in Contao 5
  core-bundle/src/Image/Studio/Figure.php
Labels: bug

#3227 Use ClockMock for time sensitive test
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  phpunit.xml.dist
Labels: bug

#3190 Consider the robots.txt content in the SearchIndexSubscriber
  composer.json
  core-bundle/composer.json
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
Labels: bug

#3197 Allow defining entities alongside DCA definitions
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
Labels: bug

#3218 Do not start the session in the login module
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
Labels: bug

#3231 Fix the tools
  tools/ecs/composer.lock
Labels: CI

#3220 Correctly clean up left-over records in DCA mode 5
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: bug

#3233 Fix session service check in AddSessionBagsPass
  core-bundle/src/DependencyInjection/Compiler/AddSessionBagsPass.php
  core-bundle/tests/DependencyInjection/Compiler/AddSessionBagsPassTest.php
Labels: bug
