Repository contao/contao, pull requests merged in 2021-06, with the labels that each got.

#3041 Use a better label for the password confirmation field
  core-bundle/src/Resources/contao/languages/en/default.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.en.xlf
Labels: bug

#3048 Fix another PHP 8 "undefined array key" issue
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#3051 Remove the `addWizardClass` workaround
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/icons/alias.svg
  core-bundle/src/Resources/contao/themes/flexible/icons/pickpage.svg
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: feature

#2960 Protect users against Google FLoC
  core-bundle/src/Resources/contao/library/Contao/Template.php
Labels: feature

#3046 Add the "findCalendarBoundaries" hook
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
Labels: bug

#3049 Get rid of more unit test deprecations
  composer.json
  core-bundle/composer.json
  core-bundle/src/EventListener/TwoFactorFrontendListener.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Logout/LogoutHandler.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Logout/LogoutHandlerTest.php
  installation-bundle/composer.json
  manager-bundle/composer.json
Labels: CI

#3042 Handle non-string arguments in the `FilesModel::findByPath()` method
  core-bundle/src/Resources/contao/models/FilesModel.php
Labels: bug

#3043 Rename the close button at the bottom of the modal window
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#3014 Ensure clean response context and unify meta handling
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/templates/frontend/fe_page.html5
  core-bundle/src/Routing/ResponseContext/ContaoWebpageResponseContext.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Routing/ResponseContext/ContaoWebpageResponseContextTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
Labels: feature

#3054 Fix a language typo
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
Labels: bug

#3058 Do not cast the picker values to integers
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug

#3057 Sort routes by region if no preferred language matches
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/Routing/Matcher/LanguageFilter.php
  core-bundle/tests/Fixtures/Functional/Routing/language-and-region.yml
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Routing/AbstractPageRouteProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: feature

#3059 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_content.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/de/tl_content.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/modules.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_module.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_user.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/it/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_content.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_content.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_content.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.cs.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.de.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.es.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.fr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.it.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ja.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.nl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.pl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ru.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sv.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.tr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.zh.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.de.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.ja.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.ru.xlf
Labels: release

#3061 Merge branch '4.9' into 4.11
  CONTRIBUTORS.md
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/FilesModel.php
  core-bundle/src/Resources/contao/models/FormFieldModel.php
  core-bundle/src/Resources/contao/widgets/Picker.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.en.xlf
Labels: release

#3063 Backport the CI fixes
  .github/workflows/ci.yml
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: CI

#3071 Update the changelog and the language files
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_content.xlf
  core-bundle/src/Resources/contao/languages/de/countries.xlf
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/de/tl_content.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/modules.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_module.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_user.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/it/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_content.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_content.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_content.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.cs.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.de.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.es.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.fr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.it.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ja.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.nl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.pl.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ru.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sv.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.tr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.zh.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.de.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.ja.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.ru.xlf
Labels: release

#2931 Fix filtering for recurring events
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
Labels: bug

#3073 Allow null in FigureBuilder#from()
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#3075 Harden `FigureBuilder::from()` against invalid types
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#3055 Add an enhanced Markdown content element
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/config/default.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/elements/ContentMarkdown.php
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/FilesModel.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
Labels: feature

#3052 Remove the password confirmation field
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/controllers/BackendPassword.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/forms/FormPassword.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/templates/backend/be_password.html5
  core-bundle/src/Resources/contao/templates/backend/be_widget_pw.html5
  core-bundle/src/Resources/contao/templates/forms/form_password.html5
  core-bundle/src/Resources/contao/templates/forms/form_row_double.html5
  core-bundle/src/Resources/contao/widgets/Password.php
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.en.xlf
  installation-bundle/src/Resources/views/main.html.twig
  installation-bundle/src/Resources/views/password.html.twig
Labels: feature

#3076 Add a license field to the file metadata
  core-bundle/src/File/Metadata.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/tests/File/MetadataTest.php
Labels: feature

#3079 Fix another invalid array access
  core-bundle/src/Resources/contao/elements/ContentProxy.php
Labels: bug

#3053 Add a page controller for root pages
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/Page/RootPageController.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/contao/pages/PageRoot.php
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/tests/Controller/Page/RootPageControllerTest.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Functional/app/AppKernel.php
  core-bundle/tests/Functional/app/config/config_test.yml
Labels: feature

#3066 Rework the response context
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Routing/ResponseContext/ContaoWebpageResponseContext.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/HtmlHeadBag/HtmlHeadBag.php
  core-bundle/src/Routing/ResponseContext/ResponseContext.php
  core-bundle/src/Routing/ResponseContext/ResponseContextAccessor.php
  core-bundle/src/Routing/ResponseContext/ResponseContextInterface.php
  core-bundle/tests/Routing/ResponseContext/ContaoWebpageResponseContextTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/HtmlHeadBag/HtmlHeadBagTest.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextAccessorTest.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextTest.php
  core-bundle/tests/Routing/ResponseContext/WebpageResponseContextTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
Labels: feature

#3080 Reduce memory consumption in search
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/library/Contao/SearchResult.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
Labels: feature

#3083 Fix the indentation in the news_full template
  news-bundle/src/Resources/contao/templates/news/news_full.html5
Labels: bug

#3082 Remove the technical details from the default search template
  core-bundle/src/Resources/contao/templates/modules/mod_search.html5
  core-bundle/src/Resources/contao/templates/search/search_default.html5
Labels: feature

#3085 Do not disable search and cache in FAQ and newsletter readers
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
Labels: bug

#3087 Remove two superfluous labels
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#3094 Revert a change in the services.php file
  core-bundle/src/Resources/contao/library/Contao/User.php
  manager-bundle/src/Resources/skeleton/config/services.php
Labels: CI

#3084 Rename the `web` folder to `public`
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/EventListener/InsecureInstallationListener.php
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
  core-bundle/src/Resources/contao/library/Contao/Image.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/tests/Command/InstallCommandTest.php
  core-bundle/tests/Command/SymlinksCommandTest.php
  core-bundle/tests/Contao/CombinerTest.php
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/Contao/PictureTest.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/EventListener/InsecureInstallationListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  manager-bundle/src/Command/InstallWebDirCommand.php
  manager-bundle/src/Resources/skeleton/public/.htaccess
  manager-bundle/src/Resources/skeleton/public/app.php
  manager-bundle/src/Resources/skeleton/public/index.php
  manager-bundle/src/Resources/skeleton/public/preview.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
  manager-bundle/tests/Command/InstallWebDirCommandTest.php
Labels: feature

#3092 Remove redundant arguments from private methods
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/tests/Command/UserListCommandTest.php
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/EventListener/SubrequestCacheSubscriberTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServicesTest.php
  manager-bundle/src/Composer/ScriptHandler.php
Labels: CI

#3098 Automatically inject container for tagged controllers
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterPagesPassTest.php
  core-bundle/tests/Fixtures/src/Controller/Page/TestPageController.php
Labels: bug

#3088 Add a guests group to the list of allowed groups
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  comments-bundle/src/Resources/contao/dca/tl_content.php
  comments-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/EventListener/DataContainer/MemberGroupsListener.php
  core-bundle/src/Migration/Version412/MergeGuestsOnlyMigration.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_article.xlf
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Database/Updater.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/ModuleModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/EventListener/DataContainer/MemberGroupsListenerTest.php
  faq-bundle/src/Resources/contao/dca/tl_module.php
  listing-bundle/src/Resources/contao/dca/tl_module.php
  news-bundle/src/Resources/contao/dca/tl_module.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
Labels: feature

#3081 Fix the unit tests on PHP 8.1
  manager-bundle/src/ContaoManager/Plugin.php
Labels: CI

#3102 Allow direct links to public files in the file picker
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: feature

#3090 Allow empty content element translation key
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#2962 Centralize the JSON-LD metadata management
  comments-bundle/src/Resources/contao/classes/Comments.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/Event/AbstractResponseContextEvent.php
  core-bundle/src/Event/JsonLdEvent.php
  core-bundle/src/EventListener/ContaoJsonLdSchemaListener.php
  core-bundle/src/File/Metadata.php
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/templates/frontend/fe_page.html5
  core-bundle/src/Resources/contao/templates/image/image.html5
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/JsonLd/ContaoPageSchema.php
  core-bundle/src/Routing/ResponseContext/JsonLd/JsonLdManager.php
  core-bundle/src/Routing/ResponseContext/ResponseContext.php
  core-bundle/tests/Event/JsonEventTest.php
  core-bundle/tests/EventListener/ContaoJsonLdSchemaListenerTest.php
  core-bundle/tests/File/MetadataTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/JsonLd/ContaoPageSchemaTest.php
  core-bundle/tests/Routing/ResponseContext/JsonLd/JsonLdManagerTest.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextTest.php
Labels: feature

#3112 Use "anon." as username if authentication fails
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/tests/Security/Authentication/AuthenticationFailureHandlerTest.php
Labels: bug

#3113 Use "anon." as username if authentication fails
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/tests/Security/Authentication/AuthenticationFailureHandlerTest.php
Labels: bug

#3114 Merge branch '4.9' into 4.11
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/phpunit.xml.dist
  core-bundle/src/Cron/PurgeExpiredDataCron.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/tests/Cron/PurgeExpiredDataCronTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  manager-bundle/src/ContaoManager/Plugin.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  news-bundle/src/Resources/contao/templates/news/news_full.html5
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
  phpunit.xml.dist
Labels: release

#3115 Merge branch '4.11' into 4.x
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/phpunit.xml.dist
  core-bundle/src/Cron/PurgeExpiredDataCron.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentProxy.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/tests/Cron/PurgeExpiredDataCronTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterPagesPassTest.php
  core-bundle/tests/Fixtures/src/Controller/Page/TestPageController.php
  core-bundle/tests/Security/Authentication/AuthenticationFailureHandlerTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  manager-bundle/src/ContaoManager/Plugin.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  news-bundle/src/Resources/contao/templates/news/news_full.html5
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
  phpunit.xml.dist
Labels: release

#3107 Add the default WebPage schema.org data again
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
Labels: feature

#3100 Use HTTPS for all schema.org links
  UPGRADE.md
  calendar-bundle/src/Resources/contao/templates/calendar/cal_default.html5
  calendar-bundle/src/Resources/contao/templates/events/event_full.html5
  calendar-bundle/src/Resources/contao/templates/events/event_list.html5
  calendar-bundle/src/Resources/contao/templates/events/event_teaser.html5
  calendar-bundle/src/Resources/contao/templates/events/event_upcoming.html5
  core-bundle/src/Resources/contao/templates/gallery/gallery_default.html5
  core-bundle/src/Resources/contao/templates/modules/mod_breadcrumb.html5
  core-bundle/src/Resources/contao/templates/modules/mod_navigation.html5
  core-bundle/src/Resources/views/Image/Studio/_macros.html.twig
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  news-bundle/src/Resources/contao/templates/news/news_full.html5
  news-bundle/src/Resources/contao/templates/news/news_latest.html5
  news-bundle/src/Resources/contao/templates/news/news_short.html5
  news-bundle/src/Resources/contao/templates/news/news_simple.html5
Labels: feature

#3110 Add the `rawPlainText()` and `rawHtmlToPlainText()` template helper methods
  core-bundle/src/Resources/contao/library/Contao/Template.php
Labels: feature

#3106 Update the tools
  composer.json
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI

#3118 Update the CI tools
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/FrontendUser.php
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
  core-bundle/src/Resources/contao/library/Contao/ZipWriter.php
  core-bundle/src/Routing/Candidates/AbstractCandidates.php
  core-bundle/tests/Contao/ModuleTest.php
  tools/ecs/composer.json
  tools/ecs/composer.lock
Labels: CI

#3123 Fix another invalid array access in ModuleProxy
  core-bundle/src/Resources/contao/modules/ModuleProxy.php
Labels: bug

#3120 Beautify the JSON-LD by sorting by key
  core-bundle/src/Resources/contao/library/Contao/ArrayUtil.php
  core-bundle/src/Routing/ResponseContext/JsonLd/JsonLdManager.php
  core-bundle/tests/Contao/ArrayUtilTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Routing/ResponseContext/JsonLd/JsonLdManagerTest.php
Labels: feature

#2940 Show the Contao layout in the Symfony profiler
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: feature

#3119 Use schema.org JSON-LD in the news-bundle
  news-bundle/src/Resources/contao/modules/ModuleNews.php
  news-bundle/src/Resources/contao/templates/news/news_full.html5
  news-bundle/src/Resources/contao/templates/news/news_latest.html5
  news-bundle/src/Resources/contao/templates/news/news_short.html5
  news-bundle/src/Resources/contao/templates/news/news_simple.html5
Labels: feature

#2958 Fix the tooltips in the JavaScript wizards
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
Labels: bug

#3077 Correctly render showColumns in the picker widget
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/Picker.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#3125 Check if tstamp exists before hiding unsaved element
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
Labels: bug

#3130 Add more null checks for DCA lang references
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
Labels: bug

#3135 Handle protected pages in the "quicklink" module
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
Labels: feature
