Repository contao/contao, pull requests merged in 2021-10, with the labels that each got.

#3503 Correctly handle empty image size formats
  core-bundle/src/Image/PictureFactory.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: bug

#3526 Improve the JwtManager
  manager-bundle/src/HttpKernel/JwtManager.php
Labels: bug

#3391 Always show the parent trails in the tree view
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Database.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: feature

#3534 Translate all languages in the file meta data
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
Labels: bug

#3496 Handle edge cases in StringUtil::convertEncoding()
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug

#3537 Harden more time-sensitive tests
  core-bundle/phpunit.xml.dist
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
Labels: bug

#3543 Fix the meta wizard language menu
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
Labels: bug

#3545 Merge branch '4.9' into 4.12
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
  manager-bundle/src/HttpKernel/JwtManager.php
Labels: release

#3546 Merge branch '4.12' into 4.x
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/phpunit.xml.dist
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  manager-bundle/src/HttpKernel/JwtManager.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: release

#3544 Only add regular pages to the sitemap
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: bug

#3553 Enable parallel execution in ECS
  core-bundle/tests/Contao/StringUtilTest.php
  tools/ecs/composer.lock
  tools/psalm/composer.lock
Labels: CI
