Repository contao/contao, pull requests merged in 2021-01, with the labels that each got.

#2611 Update the TODOs
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Resources/config/services.yml
  psalm.xml
Labels: feature

#2475 Adjust the PictureInterface for Contao 5
  core-bundle/src/Image/PictureFactoryInterface.php
  phpstan.neon.dist
Labels: bug

#2623 Fix the Psalm configuration
  psalm.xml
Labels: CI

#1301 Implement real URL in preview toolbar
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: feature

#1779 Allow to override page title and description in FAQs
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  faq-bundle/src/Resources/contao/languages/en/tl_faq.xlf
  faq-bundle/src/Resources/contao/models/FaqModel.php
  faq-bundle/src/Resources/contao/modules/ModuleFaq.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
Labels: feature

#2554 Support native transport and other mailer transport options
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/AddNativeTransportFactoryPass.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddNativeTransportFactoryPassTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: feature

#2438 Remove the CDN integration of MooTools and jQuery
  UPGRADE.md
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/languages/en/tl_layout.xlf
  core-bundle/src/Resources/contao/models/LayoutModel.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
Labels: feature

#1937 Allow rendering a Figure inline from PHP templates
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/tests/Contao/TemplateTest.php
Labels: feature

#2605 Symlink the highlight.php styles folder
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/Resources/contao/elements/ContentCode.php
  core-bundle/src/Resources/contao/templates/elements/ce_code.html5
Labels: bug

#2232 Auto configure doctrine.orm.mappings for app entities
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
  manager-bundle/tests/Fixtures/app-with-entities/src/Entity/.gitignore
  manager-bundle/tests/Fixtures/app/.gitignore
Labels: feature

#2615 Fix news link markup
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#2617 Adjust Contao 2FA implementation to scheb/2fa 5.x / PHP 8 compatibility
  composer.json
  core-bundle/composer.json
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/DependencyInjection/Security/ContaoLoginFactoryTest.php
  core-bundle/tests/Functional/app/config/config_test.yml
  core-bundle/tests/Security/Authentication/ContaoLoginAuthenticationListenerTest.php
  manager-bundle/src/HttpKernel/JwtManager.php
  manager-bundle/src/Resources/skeleton/config/config.yml
Labels: bug

#2625 Merge branch '4.9' into 4.10
  .github/workflows/ci.yml
  .gitignore
  .yamllint
  README.md
  calendar-bundle/composer.json
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/DependencyInjection/Security/ContaoLoginFactoryTest.php
  core-bundle/tests/Functional/app/config/config_test.yml
  core-bundle/tests/Security/Authentication/ContaoLoginAuthenticationListenerTest.php
  faq-bundle/composer.json
  installation-bundle/composer.json
  manager-bundle/composer.json
  manager-bundle/src/HttpKernel/JwtManager.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  monorepo.yml
  news-bundle/composer.json
  news-bundle/src/Resources/contao/modules/ModuleNews.php
  phpstan.neon.dist
  psalm.xml
  tools/ecs/composer.json
  tools/monorepo/composer.json
  tools/phpstan/composer.json
  tools/psalm/composer.json
Labels: release

#2555 Do not return empty strings in the link_url insert tag
  calendar-bundle/src/EventListener/InsertTagsListener.php
  calendar-bundle/tests/EventListener/InsertTagsListenerTest.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  faq-bundle/src/EventListener/InsertTagsListener.php
  faq-bundle/tests/EventListener/InsertTagsListenerTest.php
  news-bundle/src/EventListener/InsertTagsListener.php
  news-bundle/tests/EventListener/InsertTagsListenerTest.php
Labels: bug

#2627 Merge branch '4.10' into master
  .github/workflows/ci.yml
  calendar-bundle/src/EventListener/InsertTagsListener.php
  calendar-bundle/tests/EventListener/InsertTagsListenerTest.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/src/Image/PictureFactoryInterface.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/src/ServiceAnnotation/Callback.php
  core-bundle/src/ServiceAnnotation/Hook.php
  core-bundle/src/ServiceAnnotation/PickerProvider.php
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/DependencyInjection/Security/ContaoLoginFactoryTest.php
  core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php
  core-bundle/tests/EventListener/InsertTags/DateListenerTest.php
  core-bundle/tests/Functional/app/config/config_test.yml
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Security/Authentication/ContaoLoginAuthenticationListenerTest.php
  faq-bundle/src/EventListener/InsertTagsListener.php
  faq-bundle/tests/EventListener/InsertTagsListenerTest.php
  manager-bundle/src/HttpKernel/JwtManager.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  monorepo.yml
  news-bundle/src/EventListener/InsertTagsListener.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
  news-bundle/tests/EventListener/InsertTagsListenerTest.php
  phpstan.neon.dist
Labels: release

#2591 Retrieve PageModel from current request and fix BC break
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#2609 Correctly validat min and max value in text field
  core-bundle/src/Resources/contao/forms/FormTextField.php
Labels: bug

#2628 Use token checker instead of FE_USER_LOGGED_IN constant
  DEPRECATED.md
  calendar-bundle/src/Resources/contao/classes/Events.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/elements/ContentGallery.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/forms/FormFileUpload.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#2072 Deprecate Controller::addImageToTemplate
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Image/Studio/ImageResult.php
  core-bundle/src/Image/Studio/LegacyFigureBuilderTrait.php
  core-bundle/src/Image/Studio/LightboxResult.php
  core-bundle/src/Resources/contao/elements/ContentAccordion.php
  core-bundle/src/Resources/contao/elements/ContentGallery.php
  core-bundle/src/Resources/contao/elements/ContentHyperlink.php
  core-bundle/src/Resources/contao/elements/ContentImage.php
  core-bundle/src/Resources/contao/elements/ContentText.php
  core-bundle/src/Resources/contao/elements/ContentVimeo.php
  core-bundle/src/Resources/contao/elements/ContentYouTube.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/modules/ModuleRandomImage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: feature

#2293 Store 2FA backup codes hashed
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/Migration/Version411/TwoFactorBackupCodesMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/modules/ModuleTwoFactor.php
  core-bundle/src/Resources/contao/templates/backend/be_two_factor.html5
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
  core-bundle/src/Security/TwoFactor/BackupCodeManager.php
  core-bundle/tests/Migration/Version411/TwoFactorBackupCodesMigrationTest.php
  core-bundle/tests/Security/TwoFactor/BackupCodeManagerTest.php
Labels: feature

#2049 Drop schema filter + adjust schema generation
  composer.json
  core-bundle/composer.json
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/src/Doctrine/Schema/SchemaProvider.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Doctrine/DoctrineTestCase.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  core-bundle/tests/Doctrine/Schema/SchemaProviderTest.php
  core-bundle/tests/EventListener/DoctrineSchemaListenerTest.php
  core-bundle/tests/Fixtures/Entity/Foo.php
  installation-bundle/src/Database/Installer.php
  installation-bundle/src/Resources/config/services.yml
  installation-bundle/tests/Database/InstallerTest.php
Labels: feature

#1999 Add config + css for back end theme
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/src/Resources/contao/templates/backend/be_login_two_factor.html5
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: feature

#2614 Fix file manager performance with large non-image files
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/tests/Image/ImageFactoryTest.php
Labels: bug

#2633 Update the contributors file and fix two minor CI issues
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/library/Contao/GdImage.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: CI

#2635 Loosen type constraint for $rowData['fullsize']
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#2636 Fix Escargot using wrong User-Agent request header
  core-bundle/src/Crawl/Escargot/Factory.php
Labels: bug

#2639 Correctly match language URL if slash is missing
  core-bundle/src/Routing/Candidates/AbstractCandidates.php
  core-bundle/tests/Routing/Candidates/CandidatesTest.php
Labels: bug

#2640 Merge branch '4.9' into 4.10
  DEPRECATED.md
  calendar-bundle/src/Resources/contao/classes/Events.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/elements/ContentGallery.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/forms/FormFileUpload.php
  core-bundle/src/Resources/contao/forms/FormTextField.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  manager-bundle/tests/ContaoManager/PluginTest.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: release

#2632 Deserialize image size when using maxWidth
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
Labels: bug

#2199 Do not encode HTML in metadata caption
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Resources/views/Image/Studio/_macros.html.twig
  core-bundle/tests/Image/Studio/FigureTest.php
Labels: bug

#2641 Merge branch '4.10' into master
  DEPRECATED.md
  calendar-bundle/src/Resources/contao/classes/Events.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/elements/ContentGallery.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/forms/FormFileUpload.php
  core-bundle/src/Resources/contao/forms/FormTextField.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/views/Image/Studio/_macros.html.twig
  core-bundle/src/Routing/Candidates/AbstractCandidates.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  core-bundle/tests/Routing/Candidates/PageCandidatesTest.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: release

#2187 Insert tags inside Twig templates
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Twig/Extension/TextExtension.php
  core-bundle/src/Twig/Runtime/InsertTagRuntime.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Twig/Extension/TextExtensionTest.php
  core-bundle/tests/Twig/Runtime/InsertTagRuntimeTest.php
Labels: feature

#2501 Handle altering twig bundle paths at runtime
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/RewireTwigPathsPass.php
  core-bundle/src/EventListener/BackendRebuildCacheMessageListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Twig/FailTolerantFilesystemLoader.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/TwigPathsPassTest.php
  core-bundle/tests/EventListener/BackendRebuildCacheMessageListenerTest.php
  core-bundle/tests/Fixtures/Twig/templates/bundles/ContaoCoreBundle/.gitignore
  core-bundle/tests/Fixtures/Twig/templates/other/.gitignore
  core-bundle/tests/Twig/FailTolerantFilesystemLoaderTest.php
Labels: feature

#2606 Fix another E_WARNING issue
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#2297 Add httpurl and custom rgxp options
  core-bundle/src/EventListener/DataContainer/ValidateCustomRgxpListener.php
  core-bundle/src/EventListener/Widget/CustomRgxpListener.php
  core-bundle/src/EventListener/Widget/HttpUrlListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/DataContainer/ValidateCustomRgxpListenerTest.php
  core-bundle/tests/EventListener/Widget/CustomRgxpListenerTest.php
  core-bundle/tests/EventListener/Widget/HttpUrlListenerTest.php
Labels: feature

#2607 Figure insert tag
  core-bundle/src/Image/Studio/FigureRenderer.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Twig/Runtime/FigureRendererRuntime.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Image/Studio/FigureRendererTest.php
  core-bundle/tests/Twig/Runtime/FigureRendererRuntimeTest.php
Labels: feature

#2651 Update ECS to a version that supports PHP 8
  .github/workflows/ci.yml
  composer.json
  core-bundle/tests/EventListener/InsecureInstallationListenerTest.php
  core-bundle/tests/EventListener/UserSessionListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/ImageSizesTest.php
  core-bundle/tests/Security/User/UserCheckerTest.php
  tools/ecs/composer.json
Labels: CI

#2654 Always pass the DC object to the toggleFeatured() method
  core-bundle/src/Resources/contao/classes/Ajax.php
Labels: bug

#2655 Improve rendering long titles and file names
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#2658 Do not translate the analytics template names
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/languages/en/tl_layout.xlf
Labels: bug

#2660 Remove the separate CI run for PHP 8
  .github/workflows/ci.yml
Labels: CI

#2664 Use 2fa/* subpackages instead of scheb/2fa
  composer.json
  core-bundle/composer.json
Labels: bug

#2657 Fix the search query if there are no keywords
  core-bundle/src/Resources/contao/library/Contao/Search.php
Labels: bug

#2656 Correctly format the search query time
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
Labels: bug

#2653 Fix the comments cache tagging
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#2666 Reset the custom template if the element type changes
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
Labels: bug

#2668 Fix empty value for boolean type
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#2669 Use a listener to reset custom templates
  core-bundle/src/EventListener/DataContainer/ResetCustomTemplateListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
Labels: bug

#2667 Ignore Monolog log files when rotating log files
  core-bundle/src/Resources/contao/library/Contao/Automator.php
Labels: bug

#2672 Merge branch '4.9' into 4.10
  .github/workflows/ci.yml
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/EventListener/DataContainer/ResetCustomTemplateListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/tests/Contao/CombinerTest.php
Labels: release

#2673 Correctly handle hosts with port number
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Routing/Matcher/UrlMatcher.php
  core-bundle/tests/Fixtures/Functional/Routing/localhost.yml
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#2675 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/it/tl_page.xlf
Labels: release

#2676 Merge branch '4.10' into 4.11
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/EventListener/DataContainer/ResetCustomTemplateListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Routing/Matcher/UrlMatcher.php
  core-bundle/tests/Contao/CombinerTest.php
  core-bundle/tests/Fixtures/Functional/Routing/localhost.yml
  core-bundle/tests/Functional/RoutingTest.php
Labels: release

#2661 Use type="url" for httpurl text fields
  core-bundle/src/Resources/contao/forms/FormTextField.php
Labels: bug

#2662 Fix entity encoding in the figure insert tag
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#2679 Fix yet another E_WARNING issue
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
Labels: bug

#2685 Use the request attribute to determine preview mode
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  manager-bundle/src/Resources/skeleton/web/preview.php
Labels: bug

#2683 Adjust the scheb/2fa-bundle integration
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/tests/DependencyInjection/Security/ContaoLoginFactoryTest.php
Labels: bug

#2688 Fix a BC break in the AbstractFragmentController
  core-bundle/src/Controller/AbstractFragmentController.php
Labels: bug

#2693 Fix a wrong class reference in the Widget class
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#2694 Remove the legacy encryption logic
  LIMITATIONS.md
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/src/Resources/contao/library/Contao/Encryption.php
Labels: bug

#2698 Handle root pages without hostname in the SitemapController
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: bug

#2701 Correctly match page controllers with absolute paths
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/Routing/Candidates/PageCandidates.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: bug

#2702 Register the SitemapController in the services.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#2703 Correctly show fields with an input_field_callback
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#2704 Fix the rgxp=>httpurl implementation
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/forms/FormTextField.php
  core-bundle/src/Resources/contao/widgets/TextField.php
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
Labels: bug
