Repository contao/contao, pull requests merged in 2021-05, with the labels that each got.

#2985 Commit the composer.lock files of the tools
  .github/workflows/ci.yml
  .gitignore
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
Labels: CI

#2990 Commit the composer.lock files of the tools
  .github/workflows/ci.yml
  .gitignore
  core-bundle/src/Doctrine/Schema/SchemaProvider.php
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
  core-bundle/tests/Twig/Runtime/FigureRendererRuntimeTest.php
  phpstan.neon.dist
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI

#2894 Fix a normalize whitespace error in the DomCrawler
  core-bundle/src/Search/Document.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
Labels: bug

#2967 Use the date formats from the page context for insert tags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#2989 Fix the favicon.ico route
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#2977 Fix external news targets not opening in a new window
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#2935 Fix the PageModel registry state
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
Labels: bug

#2971 Do not render an empty custom navigation
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
Labels: bug

#2930 Add template properties to fragment proxy
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/Fragment/Reference/ContentElementReference.php
  core-bundle/src/Fragment/Reference/FrontendModuleReference.php
  core-bundle/src/Resources/contao/elements/ContentAlias.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/elements/ContentProxy.php
  core-bundle/src/Resources/contao/modules/ModuleProxy.php
Labels: bug

#2996 Correctly strip the root path in the FilesModel and Dbafs classes
  core-bundle/src/Resources/contao/library/Contao/Dbafs.php
  core-bundle/src/Resources/contao/models/FilesModel.php
Labels: bug

#3002 Fix the prefer-lowest tests
  core-bundle/tests/Contao/Database/ResultTest.php
Labels: CI

#2991 Enable "useSSL" by default unless the backend request is insecure
  core-bundle/src/EventListener/DataContainer/PageUseSslDefaultListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#2713 Mention removal of MediaElement.js in the UPGRADE.md file
  UPGRADE.md
Labels: bug

#3005 CS fixes for 4.x
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
Labels: CI

#3004 Fix an inconsistency in the routing functional tests
  core-bundle/tests/Fixtures/Functional/Routing/root-with-home.yml
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#3008 Update the CI tools
  core-bundle/src/Resources/contao/widgets/SerpPreview.php
  core-bundle/tests/Command/DebugFragmentsCommandTest.php
  core-bundle/tests/Config/Loader/PhpFileLoaderTest.php
  core-bundle/tests/Config/Loader/XliffFileLoaderTest.php
  core-bundle/tests/Contao/CombinerTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Contao/ValidatorTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  core-bundle/tests/Security/TwoFactor/AuthenticatorTest.php
  manager-bundle/tests/Command/InstallWebDirCommandTest.php
  manager-bundle/tests/Dotenv/DotenvDumperTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI

#2804 Drop the LegacyFigureBuilderTrait
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Image/Studio/LegacyFigureBuilderTrait.php
  core-bundle/src/Resources/contao/elements/ContentAccordion.php
  core-bundle/src/Resources/contao/elements/ContentGallery.php
  core-bundle/src/Resources/contao/elements/ContentHyperlink.php
  core-bundle/src/Resources/contao/elements/ContentImage.php
  core-bundle/src/Resources/contao/elements/ContentText.php
  core-bundle/src/Resources/contao/elements/ContentVimeo.php
  core-bundle/src/Resources/contao/elements/ContentYouTube.php
  core-bundle/src/Resources/contao/modules/ModuleRandomImage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: feature

#3010 Remove a left-over call to the LegacyFigureBuilderTrait
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#2975 Add the response context
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Routing/ResponseContext/ContaoWebpageResponseContext.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/PartialResponseHeaderBag.php
  core-bundle/src/Routing/ResponseContext/ResponseContext.php
  core-bundle/src/Routing/ResponseContext/ResponseContextAccessor.php
  core-bundle/src/Routing/ResponseContext/ResponseContextInterface.php
  core-bundle/src/Routing/ResponseContext/WebpageResponseContext.php
  core-bundle/tests/Fixtures/Routing/FooResponseContext.php
  core-bundle/tests/Routing/ResponseContext/ContaoWebpageResponseContextTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextAccessorTest.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextTest.php
  core-bundle/tests/Routing/ResponseContext/WebpageResponseContextTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
Labels: feature

#2999 Remove two left-over autocomplete attributes
  core-bundle/src/Resources/contao/widgets/Password.php
Labels: bug

#3000 Simplify the latest DC_Table change
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3017 Handle UUIDs in the file metadata class
  core-bundle/src/File/Metadata.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/File/MetadataTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: feature

#2970 Load protected status from parent pages in customnav
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
Labels: bug

#2937 Fix PHP 8 compat of DC_Table/Environment
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Environment.php
Labels: bug

#2987 Add tests for the image studio macros
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/views/Image/Studio/_macros.html.twig
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
Labels: bug

#3019 Dispatch an event to define metadata inside the FigureBuilder
  core-bundle/src/Event/FileMetadataEvent.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Image/Studio/Studio.php
  core-bundle/tests/Event/FileMetadataEventTest.php
  core-bundle/tests/Image/Studio/FigureBuilderIntegrationTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/StudioTest.php
Labels: feature

#2952 Set a label for the Contao Manager back end menu entry
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/src/Resources/translations/ContaoManagerBundle.en.xlf
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
Labels: bug

#3029 Do not modify the select name at runtime
  core-bundle/src/Resources/contao/forms/FormSelectMenu.php
Labels: bug

#3007 Allow saving the value 0 in the KeyValueWizard
  core-bundle/src/Resources/contao/widgets/KeyValueWizard.php
Labels: bug

#3028 Do not require ocramius/proxy-manager
  composer.json
  manager-bundle/composer.json
Labels: bug

#3030 Update the CI tools and fix the mysqli::real_connect() warning
  composer.json
  manager-bundle/tests/ContaoManager/PluginTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
Labels: CI

#3035 Merge branch '4.11' into 4.x
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/forms/FormSelectMenu.php
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/widgets/KeyValueWizard.php
  core-bundle/src/Resources/views/Image/Studio/_macros.html.twig
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  manager-bundle/composer.json
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/src/Resources/translations/ContaoManagerBundle.en.xlf
  manager-bundle/tests/ContaoManager/PluginTest.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
  tools/ecs/composer.lock
  tools/psalm/composer.lock
Labels: release

#3036 Add a CI job for PHP 8.1
  .github/workflows/ci.yml
  core-bundle/tests/EventListener/GlobalsMapListenerTest.php
Labels: CI

#2994 Hide unsaved content elements in the front end
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/FormFieldModel.php
Labels: bug

#3038 Reduce the deprecation warnings in the tests
  .github/workflows/ci.yml
  composer.json
  core-bundle/composer.json
  core-bundle/src/Cors/WebsiteRootsConfigProvider.php
  core-bundle/src/Migration/Version409/CeAccessMigration.php
  core-bundle/src/Migration/Version411/TwoFactorBackupCodesMigration.php
  core-bundle/src/Resources/contao/library/Contao/Combiner.php
  core-bundle/tests/Cors/WebsiteRootsConfigProviderTest.php
  core-bundle/tests/EventListener/GlobalsMapListenerTest.php
  core-bundle/tests/Migration/Version409/CeAccessMigrationTest.php
  core-bundle/tests/Migration/Version411/TwoFactorBackupCodesMigrationTest.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  core-bundle/tests/Routing/Candidates/PageCandidatesTest.php
  manager-bundle/tests/ContaoManager/PluginTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI
