Repository contao/contao, pull requests merged in 2021-09, with the labels that each got.

#3394 Show table name in model relation exception
  core-bundle/src/Resources/contao/library/Contao/Model.php
Labels: bug

#3405 Harden the version 4.5.0 migration
  core-bundle/src/Migration/Version405/Version450Update.php
Labels: bug

#3396 Evaluate robots setting for sitemap
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: bug

#3406 Remove the "generateSitemap" cronjob
  core-bundle/src/Resources/contao/config/config.php
Labels: bug

#3410 Use PHP functions to modify query strings
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/modules/ModuleLogout.php
  core-bundle/src/Resources/contao/pages/PageLogout.php
  core-bundle/tests/Contao/ControllerTest.php
Labels: bug

#3417 Use PHP functions to modify query strings
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/modules/ModuleLogout.php
  core-bundle/src/Resources/contao/pages/PageLogout.php
  core-bundle/tests/Contao/ControllerTest.php
Labels: bug

#3423 Convert allowed attributes to lowercase
  core-bundle/src/Resources/contao/dca/tl_settings.php
Labels: bug

#3412 Do not dynamically disable HttpCache but rely on env vars instead
  manager-bundle/src/HttpKernel/ContaoKernel.php
Labels: bug

#3407 Respect the `decodeEntities` flag with rgxp => url
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#3422 Handle `%` characters in the SERP preview
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: bug

#3329 Make sure X-Forwarded-Host is trusted if trusted hosts are configured
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
Labels: bug

#3408 Handle another illegal array access on empty labels
  core-bundle/src/Resources/contao/widgets/FileTree.php
Labels: bug

#3434 Update the dependencies and remove the BC layers
  .github/workflows/ci.yml
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/EventListener/ClearSessionDataListener.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/EventListener/ExceptionConverterListener.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/EventListener/RequestTokenListener.php
  core-bundle/src/EventListener/SubrequestCacheSubscriber.php
  core-bundle/src/Framework/ScopeAwareTrait.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Routing/ScopeMatcher.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Logout/LogoutHandler.php
  core-bundle/tests/EventListener/BackendLocaleListenerTest.php
  core-bundle/tests/EventListener/BackendRebuildCacheMessageListenerTest.php
  core-bundle/tests/EventListener/BypassMaintenanceListenerTest.php
  core-bundle/tests/EventListener/ClearSessionDataListenerTest.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
  core-bundle/tests/EventListener/ExceptionConverterListenerTest.php
  core-bundle/tests/EventListener/InsecureInstallationListenerTest.php
  core-bundle/tests/EventListener/LocaleSubscriberTest.php
  core-bundle/tests/EventListener/MakeResponsePrivateListenerTest.php
  core-bundle/tests/EventListener/MergeHttpHeadersListenerTest.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/EventListener/RefererIdListenerTest.php
  core-bundle/tests/EventListener/RequestTokenListenerTest.php
  core-bundle/tests/EventListener/ResponseExceptionListenerTest.php
  core-bundle/tests/EventListener/StoreRefererListenerTest.php
  core-bundle/tests/EventListener/SubrequestCacheSubscriberTest.php
  core-bundle/tests/EventListener/TwoFactorFrontendListenerTest.php
  core-bundle/tests/EventListener/UserSessionListenerTest.php
  core-bundle/tests/Routing/ScopeMatcherTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Authentication/ContaoLoginAuthenticationListenerTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
  core-bundle/tests/Security/Logout/LogoutHandlerTest.php
  faq-bundle/composer.json
  installation-bundle/composer.json
  listing-bundle/composer.json
  manager-bundle/composer.json
  manager-bundle/src/ContaoManager/ApiCommand/GetDotEnvCommand.php
  manager-bundle/src/Dotenv/DotenvDumper.php
  manager-bundle/src/Resources/config/services.yml
  news-bundle/composer.json
  newsletter-bundle/composer.json
Labels: feature

#3191 Use v2 of league/commonmark
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/ContentElement/MarkdownController.php
Labels: feature

#3432 Make the "guests only" deprecation messages more clear
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
Labels: bug

#3436 Drop the contao/polyfill-symfony package
  composer.json
  core-bundle/composer.json
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Translation/DataCollectorTranslator.php
  core-bundle/src/Translation/Translator.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
  core-bundle/tests/Security/Authentication/ContaoLoginAuthenticationListenerTest.php
  core-bundle/tests/Translation/TranslatorTest.php
  phpstan.neon.dist
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: feature

#3440 Convert languages outside the sorting callback
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
Labels: bug

#3441 Add canonical name to routes
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
Labels: bug

#3447 Update the tools
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Mailer/AvailableTransports.php
  core-bundle/src/Mailer/ContaoMailer.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/widgets/SerpPreview.php
  core-bundle/src/Security/TwoFactor/Authenticator.php
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php
  core-bundle/tests/Image/Studio/ImageResultTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  tools/ecs/composer.lock
Labels: CI

#3442 Change all occurrences of master (request) to main
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/EventListener/RefererIdListener.php
  core-bundle/src/EventListener/RequestTokenListener.php
  core-bundle/src/EventListener/StoreRefererListener.php
  core-bundle/src/EventListener/TwoFactorFrontendListener.php
  core-bundle/src/EventListener/UserSessionListener.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Routing/ScopeMatcher.php
  core-bundle/src/Security/Authentication/Provider/AuthenticationProvider.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/src/Util/PackageUtil.php
  core-bundle/tests/EventListener/MakeResponsePrivateListenerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/EventListener/RequestTokenListenerTest.php
  core-bundle/tests/EventListener/SubrequestCacheSubscriberTest.php
  core-bundle/tests/EventListener/TwoFactorFrontendListenerTest.php
  core-bundle/tests/Routing/ScopeMatcherTest.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
Labels: feature

#3445 Allow to pass the actual 40x page to the page type
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/pages/PageError401.php
  core-bundle/src/Resources/contao/pages/PageError403.php
  core-bundle/src/Resources/contao/pages/PageError404.php
Labels: feature

#3444 Service priority 0 is not the same as not-set priority
  core-bundle/src/ServiceAnnotation/Callback.php
  core-bundle/src/ServiceAnnotation/Hook.php
  core-bundle/src/ServiceAnnotation/PickerProvider.php
Labels: bug

#3449 Handle invalid array access in tl_page
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#3452 Update the tools
  .github/workflows/ci.yml
  composer.json
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Translation/TranslatorTest.php
  core-bundle/tests/Twig/Interop/ContextHelperTest.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
  phpstan.neon.dist
  tools/ecs/composer.lock
  tools/psalm/composer.json
  tools/psalm/composer.lock
Labels: CI

#3379 Add "Do Not Track" option to the Vimeo content element
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
Labels: feature

#3454 Fix the event endTime adjustment
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
Labels: bug

#3455 Handle flags in insertTagToSrc()
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
Labels: bug

#3459 Fix a broken if-condition in tl_files::excludeFolder()
  core-bundle/src/Resources/contao/dca/tl_files.php
Labels: bug

#3460 Fix the position of the pagination menu in "edit multiple" mode
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3462 Add a label for "edit multiple" to the deep link confirmation screen
  core-bundle/src/Resources/contao/controllers/BackendConfirm.php
Labels: bug

#3426 Migrate the newsletter module keys in version 4.0
  newsletter-bundle/src/Migration/Version400/NewsletterModuleMigration.php
Labels: bug

#3457 Fix the picker for child tables without PID
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
Labels: bug

#3467 Prevent image overflow for selected content elements
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#3416 Dispatch the PreviewUrlCreateEvent even with an empty ID
  calendar-bundle/src/EventListener/PreviewUrlCreateListener.php
  core-bundle/src/Event/PreviewUrlCreateEvent.php
  core-bundle/src/EventListener/Menu/BackendPreviewListener.php
  core-bundle/src/EventListener/PreviewUrlCreateListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/Menu/BackendPreviewListenerTest.php
  core-bundle/tests/EventListener/PreviewUrlCreateListenerTest.php
  news-bundle/src/EventListener/PreviewUrlCreateListener.php
Labels: bug

#3461 Do not reset the entire flash bag when resetting the message system
  core-bundle/src/Resources/contao/library/Contao/Message.php
Labels: bug

#3464 Redirect if the back end is called via the front end preview entry point
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/EventListener/BackendPreviewRedirectListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/BackendPreviewRedirectListenerTest.php
Labels: bug

#3446 Fix user permissions for custom page controllers
  core-bundle/src/EventListener/DataContainer/PageTypeOptionsListener.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
Labels: bug

#3414 Improve the Twig theme path handling
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/EventListener/DataContainer/ThemeTemplatesListener.php
  core-bundle/src/Exception/InvalidThemePathException.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Twig/Inheritance/TemplateHierarchyInterface.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/src/Twig/Loader/ThemeNamespace.php
  core-bundle/tests/Command/DebugContaoTwigCommandTest.php
  core-bundle/tests/EventListener/DataContainer/ThemeTemplatesListenerTest.php
  core-bundle/tests/Exception/InvalidThemePathExceptionTest.php
  core-bundle/tests/Fixtures/Twig/inheritance/themes/foo/.gitkeep
  core-bundle/tests/Fixtures/Twig/inheritance/themes/invalid.theme/.gitkeep
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
  core-bundle/tests/Twig/Loader/ThemeTest.php
Labels: bug

#3481 Fix inconsistencies in the search field rendering
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#3478 Hide the captcha legend in the registration module
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#3456 Set memory limit for sub-processes when running contao-setup
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
Labels: bug

#3480 Correctly handle empty values in the registration module
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#3475 Allow WebP to PNG/JPG conversion
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/languages/en/tl_image_size.xlf
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: bug

#3497 Fix the option sorting in the back end drop-downs
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/System.php
Labels: bug

#3504 Add assertions to the picture factory tests
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: CI

#3499 Load DataContainer before determining empty value
  core-bundle/src/Resources/contao/forms/Form.php
Labels: bug

#3509 Unset the noComments field if the comments bundle is not installed
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: bug

#3508 Unset the noComments field if the comments bundle is not installed
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: bug

#3506 Add the missing stuff from the 4.9-4.12 upstream merge
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/Route404Provider.php
Labels: release

#3514 Fix the PHP 8.1 job
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI

#3515 Fix the PHP 8.1 job
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
Labels: CI

#3516 Fix the PHP 8.1 job
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: CI

#3512 Decode the subject when sending form submission via email
  core-bundle/src/Resources/contao/forms/Form.php
Labels: bug

#3513 Allow HTML by default only for tinyMCE and ace|html
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#3517 Merge duplicate tags in HTML attributes config
  core-bundle/src/Resources/contao/dca/tl_settings.php
Labels: bug

#3519 Do not encode option values
  core-bundle/src/Resources/contao/widgets/CheckBox.php
  core-bundle/src/Resources/contao/widgets/CheckBoxWizard.php
  core-bundle/src/Resources/contao/widgets/RadioButton.php
  core-bundle/src/Resources/contao/widgets/RadioTable.php
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
Labels: bug

#3521 Document another known limitation
  LIMITATIONS.md
Labels: bug

#3520 Remove incomplete translations
  core-bundle/src/Resources/contao/languages/nl/countries.xlf
  core-bundle/src/Resources/contao/languages/nl/languages.xlf
  core-bundle/src/Resources/contao/languages/pt/countries.xlf
  core-bundle/src/Resources/contao/languages/pt/languages.xlf
  core-bundle/src/Resources/contao/languages/sl/countries.xlf
  core-bundle/src/Resources/contao/languages/sl/languages.xlf
Labels: bug

#3524 Add an event count to the event list
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
Labels: feature

#3522 Optionally delete the home directory in the "close account" module
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/models/ModuleModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
Labels: feature

#3529 Merge branch '4.12' into 4.x
  LIMITATIONS.md
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_settings.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/languages/en/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/nl/countries.xlf
  core-bundle/src/Resources/contao/languages/nl/languages.xlf
  core-bundle/src/Resources/contao/languages/pt/countries.xlf
  core-bundle/src/Resources/contao/languages/pt/languages.xlf
  core-bundle/src/Resources/contao/languages/sl/countries.xlf
  core-bundle/src/Resources/contao/languages/sl/languages.xlf
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/CheckBox.php
  core-bundle/src/Resources/contao/widgets/CheckBoxWizard.php
  core-bundle/src/Resources/contao/widgets/RadioButton.php
  core-bundle/src/Resources/contao/widgets/RadioTable.php
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: release
