Repository contao/contao, pull requests merged in 2021-12, with the labels that each got.

#3741 Make sure GUIDs in RSS feeds are unique
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  core-bundle/src/Resources/contao/library/Contao/Feed.php
Labels: bug

#3753 Merge branch '4.9' into 4.12
  calendar-bundle/phpunit.xml.dist
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  core-bundle/phpunit.xml.dist
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/EventListener/StoreRefererListener.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/library/Contao/Feed.php
  core-bundle/src/Resources/contao/library/Contao/Folder.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/FileSelector.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/EventListener/StoreRefererListenerTest.php
  core-bundle/tests/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServicesTest.php
  faq-bundle/phpunit.xml.dist
  installation-bundle/phpunit.xml.dist
  manager-bundle/phpunit.xml.dist
  manager-bundle/tests/Api/ApplicationTest.php
  news-bundle/phpunit.xml.dist
  phpstan.neon.dist
  phpunit.xml.dist
Labels: release

#3626 Support arbitrary classes as Twig context
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Twig/Interop/ContextFactory.php
  core-bundle/src/Twig/Interop/ContextHelper.php
  core-bundle/tests/Fixtures/Twig/ParentClassWithMembersStub.php
  core-bundle/tests/Twig/Interop/ContextFactoryTest.php
  core-bundle/tests/Twig/Interop/ContextHelperTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: bug

#3754 Handle all driver exceptions in the template locator
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
Labels: bug

#3755 Adjust the service ID of the new interest cohort listener
  core-bundle/src/Resources/config/listener.yml
Labels: bug

#3757 Fix two more service IDs
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php
Labels: bug

#3758 Add transitive dependency on symfony/twig-bridge
  composer.json
  core-bundle/composer.json
Labels: bug

#3746 Upgrade symfony/security-bundle to 5.4 and fix TokenInterface usage
  composer.json
  core-bundle/composer.json
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  core-bundle/tests/Security/Authentication/Token/FrontendPreviewTokenTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  manager-bundle/composer.json
  phpstan.neon
Labels: bug

#3750 Make Symfony 5.4 the minimum requirement
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/README.md
  core-bundle/composer.json
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/Controller/Page/RootPageController.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Functional/app/config/security.yml
  faq-bundle/composer.json
  installation-bundle/composer.json
  listing-bundle/composer.json
  manager-bundle/composer.json
  manager-bundle/src/Resources/skeleton/config/security.yml
  news-bundle/composer.json
  newsletter-bundle/composer.json
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
  tools/service-linter/composer.lock
Labels: feature

#3743 Fix the PasswordHasherFactory usage
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
  core-bundle/src/Resources/contao/controllers/BackendPassword.php
  core-bundle/src/Resources/contao/forms/FormPassword.php
  core-bundle/src/Resources/contao/library/Contao/Encryption.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/widgets/Password.php
  core-bundle/tests/DependencyInjection/Compiler/MakeServicesPublicPassTest.php
Labels: bug

#3744 Show bubbled exceptions in the pretty error screen listener
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
Labels: bug

#3759 Unify the MakeServicesPublicPass
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
Labels: bug

#3764 Make the autowiring aliases of renamed services public
  core-bundle/src/Resources/config/services.yml
Labels: bug

#3727 Link parent elements in the back end breadcrumb trail
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: feature

#3673 Fix undefined array key "panelLayout"
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3769 Run the code inspector (again)
  calendar-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/EventListener/Security/SwitchUserListener.php
  core-bundle/src/Migration/AbstractMigration.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Routing/ResponseContext/ResponseContext.php
  core-bundle/src/Search/Document.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/Command/UserCreateCommandTest.php
  core-bundle/tests/Command/UserPasswordCommandTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Doctrine/Backup/BackupManagerTest.php
  core-bundle/tests/Doctrine/DoctrineTestCase.php
  core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php
  core-bundle/tests/EventListener/InsecureInstallationListenerTest.php
  core-bundle/tests/EventListener/MergeHttpHeadersListenerTest.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/EventListener/Security/TwoFactorFrontendListenerTest.php
  core-bundle/tests/EventListener/StoreRefererListenerTest.php
  core-bundle/tests/EventListener/UserSessionListenerTest.php
  core-bundle/tests/Fragment/FragmentHandlerTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/Intl/LocalesTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
  core-bundle/tests/OptIn/OptInTokenTest.php
  core-bundle/tests/Routing/Candidates/PageCandidatesTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/Authentication/ContaoLoginAuthenticationListenerTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
  core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  core-bundle/tests/String/SimpleTokenParserTest.php
  core-bundle/tests/Translation/MessageCatalogueTest.php
  core-bundle/tests/Translation/TranslatorTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Runtime/LegacyTemplateFunctionsRuntimeTest.php
  installation-bundle/src/InstallTool.php
  manager-bundle/src/Api/Application.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/src/HttpKernel/JwtManager.php
  manager-bundle/tests/Api/ApplicationTest.php
  news-bundle/src/EventListener/PreviewUrlConvertListener.php
Labels: CI

#3765 Do not deprecate the autowiring aliases
  core-bundle/src/Resources/config/services.yml
Labels: bug

#3604 Use the back end access voter instead of hasAccess() and isAllowed()
  calendar-bundle/src/Resources/contao/dca/tl_calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/Messages.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/controllers/BackendFile.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/controllers/BackendPage.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_style_sheet.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/tests/Security/Voter/BackendAccessVoterTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  faq-bundle/src/Resources/contao/dca/tl_faq_category.php
  news-bundle/src/Resources/contao/dca/tl_module.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/dca/tl_news_archive.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_channel.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: feature

#3674 Add a DCA option to collapse inactive checkbox groups
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/widgets/CheckBox.php
Labels: feature

#3660 Add Chosen to select menus in the backend DCA filters
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: feature

#3773 Fix a few minor issues
  core-bundle/src/EventListener/UserAwareTrait.php
  core-bundle/src/Resources/contao/widgets/Picker.php
  core-bundle/tests/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServicesTest.php
  maker-bundle/phpunit.xml.dist
Labels: CI

#3778 Ensure type-safety when replacing legacy insert tags
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#3781 Fix unknown "ansi_to_html" filter error
  composer.json
  installation-bundle/composer.json
  installation-bundle/src/Resources/config/services.yml
Labels: bug

#3605 Do not generate routes for error pages
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/DependencyInjection/Attribute/AsPage.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/src/Routing/Page/RouteConfig.php
  core-bundle/src/Routing/Page/UnroutablePageRouteCompiler.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/src/ServiceAnnotation/Page.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/Fixtures/Functional/Routing/news.yml
  core-bundle/tests/Routing/Page/PageRegistryTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: feature

#3788 Clarify internal style sheets deprecation
  core-bundle/src/Resources/contao/languages/en/default.xlf
Labels: bug

#3796 Correctly handle unroutable legacy types
  core-bundle/src/Routing/Page/PageRegistry.php
Labels: bug

#3798 Use unroutable pages types to limit queries
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Routing/Page/PageRegistry.php
Labels: feature

#3799 Make the page registry service public
  core-bundle/src/Resources/config/services.yml
Labels: bug

#3795 Fix issues with non-admin users
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3801 Add a missing isset() when checking for the mailer DSN
  manager-bundle/src/ContaoManager/Plugin.php
Labels: bug

#3786 Use lower case for "fixes" in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CI

#3792 Fix more PHP8 warnings
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/templates/navigation/nav_default.html5
Labels: bug

#3803 Fix infinite 4.8.0 migration when custom templates are present
  core-bundle/src/Migration/Version408/Version480Update.php
Labels: bug

#3807 Merge branch '4.9' into 4.12
  composer.json
  core-bundle/composer.json
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
  core-bundle/src/EventListener/StoreRefererListener.php
  core-bundle/src/Migration/Version408/Version480Update.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/templates/navigation/nav_default.html5
  core-bundle/tests/EventListener/StoreRefererListenerTest.php
  installation-bundle/composer.json
  installation-bundle/src/Resources/config/services.yml
Labels: release

#3808 Merge branch '4.12' into 4.x
  composer.json
  core-bundle/composer.json
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
  core-bundle/src/EventListener/StoreRefererListener.php
  core-bundle/src/Migration/Version408/Version480Update.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/templates/navigation/nav_default.html5
  core-bundle/tests/EventListener/StoreRefererListenerTest.php
  installation-bundle/composer.json
  installation-bundle/src/Resources/config/services.yml
  manager-bundle/src/ContaoManager/Plugin.php
Labels: release

#3804 Always show debug log and fetch crawl status earlier
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/templates/backend/be_crawl.html5
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: feature

#3810 Use mode constants in Picker widget
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug

#3811 Prevent installing the Symfony framework bundle in version 6
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.json
  tools/psalm/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#3815 Enable image lazy loading in file manager
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#3813 Replace ramsey/uuid with symfony/uid
  composer.json
  core-bundle/composer.json
  core-bundle/src/Crawl/Escargot/Factory.php
Labels: feature

#3797 Allow previewing unroutable pages
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Event/PreviewUrlConvertEvent.php
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
Labels: feature

#3820 Adjust some minor issues
  core-bundle/src/Doctrine/Backup/Dumper.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Routing/Matcher/LegacyMatcherTest.php
Labels: CI

#3812 Increase the length of URL fields
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: feature

#3819 Add comments to our interfaces and abstract classes
  core-bundle/src/Config/Dumper/DumperInterface.php
  core-bundle/src/Config/ResourceFinderInterface.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/Doctrine/Backup/Config/AbstractConfig.php
  core-bundle/src/Image/ImageFactoryInterface.php
  core-bundle/src/Image/PictureFactoryInterface.php
  core-bundle/src/Picker/AbstractInsertTagPickerProvider.php
  core-bundle/src/Picker/AbstractPickerProvider.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Picker/DcaPickerProviderInterface.php
  core-bundle/src/Picker/PickerBuilderInterface.php
  core-bundle/src/Picker/PickerInterface.php
  core-bundle/src/Picker/PickerProviderInterface.php
Labels: feature

#3822 Add a Template property to controller-like classes
  core-bundle/src/Resources/contao/controllers/BackendCustom.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
Labels: bug

#3725 PHP 8.1
  .github/workflows/ci.yml
Labels: CI

#3830 Update the changelog and the language files
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/ru/default.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sr/modules.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_settings.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.cs.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.de.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.es.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.fr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.it.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ja.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.lv.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.ru.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.sr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.tr.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.zh.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.es.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.it.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.ja.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.ru.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.sl.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.sr.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.sv.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.tr.xlf
Labels: release

#3831 Merge branch '4.9' into 4.12
  .github/workflows/ci.yml
  core-bundle/src/Resources/contao/controllers/BackendCustom.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/tests/Twig/Interop/ContextFactoryTest.php
Labels: release

#3833 Merge branch '4.12' into 4.x
  .github/workflows/ci.yml
  core-bundle/src/Resources/contao/controllers/BackendCustom.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/tests/Twig/Interop/ContextFactoryTest.php
Labels: release

#3837 Do not check on null as the username can be empty
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
Labels: bug

#3841 Removed an unused setup method
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
Labels: bug

#3839 Remove page from index if "Do not search" is checked
  core-bundle/src/EventListener/DataContainer/PageSearchListener.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/tests/EventListener/DataContainer/PageSearchListenerTest.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
Labels: feature

#3835 Remove the alias field from unroutable pages
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
Labels: bug

#3816 Rework the @throws annotations
  calendar-bundle/src/EventListener/PreviewUrlCreateListener.php
  core-bundle/src/Config/Loader/XliffFileLoader.php
  core-bundle/src/Config/ResourceFinder.php
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/Csrf/MemoryTokenStorage.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/DependencyInjection/Compiler/AddCronJobsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterHookListenersPass.php
  core-bundle/src/Doctrine/Backup/Backup.php
  core-bundle/src/Doctrine/Backup/BackupManager.php
  core-bundle/src/EventListener/InsecureInstallationListener.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/EventListener/PreviewUrlCreateListener.php
  core-bundle/src/EventListener/RequestTokenListener.php
  core-bundle/src/EventListener/Security/SwitchUserListener.php
  core-bundle/src/EventListener/UserSessionListener.php
  core-bundle/src/HttpKernel/Bundle/ContaoModuleBundle.php
  core-bundle/src/Monolog/ContaoContext.php
  core-bundle/src/Monolog/ContaoTableHandler.php
  core-bundle/src/OptIn/OptInToken.php
  core-bundle/src/Routing/UrlGenerator.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/src/Security/User/ContaoUserProvider.php
  core-bundle/src/Security/User/UserChecker.php
  core-bundle/src/Session/LazySessionAccess.php
  installation-bundle/src/Controller/InstallationController.php
  news-bundle/src/EventListener/PreviewUrlCreateListener.php
Labels: bug

#3791 Add annotations that generating page URLs can throw an exception
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#3845 Register a controller for error page types
  core-bundle/src/Controller/Page/Error4xxPageController.php
  core-bundle/src/Controller/Page/RootPageController.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/tests/Controller/Page/Error4xxPageControllerTest.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
Labels: bug

#3855 Normalize the composer.json files and remove extra.symfony.require
  .github/workflows/ci.yml
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  installation-bundle/composer.json
  listing-bundle/composer.json
  maker-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  newsletter-bundle/composer.json
Labels: CI

#3628 Make image width and height overwritable in the upload widget
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/forms/FormFileUpload.php
  core-bundle/src/Resources/contao/languages/en/tl_form_field.xlf
Labels: feature

#3861 Fix the back end pagination menu
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3863 Harden the Picker class against undefined array keys
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug

#3859 Deprecate two global variables
  DEPRECATED.md
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: bug

#3858 Revert replacing insert tags in the template inheritance trait
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php
Labels: bug

#3846 Fixed debug:pages command and show dynamic content composition
  core-bundle/src/Command/DebugPagesCommand.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
Labels: bug

#3729 Maintenance mode per root page
  core-bundle/src/Controller/Page/ErrorPageController.php
  core-bundle/src/EventListener/FilterPageTypeListener.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/EventListener/ServiceUnavailableListener.php
  core-bundle/src/Exception/ServiceUnavailableException.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/themes/flexible/icons/error_503.svg
  core-bundle/src/Resources/contao/themes/flexible/icons/error_503_1.svg
  core-bundle/tests/Controller/Page/Error4xxPageControllerTest.php
  core-bundle/tests/Controller/Page/ErrorPageControllerTest.php
  core-bundle/tests/EventListener/FilterPageTypeListenerTest.php
  core-bundle/tests/EventListener/ServiceUnavailableListenerTest.php
Labels: feature

#3864 Fix the unit tests
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  tools/ecs/composer.json
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.json
  tools/psalm/composer.lock
  tools/service-linter/composer.json
  tools/service-linter/composer.lock
Labels: CI

#3850 Add a backup retention policy
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Doctrine/Backup/Backup.php
  core-bundle/src/Doctrine/Backup/BackupManager.php
  core-bundle/src/Doctrine/Backup/RetentionPolicy.php
  core-bundle/src/Doctrine/Backup/RetentionPolicyInterface.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Doctrine/Backup/BackupManagerTest.php
  core-bundle/tests/Doctrine/Backup/RetentionPolicyTest.php
Labels: feature

#3737 Improve the system maintenance mode
  composer.json
  core-bundle/composer.json
  core-bundle/src/ContaoManager/Plugin.php
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
  core-bundle/src/EventListener/BypassMaintenanceListener.php
  core-bundle/src/EventListener/ExceptionConverterListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/classes/Maintenance.php
  core-bundle/src/Resources/contao/classes/Messages.php
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
  core-bundle/src/Resources/contao/templates/backend/be_crawl.html5
  core-bundle/src/Resources/contao/templates/backend/be_maintenance_mode.html5
  core-bundle/tests/ContaoManager/PluginTest.php
  core-bundle/tests/DependencyInjection/Compiler/MakeServicesPublicPassTest.php
  core-bundle/tests/EventListener/BypassMaintenanceListenerTest.php
  core-bundle/tests/EventListener/ExceptionConverterListenerTest.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  manager-bundle/composer.json
  manager-bundle/src/Command/MaintenanceModeCommand.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/Resources/config/services.yml
  manager-bundle/src/Resources/skeleton/config/config.yml
  manager-bundle/src/Resources/skeleton/public/index.php
  manager-bundle/tests/Command/MaintenanceModeCommandTest.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: feature

#3867 Serialize array value before saving
  core-bundle/src/Resources/contao/dca/tl_layout.php
Labels: bug

#3868 Set logout response depending on scope
  core-bundle/src/EventListener/Security/LogoutSuccessListener.php
Labels: bug

#3865 Use generic image format labels
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/languages/en/tl_image_size.xlf
Labels: bug

#3793 Allow creating nested folders in the file manager
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/library/Contao/Files.php
Labels: feature

#3866 Fix some minor issues
  composer.json
  core-bundle/src/Controller/InsertTagsController.php
  core-bundle/src/DependencyInjection/Compiler/AddNativeTransportFactoryPass.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/tests/Contao/CombinerTest.php
  core-bundle/tests/Controller/InsertTagsControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  installation-bundle/composer.json
  installation-bundle/src/Database/Installer.php
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.en.xlf
  installation-bundle/tests/Database/InstallerTest.php
Labels: bug

#3836 Report HTTP exceptions as warnings for the crawler instead of errors
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
Labels: bug

#3877 Enforce final newline in HTML5 templates
  .editorconfig
Labels: bug

#3871 Rename the token value method
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/library/Contao/RequestToken.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/Controller/FrontendControllerTest.php
  core-bundle/tests/Csrf/ContaoCsrfTokenManagerTest.php
Labels: bug

#3878 Enhance the service ID validation
  core-bundle/src/Resources/config/legacy_routing.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  maker-bundle/src/Resources/config/services.yaml
  tools/service-linter/composer.json
  tools/service-linter/composer.lock
  tools/service-linter/src/LintServiceIdsCommand.php
Labels: CI

#3882 Do not initialize the framework to get the Automator commands
  core-bundle/src/Command/AutomatorCommand.php
Labels: bug

#3876 Correctly handle array values in DCs
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3873 Stop using BE_USER_LOGGED_IN constant
  DEPRECATED.md
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  core-bundle/src/DataCollector/ContaoDataCollector.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/templates/analytics/analytics_google.html5
  core-bundle/src/Resources/contao/templates/analytics/analytics_matomo.html5
  core-bundle/tests/DataCollector/ContaoDataCollectorTest.php
  news-bundle/src/Resources/contao/models/NewsModel.php
Labels: bug

#3885 Unify the command output format
  core-bundle/src/Command/UserListCommand.php
Labels: bug

#3884 Check for unpublished elements when generating the RSS feed
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/models/NewsModel.php
Labels: bug
