Repository contao/contao, pull requests merged in 2021-11, with the labels that each got.

#3607 Ignore routes without root ID instead of throwing an exception
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: bug

#3627 Add the missing dot-env features
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#3623 Do not set the server_version
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#3634 Merge branch '4.9' into 4.12
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/src/EventListener/InterestCohortListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: release

#3507 Handle pages from PageRegistry in DebugPagesCommand
  core-bundle/src/Command/DebugPagesCommand.php
  core-bundle/tests/Command/DebugPagesCommandTest.php
Labels: bug

#3636 Merge branch '4.12' into 4.x
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Command/DebugPagesCommand.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/src/EventListener/InterestCohortListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Command/DebugPagesCommandTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: release

#3602 Add the HtmlDecoder service
  calendar-bundle/src/Resources/contao/classes/Events.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/String/HtmlDecoder.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/String/HtmlDecoderTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaq.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
Labels: feature

#3609 Move the simple token parser into the String namespace
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/String/SimpleTokenExpressionLanguage.php
  core-bundle/src/String/SimpleTokenParser.php
  core-bundle/src/Util/SimpleTokenExpressionLanguage.php
  core-bundle/src/Util/SimpleTokenParser.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/String/SimpleTokenParserTest.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: feature

#3625 Add a template element and module
  core-bundle/src/Controller/ContentElement/TemplateController.php
  core-bundle/src/Controller/FrontendModule/TemplateController.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/modules.xlf
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/templates/elements/ce_template.html5
  core-bundle/src/Resources/contao/templates/modules/mod_template.html5
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/tests/Controller/ContentElement/TemplateControllerTest.php
Labels: feature

#3617 Do not index documents if the canonical URL does not match
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: feature

#3207 Relay statement parameters to doctrine dbal
  core-bundle/src/Resources/contao/library/Contao/Database/Statement.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  core-bundle/tests/Contao/Database/StatementTest.php
Labels: feature

#3596 Fix the visible root trail check in the extended tree view
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3641 Replace the remaining mode/flag numbers with constants
  calendar-bundle/src/Resources/contao/dca/tl_calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_style_sheet.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/widgets/Picker.php
  faq-bundle/src/Resources/contao/dca/tl_faq_category.php
  news-bundle/src/Resources/contao/dca/tl_news_archive.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
Labels: bug

#3643 Fix the DB query in the Versions class
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: bug

#3616 Support canonical URLs in the front end
  core-bundle/src/EventListener/DataContainer/DisableCanonicalFieldsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/templates/frontend/fe_page.html5
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/HtmlHeadBag/HtmlHeadBag.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/HtmlHeadBag/HtmlHeadBagTest.php
Labels: feature

#3653 Do not block the contao.backend namespace
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
Labels: bug

#3472 Make the backend path configurable
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/config/routes.yml
  manager-bundle/src/Resources/skeleton/config/security.yml
Labels: feature

#3645 Restore backwards compatiblilty for DB Statement
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
  core-bundle/src/Resources/contao/library/Contao/Database/Statement.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Contao/Database/StatementTest.php
  core-bundle/tests/Functional/StatementTest.php
Labels: bug

#3658 Correctly check whether the root page allows canonical URLs
  core-bundle/src/EventListener/DataContainer/DisableCanonicalFieldsListener.php
  core-bundle/src/Resources/config/listener.yml
Labels: bug

#3622 Make replacing insert tags more granular
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php
Labels: feature

#3640 Use the Composer OAuth token in the CI
  .github/workflows/ci.yml
Labels: CI

#3637 Fix the decorator pattern in the FailTolerantProxyCacheWarmer
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/EventListener/CommandSchedulerListener.php
Labels: bug

#3665 Handle doctrine binary types in version compare view
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: bug

#3654 Ensure defined admin email is always used as sender
  core-bundle/src/OptIn/OptInToken.php
  core-bundle/src/Resources/contao/library/Contao/Email.php
Labels: bug

#3656 Do not set the global page object in the back end
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: bug

#3601 Inline fragments should not compile the front end template
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Resources/contao/classes/FragmentTemplate.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
Labels: bug

#3670 Merge branch '4.9' into 4.12
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/src/OptIn/OptInToken.php
  core-bundle/src/Resources/contao/classes/FragmentTemplate.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/library/Contao/Email.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: release

#3671 Merge branch '4.12' into 4.x
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/src/OptIn/OptInToken.php
  core-bundle/src/Resources/contao/classes/FragmentTemplate.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/library/Contao/Email.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: release

#3675 Fix more deprecations and use typed properties where possible
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/Event/GenerateSymlinksEvent.php
  core-bundle/src/Event/SlugValidCharactersEvent.php
  core-bundle/src/Fragment/FragmentRegistry.php
  core-bundle/src/Framework/FrameworkAwareTrait.php
  core-bundle/src/HttpKernel/Header/MemoryHeaderStorage.php
  core-bundle/src/Monolog/ContaoTableHandler.php
  core-bundle/src/Translation/DataCollectorTranslator.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  core-bundle/tests/EventListener/ExceptionConverterListenerTest.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/Functional/Migration/RoutingMigrationTest.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Monolog/ContaoTableHandlerTest.php
Labels: CI

#3668 Do not automatically focus input fields with autocomplete
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#3678 Fix parameter name in tl_page::getTitleTag()
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#3676 Replace FragmentRendererPass with tagged locator
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/ContaoCoreBundleTest.php
Labels: bug

#3664 Update PHPStan to v1.0
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Exception/RouteParametersException.php
  core-bundle/src/Monolog/ContaoTableProcessor.php
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  core-bundle/tests/Routing/LegacyRouteProviderTest.php
  core-bundle/tests/Routing/PageUrlGeneratorTest.php
  core-bundle/tests/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServicesTest.php
  phpstan.neon.dist
  tools/phpstan/composer.json
  tools/phpstan/composer.lock
Labels: feature, CI

#3638 Add an insert tags service
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/File/ModelMetadataTrait.php
  core-bundle/src/InsertTag/ChunkedText.php
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/classes/StyleSheets.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php
  core-bundle/src/Resources/contao/models/FilesModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/String/HtmlDecoder.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Interop/ContaoEscaper.php
  core-bundle/src/Twig/Runtime/InsertTagRuntime.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/File/MetadataTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/FigureRendererTest.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/String/HtmlDecoderTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/InsertTagTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperTest.php
  core-bundle/tests/Twig/Runtime/InsertTagRuntimeTest.php
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
Labels: feature

#3659 Add a cache tag service for entity/model classes
  core-bundle/src/Cache/EntityCacheTags.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/tests/Cache/EntityCacheTagsTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
  core-bundle/tests/Controller/ContentElement/TemplateControllerTest.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/Fixtures/Entity/Author.php
  core-bundle/tests/Fixtures/Entity/BlogPost.php
  core-bundle/tests/Fixtures/Entity/Comment.php
  core-bundle/tests/Fixtures/Entity/Tag.php
Labels: feature

#3682 Fix type error when trying to copy website root
  core-bundle/src/Util/LocaleUtil.php
Labels: bug

#3681 Fix the fragment handler
  core-bundle/src/Resources/config/services.yml
Labels: bug

#3685 Update the tools
  manager-bundle/src/Resources/skeleton/config/services.php
  manager-bundle/src/Resources/skeleton/public/app.php
  manager-bundle/src/Resources/skeleton/public/index.php
  manager-bundle/src/Resources/skeleton/public/preview.php
  manager-bundle/src/Resources/skeleton/system/initialize.php
  tools/ecs/composer.lock
  tools/psalm/composer.lock
Labels: CI

#3680 Fix a wrong method usage
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/modules/Module.php
Labels: bug

#3647 Set language of redirect page in global context
  core-bundle/src/Resources/contao/pages/PageRedirect.php
Labels: bug

#3696 Lower the maximum insert tag recursion level
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#3691 Fix an array to string conversion
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3699 Use ClockMock for time sensitive remember me token test
  core-bundle/tests/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServicesTest.php
  phpunit.xml.dist
Labels: bug

#3690 Correctly store the referrer in the back end
  core-bundle/src/EventListener/StoreRefererListener.php
  core-bundle/tests/EventListener/StoreRefererListenerTest.php
Labels: bug

#3619 Add PHP8 attributes for our existing service annotations
  core-bundle/src/DependencyInjection/Attribute/AsCallback.php
  core-bundle/src/DependencyInjection/Attribute/AsContentElement.php
  core-bundle/src/DependencyInjection/Attribute/AsCronJob.php
  core-bundle/src/DependencyInjection/Attribute/AsFrontendModule.php
  core-bundle/src/DependencyInjection/Attribute/AsHook.php
  core-bundle/src/DependencyInjection/Attribute/AsPage.php
  core-bundle/src/DependencyInjection/Attribute/AsPickerProvider.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
Labels: feature

#3603 Add a setting for allowed insert tags
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: feature

#3704 Run the code inspector
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Security/User/UserChecker.php
  core-bundle/src/ServiceAnnotation/AbstractFragmentAnnotation.php
  core-bundle/src/String/HtmlDecoder.php
  core-bundle/src/Twig/Interop/ContextHelper.php
  core-bundle/src/Twig/Runtime/PictureConfigurationRuntime.php
  core-bundle/tests/String/SimpleTokenParserTest.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: CI

#3705 Fix a typo in a listener ID
  core-bundle/src/Resources/config/listener.yml
Labels: bug

#3717 Move the ECS configuration into the tools folder
  .github/workflows/ci.yml
  composer.json
  phpstan.neon
  tools/ecs/composer.json
  tools/ecs/composer.lock
  tools/ecs/config/default.php
  tools/ecs/config/legacy.php
  tools/ecs/config/template.php
Labels: CI

#3714 Do not unnecessarily fetch the PageRoute twice
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: bug

#3716 Fix backwards compatibility for label::LNG and CNT
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#3715 Delete obsolete language files
  core-bundle/src/Resources/contao/languages/cs/countries.xlf
  core-bundle/src/Resources/contao/languages/cs/languages.xlf
  core-bundle/src/Resources/contao/languages/de/countries.xlf
  core-bundle/src/Resources/contao/languages/de/languages.xlf
  core-bundle/src/Resources/contao/languages/es/countries.xlf
  core-bundle/src/Resources/contao/languages/es/languages.xlf
  core-bundle/src/Resources/contao/languages/fa/countries.xlf
  core-bundle/src/Resources/contao/languages/fa/languages.xlf
  core-bundle/src/Resources/contao/languages/fr/countries.xlf
  core-bundle/src/Resources/contao/languages/fr/languages.xlf
  core-bundle/src/Resources/contao/languages/it/countries.xlf
  core-bundle/src/Resources/contao/languages/it/languages.xlf
  core-bundle/src/Resources/contao/languages/ja/countries.xlf
  core-bundle/src/Resources/contao/languages/ja/languages.xlf
  core-bundle/src/Resources/contao/languages/pl/countries.xlf
  core-bundle/src/Resources/contao/languages/pl/languages.xlf
  core-bundle/src/Resources/contao/languages/ru/countries.xlf
  core-bundle/src/Resources/contao/languages/ru/languages.xlf
  core-bundle/src/Resources/contao/languages/sr/countries.xlf
  core-bundle/src/Resources/contao/languages/sr/languages.xlf
  core-bundle/src/Resources/contao/languages/sv/countries.xlf
  core-bundle/src/Resources/contao/languages/sv/languages.xlf
  core-bundle/src/Resources/contao/languages/zh/countries.xlf
  core-bundle/src/Resources/contao/languages/zh/languages.xlf
Labels: bug

#3718 Merge branch '4.12' into 4.x
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/cs/countries.xlf
  core-bundle/src/Resources/contao/languages/cs/languages.xlf
  core-bundle/src/Resources/contao/languages/de/countries.xlf
  core-bundle/src/Resources/contao/languages/de/languages.xlf
  core-bundle/src/Resources/contao/languages/es/countries.xlf
  core-bundle/src/Resources/contao/languages/es/languages.xlf
  core-bundle/src/Resources/contao/languages/fa/countries.xlf
  core-bundle/src/Resources/contao/languages/fa/languages.xlf
  core-bundle/src/Resources/contao/languages/fr/countries.xlf
  core-bundle/src/Resources/contao/languages/fr/languages.xlf
  core-bundle/src/Resources/contao/languages/it/countries.xlf
  core-bundle/src/Resources/contao/languages/it/languages.xlf
  core-bundle/src/Resources/contao/languages/ja/countries.xlf
  core-bundle/src/Resources/contao/languages/ja/languages.xlf
  core-bundle/src/Resources/contao/languages/pl/countries.xlf
  core-bundle/src/Resources/contao/languages/pl/languages.xlf
  core-bundle/src/Resources/contao/languages/ru/countries.xlf
  core-bundle/src/Resources/contao/languages/ru/languages.xlf
  core-bundle/src/Resources/contao/languages/sr/countries.xlf
  core-bundle/src/Resources/contao/languages/sr/languages.xlf
  core-bundle/src/Resources/contao/languages/sv/countries.xlf
  core-bundle/src/Resources/contao/languages/sv/languages.xlf
  core-bundle/src/Resources/contao/languages/zh/countries.xlf
  core-bundle/src/Resources/contao/languages/zh/languages.xlf
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Util/LocaleUtil.php
Labels: release

#3611 Decorate the access decision manager
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Security/Authentication/AccessDecisionManager.php
  core-bundle/tests/Security/Authentication/AccessDecisionManagerTest.php
Labels: feature

#3631 Backup management on CLI
  core-bundle/src/Command/Backup/AbstractBackupCommand.php
  core-bundle/src/Command/Backup/BackupCreateCommand.php
  core-bundle/src/Command/Backup/BackupListCommand.php
  core-bundle/src/Command/Backup/BackupRestoreCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Doctrine/Backup/Backup.php
  core-bundle/src/Doctrine/Backup/BackupManager.php
  core-bundle/src/Doctrine/Backup/BackupManagerException.php
  core-bundle/src/Doctrine/Backup/Config/AbstractConfig.php
  core-bundle/src/Doctrine/Backup/Config/CreateConfig.php
  core-bundle/src/Doctrine/Backup/Config/RestoreConfig.php
  core-bundle/src/Doctrine/Backup/Dumper.php
  core-bundle/src/Doctrine/Backup/DumperInterface.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Command/Backup/BackupCreateCommandTest.php
  core-bundle/tests/Command/Backup/BackupListCommandTest.php
  core-bundle/tests/Command/Backup/BackupRestoreCommandTest.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Doctrine/Backup/BackupManagerTest.php
  core-bundle/tests/Doctrine/Backup/BackupTest.php
  core-bundle/tests/Doctrine/Backup/Config/CreateConfigTest.php
  core-bundle/tests/Doctrine/Backup/Config/RestoreConfigTest.php
  core-bundle/tests/Doctrine/Backup/DumperTest.php
Labels: feature

#3620 Deprecate the request_token insert tag
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/templates/modules/mod_comment_form.html5
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/RequestToken.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/templates/forms/form_wrapper.html5
  core-bundle/src/Resources/contao/templates/member/member_default.html5
  core-bundle/src/Resources/contao/templates/member/member_grouped.html5
  core-bundle/src/Resources/contao/templates/modules/mod_changePassword.html5
  core-bundle/src/Resources/contao/templates/modules/mod_login.html5
  core-bundle/src/Resources/contao/templates/modules/mod_password.html5
  core-bundle/src/Resources/contao/templates/modules/mod_quicklink.html5
  core-bundle/src/Resources/contao/templates/modules/mod_quicknav.html5
  core-bundle/tests/Controller/FrontendControllerTest.php
  core-bundle/tests/Csrf/ContaoCsrfTokenManagerTest.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
  newsletter-bundle/src/Resources/contao/templates/newsletter/nl_default.html5
Labels: feature

#3614 Add a nonce to all string placeholders
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Twig/Interop/PhpTemplateParentReferenceNode.php
  core-bundle/src/Twig/Interop/PhpTemplateProxyNodeVisitor.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Interop/PhpTemplateParentReferenceNodeTest.php
  core-bundle/tests/Twig/Interop/PhpTemplateProxyNodeVisitorTest.php
Labels: feature

#3719 Forward error handling to routing controller
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/Fixtures/src/Controller/PageError401Controller.php
  core-bundle/tests/Fixtures/src/Controller/PageError403Controller.php
  core-bundle/tests/Fixtures/src/Controller/PageError404Controller.php
  core-bundle/tests/Fixtures/src/Exception/PageError401Exception.php
  core-bundle/tests/Fixtures/src/Exception/PageErrorResponseException.php
  core-bundle/tests/Fixtures/src/Page/PageError401.php
  core-bundle/tests/Security/Authentication/AuthenticationEntryPointTest.php
Labels: feature

#3720 Fix security permissions for custom backend paths
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  installation-bundle/src/Controller/InstallationController.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  manager-bundle/src/Resources/skeleton/config/security.yml
Labels: bug

#3721 Adjust the security.yml file of the functional tests
  core-bundle/README.md
  core-bundle/tests/Functional/app/config/security.yml
Labels: CI

#3723 Stop using the LegacyEventDispatcherProxy class
  core-bundle/tests/PhpunitExtension/DeprecatedClasses.php
  manager-bundle/src/HttpKernel/ContaoCache.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
Labels: bug

#3728 Remove some left-over @expectedDeprecation and @trigger_error()
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: CI

#3735 Correctly fix a wrong method usage
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
Labels: bug

#3692 Remove the script name before signing a redirect URI
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
Labels: bug

#3470 Make sure .public is a file and not a directory
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/library/Contao/Folder.php
  core-bundle/src/Resources/contao/widgets/FileSelector.php
Labels: bug

#3734 Delete uploads if form did not validate
  core-bundle/src/Resources/contao/forms/Form.php
Labels: bug

#3738 Fix the back end tree view CSS
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#3739 Handle the routing exception in more navigation modules
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
Labels: bug

#3732 Disable form autocomplete for preview bar
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
Labels: bug

#3749 Fix the CI chain
  calendar-bundle/phpunit.xml.dist
  core-bundle/phpunit.xml.dist
  faq-bundle/phpunit.xml.dist
  installation-bundle/phpunit.xml.dist
  manager-bundle/phpunit.xml.dist
  manager-bundle/tests/Api/ApplicationTest.php
  news-bundle/phpunit.xml.dist
  phpunit.xml.dist
Labels: CI
