Repository contao/contao, pull requests merged in 2021-02, with the labels that each got.

#2726 Fix the functional tests
  .github/workflows/ci.yml
Labels: CI

#2723 Fix the functional tests
  .github/workflows/ci.yml
Labels: CI

#2727 Fix the functional tests
  .github/workflows/ci.yml
Labels: CI

#2728 Fix the functional tests
  .github/workflows/ci.yml
Labels: CI

#2736 Fix the PhpStan configuration
  phpstan.neon.dist
Labels: CI

#2497 Re-use tl_member DCA password field in ModuleCloseAccount
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
Labels: bug

#2739 Merge branch '4.9' into 4.10
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/src/Util/PackageUtil.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/DependencyInjection/Security/ContaoLoginFactoryTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  manager-bundle/src/Resources/skeleton/web/preview.php
  phpstan.neon.dist
Labels: release

#2690 Correctly handle trailing slashes in URLs
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
Labels: bug

#2716 Urldecode file paths from metadata URLs in the FigureBuilder
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Fixtures/files/public/foo (bar).jpg
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#2740 Merge branch '4.10' into 4.11
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/src/Util/PackageUtil.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/DependencyInjection/Security/ContaoLoginFactoryTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/Fixtures/files/public/foo (bar).jpg
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  manager-bundle/src/Resources/skeleton/web/preview.php
  phpstan.neon.dist
Labels: release

#2731 Do not replace template data recursively when applying legacy template data
  core-bundle/src/Image/Studio/Figure.php
Labels: bug

#2732 Handle non-existing resources in the FigureRenderer
  core-bundle/src/Image/Studio/FigureRenderer.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Twig/Runtime/FigureRendererRuntime.php
  core-bundle/tests/Image/Studio/FigureRendererTest.php
Labels: bug

#2743 Change the default URL suffix
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/tests/Fixtures/Functional/Routing/domain-without-hostname.yml
  core-bundle/tests/Fixtures/Functional/Routing/issue-2465.yml
  core-bundle/tests/Fixtures/Functional/Routing/language-index-mix.yml
  core-bundle/tests/Fixtures/Functional/Routing/language-sorting.yml
  core-bundle/tests/Fixtures/Functional/Routing/localhost.yml
  core-bundle/tests/Fixtures/Functional/Routing/page-without-alias.yml
  core-bundle/tests/Fixtures/Functional/Routing/root-with-folder-urls.yml
  core-bundle/tests/Fixtures/Functional/Routing/root-with-index.yml
  core-bundle/tests/Fixtures/Functional/Routing/root-with-special-chars.yml
  core-bundle/tests/Fixtures/Functional/Routing/root-without-fallback-language.yml
  core-bundle/tests/Fixtures/Functional/Routing/same-domain-root-with-index.yml
  core-bundle/tests/Fixtures/Functional/Routing/same-domain-root.yml
Labels: bug

#2752 Symlink highlight.php as highlight_php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/Resources/contao/templates/elements/ce_code.html5
Labels: bug

#2737 Use the internal page title for the search index
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: bug

#2747 Do not query for PIDs when building the breadcrumb of a File data container
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#2717 Use the chained router to find root pages
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Functional/app/Resources/contao_test.sql
Labels: bug

#2721 Ignore custom templates in the back end
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  core-bundle/tests/Fixtures/src/Controller/ContentElement/TestController.php
  core-bundle/tests/Fixtures/src/Controller/FrontendModule/TestController.php
Labels: bug

#1909 Correctly handle custom default templates of fragments
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
  core-bundle/tests/Fixtures/src/Contao/LegacyElement.php
  core-bundle/tests/Fixtures/src/Contao/LegacyModule.php
Labels: bug

#2755 Remove an unnecessary loadLanguageFile() call
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
Labels: bug

#2749 Correctly fix the domain when generating URLs from a page array
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#2754 Fix the line-height of the main headline
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#2756 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  calendar-bundle/src/Resources/contao/languages/sq/tl_calendar.xlf
  comments-bundle/src/Resources/contao/languages/sq/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  faq-bundle/src/Resources/contao/languages/sk/tl_faq.xlf
  faq-bundle/src/Resources/contao/languages/sk/tl_faq_category.xlf
  faq-bundle/src/Resources/contao/languages/sq/tl_faq_category.xlf
  news-bundle/src/Resources/contao/languages/sq/modules.xlf
  news-bundle/src/Resources/contao/languages/sq/tl_module.xlf
  news-bundle/src/Resources/contao/languages/sq/tl_news.xlf
  news-bundle/src/Resources/contao/languages/sq/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/sq/tl_user.xlf
Labels: release

#2757 Merge branch '4.9' into 4.10
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
  core-bundle/tests/Fixtures/Functional/Routing/root-with-home.yml
  core-bundle/tests/Fixtures/src/Contao/LegacyElement.php
  core-bundle/tests/Fixtures/src/Contao/LegacyModule.php
  core-bundle/tests/Fixtures/src/Controller/ContentElement/TestController.php
  core-bundle/tests/Fixtures/src/Controller/FrontendModule/TestController.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
  phpstan.neon.dist
Labels: release

#2758 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  calendar-bundle/src/Resources/contao/languages/pl/tl_calendar_events.xlf
  calendar-bundle/src/Resources/contao/languages/sq/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/sq/tl_calendar_events.xlf
  comments-bundle/src/Resources/contao/languages/sq/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pl/default.xlf
  core-bundle/src/Resources/contao/languages/pl/exception.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_files.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_page.xlf
  faq-bundle/src/Resources/contao/languages/sk/tl_faq.xlf
  faq-bundle/src/Resources/contao/languages/sk/tl_faq_category.xlf
  faq-bundle/src/Resources/contao/languages/sq/tl_faq_category.xlf
  news-bundle/src/Resources/contao/languages/pl/tl_news.xlf
  news-bundle/src/Resources/contao/languages/sq/modules.xlf
  news-bundle/src/Resources/contao/languages/sq/tl_module.xlf
  news-bundle/src/Resources/contao/languages/sq/tl_news.xlf
  news-bundle/src/Resources/contao/languages/sq/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/sq/tl_user.xlf
Labels: release

#2765 Merge branch '4.10' into 4.11
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
  core-bundle/tests/Fixtures/Functional/Routing/root-with-home.yml
  core-bundle/tests/Fixtures/src/Contao/LegacyElement.php
  core-bundle/tests/Fixtures/src/Contao/LegacyModule.php
  core-bundle/tests/Fixtures/src/Controller/ContentElement/TestController.php
  core-bundle/tests/Fixtures/src/Controller/FrontendModule/TestController.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
  phpstan.neon.dist
Labels: release

#2766 Automatically prefix the back end attributes
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
Labels: bug

#2764 Fix an illegal array access in DCTable::reviseTables()
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#2763 Fix an illegal array access in BackendUser::navigation()
  core-bundle/src/Resources/contao/classes/BackendUser.php
Labels: bug

#2789 Make PHPStan not nag about changing values in $GLOBALS
  core-bundle/tests/Config/Loader/XliffFileLoaderTest.php
  phpstan.neon.dist
Labels: CI
