Repository contao/contao, pull requests merged in 2022-08, with the labels that each got.

#5037 Fix a wrong method call in the Newsletter class
  newsletter-bundle/contao/classes/Newsletter.php
Labels: bug

#5017 Use the new features of ACE 1.8
  composer.json
  core-bundle/composer.json
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/templates/backend/be_ace.html5
Labels: feature

#5063 Drop support for MAILER_URL
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#5026 Also set collation for database.sql files
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
Labels: bug

#5059 Fix illegal string offsets in the translator
  core-bundle/src/Translation/MessageCatalogue.php
  core-bundle/tests/Translation/TranslatorTest.php
Labels: bug

#5058 Fix illegal string offsets in the translator
  core-bundle/src/Translation/Translator.php
  core-bundle/tests/Translation/TranslatorTest.php
Labels: bug

#5057 Fix empty form uploads causing an error
  core-bundle/contao/forms/Form.php
Labels: bug

#5038 Remove two redundant body classes
  core-bundle/contao/templates/backend/be_help.html5
  core-bundle/contao/templates/backend/be_popup.html5
Labels: bug

#5073 Fix broken insert tag flags
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#5079 Add the removed count increment again
  news-bundle/contao/modules/ModuleNews.php
Labels: bug

#5083 Fix invalid parameter number error
  core-bundle/contao/library/Contao/Database.php
Labels: bug

#5088 Show the video URL in the backend preview
  core-bundle/contao/templates/_new/content_element/_video.html.twig
Labels: bug

#5066 Auto-generate and dump the APP_SECRET during contao-setup
  manager-bundle/config/services.yaml
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
Labels: bug

#5070 Fix DcaLoader exceptions
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/tests/Contao/DcaLoaderTest.php
Labels: bug

#5094 Fix compatibility with doctrine/dbal 3.3.8
  core-bundle/tests/Migration/CommandCompilerTest.php
Labels: bug

#5071 Deprecate noCache parameter of DcaLoader
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
Labels: bug

#5093 Fix undefined array key breadcrumb
  core-bundle/contao/dca/tl_templates.php
Labels: bug

#5098 Fix compatibility with doctrine/dbal 3.3.8
  installation-bundle/tests/Database/InstallerTest.php
Labels: bug

#5095 Don’t use deprecated getIdentifierQuoteCharacter()
  core-bundle/src/Resources/contao/library/Contao/Database.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
Labels: bug

#5036 Don’t cast null values in Model::convertToPhpValue
  core-bundle/contao/library/Contao/Model.php
  core-bundle/tests/Contao/ModelTest.php
Labels: bug

#4939 Fix sectionwizard.js
  core-bundle/public/sectionwizard.js
  core-bundle/public/sectionwizard.min.js
Labels: bug

#5035 Check DCA config when adding default operations
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
Labels: bug

#5048 Fix modulewizard.js
  core-bundle/public/modulewizard.js
  core-bundle/public/modulewizard.min.js
Labels: bug

#5097 Allow null query on unique fields and implement early return
  core-bundle/contao/library/Contao/Model.php
Labels: bug

#5060 Do not modify the global TL_LANG array
  core-bundle/src/DataContainer/DataContainerOperation.php
  core-bundle/tests/DataContainer/DataContainerOperationTest.php
Labels: bug

#5076 Handle empty array when preloading records
  core-bundle/contao/classes/DataContainer.php
Labels: bug

#5016 Fix several argument warnings on PHP methods
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/forms/FormSelectMenu.php
  core-bundle/src/Resources/contao/forms/FormTextArea.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/models/FilesModel.php
Labels: bug

#4862 Modern fragments: download content elements
  UPGRADE.md
  core-bundle/config/controller.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/config/config.php
  core-bundle/contao/templates/_new/component/_download.html.twig
  core-bundle/contao/templates/content_element/download.html.twig
  core-bundle/contao/templates/content_element/downloads.html.twig
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/src/Filesystem/FileDownloadHelper.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/PublicUri/ContentDispositionAware.php
  core-bundle/src/Filesystem/PublicUri/ContentDispositionOption.php
  core-bundle/src/Filesystem/PublicUri/SymlinkedLocalFilesProvider.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/DownloadsControllerTest.php
  core-bundle/tests/Filesystem/FileDownloadHelperTest.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
Labels: feature

#4893 Modern fragments: article teaser + player content elements
  UPGRADE.md
  core-bundle/config/controller.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/config/config.php
  core-bundle/contao/templates/_new/component/_figure.html.twig
  core-bundle/contao/templates/_new/component/_headline.html.twig
  core-bundle/contao/templates/_new/component/_list.html.twig
  core-bundle/contao/templates/_new/component/_read_more.html.twig
  core-bundle/contao/templates/_new/component/_stylesheet.html.twig
  core-bundle/contao/templates/_new/content_element/player.html.twig
  core-bundle/contao/templates/_new/content_element/teaser.html.twig
  core-bundle/src/Controller/ContentElement/PlayerController.php
  core-bundle/src/Controller/ContentElement/TeaserController.php
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/FormatterRuntime.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/PlayerControllerTest.php
  core-bundle/tests/Controller/ContentElement/TeaserControllerTest.php
  core-bundle/tests/Filesystem/FilesystemItemIteratorTest.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Runtime/FormatterRuntimeTest.php
Labels: feature

#5103 Use CSS variables in the back end
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/confirm.css
  core-bundle/contao/themes/flexible/confirm.min.css
  core-bundle/contao/themes/flexible/conflict.css
  core-bundle/contao/themes/flexible/conflict.min.css
  core-bundle/contao/themes/flexible/diff.css
  core-bundle/contao/themes/flexible/diff.min.css
  core-bundle/contao/themes/flexible/fonts.css
  core-bundle/contao/themes/flexible/help.css
  core-bundle/contao/themes/flexible/help.min.css
  core-bundle/contao/themes/flexible/icons/alert.svg
  core-bundle/contao/themes/flexible/icons/chevron-down.svg
  core-bundle/contao/themes/flexible/icons/content.svg
  core-bundle/contao/themes/flexible/icons/debug.svg
  core-bundle/contao/themes/flexible/icons/logo.svg
  core-bundle/contao/themes/flexible/icons/manual.svg
  core-bundle/contao/themes/flexible/icons/monitor.svg
  core-bundle/contao/themes/flexible/icons/person.svg
  core-bundle/contao/themes/flexible/icons/preview.svg
  core-bundle/contao/themes/flexible/icons/profile.svg
  core-bundle/contao/themes/flexible/icons/wrench.svg
  core-bundle/contao/themes/flexible/login.css
  core-bundle/contao/themes/flexible/login.min.css
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/contao/themes/flexible/popup.css
  core-bundle/contao/themes/flexible/popup.min.css
  core-bundle/contao/themes/flexible/switch.css
  core-bundle/contao/themes/flexible/switch.min.css
  core-bundle/contao/themes/flexible/tinymce.css
  core-bundle/contao/themes/flexible/tinymce.min.css
Labels: feature

#5105 Update and run the tools
  core-bundle/contao/elements/ContentAlias.php
  core-bundle/contao/elements/ContentModule.php
  core-bundle/contao/library/Contao/Model.php
  core-bundle/contao/models/PageModel.php
  maker-bundle/src/Reflection/ImportExtractor.php
  maker-bundle/src/Reflection/SignatureGenerator.php
  tools/ecs/composer.lock
  tools/ecs/config/legacy.php
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#4682 News feeds as page controller
  UPGRADE.md
  calendar-bundle/contao/languages/en/tl_layout.xlf
  composer.json
  core-bundle/contao/languages/en/tl_layout.xlf
  core-bundle/contao/themes/flexible/icons/feed.svg
  core-bundle/contao/themes/flexible/icons/feed_1.svg
  core-bundle/contao/themes/flexible/icons/feed_2.svg
  core-bundle/contao/themes/flexible/icons/feed_3.svg
  core-bundle/src/Controller/AbstractController.php
  news-bundle/composer.json
  news-bundle/config/services.yaml
  news-bundle/contao/classes/News.php
  news-bundle/contao/config/config.php
  news-bundle/contao/dca/tl_content.php
  news-bundle/contao/dca/tl_layout.php
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/dca/tl_news_archive.php
  news-bundle/contao/dca/tl_news_feed.php
  news-bundle/contao/dca/tl_page.php
  news-bundle/contao/dca/tl_user.php
  news-bundle/contao/dca/tl_user_group.php
  news-bundle/contao/languages/en/default.xlf
  news-bundle/contao/languages/en/modules.xlf
  news-bundle/contao/languages/en/tl_layout.xlf
  news-bundle/contao/languages/en/tl_news_archive.xlf
  news-bundle/contao/languages/en/tl_news_feed.xlf
  news-bundle/contao/languages/en/tl_page.xlf
  news-bundle/contao/languages/en/tl_user.xlf
  news-bundle/contao/models/NewsFeedModel.php
  news-bundle/src/Controller/Page/NewsFeedController.php
  news-bundle/src/Cron/GenerateFeedsCron.php
  news-bundle/src/Event/FetchArticlesForFeedEvent.php
  news-bundle/src/Event/TransformArticleForFeedEvent.php
  news-bundle/src/EventListener/DataContainer/LayoutFeedOptionsListener.php
  news-bundle/src/EventListener/DataContainer/PageListener.php
  news-bundle/src/EventListener/GeneratePageListener.php
  news-bundle/src/EventListener/InsertTagsListener.php
  news-bundle/src/EventListener/NewsFeedListener.php
  news-bundle/src/Migration/FeedMigration.php
  news-bundle/src/Security/ContaoNewsPermissions.php
  news-bundle/tests/Controller/Page/NewsFeedControllerTest.php
  news-bundle/tests/Cron/GenerateFeedsCronTest.php
  news-bundle/tests/EventListener/DataContainer/LayoutFeedOptionsListenerTest.php
  news-bundle/tests/EventListener/DataContainer/PageListenerTest.php
  news-bundle/tests/EventListener/GeneratePageListenerTest.php
  news-bundle/tests/EventListener/InsertTagsListenerTest.php
  news-bundle/tests/EventListener/NewsFeedListenerTest.php
  news-bundle/tests/Migration/FeedMigrationTest.php
Labels: feature

#5115 Fix member registration issues
  core-bundle/contao/models/OptInModel.php
  core-bundle/contao/modules/ModuleRegistration.php
Labels: bug

#5117 Change default CSS class names for content elements
  core-bundle/contao/templates/_new/content_element/_base.html.twig
  core-bundle/tests/Controller/ContentElement/CodeControllerTest.php
  core-bundle/tests/Controller/ContentElement/DownloadsControllerTest.php
  core-bundle/tests/Controller/ContentElement/HyperlinkControllerTest.php
  core-bundle/tests/Controller/ContentElement/ImagesControllerTest.php
  core-bundle/tests/Controller/ContentElement/ListControllerTest.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
  core-bundle/tests/Controller/ContentElement/PlayerControllerTest.php
  core-bundle/tests/Controller/ContentElement/TableControllerTest.php
  core-bundle/tests/Controller/ContentElement/TeaserControllerTest.php
  core-bundle/tests/Controller/ContentElement/TextControllerTest.php
  core-bundle/tests/Controller/ContentElement/ToplinkControllerTest.php
  core-bundle/tests/Controller/ContentElement/VideoControllerTest.php
Labels: bug

#5010 Fix adjustTime in tl_calendar_events
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
Labels: bug

#5077 Fix indeterministic order for non-unique filters in DC_Table
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5032 Allow null for PaletteManipulator parent
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/tests/DataContainer/PaletteManipulatorTest.php
Labels: bug

#4968 Set login constants in request listener
  core-bundle/src/EventListener/LegacyLoginConstantsListener.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/Framework/ContaoFrameworkTest.php
Labels: bug

#5011 Stop using utf8_decode() and utf8_encode()
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug, CI

#5075 Do not include "index" in folderUrl
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/tests/Contao/PageModelTest.php
Labels: bug

#4777 Fix the missing cache tag invalidation in tree view
  core-bundle/src/EventListener/PageTrailCacheTagsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/tests/EventListener/PageTrailCacheTagsListenerTest.php
Labels: bug

#5101 Check database version in migrate command
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: bug

#5072 Backport lazy services for CronJob repository
  composer.json
  core-bundle/composer.json
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/Cron/LegacyCronTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#4628 Automatically reduce tl_search.url length
  core-bundle/src/EventListener/DoctrineSchema/AdjustSearchUrlLengthListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/DoctrineSchema/AdjustSearchUrlLengthListenerTest.php
Labels: bug

#5121 Remove leftover code in the DataContainer class
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#5123 Remove the "draft" overlay
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#5124 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  calendar-bundle/src/Resources/contao/languages/tr/default.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_member.xlf
  core-bundle/src/Resources/contao/languages/de/tl_content.xlf
  core-bundle/src/Resources/contao/languages/de/tl_member.xlf
  core-bundle/src/Resources/contao/languages/de/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/es/tl_member.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_member.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_member.xlf
  core-bundle/src/Resources/contao/languages/it/tl_member.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_member.xlf
  core-bundle/src/Resources/contao/languages/lv/tl_member.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_member.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_member.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_member.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_member.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_member.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_member.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_member.xlf
  core-bundle/src/Resources/contao/languages/tr/default.xlf
  core-bundle/src/Resources/contao/languages/tr/tl_member.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_member.xlf
Labels: bug, release

#5127 Merge branch '4.9' into 4.13
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Cron/LegacyCron.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/EventListener/PageTrailCacheTagsListener.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/templates/analytics/analytics_google.html5
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/Cron/LegacyCronTest.php
  core-bundle/tests/DataContainer/PaletteManipulatorTest.php
  core-bundle/tests/EventListener/PageTrailCacheTagsListenerTest.php
Labels: bug, release

#5108 Do not override manually defined ptable configuration
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
Labels: bug

#5129 Handle non-existing table in DcaExtractor
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
Labels: bug

#5061 Improve canonical URL help text
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
Labels: bug

#5009 Keep the ResponseContextAccessor available for autowiring
  core-bundle/src/Resources/config/services.yml
Labels: bug

#4988 Redirect to fragment URL on preview URL error
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
Labels: bug

#5064 Deprecate the MAILER_URL environment variable
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#4979 Fix legacy routing matcher not matching the route if page has no alias
  core-bundle/src/Routing/Matcher/LegacyMatcher.php
Labels: bug

#5092 Check database version in migrate command
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: bug

#5104 Skip the database backup in contao:migrate command if there is no work to do
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Migration/MigrationCollection.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Migration/MigrationCollectionTest.php
Labels: bug

#5142 Support pid foreign keys in DC_Table
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5112 Allow subpalettes based on value 0 in case of selects
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5145 Fix typo in tl_comments
  comments-bundle/src/Resources/contao/dca/tl_comments.php
Labels: bug

#5140 Fix division by zero in _list.html.twig
  core-bundle/contao/templates/_new/component/_list.html.twig
Labels: bug

#5148 Update and run the tools
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Framework/Adapter.php
  core-bundle/src/InsertTag/ChunkedText.php
  core-bundle/src/Mailer/AvailableTransports.php
  manager-bundle/src/Resources/skeleton/config/services.php
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: bug, CI

#5149 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  calendar-bundle/src/Resources/contao/languages/tr/default.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_member.xlf
  core-bundle/src/Resources/contao/languages/cs/tl_page.xlf
  core-bundle/src/Resources/contao/languages/de/tl_content.xlf
  core-bundle/src/Resources/contao/languages/de/tl_member.xlf
  core-bundle/src/Resources/contao/languages/de/tl_page.xlf
  core-bundle/src/Resources/contao/languages/de/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/es/tl_member.xlf
  core-bundle/src/Resources/contao/languages/es/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_member.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_member.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_page.xlf
  core-bundle/src/Resources/contao/languages/it/tl_member.xlf
  core-bundle/src/Resources/contao/languages/it/tl_page.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_member.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_page.xlf
  core-bundle/src/Resources/contao/languages/lv/tl_member.xlf
  core-bundle/src/Resources/contao/languages/lv/tl_page.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_member.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_member.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_member.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_page.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_member.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_member.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_member.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_member.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_page.xlf
  core-bundle/src/Resources/contao/languages/tr/default.xlf
  core-bundle/src/Resources/contao/languages/tr/tl_member.xlf
  core-bundle/src/Resources/contao/languages/tr/tl_page.xlf
Labels: bug, release

#5150 Merge branch '4.13' into 5.0
  calendar-bundle/contao/dca/tl_calendar_events.php
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/forms/FormSelect.php
  core-bundle/contao/forms/FormTextarea.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_page.xlf
  core-bundle/contao/library/Contao/Database.php
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/contao/library/Contao/System.php
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/contao/models/FilesModel.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/Module.php
  core-bundle/contao/modules/ModuleBreadcrumb.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/contao/templates/analytics/analytics_google.html5
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Cron/Cron.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/src/EventListener/PageTrailCacheTagsListener.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Migration/MigrationCollection.php
  core-bundle/src/Translation/MessageCatalogue.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/DataContainer/PaletteManipulatorTest.php
  core-bundle/tests/EventListener/PageTrailCacheTagsListenerTest.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Migration/MigrationCollectionTest.php
  core-bundle/tests/Translation/TranslatorTest.php
  manager-bundle/skeleton/config/services.php
Labels: release

#5146 Fix Input::isPost() behavior for empty requests
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/controllers/BackendCustom.php
  core-bundle/contao/controllers/BackendMain.php
  core-bundle/src/Controller/AbstractBackendController.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#5135 Fix the headline template
  core-bundle/contao/templates/_new/component/_headline.html.twig
  core-bundle/contao/templates/_new/content_element/_base.html.twig
  core-bundle/contao/templates/_new/content_element/headline.html.twig
  core-bundle/tests/Controller/ContentElement/HeadlineControllerTest.php
Labels: bug

#5144 Fix type error in slug generation
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_form.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
Labels: bug

#5147 Fix loop when loading DCA and BackendUser
  calendar-bundle/contao/dca/tl_calendar_events.php
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/DcaLoader.php
  faq-bundle/contao/dca/tl_faq.php
  news-bundle/contao/dca/tl_news.php
Labels: bug

#5154 Allow empty key for subpalette suffix based on select
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5139 Add static URLs to data-icon attributes
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_member_group.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  core-bundle/contao/library/Contao/Image.php
Labels: bug

#4326 Fix the remaining relative URLs
  core-bundle/contao/classes/Versions.php
  core-bundle/contao/library/Contao/Template.php
  core-bundle/contao/models/PageModel.php
  core-bundle/src/EventListener/BackendPreviewRedirectListener.php
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/tests/EventListener/BackendPreviewRedirectListenerTest.php
Labels: bug

#5159 Do not define ptable for tl_content
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#5158 Do not define ptable for tl_content
  core-bundle/contao/dca/tl_content.php
Labels: bug

#5156 Correctly handle RTL layout and window border in tips
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/public/tips.js
  core-bundle/public/tips.min.js
Labels: bug

#5141 Don’t use sprintf() for alias URLs
  calendar-bundle/contao/classes/Calendar.php
  calendar-bundle/src/EventListener/SitemapListener.php
  faq-bundle/contao/dca/tl_faq.php
  faq-bundle/contao/modules/ModuleFaqList.php
  faq-bundle/src/EventListener/SitemapListener.php
  news-bundle/src/EventListener/SitemapListener.php
  newsletter-bundle/contao/modules/ModuleNewsletterList.php
  newsletter-bundle/src/EventListener/SitemapListener.php
Labels: bug

#5162 Update the changelog and the language files
  CHANGELOG.md
  core-bundle/contao/languages/cs/default.xlf
  core-bundle/contao/languages/cs/tl_page.xlf
  core-bundle/contao/languages/de/default.xlf
  core-bundle/contao/languages/de/tl_page.xlf
  core-bundle/contao/languages/es/default.xlf
  core-bundle/contao/languages/es/tl_page.xlf
  core-bundle/contao/languages/fa/default.xlf
  core-bundle/contao/languages/fa/tl_page.xlf
  core-bundle/contao/languages/it/default.xlf
  core-bundle/contao/languages/it/tl_page.xlf
  core-bundle/contao/languages/ja/default.xlf
  core-bundle/contao/languages/ja/modules.xlf
  core-bundle/contao/languages/ja/tl_layout.xlf
  core-bundle/contao/languages/ja/tl_page.xlf
  core-bundle/contao/languages/nl/default.xlf
  core-bundle/contao/languages/nl/tl_page.xlf
  core-bundle/contao/languages/pl/default.xlf
  core-bundle/contao/languages/pl/tl_page.xlf
  core-bundle/contao/languages/pt/default.xlf
  core-bundle/contao/languages/pt/tl_page.xlf
  core-bundle/contao/languages/ru/default.xlf
  core-bundle/contao/languages/ru/modules.xlf
  core-bundle/contao/languages/ru/tl_layout.xlf
  core-bundle/contao/languages/ru/tl_page.xlf
  core-bundle/contao/languages/sr/default.xlf
  core-bundle/contao/languages/sr/tl_page.xlf
  core-bundle/contao/languages/sv/default.xlf
  core-bundle/contao/languages/sv/tl_page.xlf
  core-bundle/contao/languages/tr/default.xlf
  core-bundle/contao/languages/tr/modules.xlf
  core-bundle/contao/languages/tr/tl_layout.xlf
  core-bundle/contao/languages/tr/tl_page.xlf
  news-bundle/contao/languages/de/modules.xlf
  news-bundle/contao/languages/ja/default.xlf
  news-bundle/contao/languages/ja/modules.xlf
  news-bundle/contao/languages/ru/default.xlf
  news-bundle/contao/languages/ru/modules.xlf
  news-bundle/contao/languages/tr/default.xlf
  news-bundle/contao/languages/tr/modules.xlf
Labels: release

#5163 Fix check for existing label in DcaLoader
  core-bundle/contao/library/Contao/DcaLoader.php
Labels: bug

#5132 Check for column options in AdjustSearchUrlLengthListener
  core-bundle/src/EventListener/DoctrineSchema/AdjustSearchUrlLengthListener.php
Labels: bug

#5143 Do not run the DC constructor inside the picker widget
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug

#5155 Deprecate Calendar::addEvent()
  calendar-bundle/src/Resources/contao/classes/Calendar.php
Labels: bug

#5130 Only set login constants in master request
  core-bundle/src/EventListener/LegacyLoginConstantsListener.php
  core-bundle/src/Framework/ContaoFramework.php
Labels: bug

#5137 Set login constants in request listener
  core-bundle/src/EventListener/LegacyLoginConstantsListener.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/Framework/ContaoFrameworkTest.php
Labels: bug

#5164 Fix check for existing label in DcaLoader
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
Labels: bug

#5165 Add the password toggle to the "change password" dialog
  core-bundle/src/Resources/contao/controllers/BackendPassword.php
  core-bundle/src/Resources/contao/templates/backend/be_password.html5
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/login.min.css
Labels: bug

#5166 Merge branch '4.9' into 4.13
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  core-bundle/src/EventListener/DoctrineSchema/AdjustSearchUrlLengthListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
  core-bundle/src/Resources/contao/widgets/Picker.php
  core-bundle/tests/EventListener/DoctrineSchema/AdjustSearchUrlLengthListenerTest.php
Labels: bug, release

#5168 Merge branch '4.13' into 5.0
  core-bundle/contao/controllers/BackendPassword.php
  core-bundle/contao/templates/backend/be_password.html5
  core-bundle/contao/themes/flexible/login.css
  core-bundle/contao/themes/flexible/login.min.css
  core-bundle/contao/widgets/Picker.php
  core-bundle/tests/Cron/CronTest.php
Labels: release

#5171 Fix icons.css compatbility in downloads element
  core-bundle/contao/templates/content_element/download.html.twig
  core-bundle/contao/templates/content_element/downloads.html.twig
  core-bundle/tests/Controller/ContentElement/DownloadsControllerTest.php
Labels: bug

#5170 Correctly replace insert tags within links in the markdown element
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/src/InsertTag/CommonMarkExtension.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
  core-bundle/tests/InsertTag/CommonMarkExtensionTest.php
Labels: bug

#5174 Fix compatibility with Symfony 6
  composer.json
  core-bundle/composer.json
  core-bundle/src/Fragment/FragmentHandler.php
  core-bundle/src/HttpKernel/ControllerResolver.php
  core-bundle/src/Routing/Candidates/AbstractCandidates.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Contao/DcaExtractorTest.php
  core-bundle/tests/HttpKernel/ControllerResolverTest.php
  core-bundle/tests/Picker/PickerTest.php
  manager-bundle/composer.json
Labels: bug

#5173 Move media above richtext
  core-bundle/contao/templates/_new/content_element/text.html.twig
  core-bundle/tests/Controller/ContentElement/TextControllerTest.php
Labels: bug

#5175 Fix loading empty DCAs in unit tests
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Command/DebugPagesCommandTest.php
  core-bundle/tests/Config/Loader/PhpFileLoaderTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Contao/TemplateLoaderTest.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare1.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare2.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare3.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare4.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare5.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare6.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_namespace1.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_namespace2.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
Labels: bug

#5013 Do not insert fields that do not exist in the DB
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5180 Fix configuration of TemplateOptionsListener
  core-bundle/config/listener.yaml
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
Labels: bug

#5181 Update the changelog
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
Labels: bug, release

#5182 Merge branch '4.9' into 4.13
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/tests/Contao/DcaExtractorTest.php
Labels: bug, release

#5167 Allow usages of picker without active record
  core-bundle/src/Resources/contao/classes/Ajax.php
Labels: bug

#5099 Fix the preview link purge job
  core-bundle/src/Cron/PurgePreviewLinksCron.php
  core-bundle/tests/Cron/PurgePreviewLinksCronTest.php
Labels: bug

#4571 Allow searching content elements and members by ID
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_member.php
Labels: bug

#5185 Make the maker-bundle compatible with symfony/maker-bundle >= 1.44.0
  maker-bundle/src/Maker/MakeContentElement.php
  maker-bundle/src/Maker/MakeDcaCallback.php
  maker-bundle/src/Maker/MakeEventListener.php
  maker-bundle/src/Maker/MakeFrontendModule.php
  maker-bundle/src/Maker/MakeHook.php
Labels: bug

#5186 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/ja/tl_page.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_page.xlf
Labels: bug, release

#5176 Add CSS class for number of columns to gallery template
  core-bundle/contao/templates/_new/content_element/gallery.html.twig
  core-bundle/tests/Controller/ContentElement/ImagesControllerTest.php
Labels: bug

#5188 Add compatibility with symfony/cache ^6.0
  manager-bundle/skeleton/config/config.yaml
  manager-bundle/skeleton/config/services.yaml
Labels: bug

#5189 Fix compatibility with Symfony 6 session
  calendar-bundle/contao/dca/tl_calendar.php
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/contao/dca/tl_calendar_feed.php
  calendar-bundle/contao/dca/tl_content.php
  comments-bundle/contao/classes/Comments.php
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/config/services.yaml
  core-bundle/contao/classes/Ajax.php
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/classes/Crawl.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/classes/Theme.php
  core-bundle/contao/controllers/BackendConfirm.php
  core-bundle/contao/controllers/BackendMain.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_files.php
  core-bundle/contao/dca/tl_form.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/drivers/DC_File.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/Message.php
  core-bundle/contao/library/Contao/System.php
  core-bundle/contao/modules/ModuleChangePassword.php
  core-bundle/contao/modules/ModuleCloseAccount.php
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/widgets/CheckBox.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/AddSessionBagsPass.php
  core-bundle/src/Session/SessionFactory.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddSessionBagsPassTest.php
  faq-bundle/contao/dca/tl_faq.php
  faq-bundle/contao/dca/tl_faq_category.php
  news-bundle/contao/dca/tl_content.php
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/dca/tl_news_archive.php
  newsletter-bundle/contao/dca/tl_newsletter.php
  newsletter-bundle/contao/dca/tl_newsletter_channel.php
  newsletter-bundle/contao/dca/tl_newsletter_recipients.php
  newsletter-bundle/contao/modules/ModuleSubscribe.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
Labels: bug

#5179 Fix download element back end layout
  core-bundle/contao/dca/tl_content.php
Labels: bug

#5191 Run the tools
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/controllers/BackendPassword.php
  core-bundle/contao/library/Contao/Input.php
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
  core-bundle/src/Mailer/ContaoMailer.php
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: CI

#5190 Session cleanup
  core-bundle/contao/forms/Form.php
  core-bundle/src/EventListener/BackendRebuildCacheMessageListener.php
Labels: CI

#5194 Deprecate the Controller::setStaticUrls() method
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#5193 Clear the DEPRECATED.md file and remove some leftovers
  DEPRECATED.md
  UPGRADE.md
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/pages/PageRegular.php
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/tests/TestCase.php
Labels: bug, BC break

#5195 Fix backend preview redirect
  core-bundle/contao/models/PageModel.php
Labels: bug

#5169 Fix server check in migrate and improve message
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: bug

#5001 Use Controller::getContentElement() in the alias element
  core-bundle/contao/elements/ContentAlias.php
  core-bundle/contao/elements/ContentModule.php
Labels: bug

#5197 Final cleanup
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/Routing/PageUrlGenerator.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  news-bundle/src/Controller/Page/NewsFeedController.php
Labels: CI

#5198 Fix skipping backups with schema diff
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: bug

#5199 Fix Input compatibility with Symfony 6
  core-bundle/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#5200 Fix the limit-height.js script
  core-bundle/public/limit-height.js
  core-bundle/public/limit-height.min.js
Labels: bug

#5201 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/contao/languages/ru/tl_page.xlf
Labels: release

#5205 Drop the deprecated article-to-PDF functionality
  core-bundle/composer.json
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/modules/ModuleArticle.php
  manager-bundle/composer.json
Labels: bug

#5206 Deprecate the article-to-PDF functionality
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
Labels: bug

#5204 Do not use the `filesystem` service in the `Folder` class
  core-bundle/contao/library/Contao/Folder.php
Labels: bug

#5207 Fix database exception during contao-setup
  manager-bundle/skeleton/config/config.yaml
Labels: bug

#5214 Use boolean instead of empty string
  core-bundle/contao/controllers/BackendPassword.php
Labels: bug

#5216 Allow to disable ChmodTable widget
  core-bundle/contao/widgets/ChmodTable.php
Labels: bug

#5217 Fix the password field icon
  core-bundle/contao/templates/backend/be_password.html5
  core-bundle/contao/themes/flexible/login.css
  core-bundle/contao/themes/flexible/login.min.css
Labels: bug

#4930 Do not set HTTP header in Versions::addToTemplate
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: bug

#5224 Use the correct label for the "confirm password" field
  core-bundle/src/Resources/contao/forms/FormPassword.php
Labels: bug

#5225 Check the ID when sending comment notifications
  comments-bundle/src/Resources/contao/dca/tl_comments.php
Labels: bug

#5208 Fix the custom paste modes not working properly
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#5221 Correctly validate same page alias with required parameters on multiple domains
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
Labels: bug

#5226 Fix a CSS issue in the install tool database update screen
  core-bundle/src/Resources/contao/themes/flexible/install.css
  core-bundle/src/Resources/contao/themes/flexible/install.min.css
Labels: bug

#5222 Use the firewall name instead of the scope to determine the access strategy
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Security/Authentication/AccessDecisionManager.php
  core-bundle/tests/Security/Authentication/AccessDecisionManagerTest.php
Labels: bug

#5228 Merge branch '4.9' into 4.13
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/forms/FormPassword.php
  core-bundle/src/Resources/contao/themes/flexible/install.css
  core-bundle/src/Resources/contao/themes/flexible/install.min.css
Labels: bug, release

#5227 Fix the password field icon
  core-bundle/src/Resources/contao/templates/backend/be_password.html5
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/login.min.css
Labels: bug

#5229 Merge branch '4.13' into 5.0
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/config/services.yaml
  core-bundle/contao/classes/Versions.php
  core-bundle/contao/forms/FormPassword.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Security/Authentication/AccessDecisionManager.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/Security/Authentication/AccessDecisionManagerTest.php
Labels: release

#5192 Use getCurrentRequest() instead of getMainRequest()
  core-bundle/config/controller.yaml
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Controller/ContentElement/HyperlinkController.php
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/EventListener/DbafsMetadataSubscriber.php
  core-bundle/src/Filesystem/PublicUri/SymlinkedLocalFilesProvider.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Security/Authentication/AccessDecisionManager.php
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/src/Twig/Runtime/UrlRuntime.php
  core-bundle/tests/Controller/ContentElement/HyperlinkControllerTest.php
  core-bundle/tests/EventListener/DbafsMetadataSubscriberTest.php
  core-bundle/tests/Filesystem/PublicUri/SymlinkedLocalFilesProviderTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
Labels: bug

#5233 Backport 'GitHub workflows security hardening'
  .github/workflows/ci.yml
Labels: bug, CI

#5231 Do not use POST values directly for Reply-To and Cc
  core-bundle/src/Resources/contao/forms/Form.php
Labels: bug
