Repository contao/contao, pull requests merged in 2022-01, with the labels that each got.

#3892 Fix method name to get default token value
  comments-bundle/src/Resources/contao/classes/Comments.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: bug

#3889 Add generic toggle operation handling
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: feature

#3862 Add an "overview page" field
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  calendar-bundle/src/Resources/contao/languages/en/default.xlf
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/templates/modules/mod_eventreader.html5
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/models/ModuleModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/tests/Fixtures/Functional/Routing/news.yml
  faq-bundle/src/Resources/contao/dca/tl_module.php
  faq-bundle/src/Resources/contao/languages/en/default.xlf
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  faq-bundle/src/Resources/contao/templates/modules/mod_faqreader.html5
  news-bundle/src/Resources/contao/dca/tl_module.php
  news-bundle/src/Resources/contao/languages/en/default.xlf
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  news-bundle/src/Resources/contao/templates/modules/mod_newsreader.html5
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
  newsletter-bundle/src/Resources/contao/languages/en/default.xlf
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
  newsletter-bundle/src/Resources/contao/templates/modules/mod_newsletterreader.html5
Labels: feature

#3829 Handle `$objPage` not being set in the InsertTags class
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#3888 Deprecate System::getTimeZones()
  core-bundle/src/Resources/contao/config/default.php
  core-bundle/src/Resources/contao/config/timezones.php
  core-bundle/src/Resources/contao/dca/tl_settings.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/tests/Contao/ControllerTest.php
Labels: feature

#3489 Add the send newsletter event
  .github/workflows/ci.yml
  composer.json
  newsletter-bundle/.gitattributes
  newsletter-bundle/.gitignore
  newsletter-bundle/composer.json
  newsletter-bundle/phpunit.xml.dist
  newsletter-bundle/src/Event/SendNewsletterEvent.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/languages/en/tl_newsletter.xlf
  newsletter-bundle/tests/ContaoManager/PluginTest.php
  newsletter-bundle/tests/Event/SendNewsletterEventTest.php
  phpunit.xml.dist
Labels: feature, needs documentation

#3905 Deprecate the PackageUtil class
  DEPRECATED.md
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/VersionCommand.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DataCollector/ContaoDataCollector.php
  core-bundle/src/DependencyInjection/Compiler/AddAssetsPackagesPass.php
  core-bundle/src/DependencyInjection/Compiler/AddPackagesPass.php
  core-bundle/src/Resources/contao/controllers/BackendCustom.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Util/PackageUtil.php
  core-bundle/tests/Command/VersionCommandTest.php
  core-bundle/tests/DataCollector/ContaoDataCollectorTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddAssetsPackagesPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddPackagesPassTest.php
  manager-bundle/src/Console/ContaoApplication.php
  manager-bundle/tests/Console/ContaoApplicationTest.php
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
  tools/service-linter/composer.lock
Labels: bug

#3630 Support image sizes in news and calendar feeds
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar_feed.xlf
  core-bundle/src/EventListener/ImageSizeOptionsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/library/Contao/FeedItem.php
  core-bundle/tests/EventListener/ImageSizeOptionsListenerTest.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  news-bundle/src/Resources/contao/languages/en/tl_news_feed.xlf
Labels: feature

#3911 Support Typescript in the code editor
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: feature

#3917 Update maintenance response and add to preview endpoint
  manager-bundle/src/Resources/skeleton/public/index.php
  manager-bundle/src/Resources/skeleton/public/preview.php
Labels: bug

#3912 Move the imgSize labels to the default.xlf file
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  calendar-bundle/src/Resources/contao/languages/en/tl_calendar_feed.xlf
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  news-bundle/src/Resources/contao/languages/en/tl_news_feed.xlf
Labels: bug

#3916 Fixed tl_page permissions for routing fields
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/views/Backend/be_route_conflicts.html.twig
Labels: bug

#3920 Update the tools
  core-bundle/src/Resources/contao/dca/tl_style_sheet.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  phpstan.neon
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: CI

#3644 Allow MODE_PARENT without child_record_callback
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/widgets/Picker.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: feature

#3848 Add file previews for downloads
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Image/Preview/FallbackPreviewProvider.php
  core-bundle/src/Image/Preview/ImaginePreviewProvider.php
  core-bundle/src/Image/Preview/MissingPreviewProviderException.php
  core-bundle/src/Image/Preview/PreviewFactory.php
  core-bundle/src/Image/Preview/PreviewProviderInterface.php
  core-bundle/src/Image/Preview/UnableToGeneratePreviewException.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/controllers/BackendPopup.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/elements/ContentDownload.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/templates/backend/be_popup.html5
  core-bundle/src/Resources/contao/templates/elements/ce_download.html5
  core-bundle/src/Resources/contao/templates/elements/ce_downloads.html5
  core-bundle/src/Resources/contao/themes/flexible/popup.css
  core-bundle/src/Resources/contao/themes/flexible/popup.min.css
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Image/Preview/FallbackPreviewProviderTest.php
  core-bundle/tests/Image/Preview/ImaginePreviewProviderTest.php
  core-bundle/tests/Image/Preview/PreviewFactoryTest.php
Labels: feature

#3883 Improve the maintenance mode command
  manager-bundle/src/Command/MaintenanceModeCommand.php
  manager-bundle/tests/Command/MaintenanceModeCommandTest.php
Labels: feature

#3914 Show route path with regexp in page settings
  core-bundle/src/EventListener/DataContainer/PageRoutingListener.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/views/Backend/be_route_conflicts.html.twig
  core-bundle/src/Resources/views/Backend/be_route_path.html.twig
  core-bundle/tests/EventListener/DataContainer/PageRoutingListenerTest.php
Labels: feature

#3926 Add CSS definitions for info texts in widgets
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/views/Backend/be_route_path.html.twig
Labels: feature

#3498 Improve the undo module for better editor experience
  comments-bundle/src/Resources/public/comments.min.css
  core-bundle/src/EventListener/DataContainer/Undo/JumpToParentButtonListener.php
  core-bundle/src/EventListener/DataContainer/Undo/LabelListener.php
  core-bundle/src/EventListener/DataContainer/Undo/UndoListenerTrait.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_undo.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_undo.xlf
  core-bundle/src/Resources/contao/themes/flexible/icons/parent.svg
  core-bundle/src/Resources/contao/themes/flexible/icons/parent_.svg
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/views/Backend/be_undo_label.html.twig
  core-bundle/tests/EventListener/DataContainer/Undo/JumpToParentButtonListenerTest.php
  core-bundle/tests/EventListener/DataContainer/Undo/LabelListenerTest.php
  core-bundle/tests/Fixtures/src/Contao/DC_NewsTableStub.php
Labels: feature

#2959 Add the back end attributes and badge title to the preview toolbar
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: feature

#3929 Adjust the SERP preview formatting
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#3180 Render be_main with custom back end controller
  core-bundle/src/Controller/AbstractBackendController.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Twig/Runtime/LegacyTemplateFunctionsRuntime.php
  core-bundle/tests/Controller/AbstractBackendControllerTest.php
Labels: feature

#3684 Use the metadata for the player caption
  core-bundle/src/Resources/contao/elements/ContentMedia.php
Labels: feature

#3785 Show member groups for content elements when protected
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: feature

#3909 Correctly handle types and empty values in DC_Table::save()
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Database/Statement.php
Labels: bug

#3872 Add front end preview links
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Controller/PreviewLinkController.php
  core-bundle/src/Cron/PurgePreviewLinksCron.php
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/dca/tl_preview_link.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/modules.xlf
  core-bundle/src/Resources/contao/languages/en/tl_preview_link.xlf
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/icons/share.svg
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base.html.twig
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
  core-bundle/src/Routing/Matcher/PublishedFilter.php
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/Controller/PreviewLinkControllerTest.php
  core-bundle/tests/Cron/PurgePreviewLinksCronTest.php
  core-bundle/tests/EventListener/DataContainer/PreviewLinkListenerTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
Labels: feature

#3896 Improve the toggle operation
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: bug, needs documentation

#3774 Add a DBAFS service and integrate Flysystem
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/FilesyncCommand.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/DependencyInjection/Filesystem/ConfigureFilesystemInterface.php
  core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php
  core-bundle/src/Event/AbstractDbafsMetadataEvent.php
  core-bundle/src/EventListener/DbafsMetadataSubscriber.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/Dbafs/DbafsFactory.php
  core-bundle/src/Filesystem/Dbafs/DbafsInterface.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/Dbafs/Hashing/Context.php
  core-bundle/src/Filesystem/Dbafs/Hashing/HashGenerator.php
  core-bundle/src/Filesystem/Dbafs/Hashing/HashGeneratorInterface.php
  core-bundle/src/Filesystem/Dbafs/RetrieveDbafsMetadataEvent.php
  core-bundle/src/Filesystem/Dbafs/StoreDbafsMetadataEvent.php
  core-bundle/src/Filesystem/Dbafs/UnableToResolveUuidException.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/FilesystemUtil.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemException.php
  core-bundle/src/Filesystem/VirtualFilesystemFactory.php
  core-bundle/src/Filesystem/VirtualFilesystemInterface.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/tests/Command/FilesyncCommandTest.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/DependencyInjection/Compiler/ConfigureFilesystemPassTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/DependencyInjection/Filesystem/FilesystemConfigurationTest.php
  core-bundle/tests/EventListener/DbafsMetadataSubscriberTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSetTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsFactoryTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/Dbafs/Hashing/ContextTest.php
  core-bundle/tests/Filesystem/Dbafs/Hashing/HashGeneratorTest.php
  core-bundle/tests/Filesystem/Dbafs/RetrieveDbafsMetadataEventTest.php
  core-bundle/tests/Filesystem/Dbafs/StoreDbafsMetadataEventTest.php
  core-bundle/tests/Filesystem/Dbafs/UnableToResolveUuidExceptionTest.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
  core-bundle/tests/Filesystem/FilesystemUtilTest.php
  core-bundle/tests/Filesystem/MountManagerTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemExceptionTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemFactoryTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  core-bundle/tests/Fixtures/Filesystem/FilesystemConfiguringExtension.php
  core-bundle/tests/Functional/DbafsTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: feature

#3419 Add options to customize the layout inheritance for pages
  core-bundle/src/EventListener/DataContainer/LayoutOptionsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/EventListener/DataContainer/LayoutOptionsListenerTest.php
Labels: feature

#3613 Add a root page dependent module selector
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/FrontendModule/RootPageDependentModulesController.php
  core-bundle/src/EventListener/Widget/RootPageDependentSelectListener.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/languages/en/modules.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/models/ModuleModel.php
  core-bundle/src/Resources/contao/widgets/RootPageDependentSelect.php
  core-bundle/tests/Contao/RootPageDependentSelectTest.php
  core-bundle/tests/Controller/FrontendModule/RootPageDependentModulesControllerTest.php
  core-bundle/tests/EventListener/Widget/RootPageDependentSelectListenerTest.php
Labels: feature, needs documentation

#3938 Remove remaining deprecations
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/tests/Controller/FrontendControllerTest.php
  core-bundle/tests/Functional/app/config/config_test.yml
Labels: bug

#3937 Various small filesystem tweaks
  core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemInterface.php
  core-bundle/tests/DependencyInjection/Filesystem/FilesystemConfigurationTest.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
Labels: bug

#3927 Explicitly set rootPaste, deprecate implicit rootPaste
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3940 Run the code inspector
  core-bundle/src/Image/Preview/ImaginePreviewProvider.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/tests/EventListener/DataContainer/PreviewLinkListenerTest.php
  core-bundle/tests/Functional/DbafsTest.php
Labels: CI

#3945 Make security.encoder_factory public again
  core-bundle/src/DependencyInjection/Compiler/MakeServicesPublicPass.php
Labels: bug

#3946 Remove the AddPackagesPassTest
  core-bundle/tests/DependencyInjection/Compiler/AddPackagesPassTest.php
Labels: CI

#3939 Fix duplicating child records with dynamic ptable
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3952 Fix default log context for Email::sendTo
  core-bundle/src/Resources/contao/library/Contao/Email.php
Labels: bug

#3949 Fix a leftover System::log call
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
Labels: bug

#3934 Fixed permission check for preview links
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
Labels: bug

#3962 Fix the button alignment in the parent view
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#3953 Fix the PackageUtil class
  core-bundle/src/Util/PackageUtil.php
  core-bundle/tests/DependencyInjection/Compiler/AddPackagesPassTest.php
Labels: bug

#3966 Add compatibility with symfony/filesystem 5.4
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  installation-bundle/composer.json
  listing-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  newsletter-bundle/composer.json
Labels: bug

#3961 Gray out expired preview links
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
Labels: bug

#3943 Generate useful error message on routing issues
  core-bundle/src/Exception/RouteParametersException.php
  core-bundle/src/Routing/PageUrlGenerator.php
Labels: bug

#3968 Correctly hash the preview file path
  core-bundle/src/Image/Preview/PreviewFactory.php
Labels: bug

#3970 Handle quoted column names in the Statement class
  core-bundle/src/Resources/contao/library/Contao/Database/Statement.php
Labels: bug

#3975 Allow custom labels for the overview links
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  faq-bundle/src/Resources/contao/dca/tl_module.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/dca/tl_module.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
Labels: bug

#3972 Add require-checker tool
  .github/workflows/ci.yml
  composer.json
  core-bundle/composer.json
  core-bundle/src/Image/Preview/PreviewFactory.php
  maker-bundle/composer.json
  maker-bundle/src/Generator/ClassGenerator.php
  maker-bundle/src/Generator/DcaGenerator.php
  maker-bundle/src/Generator/LanguageFileGenerator.php
  maker-bundle/src/Generator/TemplateGenerator.php
  maker-bundle/src/Maker/AbstractFragmentMaker.php
  tools/require-checker/composer.json
  tools/require-checker/composer.lock
  tools/require-checker/config.json
Labels: CI

#3935 Allow Flysystem v3
  composer.json
  core-bundle/composer.json
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemException.php
  core-bundle/src/Filesystem/VirtualFilesystemInterface.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Filesystem/MountManagerTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemExceptionTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
Labels: bug

#3978 Change the root page icon in maintenance mode
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/themes/flexible/icons/root_1.svg
  core-bundle/src/Resources/contao/themes/flexible/icons/root_2.svg
  core-bundle/tests/Contao/ControllerTest.php
Labels: bug

#3979 Sort the root IDs if there is a `sorting` column
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#3842 Simplify expression in Crawl\Escargot\Factory
  core-bundle/src/Crawl/Escargot/Factory.php
Labels: bug

#3915 Do not generate URL for insert tags that don’t need it
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#3910 Fix the ScriptHandlers for Composer 2.3
  core-bundle/src/Composer/ScriptHandler.php
  core-bundle/tests/Composer/ScriptHandlerTest.php
  manager-bundle/src/Composer/ScriptHandler.php
Labels: bug

#3488 Add a configuration for allowed URL protocols
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
Labels: bug

#3790 Add a debounce wrapper to the username autosuggester
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
Labels: bug

#3981 Reduce the scope of the authentication listener
  core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php
Labels: bug

#3971 Fix `Input::post()` for form data
  core-bundle/src/Resources/contao/library/Contao/Input.php
Labels: bug

#3984 Add the config.allow-plugins settings to the composer.json files
  composer.json
  tools/ecs/composer.json
Labels: bug

#3947 Remove the routing error log in breadcrumb module
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
Labels: bug

#3987 Fix the available transports service
  core-bundle/src/DependencyInjection/Compiler/AddAvailableTransportsPass.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/Compiler/AddAvailableTransportsPassTest.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_channel.php
Labels: bug

#3991 Fix an 'Attempt to read property "language" on null' warning
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
Labels: bug

#4005 Fixed missing service name adjustments
  core-bundle/src/DependencyInjection/Compiler/SearchIndexerPass.php
  core-bundle/tests/DependencyInjection/Compiler/SearchIndexerPassTest.php
Labels: bug

#4002 Add a better exception message if a page is unroutable
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#4010 Update the tools
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/helper/functions.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Folder.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
  core-bundle/src/Resources/contao/widgets/FileSelector.php
  tools/ecs/composer.lock
  tools/ecs/config/default.php
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
  tools/require-checker/composer.lock
Labels: CI

#4001 Check `$objPage` in `Controller::getTemplate()`
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#4012 Allow filtering for files/directories when listing contents
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemInterface.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/FilesystemItemIteratorTest.php
Labels: feature

#4030 Correctly handle parameter for requireItem
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/tests/Routing/AbstractPageRouteProviderTest.php
Labels: bug

#4028 Fix replacing insert tags on non-strings
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  core-bundle/src/File/ModelMetadataTrait.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/models/FilesModel.php
  news-bundle/src/Resources/contao/classes/News.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#4027 Also make the AvailableTransports service alias public
  core-bundle/src/Resources/config/services.yml
Labels: bug

#4019 Use `sprintf()` in exception messages
  core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php
  core-bundle/src/Event/AbstractDbafsMetadataEvent.php
  core-bundle/src/EventListener/DbafsMetadataSubscriber.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/FilesystemUtil.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Image/Studio/FigureRenderer.php
  core-bundle/src/Twig/Interop/ContextFactory.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/src/Twig/Loader/ThemeNamespace.php
  core-bundle/tests/DependencyInjection/Filesystem/FilesystemConfigurationTest.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/Dbafs/RetrieveDbafsMetadataEventTest.php
  core-bundle/tests/Filesystem/Dbafs/StoreDbafsMetadataEventTest.php
  core-bundle/tests/Filesystem/FilesystemUtilTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  core-bundle/tests/Image/Studio/FigureRendererTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Interop/ContextFactoryTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  core-bundle/tests/Twig/Loader/ThemeTest.php
  tools/ecs/composer.lock
  tools/ecs/config/legacy.php
  tools/psalm/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#4013 Reload translations if the language changes
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/tests/Contao/SystemTest.php
  core-bundle/tests/Fragment/Reference/ContentElementReferenceTest.php
  core-bundle/tests/Fragment/Reference/FrontendModuleReferenceTest.php
Labels: bug

#4020 Fix compatibility with Composer 2.2.5
  composer.json
  core-bundle/composer.json
  core-bundle/src/DependencyInjection/Compiler/AddAssetsPackagesPass.php
  core-bundle/src/DependencyInjection/Compiler/AddPackagesPass.php
  core-bundle/src/Util/PackageUtil.php
  core-bundle/tests/DependencyInjection/Compiler/AddPackagesPassTest.php
Labels: bug

#4031 Backport 'Replace phpunit/token-stream with nikic/php-parser'
  composer.json
  core-bundle/composer.json
  core-bundle/src/Config/Loader/PhpFileLoader.php
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
  core-bundle/tests/Config/Loader/PhpFileLoaderTest.php
Labels: bug
