Repository contao/contao, pull requests merged in 2022-09, with the labels that each got.

#5234 Correctly list the templates in "override all" mode
  core-bundle/src/Resources/contao/dca/tl_form_field.php
Labels: bug

#5236 Deprecate the User::isMemberOf() method
  core-bundle/contao/library/Contao/User.php
Labels: bug

#5240 Improve the order of operations during the Contao setup
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
Labels: bug

#5238 Correctly check if the localconfig.php file is writeable
  core-bundle/contao/drivers/DC_File.php
Labels: bug

#5246 Move the download templates to the correct location
  core-bundle/contao/templates/_new/content_element/download.html.twig
  core-bundle/contao/templates/_new/content_element/downloads.html.twig
Labels: bug

#5243 Make modern custom templates selectable in the back end
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/tests/Contao/TemplateLoaderTest.php
Labels: bug

#5249 Fix cache tagging for aliased content elements
  core-bundle/src/Resources/contao/elements/ContentAlias.php
Labels: bug

#5237 Pass the contao.web_dir in the Automator::generateSymlinks() method
  core-bundle/contao/library/Contao/Automator.php
Labels: bug

#5260 Fix PHP8 issue if confirm key is not translated
  core-bundle/src/Resources/contao/templates/backend/be_confirm.html5
Labels: bug

#5235 Use the TemplateOptionsListener for form field templates
  core-bundle/config/listener.yaml
  core-bundle/contao/dca/tl_form_field.php
Labels: bug

#5242 Add implicit Twig namespace roots
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Fixtures/Twig/implicit-roots/contao/templates/foo/bar.html.twig
  core-bundle/tests/Fixtures/Twig/implicit-roots/templates/content_element/foo.html.twig
  core-bundle/tests/Fixtures/Twig/implicit-roots/templates/my/theme/content_element/bar.html.twig
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
Labels: bug

#5268 Fix page mounts not being applied correctly
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5269 Don't return empty theme directories in the TemplateLocator
  core-bundle/src/Twig/Loader/TemplateLocator.php
Labels: bug

#5254 Fix template options when using legacy elements
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
Labels: bug

#5266 Fix several autofocus issues in the back end
  core-bundle/contao/templates/backend/be_tinyMCE.html5
  core-bundle/public/autofocus.js
  core-bundle/public/autofocus.min.js
Labels: bug

#5270 Allow symlinked bundle paths in the template files listing
  core-bundle/src/Resources/contao/dca/tl_templates.php
Labels: bug

#5241 Fix several things when submitting data in DC_Table
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#5247 Allow creating modern templates from within the back end
  composer.json
  core-bundle/composer.json
  core-bundle/config/services.yaml
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/languages/en/tl_templates.xlf
  core-bundle/contao/templates/_new/backend/template_skeleton.html.twig
Labels: bug

#5276 Fix the opacity of draft elements
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#5275 Fix the search field in Safari 16
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
Labels: bug

#5271 Fix order of palette combiner
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5278 Update the changelog
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
Labels: bug, release

#5280 Merge branch '4.9' into 4.13
  .github/workflows/ci.yml
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug, release

#5277 Fix the order of the palette combiner
  core-bundle/tests/Contao/DataContainerTest.php
  core-bundle/tests/Contao/DcTableTest.php
Labels: bug

#5281 Update the changelog
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
Labels: bug, release

#5282 Merge branch '4.13' into 5.0
  .github/workflows/ci.yml
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/elements/ContentAlias.php
  core-bundle/contao/forms/Form.php
  core-bundle/contao/templates/backend/be_confirm.html5
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Contao/DataContainerTest.php
  core-bundle/tests/Contao/DcTableTest.php
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
Labels: release

#5284 Include mounted root pages in the topMostRootIds
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5285 Merge branch '4.13' into 5.0
  core-bundle/contao/drivers/DC_Table.php
Labels: release

#5286 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/contao/languages/cs/tl_templates.xlf
  core-bundle/contao/languages/de/tl_templates.xlf
  core-bundle/contao/languages/en/tl_templates.xlf
  core-bundle/contao/languages/es/tl_templates.xlf
  core-bundle/contao/languages/fa/tl_templates.xlf
  core-bundle/contao/languages/it/tl_templates.xlf
  core-bundle/contao/languages/ja/tl_templates.xlf
  core-bundle/contao/languages/nl/tl_templates.xlf
  core-bundle/contao/languages/pl/tl_templates.xlf
  core-bundle/contao/languages/pt/tl_templates.xlf
  core-bundle/contao/languages/ru/tl_templates.xlf
  core-bundle/contao/languages/sr/tl_templates.xlf
  core-bundle/contao/languages/sv/tl_templates.xlf
  core-bundle/contao/languages/tr/tl_templates.xlf
  core-bundle/tests/Contao/DataContainerTest.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/rector/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: release

#5291 Harden the unique field check
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#5292 Run the CS fixer
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/forms/FormTextField.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  faq-bundle/src/Resources/contao/modules/ModuleFaq.php
Labels: bug, CI

#5288 Store Input::setGet in the request attributes
  core-bundle/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#5298 Use `Webmozart\PathUtil\Path` instead of `Symfony\Component\Filesystem\Path`
  core-bundle/src/Resources/contao/dca/tl_templates.php
Labels: bug

#5296 Do not use exponential notation for float values
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug

#5302 Fix an "Undefined array key" issue in the registration module
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#5301 Do not use exponential notation for float values
  core-bundle/contao/library/Contao/StringUtil.php
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/public/core.js
  core-bundle/public/core.min.js
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug

#5250 Fix cache tagging for aliased content elements
  core-bundle/src/Resources/contao/elements/ContentAlias.php
Labels: bug

#5306 Remove the `*****` placeholder in password fields
  core-bundle/src/Resources/contao/widgets/Password.php
  core-bundle/src/Resources/contao/widgets/TextStore.php
Labels: bug

#5312 Fix another 'Undefined array key' issue
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#5314 Fix a wrong comment
  core-bundle/contao/forms/FormUpload.php
Labels: bug

#5313 Fix the basic entities migration
  core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php
Labels: bug

#5310 Fix and adjust the template content element/module
  UPGRADE.md
  core-bundle/contao/templates/_new/content_element/template.html.twig
  core-bundle/contao/templates/_new/frontend_module/template.html.twig
  core-bundle/contao/templates/elements/ce_markdown.html5
  core-bundle/contao/templates/elements/ce_template.html5
  core-bundle/contao/templates/modules/mod_template.html5
  core-bundle/src/Controller/ContentElement/TemplateController.php
  core-bundle/src/Controller/FrontendModule/TemplateController.php
  core-bundle/tests/Controller/ContentElement/TemplateControllerTest.php
Labels: bug

#5309 Backport support for nested template paths
  core-bundle/src/Twig/ContaoTwigUtil.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Twig/ContaoTwigUtilTest.php
Labels: bug

#5317 Disable spell checking in the password field toggle
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#4776 Remove invalid duplicate CSV handling
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5320 Update the tools
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Twig/Interop/ContextFactoryTest.php
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: CI

#5323 Handle CSV fields in the registration and personal data modules
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#5324 Merge branch '4.9' into 4.13
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug, release

#5325 Fix a potential PHP 8 warning in the backend help wizard
  core-bundle/src/Resources/contao/controllers/BackendHelp.php
Labels: bug

#5327 Merge branch '4.13' into 5.0
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/forms/FormText.php
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/contao/widgets/Password.php
  faq-bundle/contao/modules/ModuleFaq.php
Labels: release

#5304 Add a lock overlay for protected articles
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/themes/flexible/icons/articles_1.svg
  core-bundle/contao/themes/flexible/icons/articles_2.svg
  core-bundle/contao/themes/flexible/icons/articles_3.svg
Labels: feature

#5318 Trigger the oncopy_callback for child records
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug
