Repository contao/contao, pull requests merged in 2022-11, with the labels that each got.

#5470 Use executeStatement() instead of query() in search
  core-bundle/src/Resources/contao/library/Contao/Database.php
  core-bundle/src/Resources/contao/library/Contao/Search.php
Labels: bug

#5468 Merge branch '4.9' into 4.13
  .github/workflows/assign-pr.yml
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/widgets/TableWizard.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Fixtures/images/favicon.png
  core-bundle/tests/Functional/SearchTest.php
Labels: bug, release

#5463 Correctly check for excluded field in DC_Folder
  core-bundle/contao/drivers/DC_Folder.php
Labels: bug

#5473 Merge branch '4.13' into 5.0
  .github/workflows/assign-pr.yml
  .github/workflows/ci.yml
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/library/Contao/Database.php
  core-bundle/contao/library/Contao/Search.php
  core-bundle/contao/templates/backend/be_login.html5
  core-bundle/contao/templates/backend/be_login_two_factor.html5
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/contao/templates/backend/be_welcome.html5
  core-bundle/contao/templates/js/js_nocookie.html5
  core-bundle/contao/templates/mootools/moo_tablesort.html5
  core-bundle/contao/themes/flexible/hover.js
  core-bundle/contao/themes/flexible/hover.min.js
  core-bundle/contao/widgets/TableWizard.php
  core-bundle/public/core.js
  core-bundle/public/core.min.js
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/Migration/Version500/OrderFieldMigration.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Fixtures/images/favicon.png
  core-bundle/tests/Functional/SearchTest.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
  manager-bundle/src/ContaoManager/ApiCommand/GetDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/RemoveDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetDotEnvCommand.php
  manager-bundle/tests/ContaoManager/ApiCommand/GetDotEnvCommandTest.php
  manager-bundle/tests/ContaoManager/ApiCommand/RemoveDotEnvCommandTest.php
  manager-bundle/tests/ContaoManager/ApiCommand/SetDotEnvCommandTest.php
Labels: release

#5474 Fix bug with cache in Database::listTables()
  core-bundle/src/Resources/contao/library/Contao/Database.php
  core-bundle/tests/Contao/DatabaseTest.php
Labels: bug

#5471 Use executeStatement() in the Dbafs class
  core-bundle/src/Resources/contao/library/Contao/Dbafs.php
Labels: bug

#5488 Update the tools
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/src/Migration/CommandCompiler.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
  core-bundle/tests/Migration/CommandCompilerTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
  phpstan.neon
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#5467 Correctly handle special characters when encoding domain names
  core-bundle/src/Resources/contao/library/Contao/Idna.php
  core-bundle/tests/Contao/IdnaTest.php
Labels: bug

#5475 Handle cross-website-root redirects in the Frontend::jumpToOrReload method
  core-bundle/src/Resources/contao/classes/Frontend.php
Labels: bug

#5460 Warning: Undefined array key "PATH_TRANSLATED"
  core-bundle/src/Resources/contao/library/Contao/Environment.php
Labels: bug

#5490 Pass the unmodified row to the onshow callback
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#5489 Do not confirm password changes in the widget
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/forms/FormPassword.php
  core-bundle/src/Resources/contao/widgets/Password.php
Labels: bug

#5415 Use password widget for pwChange
  core-bundle/src/Resources/contao/controllers/BackendPassword.php
  core-bundle/src/Resources/contao/templates/backend/be_password.html5
  core-bundle/src/Resources/contao/templates/backend/be_widget_chpw.html5
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/login.min.css
Labels: bug

#5486 Correctly copy templates from symlinked sources
  core-bundle/src/Resources/contao/dca/tl_templates.php
Labels: bug

#5491 Merge branch '4.9' into 4.13
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/controllers/BackendPassword.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/library/Contao/Database.php
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Resources/contao/templates/backend/be_password.html5
  core-bundle/src/Resources/contao/templates/backend/be_widget_chpw.html5
  core-bundle/src/Resources/contao/themes/flexible/login.css
  core-bundle/src/Resources/contao/themes/flexible/login.min.css
  core-bundle/src/Resources/contao/widgets/Password.php
  core-bundle/tests/Contao/DatabaseTest.php
Labels: bug, release

#5492 Update the tools
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/src/Controller/RobotsTxtController.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Controller/FrontendModule/RootPageDependentModulesControllerTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
  core-bundle/tests/Routing/RouteProviderTest.php
  phpstan.neon
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: bug, CI

#5493 Fix the autoFocusFirstInputField function
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  package-lock.json
Labels: bug

#5434 Restore previous translations in `$GLOBALS['TL_LANG']`
  core-bundle/src/Translation/Translator.php
  core-bundle/tests/Translation/TranslatorTest.php
Labels: bug

#5454 Check the preview link validity on every request
  core-bundle/src/Controller/PreviewLinkController.php
  core-bundle/src/Cron/PurgePreviewLinksCron.php
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/dca/tl_preview_link.php
  core-bundle/src/Resources/contao/languages/en/tl_preview_link.xlf
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/src/Security/Authentication/Token/FrontendPreviewToken.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/tests/Cron/PurgePreviewLinksCronTest.php
  core-bundle/tests/EventListener/DataContainer/PreviewLinkListenerTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
  core-bundle/tests/Security/Authentication/Token/FrontendPreviewTokenTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  test-case/src/ContaoTestCase.php
Labels: bug

#5485 Fix and improve mime type handling in the VFS
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/VirtualFilesystemException.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
  core-bundle/tests/Filesystem/MountManagerTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemExceptionTest.php
Labels: bug

#5495 Check the preview link validity on every request
  core-bundle/config/services.yaml
  core-bundle/contao/dca/tl_preview_link.php
  core-bundle/contao/languages/en/tl_preview_link.xlf
  core-bundle/src/Controller/PreviewLinkController.php
  core-bundle/src/Cron/PurgePreviewLinksCron.php
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
  core-bundle/src/EventListener/PreviewAuthenticationListener.php
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/tests/Cron/PurgePreviewLinksCronTest.php
  core-bundle/tests/EventListener/DataContainer/PreviewLinkListenerTest.php
  core-bundle/tests/EventListener/PreviewAuthenticationListenerTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  test-case/src/ContaoTestCase.php
Labels: bug

#5496 Fix and improve mime type handling in the VFS
  core-bundle/contao/templates/_new/component/_download.html.twig
  core-bundle/src/Controller/ContentElement/PlayerController.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/VirtualFilesystemException.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
  core-bundle/tests/Filesystem/MountManagerTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemExceptionTest.php
Labels: bug

#5494 Merge branch '4.13' into 5.0
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/classes/Frontend.php
  core-bundle/contao/controllers/BackendPassword.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/library/Contao/Database.php
  core-bundle/contao/library/Contao/Dbafs.php
  core-bundle/contao/library/Contao/Idna.php
  core-bundle/contao/templates/backend/be_password.html5
  core-bundle/contao/templates/backend/be_widget_chpw.html5
  core-bundle/contao/themes/flexible/login.css
  core-bundle/contao/themes/flexible/login.min.css
  core-bundle/contao/widgets/Password.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Translation/Translator.php
  core-bundle/tests/Contao/DatabaseTest.php
  core-bundle/tests/Contao/IdnaTest.php
  core-bundle/tests/Translation/TranslatorTest.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: release

#5500 Display results when reloading finished crawler
  core-bundle/src/Resources/contao/classes/Crawl.php
Labels: bug

#5499 Fix automatic DBAFS sync for root resources
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/tests/Functional/DbafsTest.php
Labels: bug

#5498 Handle broken images in FigureBuilder#buildIfResourceExists()
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#5503 Merge branch '4.13' into 5.0
  core-bundle/contao/classes/Crawl.php
  core-bundle/contao/controllers/BackendPassword.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Functional/DbafsTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: release

#5315 Add a template finder service for Twig and fix custom template selection
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/src/Twig/ContaoTwigUtil.php
  core-bundle/src/Twig/Finder/Finder.php
  core-bundle/src/Twig/Finder/FinderFactory.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Contao/TemplateLoaderTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
  core-bundle/tests/Fixtures/Twig/inheritance/vendor-bundles/InvalidBundle1/templates/foo.html.twig
  core-bundle/tests/Fixtures/Twig/inheritance/vendor-bundles/InvalidBundle1/templates/sub/foo.html.twig
  core-bundle/tests/Fixtures/Twig/inheritance/vendor-bundles/InvalidBundle2/templates/text.json.twig
  core-bundle/tests/Twig/ContaoTwigUtilTest.php
  core-bundle/tests/Twig/Finder/FinderTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
Labels: bug

#5487 Render variant templates in the back end
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
Labels: bug

#5428 Read column types from database if cache is missing
  core-bundle/contao/library/Contao/Model.php
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Command/DebugPagesCommandTest.php
  core-bundle/tests/Contao/ModelTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
Labels: bug

#5504 Merge branch '5.0' into 5.x
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/library/Contao/Model.php
  core-bundle/contao/library/Contao/StringUtil.php
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/DataContainer/DataContainerOperation.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/src/Twig/ContaoTwigUtil.php
  core-bundle/src/Twig/Finder/Finder.php
  core-bundle/src/Twig/Finder/FinderFactory.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Command/DebugPagesCommandTest.php
  core-bundle/tests/Contao/ModelTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Contao/TemplateLoaderTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
  core-bundle/tests/Fixtures/Twig/inheritance/vendor-bundles/InvalidBundle1/templates/foo.html.twig
  core-bundle/tests/Fixtures/Twig/inheritance/vendor-bundles/InvalidBundle1/templates/sub/foo.html.twig
  core-bundle/tests/Fixtures/Twig/inheritance/vendor-bundles/InvalidBundle2/templates/text.json.twig
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Twig/ContaoTwigUtilTest.php
  core-bundle/tests/Twig/Finder/FinderTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
Labels: release

#5505 Use the setUp() method in the DbafsTest class
  core-bundle/tests/Functional/DbafsTest.php
Labels: bug, CI

#5511 Fix undefined array key access
  core-bundle/src/Resources/contao/classes/FrontendUser.php
Labels: bug

#5517 Handle possibly missing variable
  core-bundle/src/Resources/contao/library/Contao/Environment.php
Labels: bug

#5520 Improve the stability of the JSON export for the "user list" command
  core-bundle/src/Command/UserListCommand.php
Labels: bug

#5524 Fixed potential PHP8 issues in picker widget
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug

#5534 Fix javascript error in popups
  core-bundle/src/Resources/contao/themes/flexible/hover.js
  core-bundle/src/Resources/contao/themes/flexible/hover.min.js
Labels: bug

#5528 Increase padding on selects in Firefox
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
Labels: bug

#5333 Correctly handle invalid path in DC_Folder
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#5518 Correctly handle missing inputType in DCA
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
Labels: bug

#5539 Merge branch '4.13' into 5.0
  composer.json
  core-bundle/composer.json
  core-bundle/contao/classes/FrontendUser.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/elements/ContentAccordion.php
  core-bundle/contao/elements/ContentElement.php
  core-bundle/contao/elements/ContentText.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/hover.js
  core-bundle/contao/themes/flexible/hover.min.js
  core-bundle/contao/widgets/Picker.php
  core-bundle/contao/widgets/TimePeriod.php
  core-bundle/src/Command/UserListCommand.php
  core-bundle/tests/Functional/DbafsTest.php
Labels: release
