Repository contao/contao, pull requests merged in 2022-02, with the labels that each got.

#4032 Add a conflict for doctrine/dbal:3.3.0
  composer.json
  core-bundle/composer.json
Labels: bug

#4033 Fix some more PHP8 issues
  core-bundle/src/Picker/AbstractPickerProvider.php
  core-bundle/src/Resources/contao/widgets/ImageSize.php
Labels: bug

#4009 Fix long content being cut off in the back end popup
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#3800 Fix routing with local domain and port
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Routing/Matcher/UrlMatcher.php
  core-bundle/tests/Functional/app/Resources/contao_test.sql
Labels: bug

#3857 Fix fragments in RSS feeds
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  news-bundle/src/Resources/contao/classes/News.php
Labels: bug

#4034 Fix 'Warning: Undefined array key 1' in insert tags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#4044 Fix CI
  composer.json
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
  tools/ecs/composer.json
Labels: CI

#4053 Merge branch '4.9' into 4.12
  .editorconfig
  calendar-bundle/composer.json
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/DependencyInjection/Compiler/AddAssetsPackagesPass.php
  core-bundle/src/DependencyInjection/Compiler/AddPackagesPass.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
  core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php
  core-bundle/src/Util/PackageUtil.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Contao/SystemTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddPackagesPassTest.php
  core-bundle/tests/Fragment/Reference/ContentElementReferenceTest.php
  core-bundle/tests/Fragment/Reference/FrontendModuleReferenceTest.php
  faq-bundle/composer.json
  installation-bundle/composer.json
  listing-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  news-bundle/src/Resources/contao/classes/News.php
  newsletter-bundle/composer.json
Labels: release

#4054 Fix the PHP 8.2 CI job
  .github/workflows/ci.yml
Labels: CI

#4056 Fix merging cssID from ContentModule to FrontendModuleController
  core-bundle/src/Resources/contao/elements/ContentModule.php
Labels: bug

#3997 Fix several array to string conversions
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  core-bundle/src/Resources/contao/controllers/FrontendShare.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/library/Contao/Idna.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
Labels: bug

#4059 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_image_size_item.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/modules.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_page.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_theme.xlf
  core-bundle/src/Resources/contao/languages/lv/default.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sr/modules.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  faq-bundle/src/Resources/contao/languages/sl/tl_faq.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.fr.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.fr.xlf
  news-bundle/src/Resources/contao/languages/fa/default.xlf
  news-bundle/src/Resources/contao/languages/sr/modules.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_module.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_news.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_news_feed.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_user.xlf
  newsletter-bundle/src/Resources/contao/languages/sl/tl_newsletter_recipients.xlf
Labels: release

#4060 Fix the missing request token in ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
Labels: bug

#4043 Fix BC for `TL_LANG.LNG` and `TL_LANG.CNT`
  DEPRECATED.md
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/tests/Contao/SystemTest.php
  phpstan.neon.dist
Labels: bug

#4063 Merge branch '4.12' into 4.13
  .editorconfig
  DEPRECATED.md
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Picker/AbstractPickerProvider.php
  core-bundle/src/Resources/contao/controllers/FrontendShare.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/library/Contao/Idna.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/SortedIterator.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/ImageSize.php
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
  core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/SystemTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/Fragment/Reference/ContentElementReferenceTest.php
  core-bundle/tests/Fragment/Reference/FrontendModuleReferenceTest.php
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
  phpstan.neon
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
Labels: release

#4049 Support \Attribute::TARGET_METHOD for our DI attributes
  core-bundle/src/DependencyInjection/Attribute/AsCallback.php
  core-bundle/src/DependencyInjection/Attribute/AsCronJob.php
  core-bundle/src/DependencyInjection/Attribute/AsHook.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Fixtures/ClassWithMethod.php
Labels: bug

#4022 Add missing option showFilePreview to fileTree widget
  core-bundle/src/Resources/contao/widgets/FileTree.php
Labels: bug, needs documentation

#4067 Correctly handle null values in DCs
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#4021 Fix time sensitive test
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Doctrine/Backup/BackupManagerTest.php
  phpunit.xml.dist
Labels: bug

#4071 Update the tools
  tools/ecs/composer.lock
  tools/psalm/composer.lock
Labels: CI

#4072 Reduce memory consumption when warming up cache
  core-bundle/src/Config/Loader/PhpFileLoader.php
Labels: bug

#4075 Remove the `Controller::$Template` property
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
Labels: bug

#4045 Correctly strip all CSRF token occurrences
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
Labels: bug

#4079 Update the changelog
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
Labels: release

#4080 Merge branch '4.9' into 4.12
  core-bundle/src/Config/Loader/PhpFileLoader.php
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
Labels: release

#4076 Trigger a deprecation if an old `contao.localconfig` key is used
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: bug

#4081 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  calendar-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/default.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/fa/default.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_image_size_item.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/fr/default.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_form.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_page.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/ja/default.xlf
  core-bundle/src/Resources/contao/languages/ja/modules.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_page.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_theme.xlf
  core-bundle/src/Resources/contao/languages/lv/default.xlf
  core-bundle/src/Resources/contao/languages/nl/default.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sr/default.xlf
  core-bundle/src/Resources/contao/languages/sr/modules.xlf
  core-bundle/src/Resources/contao/languages/sv/default.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_form.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/zh/default.xlf
  faq-bundle/src/Resources/contao/languages/sl/tl_faq.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.fr.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.fr.xlf
  news-bundle/src/Resources/contao/languages/fa/default.xlf
  news-bundle/src/Resources/contao/languages/sr/modules.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_module.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_news.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_news_archive.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_news_feed.xlf
  news-bundle/src/Resources/contao/languages/sr/tl_user.xlf
  newsletter-bundle/src/Resources/contao/languages/sl/tl_newsletter_recipients.xlf
Labels: release

#4082 Merge branch '4.12' into 4.13
  core-bundle/src/Config/Loader/PhpFileLoader.php
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
Labels: release

#4003 Fix invalid array access if labels are not defined
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#4046 Encode binary data as hex literal in backup dump
  core-bundle/src/Doctrine/Backup/Dumper.php
  core-bundle/tests/Doctrine/Backup/DumperTest.php
Labels: bug

#4052 Do not fetch similar pages with empty alias
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/tests/Contao/PageModelTest.php
Labels: bug

#4085 Update the CI chain
  .github/workflows/ci.yml
  calendar-bundle/composer.json
  calendar-bundle/phpunit.xml.dist
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  core-bundle/phpunit.xml.dist
  core-bundle/tests/Cache/ContaoCacheClearerTest.php
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Command/ResizeImagesCommandTest.php
  core-bundle/tests/Command/SymlinksCommandTest.php
  core-bundle/tests/Contao/CombinerTest.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Contao/ImageTest.php
  core-bundle/tests/Contao/PictureTest.php
  core-bundle/tests/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/Preview/PreviewFactoryTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Intl/CountriesTest.php
  core-bundle/tests/Intl/LocalesTest.php
  core-bundle/tests/Security/TwoFactor/BackupCodeManagerTest.php
  faq-bundle/composer.json
  faq-bundle/phpunit.xml.dist
  installation-bundle/composer.json
  installation-bundle/phpunit.xml.dist
  listing-bundle/composer.json
  maker-bundle/composer.json
  maker-bundle/phpunit.xml.dist
  manager-bundle/composer.json
  manager-bundle/phpunit.xml.dist
  manager-bundle/tests/Cache/BundleCacheClearerTest.php
  manager-bundle/tests/Command/InstallWebDirCommandTest.php
  manager-bundle/tests/ContaoManager/ApiCommand/RemoveDotEnvCommandTest.php
  manager-bundle/tests/ContaoManager/ApiCommand/SetDotEnvCommandTest.php
  news-bundle/composer.json
  news-bundle/phpunit.xml.dist
  newsletter-bundle/composer.json
  newsletter-bundle/phpunit.xml.dist
  phpunit.xml.dist
Labels: CI

#4088 Run the code inspector
  composer.json
  core-bundle/composer.json
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/src/EventListener/DbafsMetadataSubscriber.php
  core-bundle/src/Resources/contao/widgets/Picker.php
  core-bundle/tests/Contao/SystemTest.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  core-bundle/tests/EventListener/DbafsMetadataSubscriberTest.php
Labels: CI

#4074 Fix `contao:user:list` with empty database
  core-bundle/src/Command/UserListCommand.php
Labels: bug

#4093 Allow autowiring of preview factory
  core-bundle/src/Resources/config/services.yml
Labels: bug

#4094 Fix missing fallback for densities in preview factory
  core-bundle/src/Image/Preview/PreviewFactory.php
  core-bundle/tests/Image/Preview/PreviewFactoryTest.php
Labels: bug

#4095 Fix the logger service calls
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Image.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Contao/ImageTest.php
Labels: bug

#4106 Fix trailing slashes in URL when requireItem is enabled
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
Labels: bug

#4105 Fix trailing slashes in URL for Contao 4.9
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Routing/RouteProviderTest.php
Labels: bug

#4078 Fix 'Purge the preview cache' (path not found)
  core-bundle/src/Resources/contao/library/Contao/Folder.php
Labels: bug

#4065 Fix order of parameters in AsContentElement and AsFrontendModule constructors
  core-bundle/src/DependencyInjection/Attribute/AsContentElement.php
  core-bundle/src/DependencyInjection/Attribute/AsFrontendModule.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#4096 Fix an undefiend array key
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#3992 Automatically generate Twig IDE auto-completion mappings
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderWarmerTest.php
Labels: bug

#4103 Fix the color of bold strings inside error messages
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#4042 Enable SQL strict mode by default
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: feature

#4004 Support virtual filesystem in CLI backup management
  core-bundle/src/Command/Backup/AbstractBackupCommand.php
  core-bundle/src/Command/Backup/BackupCreateCommand.php
  core-bundle/src/Command/Backup/BackupListCommand.php
  core-bundle/src/Command/Backup/BackupRestoreCommand.php
  core-bundle/src/Command/Backup/BackupStreamContentCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Doctrine/Backup/Backup.php
  core-bundle/src/Doctrine/Backup/BackupManager.php
  core-bundle/src/Doctrine/Backup/Config/AbstractConfig.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Command/Backup/BackupCreateCommandTest.php
  core-bundle/tests/Command/Backup/BackupListCommandTest.php
  core-bundle/tests/Command/Backup/BackupRestoreCommandTest.php
  core-bundle/tests/Command/Backup/BackupStreamContentCommandTest.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Doctrine/Backup/BackupManagerTest.php
  core-bundle/tests/Doctrine/Backup/BackupTest.php
  core-bundle/tests/Doctrine/Backup/Config/CreateConfigTest.php
  core-bundle/tests/Doctrine/Backup/Config/RestoreConfigTest.php
  core-bundle/tests/Doctrine/Backup/RetentionPolicyTest.php
Labels: feature

#4112 Skip all dot files when syncing the DBAFS
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
Labels: bug

#3990 Fast manual file sync for the back end
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/languages/en/tl_files.xlf
  core-bundle/src/Resources/views/Backend/be_filesync_report.html.twig
Labels: feature

#4113 Return an empty string if there is no driver
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#4114 Allow DCAs without driver
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#4099 Do not store record preview for DC_Folder instances
  core-bundle/src/EventListener/DataContainer/RecordPreviewListener.php
  core-bundle/tests/EventListener/DataContainer/RecordPreviewListenerTest.php
  core-bundle/tests/Fixtures/src/Contao/DC_ExtendedTableStub.php
  core-bundle/tests/Fixtures/src/Contao/DC_NewsTableStub.php
Labels: bug

#4115 Fix global state in unit tests
  core-bundle/phpunit.xml.dist
  manager-bundle/tests/ContaoManager/PluginTest.php
  phpunit.xml.dist
Labels: CI

#4116 Run the code inspector
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php
  core-bundle/tests/Doctrine/Backup/BackupTest.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: CI

#4118 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/pl/default.xlf
Labels: release

#4134 Remove custom template option
  core-bundle/src/Resources/contao/dca/tl_module.php
Labels: bug

#4117 Do not add the element name to the PHP attribute in the maker bundle
  maker-bundle/src/Resources/skeleton/content-element/ContentElement.tpl.php
  maker-bundle/src/Resources/skeleton/frontend-module/FrontendModule.tpl.php
Labels: bug

#4083 Unlock flatten option for imagine configuration
  core-bundle/src/DependencyInjection/Configuration.php
Labels: bug

#4136 Increase the minimum version of the Composer runtime API
  composer.json
  core-bundle/composer.json
Labels: bug

#4140 Add feed image size property doc comment
  calendar-bundle/src/Resources/contao/models/CalendarFeedModel.php
  news-bundle/src/Resources/contao/models/NewsFeedModel.php
Labels: bug

#4121 Show custom Twig templates in the back end dropdowns
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Contao/TemplateLoaderTest.php
Labels: bug

#4143 Do not use transactions for restoring backups
  core-bundle/src/Doctrine/Backup/BackupManager.php
  core-bundle/tests/Doctrine/Backup/BackupManagerTest.php
Labels: bug

#4123 Add a link to the Contao manual in the back end
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/themes/flexible/icons/manual.svg
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
Labels: feature

#4145 Fix time sensitive tests
  core-bundle/phpunit.xml.dist
  phpunit.xml.dist
Labels: bug

#4146 Detect more global state functions
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
Labels: CI

#4141 Support symlinks in the upload directory
  core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php
  core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php
  core-bundle/tests/DependencyInjection/Compiler/ConfigureFilesystemPassTest.php
  core-bundle/tests/DependencyInjection/Filesystem/FilesystemConfigurationTest.php
Labels: bug

#4133 Improve the preview links back end
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/dca/tl_preview_link.php
  core-bundle/src/Resources/contao/languages/en/tl_preview_link.xlf
  core-bundle/src/Resources/contao/themes/flexible/icons/share_.svg
  core-bundle/src/Resources/public/clipboard.js
  core-bundle/src/Resources/public/clipboard.min.js
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/EventListener/DataContainer/PreviewLinkListenerTest.php
Labels: bug

#4149 Use static description for commands
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Command/Backup/AbstractBackupCommand.php
  core-bundle/src/Command/Backup/BackupCreateCommand.php
  core-bundle/src/Command/Backup/BackupListCommand.php
  core-bundle/src/Command/Backup/BackupRestoreCommand.php
  core-bundle/src/Command/Backup/BackupStreamContentCommand.php
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Command/CronCommand.php
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/Command/DebugDcaCommand.php
  core-bundle/src/Command/DebugFragmentsCommand.php
  core-bundle/src/Command/DebugPagesCommand.php
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Command/UserListCommand.php
  core-bundle/src/Command/UserPasswordCommand.php
  core-bundle/src/Command/VersionCommand.php
  installation-bundle/src/Command/LockCommand.php
  installation-bundle/src/Command/UnlockCommand.php
  manager-bundle/src/Api/Command/VersionCommand.php
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/src/Command/DebugPluginsCommand.php
  manager-bundle/src/Command/InstallWebDirCommand.php
  manager-bundle/src/Command/MaintenanceModeCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/GenerateJwtCookieCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/GetConfigCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/GetDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/ParseJwtCookieCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/RemoveDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetConfigCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetDotEnvCommand.php
  tools/isolated-tests/src/RunTestsIsolatedCommand.php
  tools/service-linter/src/LintServiceIdsCommand.php
Labels: bug

#4151 Make the `crontao.cron` service lazy
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
Labels: bug

#4155 Allow <summary> and <details> tags by default
  core-bundle/src/Resources/contao/config/default.php
Labels: bug

#4163 Update the changelog and the language files
  CHANGELOG.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/de/default.xlf
  core-bundle/src/Resources/contao/languages/de/modules.xlf
  core-bundle/src/Resources/contao/languages/de/tl_module.xlf
  core-bundle/src/Resources/contao/languages/es/default.xlf
  core-bundle/src/Resources/contao/languages/es/tl_form.xlf
  core-bundle/src/Resources/contao/languages/es/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/es/tl_page.xlf
  core-bundle/src/Resources/contao/languages/es/tl_settings.xlf
Labels: release

#4166 Fix the CI chain
  .github/workflows/ci.yml
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  installation-bundle/composer.json
  listing-bundle/composer.json
  maker-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  newsletter-bundle/composer.json
Labels: CI

#4167 Do not skip most of the CI jobs on scheduled runs
  .github/workflows/ci.yml
Labels: CI

#4162 Fix the widget height
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#4183 Clarify the backup command description
  core-bundle/src/Command/Backup/BackupCreateCommand.php
  core-bundle/src/Command/Backup/BackupListCommand.php
  core-bundle/src/Command/Backup/BackupRestoreCommand.php
Labels: bug
