Repository contao/contao, pull requests merged in 2022-07, with the labels that each got.

#4918 Move pages and files to the "content" category
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/explain.xlf
  core-bundle/src/Resources/contao/languages/en/modules.xlf
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_files.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/src/Resources/public/core.js
Labels: feature

#4870 Disable widgets for configured settings
  core-bundle/src/EventListener/DataContainer/DisableAppConfiguredSettingsListener.php
  core-bundle/src/Resources/contao/widgets/ChmodTable.php
  core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php
Labels: bug

#4912 Remove the move operation from DC_Table
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/EditableDataContainerInterface.php
Labels: feature, BC break

#4921 Deprecate uppercase letters in insert tags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
Labels: feature

#4899 Use `disable=0` instead of `disable!=1`
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#4922 Remove $arrCache from the insert tag hooks
  UPGRADE.md
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: feature, BC break

#4907 Update the tools and run the code inspector
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Database/Statement.php
  core-bundle/tests/EventListener/DataContainer/PageSearchListenerTest.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#4925 Commit two leftover changes
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
Labels: CI

#4926 Allow to exclude all tl_page fields
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#4909 Fix the cache and clientCache values
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug, BC break

#4928 Add a template helper method to prefix relative URLs
  core-bundle/src/Resources/config/services.yaml
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/src/Twig/Runtime/UrlRuntime.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/DeprecationsNodeVisitorTest.php
  core-bundle/tests/Twig/Extension/InsertTagTest.php
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/ResponseContext/AddTokenParserTest.php
  core-bundle/tests/Twig/Runtime/UrlRuntimeTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: bug

#4934 Document changes to unknown insert tags
  UPGRADE.md
Labels: bug

#4931 Remove uncached insert tag flag
  UPGRADE.md
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
Labels: bug

#4945 Hard-code timezone to avoid time deviation
  core-bundle/tests/Controller/InsertTagsControllerTest.php
Labels: bug

#4808 Various PHP 8 fixes
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Translation/MessageCatalogue.php
Labels: bug

#4915 Modern fragments: template for the markdown element
  core-bundle/src/Resources/contao/templates/_new/content_element/markdown.html.twig
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
Labels: feature, BC break

#4864 Fix inconsistency when copying child records
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#4865 Correctly check ptable when moving records
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#4950 Merge branch '4.9' into 4.13
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentMedia.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/tests/Picker/TablePickerProviderTest.php
Labels: release

#4932 Deprecate insert tag flag uncached
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#4941 Reduce System::getContainer and $container->getParameter calls
  core-bundle/src/Resources/contao/controllers/BackendPopup.php
  core-bundle/src/Resources/contao/elements/ContentDownload.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterList.php
Labels: bug

#4953 Merge branch '4.13' into 5.x
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/EventListener/DataContainer/DisableAppConfiguredSettingsListener.php
  core-bundle/src/Migration/Version413/RelLightboxMigration.php
  core-bundle/src/Resources/config/migrations.yaml
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/controllers/BackendPopup.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentDownload.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/elements/ContentPlayer.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Translation/MessageCatalogue.php
  core-bundle/tests/Controller/BackendPreviewControllerTest.php
  core-bundle/tests/Controller/InsertTagsControllerTest.php
  core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterList.php
Labels: release

#4948 Fix potential PHP 8 warnings when resizing an uploaded image
  core-bundle/src/Resources/contao/classes/FileUpload.php
Labels: bug

#4933 Do not set header in Ajax::executePostActions
  core-bundle/src/Resources/contao/classes/Ajax.php
Labels: bug

#4940 Fix default callback order
  UPGRADE.md
  core-bundle/src/EventListener/DataContainerCallbackListener.php
  core-bundle/tests/EventListener/DataContainerCallbackListenerTest.php
Labels: bug, BC break, needs documentation

#4947 Add permission checks for paste_buttons
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#4952 Allow iterating FilesystemItemIterator multiple times
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Util/CachingTraversable.php
  core-bundle/tests/Filesystem/FilesystemItemIteratorTest.php
  core-bundle/tests/Util/CachingTraversableTest.php
Labels: bug

#4959 Add a conflict for friendsofsymfony/http-cache version 2.14.0
  composer.json
  core-bundle/composer.json
Labels: CI

#4960 Fix broken subpalette toggling
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#4958 Remove the Contao 4 migrations
  UPGRADE.md
  core-bundle/src/Migration/Version400/Version400Update.php
  core-bundle/src/Migration/Version401/Version410Update.php
  core-bundle/src/Migration/Version403/Version430Update.php
  core-bundle/src/Migration/Version404/Version440Update.php
  core-bundle/src/Migration/Version404/Version447Update.php
  core-bundle/src/Migration/Version405/Version450Update.php
  core-bundle/src/Migration/Version406/Version460Update.php
  core-bundle/src/Migration/Version407/Version470Update.php
  core-bundle/src/Migration/Version408/Version480Update.php
  core-bundle/src/Migration/Version409/CeAccessMigration.php
  core-bundle/src/Migration/Version409/PlayerColorMigration.php
  core-bundle/src/Migration/Version410/DropSearchMigration.php
  core-bundle/src/Migration/Version410/OrderFieldMigration.php
  core-bundle/src/Migration/Version411/MergeWebfontsMigration.php
  core-bundle/src/Migration/Version411/RemoveJsHighlightMigration.php
  core-bundle/src/Migration/Version411/TwoFactorBackupCodesMigration.php
  core-bundle/src/Migration/Version412/AllowedExcludedFieldsMigration.php
  core-bundle/src/Migration/Version412/PageLanguageMigration.php
  core-bundle/src/Migration/Version413/RelLightboxMigration.php
  core-bundle/src/Resources/config/migrations.yaml
  core-bundle/tests/Migration/Version409/CeAccessMigrationTest.php
  core-bundle/tests/Migration/Version411/TwoFactorBackupCodesMigrationTest.php
  newsletter-bundle/src/Migration/Version400/NewsletterModuleMigration.php
  newsletter-bundle/src/Migration/Version410/DenyListMigration.php
  newsletter-bundle/src/Resources/config/migrations.yaml
Labels: feature, BC break, needs documentation

#4961 Always set both collate and collation to the same value
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#4938 Always report the installation as being complete
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
Labels: bug

#4971 Fix the getCurrentRecord() method
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#4957 Fixed str_replace errors when passing null
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
Labels: bug

#4977 Fix the pasteinto button if access is denied
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#4973 Deprecate the importUser hook
  core-bundle/src/Resources/contao/library/Contao/User.php
Labels: bug

#4966 Use cache_suffix for TinyMCE
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
Labels: bug

#4975 Fix tl_member source translations for city and state
  core-bundle/src/Resources/contao/languages/en/tl_member.xlf
Labels: bug

#4978 Merge branch '4.9' into 4.13
  calendar-bundle/src/Picker/EventPickerProvider.php
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_member.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/tests/Picker/ArticlePickerProviderTest.php
  core-bundle/tests/Picker/PagePickerProviderTest.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  news-bundle/src/Picker/NewsPickerProvider.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
Labels: release

#4965 Use cache_suffix for TinyMCE
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
Labels: bug

#4981 Merge branch '4.13' into 5.x
  calendar-bundle/src/Picker/EventPickerProvider.php
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/FileUpload.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_member.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/src/Util/CachingTraversable.php
  core-bundle/tests/Filesystem/FilesystemItemIteratorTest.php
  core-bundle/tests/Picker/ArticlePickerProviderTest.php
  core-bundle/tests/Picker/PagePickerProviderTest.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  core-bundle/tests/Util/CachingTraversableTest.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  news-bundle/src/Picker/NewsPickerProvider.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
Labels: release

#4986 Update the tools
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/require-checker/composer.lock
Labels: CI

#4985 Fix the draft view in column mode
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#4982 Remove unused ForwardCompatibility interfaces
  core-bundle/tests/EventListener/Security/SwitchUserListenerTest.php
  core-bundle/tests/Fixtures/src/Security/User/ForwardCompatibilityTokenInterface.php
  core-bundle/tests/Fixtures/src/Security/User/ForwardCompatibilityUserInterface.php
  core-bundle/tests/Fixtures/src/Security/User/ForwardCompatibilityUserProviderInterface.php
  core-bundle/tests/Security/Authentication/AuthenticationFailureHandlerTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
Labels: CI

#4984 Always retrieve the session from the request instead of the container
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/config/services.yaml
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
Labels: bug

#4709 Add a generic voter for editable table fields
  UPGRADE.md
  calendar-bundle/src/Resources/contao/dca/tl_calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  calendar-bundle/src/Resources/contao/dca/tl_layout.php
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  calendar-bundle/src/Resources/contao/dca/tl_user.php
  calendar-bundle/src/Resources/contao/dca/tl_user_group.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  comments-bundle/src/Resources/contao/dca/tl_content.php
  comments-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/config/services.yaml
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_preview_link.php
  core-bundle/src/Resources/contao/dca/tl_settings.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_File.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Security/Voter/DataContainer/TableAccessVoter.php
  core-bundle/tests/Security/Voter/TableAccessVoterTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  faq-bundle/src/Resources/contao/dca/tl_faq_category.php
  faq-bundle/src/Resources/contao/dca/tl_module.php
  faq-bundle/src/Resources/contao/dca/tl_user.php
  faq-bundle/src/Resources/contao/dca/tl_user_group.php
  listing-bundle/src/Resources/contao/dca/tl_module.php
  news-bundle/src/Resources/contao/dca/tl_layout.php
  news-bundle/src/Resources/contao/dca/tl_module.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/dca/tl_news_archive.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  news-bundle/src/Resources/contao/dca/tl_user.php
  news-bundle/src/Resources/contao/dca/tl_user_group.php
  newsletter-bundle/src/Resources/contao/dca/tl_member.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_channel.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
  newsletter-bundle/src/Resources/contao/dca/tl_user.php
  newsletter-bundle/src/Resources/contao/dca/tl_user_group.php
Labels: feature, BC break

#4989 Make the Input::post() method compatible with Symfony 6
  core-bundle/src/Resources/contao/library/Contao/Input.php
Labels: bug

#4903 Show until/from values for content elements
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: feature

#4992 Remove the old app.php entry point
  UPGRADE.md
  manager-bundle/skeleton/public/app.php
Labels: feature, BC break

#4663 Automatically generate DCA operations with permission checks
  calendar-bundle/contao/dca/tl_calendar.php
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/contao/dca/tl_calendar_feed.php
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_form.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/dca/tl_image_size_item.php
  core-bundle/contao/dca/tl_layout.php
  core-bundle/contao/dca/tl_log.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_member_group.php
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/dca/tl_opt_in.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_preview_link.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/contao/dca/tl_undo.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  core-bundle/src/DataContainer/DataContainerOperation.php
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
  faq-bundle/contao/dca/tl_faq.php
  faq-bundle/contao/dca/tl_faq_category.php
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/dca/tl_news_archive.php
  news-bundle/contao/dca/tl_news_feed.php
Labels: feature

#4983 Make Contao compatible with Symfony 5.4 and 6.x
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
  faq-bundle/composer.json
  listing-bundle/composer.json
  maker-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  newsletter-bundle/composer.json
  test-case/composer.json
Labels: feature

#4993 Use service annotations to tag DCA callbacks
  core-bundle/config/listener.yaml
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
Labels: CI

#4834 Validate start/stop date
  calendar-bundle/config/services.yaml
  core-bundle/config/listener.yaml
  core-bundle/contao/languages/en/default.xlf
  core-bundle/src/EventListener/DataContainer/StartStopValidationListener.php
  core-bundle/tests/EventListener/DataContainer/StartStopValidationListenerTest.php
  news-bundle/config/services.yaml
Labels: feature

#4996 Use the AsCommand attribute instead of the static class properties
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Command/Backup/BackupCreateCommand.php
  core-bundle/src/Command/Backup/BackupListCommand.php
  core-bundle/src/Command/Backup/BackupRestoreCommand.php
  core-bundle/src/Command/Backup/BackupStreamContentCommand.php
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Command/CronCommand.php
  core-bundle/src/Command/CronListCommand.php
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/Command/DebugDcaCommand.php
  core-bundle/src/Command/DebugFragmentsCommand.php
  core-bundle/src/Command/DebugPagesCommand.php
  core-bundle/src/Command/FilesyncCommand.php
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Command/UserListCommand.php
  core-bundle/src/Command/UserPasswordCommand.php
  manager-bundle/src/Api/Command/VersionCommand.php
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/src/Command/DebugPluginsCommand.php
  manager-bundle/src/Command/InstallWebDirCommand.php
  manager-bundle/src/Command/MaintenanceModeCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/GenerateJwtCookieCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/GetConfigCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/GetDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/ParseJwtCookieCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/RemoveDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetConfigCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetDotEnvCommand.php
Labels: CI

#4998 Final code cleanup before the release
  calendar-bundle/contao/modules/ModuleEventMenu.php
  calendar-bundle/contao/modules/ModuleEventReader.php
  calendar-bundle/contao/modules/ModuleEventlist.php
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/classes/Theme.php
  core-bundle/contao/elements/ContentAccordion.php
  core-bundle/contao/elements/ContentDownload.php
  core-bundle/contao/elements/ContentDownloads.php
  core-bundle/contao/elements/ContentGallery.php
  core-bundle/contao/elements/ContentImage.php
  core-bundle/contao/elements/ContentText.php
  core-bundle/contao/elements/ContentVimeo.php
  core-bundle/contao/elements/ContentYouTube.php
  core-bundle/contao/library/Contao/Database/Statement.php
  core-bundle/contao/library/Contao/File.php
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/library/Contao/StringUtil.php
  core-bundle/contao/library/Contao/User.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/Module.php
  core-bundle/contao/modules/ModuleArticleList.php
  core-bundle/contao/modules/ModuleBooknav.php
  core-bundle/contao/modules/ModuleCustomnav.php
  core-bundle/contao/modules/ModuleQuicklink.php
  core-bundle/contao/modules/ModuleQuicknav.php
  core-bundle/contao/modules/ModuleRandomImage.php
  core-bundle/contao/modules/ModuleRssReader.php
  core-bundle/contao/modules/ModuleTwoFactor.php
  core-bundle/contao/widgets/FileTree.php
  faq-bundle/contao/dca/tl_faq.php
  faq-bundle/contao/modules/ModuleFaqList.php
  faq-bundle/contao/modules/ModuleFaqPage.php
  faq-bundle/contao/modules/ModuleFaqReader.php
  listing-bundle/contao/modules/ModuleListing.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  news-bundle/contao/modules/ModuleNews.php
  news-bundle/contao/modules/ModuleNewsList.php
  news-bundle/contao/modules/ModuleNewsMenu.php
  newsletter-bundle/contao/modules/ModuleNewsletterList.php
Labels: CI

#4964 Fix PHP 8 warning in ModuleRegistration
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#5000 Fix requirements with Symfony 6.x
  composer.json
  core-bundle/composer.json
Labels: bug

#5005 Fix database type error in contao:user:create command
  core-bundle/src/Command/UserCreateCommand.php
Labels: bug

#5008 Fix useSSL default value
  core-bundle/src/EventListener/DataContainer/PageUseSslDefaultListener.php
Labels: bug

#5018 Fix the CI chain
  core-bundle/src/Config/Loader/PhpFileLoader.php
  core-bundle/src/Config/Loader/XliffFileLoader.php
  core-bundle/src/Routing/ImagesLoader.php
  gulpfile.js
  manager-bundle/translations/ContaoManagerBundle.en.xlf
  phpstan.neon
  phpunit.xml.dist
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: CI

#5022 Lazy-load the RememberMeRepository
  core-bundle/config/services.yaml
  core-bundle/src/Security/Authentication/RememberMe/RememberMeTokenProvider.php
  core-bundle/tests/Security/Authentication/RememberMe/RememberMeTokenProviderTest.php
Labels: bug

#5023 Correctly handle NDJSON exceptions when checking the DB configuration
  core-bundle/src/Command/MigrateCommand.php
Labels: bug

#5020 Fix wrong UUID being applied when moving resources
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
Labels: bug
