Repository contao/contao, pull requests merged in 2022-05, with the labels that each got.

#3995 Replace old back end paths
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventMenu.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  comments-bundle/src/Resources/contao/modules/ModuleComments.php
  core-bundle/src/EventListener/Widget/RootPageDependentSelectListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/controllers/BackendFile.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/controllers/BackendPage.php
  core-bundle/src/Resources/contao/controllers/BackendPassword.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/src/Resources/contao/modules/ModuleArticleList.php
  core-bundle/src/Resources/contao/modules/ModuleArticlenav.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleLogin.php
  core-bundle/src/Resources/contao/modules/ModuleLogout.php
  core-bundle/src/Resources/contao/modules/ModuleNavigation.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/modules/ModuleRssReader.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/modules/ModuleSitemap.php
  core-bundle/src/Resources/contao/widgets/ModuleWizard.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/EventListener/Widget/RootPageDependentSelectListenerTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqList.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
  news-bundle/src/Resources/contao/modules/ModuleNewsArchive.php
  news-bundle/src/Resources/contao/modules/ModuleNewsList.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterList.php
  newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: bug

#4576 Adjust the FormTextarea widget according to the @todo comment
  UPGRADE.md
  core-bundle/src/Resources/contao/forms/FormTextarea.php
  core-bundle/src/Resources/contao/templates/forms/form_textarea.html5
Labels: feature, BC break

#4497 Revert the DcaExtractor changes
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/tests/Contao/DcaExtractorTest.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_database_assisted_folder_driver.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_file_driver.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_non_database_assisted_folder_driver.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_sql_config.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_sql_config_without_driver.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_without_sql_config.php
Labels: bug

#4584 Removed legacy markdown content element
  core-bundle/src/Resources/contao/elements/ContentMarkdown.php
Labels: feature, BC break

#4585 Remove Backend::addFileMetaInformationToRequest()
  UPGRADE.md
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: feature, BC break

#4588 Backport loop as an option to YouTube videos to 4.9
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
Labels: bug

#4586 Also ignore the Resources folder
  manager-bundle/src/Resources/skeleton/config/services.php
Labels: bug

#4587 Add missing service argument for Version410Update
  core-bundle/src/Resources/config/migrations.yml
Labels: bug

#4579 Support the `|defer` flag in the Template::generateScriptTag() method
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Twig/FragmentTemplate.php
Labels: feature

#4590 Require symfony/deprecation-contracts
  composer.json
  core-bundle/composer.json
Labels: bug

#4589 Re-introduce autowiring aliases for subscribed services
  core-bundle/src/Resources/config/services.yml
Labels: bug

#4591 Merge branch '4.9' into 4.13
  calendar-bundle/composer.json
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/widgets/OptionWizard.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Routing/FrontendLoader.php
  core-bundle/src/Routing/UrlGenerator.php
  core-bundle/tests/Contao/DcaExtractorTest.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_database_assisted_folder_driver.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_file_driver.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_non_database_assisted_folder_driver.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_sql_config.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_sql_config_without_driver.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_without_sql_config.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  installation-bundle/composer.json
  installation-bundle/src/InstallTool.php
  manager-bundle/composer.json
  manager-bundle/src/Resources/skeleton/config/services.php
  news-bundle/composer.json
  news-bundle/src/Resources/contao/classes/News.php
  newsletter-bundle/composer.json
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: release

#4595 Support more widgets in DC_Folder
  core-bundle/src/Resources/contao/classes/Ajax.php
Labels: bug

#4598 Remove leftover contao.encryption_key occurences
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug, BC break

#4599 Do not throw an exception if a page insert tag cannot be generated
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#4596 Fix upload directory check in ImageFactory on Windows
  core-bundle/src/Image/ImageFactory.php
  core-bundle/tests/Image/ImageFactoryTest.php
Labels: bug

#4600 Fix the DCA picker in the CSS editor
  core-bundle/src/Resources/contao/dca/tl_style.php
Labels: bug

#4601 Correctly toggle the CSS class when (un)publishing a format definition
  core-bundle/src/Resources/contao/dca/tl_style.php
Labels: bug

#3887 Make sure the parent directory exists when writing files
  core-bundle/src/Resources/contao/library/Contao/Files.php
Labels: bug

#4604 Use host name without port in some controllers
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Controller/RobotsTxtController.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Controller/RobotsTxtControllerTest.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: bug

#4396 Deprecate the StringUtil::toHtml5() method
  calendar-bundle/src/EventListener/InsertTagsListener.php
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/classes/Events.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Migration/Version413/RelLightboxMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/elements/ContentAccordion.php
  core-bundle/src/Resources/contao/elements/ContentTeaser.php
  core-bundle/src/Resources/contao/elements/ContentText.php
  core-bundle/src/Resources/contao/forms/FormExplanation.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/EventListener/InsertTagsListener.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#4603 Correctly generate the edit URL of a version
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: bug

#4605 Ignore port in Favicon and RobotsTxt controller
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Controller/RobotsTxtController.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Controller/RobotsTxtControllerTest.php
Labels: bug

#3711 Fix being unable to re-register after token expired
  core-bundle/src/Resources/contao/models/MemberModel.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#4514 Do not use head and attribute data in search context
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
Labels: bug

#4519 Fix ESI fragments with inline attributes
  core-bundle/src/Fragment/FragmentHandler.php
  core-bundle/tests/Fragment/FragmentHandlerTest.php
Labels: bug

#4607 Update and run the tools
  calendar-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/Command/DebugFragmentsCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Config/Loader/XliffFileLoader.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/EventListener/ClearSessionDataListener.php
  core-bundle/src/Fragment/FragmentHandler.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/src/Resources/contao/library/Contao/Dbafs.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Security/Authentication/Token/TokenCheckerTest.php
  installation-bundle/src/Controller/InstallationController.php
  news-bundle/src/EventListener/PreviewUrlConvertListener.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
Labels: CI

#4504 Improve the XDebug experience
  test-case/src/WarnXdebugPhpunitExtension.php
Labels: bug

#4609 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/tl_content.xlf
  core-bundle/src/Resources/contao/languages/de/tl_content.xlf
  core-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/it/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_content.xlf
  core-bundle/src/Resources/contao/languages/lv/tl_content.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/exception.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_opt_in.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_content.xlf
  core-bundle/src/Resources/contao/languages/zh/tl_content.xlf
Labels: release

#4611 Merge branch '4.9' into 4.13
  core-bundle/src/Fragment/FragmentHandler.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/library/Contao/Files.php
  core-bundle/src/Resources/contao/models/MemberModel.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Fragment/FragmentHandlerTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
Labels: release

#4612 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/cs/tl_content.xlf
  core-bundle/src/Resources/contao/languages/de/tl_content.xlf
  core-bundle/src/Resources/contao/languages/es/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fa/tl_content.xlf
  core-bundle/src/Resources/contao/languages/fr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/it/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ja/tl_content.xlf
  core-bundle/src/Resources/contao/languages/lv/tl_content.xlf
  core-bundle/src/Resources/contao/languages/nl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_user.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_content.xlf
  core-bundle/src/Resources/contao/languages/ru/tl_user.xlf
  core-bundle/src/Resources/contao/languages/sl/exception.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_module.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_opt_in.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_preview_link.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_undo.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_user.xlf
  core-bundle/src/Resources/contao/languages/sr/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sv/tl_content.xlf
Labels: release

#4593 Remove the Backend::getTinyTemplates() method
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: feature, BC break

#4608 Deprecate the Backend::getTinyTemplates() method
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#4613 Fix access of global DropZone class
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#4619 Run the code inspector
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/src/Repository/RememberMeRepository.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
Labels: CI

#4621 Correctly handle rgxp natural text field attributes
  core-bundle/src/Resources/contao/forms/FormTextField.php
Labels: bug

#4627 Fix RelLightboxMigration if ContaoCommentsBundle is not installed
  core-bundle/src/Migration/Version413/RelLightboxMigration.php
Labels: bug

#4622 Always set a mock session when creating feeds
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  news-bundle/src/Resources/contao/classes/News.php
Labels: bug

#4580 Replace the getSearchablePages hook in the newsletter bundle
  newsletter-bundle/src/DependencyInjection/ContaoNewsletterExtension.php
  newsletter-bundle/src/EventListener/SitemapListener.php
  newsletter-bundle/src/Resources/config/services.yml
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/config/config.php
  newsletter-bundle/tests/EventListener/SitemapListenerTest.php
Labels: BC break

#4626 Fix global state in tests
  .github/workflows/ci.yml
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Contao/DcaExtractorTest.php
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
  test-case/src/ContaoTestCase.php
Labels: CI

#4073 Replace the getSearchablePages hook in the news bundle
  news-bundle/src/EventListener/SitemapListener.php
  news-bundle/src/Resources/config/services.yml
  news-bundle/src/Resources/contao/classes/News.php
  news-bundle/src/Resources/contao/config/config.php
  news-bundle/tests/EventListener/SitemapListenerTest.php
Labels: feature

#4582 Remove the getSearchablePages hook
  UPGRADE.md
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  maker-bundle/src/Resources/config/hooks.yaml
Labels: feature, BC break

#4495 Add permission checks on global operations
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/Voter/DataContainer/DefaultDataContainerVoter.php
  core-bundle/tests/Security/Voter/DefaultDataContainerVoterTest.php
Labels: feature

#4631 Fix the empty URL check in the getCandidates() method
  core-bundle/src/Routing/Candidates/AbstractCandidates.php
  core-bundle/tests/Routing/Candidates/PageCandidatesTest.php
Labels: bug

#4592 Support both `collation:` and `collate:`
  core-bundle/tests/Functional/app/config/config_test.yml
  installation-bundle/src/Database/Installer.php
  installation-bundle/src/Resources/views/configuration_error.html.twig
  manager-bundle/src/Resources/skeleton/config/config.yml
Labels: bug

#4618 Fix the global state unit tests
  calendar-bundle/tests/EventListener/SitemapListenerTest.php
  core-bundle/tests/Contao/DcaExtractorTest.php
  core-bundle/tests/Contao/EnvironmentTest.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  test-case/src/ContaoTestCase.php
Labels: CI

#4617 Ensure that the license field in the MetaWizard contains a URL
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_files.xlf
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
Labels: bug

#4639 Fix the global state watcher tests
  faq-bundle/tests/EventListener/SitemapListenerTest.php
  news-bundle/tests/EventListener/SitemapListenerTest.php
  newsletter-bundle/tests/EventListener/SitemapListenerTest.php
Labels: CI

#4623 Improve how the Contao Twig escaper works
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: bug

#4641 Fix missing PurgePreviewLinksCron registration
  core-bundle/src/Resources/config/services.yml
Labels: bug

#4632 Undeprecate some autowiring aliases
  core-bundle/src/Resources/config/services.yml
Labels: bug

#4638 Deprecate Frontend::getCronTimeout
  core-bundle/src/Resources/contao/classes/Frontend.php
Labels: bug

#4643 Remove superfluous class name in deprecation messages
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#4644 Revert the job name change in the ci.yml file
  .github/workflows/ci.yml
Labels: CI

#4645 Remove the PHPStan ignore rule again
  phpstan.neon
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: CI

#4646 Merge branch '4.13' into 5.x
  .github/workflows/ci.yml
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  core-bundle/src/Migration/Version413/RelLightboxMigration.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/forms/FormText.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/tl_files.xlf
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/src/Routing/Candidates/AbstractCandidates.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Functional/app/config/config_test.yml
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
  core-bundle/tests/Routing/Candidates/PageCandidatesTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  installation-bundle/src/Database/Installer.php
  installation-bundle/src/Resources/views/configuration_error.html.twig
  manager-bundle/src/Resources/skeleton/config/config.yml
  news-bundle/src/Resources/contao/classes/News.php
Labels: release

#4650 Remove support for runonce.php
  UPGRADE.md
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/tests/Command/MigrateCommandTest.php
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/InstallTool.php
Labels: feature, BC break

#4661 Add missing try catch blocks
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#4656 Unset TL_CONFIG in ContaoTestCase::tearDown()
  calendar-bundle/tests/EventListener/InsertTagsListenerTest.php
  calendar-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  calendar-bundle/tests/EventListener/PreviewUrlCreateListenerTest.php
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/tests/TestCase.php
  faq-bundle/tests/EventListener/InsertTagsListenerTest.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  news-bundle/tests/EventListener/InsertTagsListenerTest.php
  news-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  news-bundle/tests/EventListener/PreviewUrlCreateListenerTest.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
  test-case/src/ContaoTestCase.php
Labels: bug

#4653 Drop support for an empty `tl_content.ptable` column
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/Migration/Version500/EmptyPtableMigration.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/models/ContentModel.php
Labels: feature, BC break

#4658 Add a Twig runtime for code highlighting
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/HighlightResult.php
  core-bundle/src/Twig/Runtime/HighlighterRuntime.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Runtime/HighlighterRuntimeTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: feature

#4657 Allow adding document scoped content from within Twig templates
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/ResponseContext/AddNode.php
  core-bundle/src/Twig/ResponseContext/AddTokenParser.php
  core-bundle/src/Twig/ResponseContext/DocumentLocation.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/ResponseContext/AddNodeTest.php
  core-bundle/tests/Twig/ResponseContext/AddTokenParserTest.php
  tools/ecs/config/default.php
Labels: feature

#4668 Fix the hasText/hasDetails usage
  calendar-bundle/src/Resources/contao/templates/events/event_full.html5
  news-bundle/src/Resources/contao/templates/news/news_full.html5
Labels: bug

#4669 Remove all "Unable to generate URL for page" log entries
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
Labels: bug

#4666 tl_content.ptable is mandatory now
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#4636 Remove TL_CRON usage from news-bundle
  news-bundle/src/Cron/GenerateFeedsCron.php
  news-bundle/src/Resources/config/services.yml
  news-bundle/src/Resources/contao/config/config.php
  news-bundle/tests/Cron/GenerateFeedsCronTest.php
Labels: feature

#4637 Remove TL_CRON usage from newsletter-bundle
  newsletter-bundle/src/Cron/PurgeSubscriptionsCron.php
  newsletter-bundle/src/Resources/config/services.yml
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/contao/config/config.php
  newsletter-bundle/tests/Cron/PurgeSubscriptionsCronTest.php
Labels: feature

#4441 Add a bag for file metadata
  core-bundle/src/EventListener/DbafsMetadataSubscriber.php
  core-bundle/src/File/MetadataBag.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/DbafsMetadataSubscriberTest.php
  core-bundle/tests/File/MetadataBagTest.php
Labels: feature

#4674 Use constants for return values of commands
  core-bundle/src/Command/AutomatorCommand.php
  core-bundle/src/Command/Backup/BackupCreateCommand.php
  core-bundle/src/Command/Backup/BackupListCommand.php
  core-bundle/src/Command/Backup/BackupRestoreCommand.php
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Command/CronCommand.php
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/Command/DebugDcaCommand.php
  core-bundle/src/Command/DebugFragmentsCommand.php
  core-bundle/src/Command/DebugPagesCommand.php
  core-bundle/src/Command/FilesyncCommand.php
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Command/UserListCommand.php
  core-bundle/src/Command/UserPasswordCommand.php
  core-bundle/src/Command/VersionCommand.php
  installation-bundle/src/Command/UnlockCommand.php
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/src/Command/DebugPluginsCommand.php
  manager-bundle/src/Command/InstallWebDirCommand.php
  manager-bundle/src/Command/MaintenanceModeCommand.php
Labels: feature

#4675 Undeprecate third Input::get() parameter
  core-bundle/src/Resources/contao/library/Contao/Input.php
Labels: bug

#4681 Fix the PHP 8 warning in Contao\Date class
  core-bundle/src/Resources/contao/library/Contao/Date.php
Labels: bug

#4443 Expose public URIs in the VFS
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/PublicUri/OptionsInterface.php
  core-bundle/src/Filesystem/PublicUri/PublicUriProviderInterface.php
  core-bundle/src/Filesystem/PublicUri/SymlinkedLocalFilesProvider.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemInterface.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Command/Backup/BackupStreamContentCommandTest.php
  core-bundle/tests/Doctrine/Backup/BackupManagerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/Dbafs/Hashing/HashGeneratorTest.php
  core-bundle/tests/Filesystem/MountManagerTest.php
  core-bundle/tests/Filesystem/PublicUri/SymlinkedLocalFilesProviderTest.php
  core-bundle/tests/Functional/DbafsTest.php
Labels: bug

#4662 Deprecate the move operation
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#4673 Fix undefined array key warning when using an article list
  core-bundle/src/Resources/contao/modules/ModuleArticleList.php
Labels: bug

#4651 Remove the deprecated "show to guests only" function
  UPGRADE.md
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  comments-bundle/src/Resources/contao/dca/tl_content.php
  comments-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Migration/Version500/AbstractGuestsMigration.php
  core-bundle/src/Migration/Version500/GuestsMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/languages/en/tl_article.xlf
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/ModuleModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModuleQuicklink.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
  faq-bundle/src/Resources/contao/dca/tl_module.php
  listing-bundle/src/Resources/contao/dca/tl_module.php
  maker-bundle/src/Resources/skeleton/content-element/tl_content.tpl.php
  maker-bundle/src/Resources/skeleton/frontend-module/tl_module.tpl.php
  news-bundle/src/Resources/contao/dca/tl_module.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
Labels: feature, BC break

#4379 Remove the textarea toggleWrap feature
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/themes/flexible/icons/wrap.svg
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: feature

#4687 Fix the unit tests
  core-bundle/tests/Controller/ContentElement/TemplateControllerTest.php
Labels: CI

#4683 Drop the DBAFS file size limit
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
Labels: bug

#4664 Add conditional setting/unsetting to the HtmlAttributes class
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/String/HtmlAttributesTest.php
Labels: feature

#4688 Update the tools
  composer.json
  core-bundle/src/File/MetadataBag.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Interop/ContaoEscaper.php
  core-bundle/tests/Fixtures/Twig/ParentClassWithMembersStub.php
  installation-bundle/src/Controller/InstallationController.php
  tools/ecs/composer.lock
  tools/ecs/config/default.php
  tools/ecs/config/legacy.php
  tools/ecs/config/template.php
Labels: CI

#4677 Drop the "loadNavigation" Ajax action
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/templates/backend/be_navigation.html5
Labels: bug

#4680 Fix the non-JS navigation toggle on backend dashboard
  core-bundle/src/Resources/contao/controllers/BackendMain.php
Labels: bug

#4686 Always delete indexed page for unsuccessful responses
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
Labels: bug

#4696 Merge branch '4.9' into 4.13
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
  news-bundle/src/Resources/contao/languages/en/tl_user.xlf
Labels: release

#4697 Update the tools
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/src/Repository/RememberMeRepository.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
  core-bundle/src/Search/Document.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Interop/ContaoEscaper.php
  core-bundle/tests/Command/Backup/BackupListCommandTest.php
  core-bundle/tests/Command/DebugContaoTwigCommandTest.php
  core-bundle/tests/Command/DebugFragmentsCommandTest.php
  core-bundle/tests/Command/DebugPagesCommandTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Framework/FrameworkAwareTraitTest.php
  core-bundle/tests/Intl/LocalesTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextTest.php
  installation-bundle/src/Controller/InstallationController.php
  tools/ecs/composer.json
  tools/ecs/composer.lock
  tools/ecs/config/default.php
  tools/ecs/config/legacy.php
  tools/ecs/config/template.php
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#4691 Fix failing backup on contao:migrate must abort the command
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: bug

#4698 Fix broken filemanager for unsupported images
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#4700 Merge branch '4.13' into 5.x
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Controller/ContentElement/TemplateController.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/PublicUri/OptionsInterface.php
  core-bundle/src/Filesystem/PublicUri/PublicUriProviderInterface.php
  core-bundle/src/Filesystem/PublicUri/SymlinkedLocalFilesProvider.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemInterface.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/library/Contao/Date.php
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Resources/contao/modules/ModuleArticleList.php
  core-bundle/src/Resources/contao/templates/elements/ce_template.html5
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Extension/DeprecationsNodeVisitor.php
  core-bundle/src/Twig/Runtime/HighlightResult.php
  core-bundle/tests/Command/Backup/BackupStreamContentCommandTest.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Controller/ContentElement/TemplateControllerTest.php
  core-bundle/tests/Doctrine/Backup/BackupManagerTest.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/Dbafs/Hashing/HashGeneratorTest.php
  core-bundle/tests/Filesystem/MountManagerTest.php
  core-bundle/tests/Filesystem/PublicUri/SymlinkedLocalFilesProviderTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  core-bundle/tests/Functional/DbafsTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/DeprecationsNodeVisitorTest.php
  core-bundle/tests/Twig/Runtime/HighlighterRuntimeTest.php
  news-bundle/src/Resources/contao/languages/en/tl_user.xlf
  tools/ecs/config/default.php
  tools/ecs/config/legacy.php
  tools/ecs/config/template.php
Labels: release

#4692 Harden against invalid input
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/tests/EventListener/RequestTokenListenerTest.php
  news-bundle/src/Resources/contao/modules/ModuleNewsArchive.php
Labels: bug

#4348 Fix an execute statement
  installation-bundle/src/InstallTool.php
Labels: bug

#3924 Show page name in duplicate alias error
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Exception/DuplicateAliasException.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
Labels: feature

#4690 Handle cases when layoutId is not set on page model
  core-bundle/src/DataCollector/ContaoDataCollector.php
  core-bundle/tests/DataCollector/ContaoDataCollectorTest.php
Labels: bug

#4705 Remove leftover callbacks
  core-bundle/src/Resources/contao/dca/tl_theme.php
Labels: bug

#4703 Remove deprecated stuff from AbstractPickerProvider
  core-bundle/src/Picker/AbstractPickerProvider.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/tests/Picker/ArticlePickerProviderTest.php
  core-bundle/tests/Picker/PickerBuilderTest.php
  core-bundle/tests/Picker/PickerTest.php
Labels: feature, BC break

#4640 Allow single and forced cron job execution
  core-bundle/src/Command/CronCommand.php
  core-bundle/src/Command/CronListCommand.php
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/tests/Cron/CronTest.php
Labels: feature, needs documentation

#4642 Remove TL_CRON usage from core-bundle
  core-bundle/src/Cron/PurgeOptInTokensCron.php
  core-bundle/src/Cron/PurgeRegistrationsCron.php
  core-bundle/src/Cron/PurgeTempFolderCron.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/tests/Cron/PurgeOptInTokensCronTest.php
  core-bundle/tests/Cron/PurgeRegistrationsCronTest.php
  core-bundle/tests/Cron/PurgeTempFolderCronTest.php
Labels: feature

#4671 Modern fragments: text content elements (part 1)
  UPGRADE.md
  composer.json
  core-bundle/composer.json
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/Controller/ContentElement/CodeController.php
  core-bundle/src/Controller/ContentElement/HeadlineController.php
  core-bundle/src/Controller/ContentElement/HtmlController.php
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/src/Controller/ContentElement/TemplateController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/Controller/FrontendModule/RootPageDependentModulesController.php
  core-bundle/src/Controller/FrontendModule/TemplateController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/templates/_new/.twig-root
  core-bundle/src/Resources/contao/templates/_new/component/_headline.html.twig
  core-bundle/src/Resources/contao/templates/_new/component/_stylesheet.html.twig
  core-bundle/src/Resources/contao/templates/_new/content_element/_base.html.twig
  core-bundle/src/Resources/contao/templates/_new/content_element/code.html.twig
  core-bundle/src/Resources/contao/templates/_new/content_element/headline.html.twig
  core-bundle/src/Resources/contao/templates/_new/content_element/html.html.twig
  core-bundle/tests/Controller/ContentElement/CodeControllerTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/HeadlineControllerTest.php
  core-bundle/tests/Controller/ContentElement/HtmlControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  phpstan.neon
Labels: feature

#4635 Remove TL_CRON usage from comments-bundle
  .github/workflows/ci.yml
  comments-bundle/composer.json
  comments-bundle/phpunit.xml.dist
  comments-bundle/src/Cron/PurgeSubscriptionsCron.php
  comments-bundle/src/DependencyInjection/ContaoCommentsExtension.php
  comments-bundle/src/Resources/config/services.yaml
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/config/config.php
  comments-bundle/tests/Cron/PurgeSubscriptionsCronTest.php
  phpunit.xml.dist
Labels: feature

#3742 Show error if preview settings could not be applied
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#4634 Remove TL_CRON usage from calendar-bundle
  calendar-bundle/src/Cron/GenerateFeedsCron.php
  calendar-bundle/src/Resources/config/services.yml
  calendar-bundle/src/Resources/contao/config/config.php
  calendar-bundle/tests/Cron/GenerateFeedsCronTest.php
Labels: feature

#4624 Implement sectionWizard in vanilla JS
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Resources/contao/widgets/SectionWizard.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/sectionwizard.js
  core-bundle/src/Resources/public/sectionwizard.min.js
Labels: feature

#4706 Remove deprecated TL_CRON support
  UPGRADE.md
  core-bundle/src/Cron/LegacyCron.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/tests/Cron/LegacyCronTest.php
Labels: feature, BC break, needs documentation

#4704 Remove DCA view permissions
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Security/ContaoCorePermissions.php
Labels: bug

#4717 Correctly handle index pages without URL prefix
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/Routing/Matcher/LanguageFilter.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/tests/Fixtures/Functional/Routing/url-prefix-mix.yml
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#4713 Also override Return-Path and Sender address
  core-bundle/src/Mailer/ContaoMailer.php
  core-bundle/tests/Mailer/ContaoMailerTest.php
Labels: bug

#4375 Rewrite fieldset toggling to vanilla JS
  core-bundle/src/Resources/contao/drivers/DC_File.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/toggle-fieldset.js
  core-bundle/src/Resources/public/toggle-fieldset.min.js
Labels: feature

#4719 Fix the PHP 8 warning if a $_SERVER variable does not exist
  core-bundle/src/Resources/contao/library/Contao/Environment.php
Labels: bug

#4720 Fix a potential PHP 8 warning in the breadcrumb module
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
Labels: bug

#4715 Support our template hierarchy in the Twig "use" tag
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicUseTokenParser.php
  core-bundle/tests/Fixtures/Twig/use/bundle/contao/templates/.twig-root
  core-bundle/tests/Fixtures/Twig/use/bundle/contao/templates/component/fruit.html.twig
  core-bundle/tests/Fixtures/Twig/use/bundle/contao/templates/component/fruit_shake.html.twig
  core-bundle/tests/Fixtures/Twig/use/bundle/contao/templates/element/menu.html.twig
  core-bundle/tests/Fixtures/Twig/use/bundle/contao/templates/element/recipe.html.twig
  core-bundle/tests/Fixtures/Twig/use/templates/.twig-root
  core-bundle/tests/Fixtures/Twig/use/templates/component/fruit_shake.html.twig
  core-bundle/tests/Fixtures/Twig/use/templates/element/recipe.html.twig
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
Labels: feature

#4716 Add two more FilesystemItemIterator related helper functions
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Filesystem/FilesystemUtil.php
  core-bundle/tests/Filesystem/FilesystemItemIteratorTest.php
  core-bundle/tests/Filesystem/FilesystemUtilTest.php
Labels: feature

#2874 Add the funding details
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  installation-bundle/composer.json
  listing-bundle/composer.json
  maker-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  newsletter-bundle/composer.json
Labels: feature

#4721 Remov support for deprecated value in tl_article.printable
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
Labels: feature, BC break

#4727 Deprecate REQUEST_TOKEN
  DEPRECATED.md
Labels: bug

#4708 Increase the tl_comments_notify.url length
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments_notify.php
  core-bundle/src/Resources/contao/library/Contao/Search.php
Labels: bug

#4736 Fix CronTest::testDoesNotRunCronJobIfAlreadyRun
  core-bundle/tests/Cron/CronTest.php
Labels: bug

#4737 Remove contao:version command
  core-bundle/src/Command/VersionCommand.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/tests/Command/VersionCommandTest.php
Labels: feature, BC break

#4738 Remove some deprecated constants
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
  phpstan.neon
Labels: feature, BC break

#4735 Use uppercase country codes for tl_member
  core-bundle/src/Migration/Version500/MemberCountryUppercaseMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_member.php
Labels: feature, BC break

#4728 Fix DBAFS when upload_path contains subfolders
  core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php
  core-bundle/src/Resources/contao/library/Contao/Dbafs.php
Labels: bug

#4718 Fix DBAFS when upload_path contains subfolders
  core-bundle/src/Resources/contao/library/Contao/Dbafs.php
Labels: bug

#4648 Implement news archive permissions as a voter
  news-bundle/src/Resources/config/services.yml
  news-bundle/src/Resources/contao/dca/tl_news_archive.php
  news-bundle/src/Security/Voter/NewsArchiveAccessVoter.php
Labels: feature

#4747 Apply the rel=lightbox migration to all rte fields
  core-bundle/src/Migration/Version413/RelLightboxMigration.php
  core-bundle/src/Resources/config/migrations.yml
Labels: bug

#4732 Fix a potential PHP 8 warning in the sitemap module
  core-bundle/src/Resources/contao/modules/ModuleSitemap.php
Labels: bug

#4743 Fix two issues
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  installation-bundle/src/Resources/views/layout.html.twig
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: bug

#4752 Deprecate orderField
  core-bundle/src/Resources/contao/widgets/FileTree.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#4748 Add AVIF to the default image formats
  core-bundle/src/DependencyInjection/Configuration.php
Labels: feature

#4746 Remove deprecated TL_SCRIPT constant
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: feature, BC break

#4740 Remove the deprecated FORM_FIELDS feature
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_File.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: feature, BC break

#4679 Fix several accessibility issues in the back end navigation
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/src/Resources/contao/themes/flexible/hover.js
  core-bundle/src/Resources/contao/themes/flexible/hover.min.js
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
Labels: bug

#4756 Use the same icons for expanding and collapsing everywhere
  core-bundle/src/Resources/contao/themes/flexible/icons/folMinus.svg
  core-bundle/src/Resources/contao/themes/flexible/icons/folPlus.svg
  core-bundle/src/Resources/contao/themes/flexible/icons/navcol.svg
  core-bundle/src/Resources/contao/themes/flexible/icons/navexp.svg
Labels: feature

#4711 Correctly support legacy DC name in picker provider
  core-bundle/src/Picker/AbstractTablePickerProvider.php
Labels: bug

#4744 Remove permission check from FrontendIndex::renderPage
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
Labels: bug

#4758 Automate our PR workflow with Github actions
  .github/workflows/assign-pr.yml
  .github/workflows/thank-you.yml
Labels: CI
