Repository contao/contao, pull requests merged in 2022-12, with the labels that each got.

#5543 Provide roles when authenticating a frontend member
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
Labels: bug

#5548 Fix the missing module references in the newsletter-bundle hooks
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: bug

#5562 Update TL_LANGUAGE deprecation
  DEPRECATED.md
  core-bundle/contao/pages/PageRedirect.php
  core-bundle/contao/pages/PageRegular.php
  core-bundle/src/EventListener/BackendLocaleListener.php
  core-bundle/src/Framework/ContaoFramework.php
Labels: bug

#5537 Fix a PHP 8 issue in the PageTree widget
  core-bundle/src/Resources/contao/widgets/PageTree.php
Labels: bug

#5569 Add a conflict for symfony/dependency-injection
  composer.json
  core-bundle/composer.json
Labels: CI

#5540 Fix a PHP 8 warning in the StyleSheets class
  core-bundle/src/Resources/contao/classes/StyleSheets.php
Labels: bug

#5556 Fix SitemapController not working for protected pages
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: bug

#5559 Allow data-lightbox in TinyMCE by default
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
Labels: bug

#5564 Do not run our Twig filesystem warmer on sub requests
  core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderWarmerTest.php
Labels: bug

#5542 Make $GLOBALS more understandable for PHPStan
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
  core-bundle/tests/EventListener/DataContainer/PreviewLinkListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  phpstan.neon
Labels: CI

#5572 Add PHP 8.2 and 8.3 to the CI workflows
  .github/workflows/ci.yml
Labels: CI

#5576 Merge branch '4.13' into 5.0
  core-bundle/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderWarmerTest.php
Labels: release

#5574 Ensure parameters are strings
  manager-bundle/src/ContaoManager/Plugin.php
Labels: bug

#5526 Correctly sort tree items when PID can be null
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5575 Ensure parameters are strings
  manager-bundle/src/ContaoManager/Plugin.php
Labels: bug

#5573 Do not handle downloads for other elements on the same page
  core-bundle/src/Controller/ContentElement/DownloadsController.php
Labels: bug

#5577 Adjust the anchor target in the navigation templates
  core-bundle/src/Resources/contao/templates/modules/mod_navigation.html5
  core-bundle/src/Resources/views/Backend/be_header_menu.html.twig
  core-bundle/src/Resources/views/Backend/be_menu.html.twig
Labels: bug

#5578 Upgrade and run the tools
  .github/workflows/ci.yml
  core-bundle/tests/EventListener/DataContainer/PreviewLinkListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  phpstan.neon
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#5581 Remove unnecessary special treatment for tl_undo
  core-bundle/src/Resources/contao/dca/tl_undo.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5265 Fix filter options with options callback
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5461 Disable the request token check for idempotent actions
  core-bundle/contao/drivers/DC_Table.php
Labels: feature

#5554 Add support for async CLI cron jobs
  composer.json
  core-bundle/composer.json
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Cron/CronJob.php
  core-bundle/src/DependencyInjection/Compiler/AddCronJobsPass.php
  core-bundle/src/Util/ProcessUtil.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddCronJobsPassTest.php
  core-bundle/tests/Fixtures/src/Cron/TestCronJob.php
  core-bundle/tests/Util/ProcessUtilTest.php
Labels: feature

#5406 Add stimulus controllers in the back end
  core-bundle/assets/backend.js
  core-bundle/assets/controllers/clipboard-controller.js
  core-bundle/assets/controllers/metawizard-controller.js
  core-bundle/assets/controllers/toggle-navigation-controller.js
  core-bundle/assets/scripts/autofocus.js
  core-bundle/assets/scripts/limit-height.js
  core-bundle/assets/scripts/modulewizard.js
  core-bundle/assets/scripts/sectionwizard.js
  core-bundle/assets/scripts/tips.js
  core-bundle/assets/scripts/toggle-fieldset.js
  core-bundle/contao/config/config.php
  core-bundle/contao/languages/en/tl_preview_link.xlf
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/contao/widgets/MetaWizard.php
  core-bundle/public/autofocus.min.js
  core-bundle/public/backend.000f284b.js
  core-bundle/public/backend.000f284b.js.map
  core-bundle/public/clipboard.js
  core-bundle/public/clipboard.min.js
  core-bundle/public/core.js
  core-bundle/public/core.min.js
  core-bundle/public/entrypoints.json
  core-bundle/public/limit-height.min.js
  core-bundle/public/manifest.json
  core-bundle/public/metawizard.js
  core-bundle/public/metawizard.min.js
  core-bundle/public/modulewizard.min.js
  core-bundle/public/sectionwizard.min.js
  core-bundle/public/tips.min.js
  core-bundle/public/toggle-fieldset.min.js
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/templates/Backend/be_menu.html.twig
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
  gulpfile.js
  package-lock.json
  package.json
  webpack.config.js
Labels: feature

#5585 Fix `PageModel::getPreviewUrl` on Windows
  core-bundle/contao/models/PageModel.php
Labels: bug

#5584 Added missing files to prepareFormData hook
  core-bundle/contao/forms/Form.php
Labels: bug

#5587 Also display the visible root trail when searching/filtering
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5590 Fix `tl_page.accesskey` database type
  core-bundle/config/migrations.yaml
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/src/Migration/Version500/AccesskeyMigration.php
Labels: bug

#5594 Also add the new "idempotent actions" logic to DC_Folder
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#5592 Add a favorites menu in the back end
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/config/config.php
  core-bundle/contao/dca/tl_favorites.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/modules.xlf
  core-bundle/contao/languages/en/tl_favorites.xlf
  core-bundle/contao/themes/flexible/icons/favorite.svg
  core-bundle/contao/themes/flexible/icons/favorite_active.svg
  core-bundle/contao/themes/flexible/icons/favorites.svg
  core-bundle/contao/themes/flexible/icons/favorites_dark.svg
  core-bundle/contao/themes/flexible/icons/favorites_group.svg
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/src/EventListener/DataContainer/BackendFavoritesListener.php
  core-bundle/src/EventListener/Menu/BackendFavoritesListener.php
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/src/Security/Voter/BackendFavoritesVoter.php
  core-bundle/tests/EventListener/DataContainer/BackendFavoritesListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendFavoritesListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
  core-bundle/tests/Security/Voter/BackendFavoritesVoterTest.php
Labels: feature

#5607 Use CSS variables for all colors and CSS classes instead of inline styles
  calendar-bundle/contao/dca/tl_calendar_events.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_form.php
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/dca/tl_image_size_item.php
  core-bundle/contao/dca/tl_log.php
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/dca/tl_settings.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/confirm.css
  core-bundle/contao/themes/flexible/confirm.min.css
  core-bundle/contao/themes/flexible/diff.css
  core-bundle/contao/themes/flexible/diff.min.css
  core-bundle/contao/themes/flexible/help.css
  core-bundle/contao/themes/flexible/help.min.css
  core-bundle/contao/themes/flexible/login.css
  core-bundle/contao/themes/flexible/login.min.css
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/contao/themes/flexible/popup.css
  core-bundle/contao/themes/flexible/popup.min.css
  core-bundle/contao/themes/flexible/switch.css
  core-bundle/contao/themes/flexible/switch.min.css
  core-bundle/contao/widgets/CheckBox.php
  core-bundle/contao/widgets/CheckBoxWizard.php
  core-bundle/contao/widgets/RootPageDependentSelect.php
  news-bundle/contao/dca/tl_news.php
  newsletter-bundle/contao/dca/tl_newsletter_recipients.php
Labels: feature
