Repository contao/contao, pull requests merged in 2022-04, with the labels that each got.

#4447 Fix simple token parser default value for unknown variables
  core-bundle/src/String/SimpleTokenParser.php
  core-bundle/tests/String/SimpleTokenParserTest.php
Labels: bug

#4448 Skip row size calculation for MyISAM
  core-bundle/src/Command/MigrateCommand.php
Labels: bug

#4451 Quote all schema names, same as we do for inserts
  core-bundle/src/Doctrine/Backup/Dumper.php
  core-bundle/tests/Doctrine/Backup/DumperTest.php
Labels: bug

#4437 Correctly resolve parameters when prepending bundle config
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
Labels: bug

#4438 Fix several errors that now appear due to removed BC layers
  core-bundle/src/Resources/contao/dca/tl_preview_link.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Model.php
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
Labels: bug

#4455 Fix Atom feed generation
  core-bundle/src/Resources/contao/library/Contao/Feed.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
Labels: bug

#4323 Add the DefaultDcaVoter
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/DataContainer/DataContainerSubject.php
  core-bundle/src/Security/Voter/DataContainer/DefaultDcaVoter.php
  core-bundle/tests/Security/DataContainer/DataContainerSubjectTest.php
  core-bundle/tests/Security/Voter/DefaultDcaVoterTest.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: feature

#4457 Run unit tests faster
  test-case/src/ContaoTestCase.php
Labels: CI

#4446 Support nested paths when generating Twig IDE autocompletion file
  core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderWarmerTest.php
Labels: bug

#4308 Drop database.sql support
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/src/Resources/contao/library/Contao/Database/Installer.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/library/Contao/SqlFileParser.php
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
  core-bundle/tests/Doctrine/DoctrineTestCase.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  installation-bundle/src/Database/Installer.php
Labels: feature, BC break

#4440 Support sorting and any/all search in FilesystemItemIterator
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Filesystem/SortMode.php
  core-bundle/tests/Filesystem/FilesystemItemIteratorTest.php
  tools/ecs/config/default.php
Labels: feature

#4417 Feature HtmlAttributes in the image studio
  UPGRADE.md
  core-bundle/src/Image/Studio/Figure.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/FigureTest.php
Labels: feature

#4456 Fix the record preview
  core-bundle/src/EventListener/DataContainer/RecordPreviewListener.php
  core-bundle/tests/EventListener/DataContainer/RecordPreviewListenerTest.php
Labels: bug

#3930 Resolve page model in request
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/EventListener/PageAccessListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/EventListener/PageAccessListenerTest.php
  core-bundle/tests/Functional/RoutingTest.php
Labels: feature

#4320 Fix missing hash option for migrate command
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: bug

#4192 Shorten the version description to the length of the DB column
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: bug

#4355 Add SQL import to the backend
  core-bundle/src/Resources/contao/classes/Theme.php
  core-bundle/src/Resources/contao/languages/en/tl_theme.xlf
Labels: feature

#4364 Remove the legacy session access
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/EventListener/ClearSessionDataListener.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/forms/FormFileUpload.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Session.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/templates/forms/form_message.html5
  core-bundle/src/Session/Attribute/AutoExpiringAttribute.php
  core-bundle/src/Session/LazySessionAccess.php
  core-bundle/src/Session/MockNativeSessionStorage.php
  core-bundle/tests/EventListener/ClearSessionDataListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Session/Attribute/AutoExpiringAttributeTest.php
  core-bundle/tests/Session/LazySessionAccessTest.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: feature, BC break

#4367 Remove the orderField support in the picker widgets
  UPGRADE.md
  core-bundle/src/Resources/contao/widgets/PageTree.php
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: feature, BC break

#4372 Rewrite MetaWizard to vanilla JS
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/metawizard.js
  core-bundle/src/Resources/public/metawizard.min.js
Labels: feature

#4462 Remove the ->setAccessible() method
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/src/Doctrine/Backup/Dumper.php
  core-bundle/tests/Command/SymlinksCommandTest.php
  core-bundle/tests/Contao/CombinerTest.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Contao/EnvironmentTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Contao/SearchTest.php
  core-bundle/tests/Contao/WidgetTest.php
  core-bundle/tests/DataCollector/ContaoDataCollectorTest.php
  core-bundle/tests/DependencyInjection/Filesystem/FilesystemConfigurationTest.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsFactoryTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemFactoryTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Routing/AbstractPageRouteProviderTest.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  maker-bundle/tests/Config/XliffMergerTest.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
Labels: CI

#4465 Remove unused variables in catch() statements
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/src/Cache/EntityCacheTags.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/Cors/WebsiteRootsConfigProvider.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Doctrine/Backup/BackupManager.php
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/EventListener/DataContainer/RecordPreviewListener.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Image/Resizer.php
  core-bundle/src/Monolog/ContaoTableHandler.php
  core-bundle/src/Picker/PickerBuilder.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/src/String/SimpleTokenParser.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php
  core-bundle/src/Twig/Loader/FailTolerantFilesystemLoader.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/Doctrine/Backup/BackupManagerTest.php
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/Database/ConnectionFactory.php
  installation-bundle/src/InstallTool.php
  manager-bundle/src/HttpKernel/JwtManager.php
  manager-bundle/src/Resources/skeleton/config/services.php
  test-case/src/FunctionalTestCase.php
  tools/rector/config/rector.php
Labels: CI

#4466 Use the PHP 8.1 str_ functions
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Config/Dumper/CombinedFileDumper.php
  core-bundle/src/Config/Loader/XliffFileLoader.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/DependencyInjection/Compiler/AddAssetsPackagesPass.php
  core-bundle/src/DependencyInjection/Compiler/DataContainerCallbackPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/Doctrine/Backup/BackupManager.php
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/EventListener/DataContainer/PageSearchListener.php
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Image/Preview/PreviewFactory.php
  core-bundle/src/Picker/AbstractInsertTagPickerProvider.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/Routing/Candidates/AbstractCandidates.php
  core-bundle/src/Routing/Matcher/LanguageFilter.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/src/Search/Document.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/src/String/SimpleTokenParser.php
  core-bundle/src/Translation/DataCollectorTranslator.php
  core-bundle/src/Translation/MessageCatalogue.php
  core-bundle/src/Translation/Translator.php
  core-bundle/src/Twig/Interop/ContextFactory.php
  core-bundle/src/Util/SymlinkUtil.php
  core-bundle/tests/Functional/PageControllerTest.php
  core-bundle/tests/Image/Preview/PreviewFactoryTest.php
  installation-bundle/src/Config/ParameterDumper.php
  installation-bundle/src/Controller/InstallationController.php
  installation-bundle/src/Database/Installer.php
  installation-bundle/src/InstallTool.php
  maker-bundle/src/Maker/AbstractFragmentMaker.php
  maker-bundle/src/Maker/MakeDcaCallback.php
  maker-bundle/src/Reflection/SignatureGenerator.php
  manager-bundle/src/Dotenv/DotenvDumper.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/src/Resources/skeleton/config/services.php
  manager-bundle/src/Twig/FileExtensionFilterIterator.php
  tools/rector/config/rector.php
Labels: CI

#4467 Make public class constants final
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriber.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/src/Cron/Cron.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/DependencyInjection/Compiler/LoggerChannelPass.php
  core-bundle/src/DependencyInjection/Compiler/RemembermeServicesPass.php
  core-bundle/src/Doctrine/Backup/Backup.php
  core-bundle/src/Doctrine/Backup/BackupManager.php
  core-bundle/src/Doctrine/DBAL/Types/BinaryStringType.php
  core-bundle/src/EventListener/BackendRebuildCacheMessageListener.php
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/EventListener/SubrequestCacheSubscriber.php
  core-bundle/src/EventListener/Widget/CustomRgxpListener.php
  core-bundle/src/EventListener/Widget/HttpUrlListener.php
  core-bundle/src/File/Metadata.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/VirtualFilesystemException.php
  core-bundle/src/Fragment/Reference/ContentElementReference.php
  core-bundle/src/Fragment/Reference/FrontendModuleReference.php
  core-bundle/src/Monolog/ContaoContext.php
  core-bundle/src/Routing/ResponseContext/JsonLd/JsonLdManager.php
  core-bundle/src/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServices.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Fixtures/Twig/ChildClassWithMembersStub.php
  manager-bundle/src/Api/Application.php
  manager-bundle/src/HttpKernel/JwtManager.php
  tools/rector/config/rector.php
Labels: CI

#4468 Enable more PHP 8.1 features
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/Doctrine/Backup/Backup.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/InsertTag/ChunkedText.php
  core-bundle/src/Intl/Countries.php
  core-bundle/src/Intl/Locales.php
  core-bundle/src/Monolog/ContaoContext.php
  core-bundle/src/Security/DataContainer/DataContainerSubject.php
  core-bundle/src/Twig/Interop/ContextFactory.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Fixtures/Entity/Comment.php
  tools/rector/config/rector.php
Labels: CI

#4469 Use ::class on objects
  core-bundle/src/Cache/EntityCacheTags.php
  core-bundle/src/Command/DebugPagesCommand.php
  core-bundle/src/Cron/CronJob.php
  core-bundle/src/Entity/RememberMe.php
  core-bundle/src/Entity/TrustedDevice.php
  core-bundle/src/EventListener/Security/TwoFactorFrontendListener.php
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Image/Preview/ImaginePreviewProvider.php
  core-bundle/src/Image/Preview/PreviewFactory.php
  core-bundle/src/Image/Resizer.php
  core-bundle/src/Routing/ResponseContext/ResponseContext.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/src/Security/User/ContaoUserProvider.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/EventListener/Security/TwoFactorFrontendListenerTest.php
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  manager-bundle/src/Command/DebugPluginsCommand.php
  tools/rector/config/rector.php
Labels: CI

#4471 Use the array spread operator instead of array_merge()
  core-bundle/src/Doctrine/Backup/RetentionPolicy.php
  core-bundle/src/EventListener/StoreRefererListener.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Migration/Version410/OrderFieldMigration.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  installation-bundle/src/Controller/InstallationController.php
  manager-bundle/tests/ContaoManager/PluginTest.php
  tools/rector/config/rector.php
Labels: CI

#4474 Convert count() to empty array comparison
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/DependencyInjection/Compiler/CrawlerPass.php
  core-bundle/src/DependencyInjection/Compiler/SearchIndexerPass.php
  core-bundle/src/Doctrine/Backup/RetentionPolicy.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/EventListener/DataContainerCallbackListener.php
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
  core-bundle/src/EventListener/HttpCache/StripQueryParametersSubscriber.php
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Image/Preview/PreviewFactory.php
  core-bundle/src/Migration/Version412/AllowedExcludedFieldsMigration.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Routing/PageUrlGenerator.php
  core-bundle/src/Routing/ResponseContext/JsonLd/JsonLdManager.php
  core-bundle/src/Search/Document.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/src/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServices.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/tests/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  manager-bundle/src/Dotenv/DotenvDumper.php
  manager-bundle/tests/Command/DebugPluginsCommandTest.php
  test-case/src/ContaoTestCase.php
  test-case/src/DeprecatedClassesPhpunitExtension.php
  tools/rector/config/rector.php
Labels: CI

#4475 Remove unused private method arguments
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  tools/rector/config/rector.php
Labels: CI

#4479 Revert 'Convert count() to empty array comparison'
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/DependencyInjection/Compiler/CrawlerPass.php
  core-bundle/src/DependencyInjection/Compiler/SearchIndexerPass.php
  core-bundle/src/Doctrine/Backup/RetentionPolicy.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/EventListener/DataContainerCallbackListener.php
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
  core-bundle/src/EventListener/HttpCache/StripQueryParametersSubscriber.php
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Image/Preview/PreviewFactory.php
  core-bundle/src/Migration/Version412/AllowedExcludedFieldsMigration.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Routing/PageUrlGenerator.php
  core-bundle/src/Routing/ResponseContext/JsonLd/JsonLdManager.php
  core-bundle/src/Search/Document.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/src/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServices.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/tests/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  manager-bundle/src/Dotenv/DotenvDumper.php
  manager-bundle/tests/Command/DebugPluginsCommandTest.php
  test-case/src/ContaoTestCase.php
  test-case/src/DeprecatedClassesPhpunitExtension.php
Labels: CI

#4482 Use the nullsafe operator
  core-bundle/src/Controller/Page/RootPageController.php
  core-bundle/src/Cron/Cron.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/EventListener/Security/LogoutSuccessListener.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Routing/ResponseContext/ResponseContextAccessor.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/src/Security/User/ContaoUserProvider.php
  core-bundle/src/String/SimpleTokenParser.php
  manager-bundle/src/Security/Logout/LogoutHandler.php
Labels: CI

#4485 Ignore the unexpected type hint required for the tagged_locator
  core-bundle/src/Fragment/FragmentHandler.php
  phpstan.neon
  tools/rector/config/rector.php
Labels: CI

#4450 Make replacing insert tags more granular
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php
Labels: feature

#4487 Remove rel="nofollow" for internal pages
  calendar-bundle/src/Resources/contao/templates/calendar/cal_mini.html5
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/templates/modules/mod_article.html5
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
Labels: bug

#4506 Disable the TinyMCE context menu by default
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
Labels: feature

#4509 Fix bug with hash comparison in migrate command
  core-bundle/src/Command/MigrateCommand.php
Labels: bug

#4515 Merge branch '4.9' into 4.13
  calendar-bundle/src/Resources/contao/templates/calendar/cal_mini.html5
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/library/Contao/Feed.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/templates/modules/mod_article.html5
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  test-case/src/ContaoTestCase.php
Labels: release

#4304 Clean up page controllers
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/pages/PageError401.php
  core-bundle/src/Resources/contao/pages/PageError403.php
  core-bundle/src/Resources/contao/pages/PageError404.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
  core-bundle/tests/Command/DebugPagesCommandTest.php
Labels: feature

#4516 Run the code inspector
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Routing/ResponseContext/ResponseContextAccessor.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextTest.php
Labels: CI

#4493 Use fixed subject string for List-Unsubscribe header
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#4470 Update version number in toggleSubpalette
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#4329 Deprecated Cache lib
  DEPRECATED.md
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  core-bundle/src/Resources/contao/library/Contao/Cache.php
Labels: feature

#4520 Merge branch '4.13' into 5.x
  calendar-bundle/src/Resources/contao/templates/calendar/cal_mini.html5
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/EventListener/DataContainer/RecordPreviewListener.php
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/library/Contao/Feed.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/modules/mod_article.html5
  core-bundle/tests/Command/CrawlCommandTest.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/EventListener/DataContainer/RecordPreviewListenerTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  test-case/src/ContaoTestCase.php
Labels: release

#4330 Remove in-memory cache
  core-bundle/src/Resources/contao/library/Contao/Cache.php
Labels: feature, BC break

#4517 Fix miscellaneous minor issues
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/library/Contao/ArrayUtil.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/widgets/RootPageDependentSelect.php
  core-bundle/tests/Contao/RootPageDependentSelectTest.php
Labels: bug

#4521 Fix the translation domain in the root page dependent select
  core-bundle/src/Resources/contao/widgets/RootPageDependentSelect.php
  core-bundle/tests/Contao/RootPageDependentSelectTest.php
Labels: bug

#4383 Rewrite tooltips to vanilla JS
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
  core-bundle/src/Resources/public/tips.js
  core-bundle/src/Resources/public/tips.min.js
Labels: feature

#4195 Set a session for the fake request
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  news-bundle/src/Resources/contao/classes/News.php
Labels: bug

#4178 Remove the "first", "even", "odd" and "last" CSS classes
  UPGRADE.md
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventMenu.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  calendar-bundle/src/Resources/contao/templates/calendar/cal_default.html5
  calendar-bundle/src/Resources/contao/templates/calendar/cal_mini.html5
  calendar-bundle/src/Resources/contao/templates/events/event_list.html5
  calendar-bundle/src/Resources/contao/templates/events/event_teaser.html5
  calendar-bundle/src/Resources/contao/templates/modules/mod_eventmenu.html5
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/templates/comments/com_default.html5
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/elements/ContentGallery.php
  core-bundle/src/Resources/contao/elements/ContentList.php
  core-bundle/src/Resources/contao/elements/ContentTable.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/forms/FormCaptcha.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/modules/ModuleRssReader.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/templates/backend/be_two_factor.html5
  core-bundle/src/Resources/contao/templates/backend/be_welcome.html5
  core-bundle/src/Resources/contao/templates/elements/ce_list.html5
  core-bundle/src/Resources/contao/templates/elements/ce_table.html5
  core-bundle/src/Resources/contao/templates/gallery/gallery_default.html5
  core-bundle/src/Resources/contao/templates/modules/mod_breadcrumb.html5
  core-bundle/src/Resources/contao/templates/rss/rss_default.html5
  core-bundle/src/Resources/contao/templates/search/search_default.html5
  core-bundle/src/Resources/contao/themes/flexible/install.css
  core-bundle/src/Resources/contao/themes/flexible/install.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqList.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  faq-bundle/src/Resources/contao/templates/modules/mod_faqlist.html5
  faq-bundle/src/Resources/contao/templates/modules/mod_faqpage.html5
  installation-bundle/src/Resources/views/main.html.twig
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
  listing-bundle/src/Resources/contao/templates/info/info_default.html5
  listing-bundle/src/Resources/contao/templates/listing/list_default.html5
  news-bundle/src/Resources/contao/modules/ModuleNews.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
  news-bundle/src/Resources/contao/templates/modules/mod_newsmenu.html5
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
  newsletter-bundle/src/Resources/public/newsletter.min.css
Labels: feature

#4527 Deprecated Contao\Request
  DEPRECATED.md
  core-bundle/src/Resources/contao/library/Contao/Request.php
Labels: feature

#4528 Only save personal data if there is no error
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
Labels: bug

#4531 Remove Contao\Request
  UPGRADE.md
  core-bundle/src/Resources/contao/library/Contao/Request.php
Labels: feature, BC break

#4530 Run Rector
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  test-case/src/ContaoDatabaseTrait.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: CI

#4369 Remove deprecated StringUtil stuff
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: feature, BC break

#4533 Fix an error when unpacking an associative array of model search criteria values
  core-bundle/src/Resources/contao/library/Contao/Model.php
Labels: bug

#4535 Fix the registration module throwing a warning in PHP 8 if captcha is disabled
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#4534 Fix the FAQ page module throwing a warning in PHP 8 if author could not be fetched
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
Labels: bug

#4536 Allow partial mocks and row()/setRow() when mocking classes with properties
  core-bundle/tests/Cache/EntityCacheTagsTest.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/File/MetadataTest.php
  core-bundle/tests/Image/Preview/PreviewFactoryTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  test-case/README.md
  test-case/src/ContaoTestCase.php
Labels: feature

#4549 Fix a type error in the listing module
  listing-bundle/src/Resources/contao/modules/ModuleListing.php
Labels: bug

#4540 Remove the deprecated insert tag stuff
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: feature, BC break

#4541 Remove the deprecated Frontend.php stuff
  core-bundle/src/Resources/contao/classes/Frontend.php
Labels: feature, BC break

#4539 Remove the deprecated template stuff
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/views/Backend/be_page.html.twig
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/LegacyTemplateFunctionsRuntime.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Runtime/LegacyTemplateFunctionsRuntimeTest.php
Labels: feature, BC break

#4543 Remove the deprecated System.php stuff
  core-bundle/src/Resources/contao/config/timezones.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/tests/Contao/ControllerTest.php
Labels: feature, BC break

#4453 Rework the input encoding
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php
  core-bundle/src/Migration/Version500/BasicEntitiesMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/drivers/DC_File.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/InputEncodingMode.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/widgets/CheckBox.php
  core-bundle/src/Resources/contao/widgets/CheckBoxWizard.php
  core-bundle/src/Resources/contao/widgets/ChmodTable.php
  core-bundle/src/Resources/contao/widgets/ImageSize.php
  core-bundle/src/Resources/contao/widgets/InputUnit.php
  core-bundle/src/Resources/contao/widgets/KeyValueWizard.php
  core-bundle/src/Resources/contao/widgets/ListWizard.php
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  core-bundle/src/Resources/contao/widgets/ModuleWizard.php
  core-bundle/src/Resources/contao/widgets/OptionWizard.php
  core-bundle/src/Resources/contao/widgets/RadioButton.php
  core-bundle/src/Resources/contao/widgets/RadioTable.php
  core-bundle/src/Resources/contao/widgets/RootPageDependentSelect.php
  core-bundle/src/Resources/contao/widgets/SectionWizard.php
  core-bundle/src/Resources/contao/widgets/SelectMenu.php
  core-bundle/src/Resources/contao/widgets/TableWizard.php
  core-bundle/src/Resources/contao/widgets/TextArea.php
  core-bundle/src/Resources/contao/widgets/TextField.php
  core-bundle/src/Resources/contao/widgets/TimePeriod.php
  core-bundle/src/Resources/contao/widgets/TrblField.php
  core-bundle/src/String/SimpleTokenParser.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Contao/WidgetTest.php
  core-bundle/tests/Controller/ContentElement/MarkdownControllerTest.php
  core-bundle/tests/Slug/SlugTest.php
  core-bundle/tests/String/HtmlDecoderTest.php
Labels: feature

#4544 Remove the deprecated Controller.php stuff
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Contao/TemplateLoaderTest.php
Labels: feature, BC break

#4545 Remove the deprecated Model.php stuff
  UPGRADE.md
  core-bundle/src/Resources/contao/library/Contao/Model.php
Labels: feature, BC break

#4393 Modern fragment foundation
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/GlobalsMapListener.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php
  core-bundle/src/Resources/contao/templates/_new/backend/module_wildcard.html.twig
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/src/Twig/Interop/ContextFactory.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/ContentElement/TemplateControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  core-bundle/tests/Controller/FrontendModule/RootPageDependentModulesControllerTest.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/EventListener/GlobalsMapListenerTest.php
  core-bundle/tests/Twig/FragmentTemplateTest.php
  core-bundle/tests/Twig/Interop/ContextFactoryTest.php
Labels: feature

#4537 Allow TinyMCE 6
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: feature

#4481 Fix AbstractTablePickerProvider
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
Labels: bug

#4548 Replace the "getSearchablePages" hook in the calendar-bundle
  calendar-bundle/src/EventListener/SitemapListener.php
  calendar-bundle/src/Resources/config/services.yml
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  calendar-bundle/src/Resources/contao/config/config.php
  calendar-bundle/tests/EventListener/SitemapListenerTest.php
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/Event/SitemapEvent.php
  core-bundle/tests/ContaoCoreBundleTest.php
  core-bundle/tests/Event/SitemapEventTest.php
  test-case/src/ContaoTestCase.php
Labels: feature

#4552 Remove the "fullscreen" option in the back end
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/config/default.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/languages/en/tl_user.xlf
  core-bundle/src/Resources/contao/library/Contao/User.php
  core-bundle/src/Resources/contao/models/UserModel.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: feature

#4319 Drop the user agent class and insert tag
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
  core-bundle/src/Resources/contao/config/agents.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Resources/contao/templates/backend/be_confirm.html5
  core-bundle/src/Resources/contao/templates/backend/be_conflict.html5
  core-bundle/src/Resources/contao/templates/backend/be_diff.html5
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/src/Resources/contao/templates/backend/be_login_two_factor.html5
  core-bundle/src/Resources/contao/templates/backend/be_password.html5
  core-bundle/tests/Contao/EnvironmentTest.php
  core-bundle/tests/Controller/AbstractBackendControllerTest.php
  installation-bundle/src/Controller/InstallationController.php
Labels: feature, BC break

#4554 Remove the BC layers in the .yml files
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/config/services.yml
  installation-bundle/src/Resources/config/services.yml
  manager-bundle/src/Resources/config/services.yml
Labels: feature, BC break

#4555 Correctly build Twig logical name from fragment template name
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/tests/Controller/AbstractFragmentControllerTest.php
  core-bundle/tests/Fixtures/src/Controller/FragmentController.php
Labels: bug

#4553 Complete more TODOs for Contao 5.0
  core-bundle/src/Command/Backup/BackupListCommand.php
  core-bundle/src/Image/Preview/PreviewFactory.php
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: feature, BC break

#4558 Run Rector
  core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php
  core-bundle/src/Twig/FragmentTemplate.php
Labels: CI

#4557 Remove more BC layers
  .gitattributes
  core-bundle/src/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPass.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/HttpKernel/Bundle/ContaoModuleBundle.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/controllers/BackendIndex.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/modules/Module.php
  core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Twig/Interop/ContextFactory.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/HttpKernel/Bundle/ContaoModuleBundleTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
  manager-bundle/src/Composer/ScriptHandler.php
Labels: feature, BC break

#4559 Remove the remaining helper files
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/Resources/contao/helper/exception.php
  core-bundle/src/Resources/contao/helper/interface.php
Labels: feature, BC break

#4510 Rewire the Input and Environment classes to use the Symfony request
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Controller/AbstractBackendController.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/controllers/BackendCustom.php
  core-bundle/src/Resources/contao/controllers/BackendMain.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/drivers/DC_File.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/elements/ContentDownload.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/forms/FormCaptcha.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/modules/ModuleTwoFactor.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/widgets/InputUnit.php
  core-bundle/src/Resources/contao/widgets/RootPageDependentSelect.php
  core-bundle/src/Resources/contao/widgets/TimePeriod.php
  core-bundle/src/Resources/contao/widgets/TrblField.php
  core-bundle/src/Routing/Enhancer/InputEnhancer.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Contao/EnvironmentTest.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/PaginationTest.php
  core-bundle/tests/Contao/RootPageDependentSelectTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Contao/WidgetTest.php
  core-bundle/tests/Controller/AbstractBackendControllerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Functional/DbafsTest.php
  core-bundle/tests/Routing/Enhancer/InputEnhancerTest.php
  core-bundle/tests/String/HtmlDecoderTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqList.php
  news-bundle/src/Resources/contao/modules/ModuleNewsArchive.php
  news-bundle/src/Resources/contao/modules/ModuleNewsList.php
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: feature

#4562 Remove TL_CROP
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/ImageSizes.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Migration/Version401/Version410Update.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/widgets/ImageSize.php
  core-bundle/tests/EventListener/ImageSizeOptionsListenerTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/ImageSizesTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: feature, BC break

#4563 Remove countries.php and getCountries hook
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPass.php
  core-bundle/src/Intl/Countries.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/config/countries.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/tests/Contao/SystemTest.php
  core-bundle/tests/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPassTest.php
  core-bundle/tests/Intl/CountriesTest.php
Labels: feature, BC break

#4564 Remove languages.php and getLanguages hook
  DEPRECATED.md
  UPGRADE.md
  core-bundle/src/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPass.php
  core-bundle/src/Intl/Locales.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/config/languages.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/System.php
  core-bundle/tests/Contao/SystemTest.php
  core-bundle/tests/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPassTest.php
  core-bundle/tests/Intl/LocalesTest.php
  phpstan.neon
Labels: feature, BC break

#4463 Sort the selectable templates in install tool
  installation-bundle/src/InstallTool.php
Labels: bug

#4477 Fix undefined value/unit for empty array in headline
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/elements/ContentElement.php
  core-bundle/src/Resources/contao/modules/Module.php
Labels: bug

#4500 Fix header fields for blank option
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#4489 Fix the SendNewsletterEvent when sending as text only
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#4501 Fix undefined sorting mode for group header
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug
