Repository contao/contao, pull requests merged in 2022-03, with the labels that each got.

#4204 Allow underscore in tag attributes
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#4210 Fix warning in ModuleArticle if page object is null
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
Labels: bug

#4226 Deprecate the Page*::generate() methods
  core-bundle/src/Resources/contao/pages/PageError401.php
  core-bundle/src/Resources/contao/pages/PageError403.php
  core-bundle/src/Resources/contao/pages/PageError404.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
Labels: bug

#4227 Support "submitOnChange" in the PageTree and Picker widgets
  core-bundle/src/Resources/contao/widgets/PageTree.php
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug

#4218 Do not process redirected URLs outside base domains
  core-bundle/src/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriber.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/tests/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
Labels: bug

#4135 Do not configure the default click jacking paths in the skeleton
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#4091 Lazy call router when replacing old backend paths
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Contao/ControllerTest.php
Labels: bug

#4229 Use the Contao short URL service for keyboard shortcuts
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/exception.xlf
  core-bundle/src/Resources/contao/languages/en/explain.xlf
Labels: bug

#4231 Remove the `$Template` property from the PageRegular class again
  core-bundle/src/Resources/contao/pages/PageRegular.php
Labels: bug

#4234 Create new versions after the onsubmit_callback in the registration module
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
Labels: bug

#4233 Make `config.sql` optional in the DCA
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
Labels: bug

#4237 Handle `0` as widget attribute value
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#4235 Add the `|urlattr` flag in the `StringUtil::srcToInsertTag()` method
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
Labels: bug

#4240 Update the tools
  .github/workflows/ci.yml
  composer.json
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/helper/functions.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Folder.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
  core-bundle/src/Resources/contao/widgets/FileSelector.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
Labels: CI

#4241 Do not use the `.tl_confirm` CSS class in the front end
  comments-bundle/src/Resources/contao/templates/modules/mod_comment_form.html5
  core-bundle/src/Resources/contao/templates/member/member_default.html5
  core-bundle/src/Resources/contao/templates/member/member_grouped.html5
  core-bundle/src/Resources/contao/templates/modules/mod_changePassword.html5
Labels: bug

#4248 Correctly encode redirect URLs between 401 pages and login forms
  core-bundle/src/Resources/contao/pages/PageError401.php
Labels: bug

#4251 Merge branch '4.9' into 4.13
  comments-bundle/src/Resources/contao/templates/modules/mod_comment_form.html5
  composer.json
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriber.php
  core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/config/default.php
  core-bundle/src/Resources/contao/dca/tl_log.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/exception.xlf
  core-bundle/src/Resources/contao/languages/en/explain.xlf
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/library/Contao/Input.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/pages/PageError401.php
  core-bundle/src/Resources/contao/pages/PageError403.php
  core-bundle/src/Resources/contao/pages/PageError404.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
  core-bundle/src/Resources/contao/templates/member/member_default.html5
  core-bundle/src/Resources/contao/templates/member/member_grouped.html5
  core-bundle/src/Resources/contao/templates/modules/mod_changePassword.html5
  core-bundle/src/Resources/contao/widgets/PageTree.php
  core-bundle/src/Resources/contao/widgets/Picker.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/src/Resources/skeleton/config/config.yml
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: release

#4208 Lower max file size in Dbafs service
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
Labels: bug

#4221 Fix the FigureRendererTest
  core-bundle/tests/Image/Studio/FigureRendererTest.php
Labels: bug

#4216 Skip non-UTF-8 resources when syncing the DBAFS
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
Labels: bug

#4244 Make sure tl_content.type has an index
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#4245 Decode equal sign when parsing query parameters of figure insert tag
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#4259 Avoid error if the DATABASE_URL environment variable is an empty string
  manager-bundle/src/ContaoManager/Plugin.php
Labels: bug

#4254 Fix infinite loop while loading of languages
  core-bundle/src/Resources/contao/library/Contao/System.php
Labels: bug

#4264 Make search accent insensitive
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/library/Contao/SearchResult.php
  core-bundle/tests/Contao/SearchTest.php
  core-bundle/tests/Functional/SearchTest.php
Labels: bug

#4262 Fix SQL commands not supported in prepared statements
  core-bundle/src/Resources/contao/library/Contao/Database/Statement.php
  core-bundle/tests/Contao/Database/StatementTest.php
Labels: bug

#4228 Improve the performance of contao:backup:create
  core-bundle/src/Doctrine/Backup/Dumper.php
  core-bundle/tests/Doctrine/Backup/DumperTest.php
Labels: bug

#4158 Set DB server version in install tool
  installation-bundle/src/Controller/InstallationController.php
  manager-bundle/src/ContaoManager/Plugin.php
Labels: bug

#4267 Fix two minor issues in the install tool
  core-bundle/src/Resources/contao/themes/flexible/install.css
  core-bundle/src/Resources/contao/themes/flexible/install.min.css
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.en.xlf
Labels: bug

#4268 Fix the type hint of the MessageCatalogue::isContaoDomain() method
  core-bundle/src/Translation/MessageCatalogue.php
Labels: bug

#4197 Fix some dynamic routes handling
  core-bundle/src/EventListener/InsecureInstallationListener.php
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
Labels: bug

#4271 Correctly show all breadcrumb items
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#4274 Fall back to the section key if there is no label
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#4275 Fix a potential PHP 8 incompatibility when generating a DCA column
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#4270 Only shorten the main headline elements if necessary
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#4273 Adjust the "Recreate the XML files" description
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
Labels: bug

#4272 Add a help wizard if the canonical URL fields are disabled
  core-bundle/src/EventListener/DataContainer/DisableCanonicalFieldsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/tests/EventListener/DataContainer/DisableCanonicalFieldsListenerTest.php
Labels: bug

#4279 Fix bug with database query returing non-string types
  core-bundle/src/Doctrine/Backup/Dumper.php
  core-bundle/tests/Doctrine/Backup/DumperTest.php
Labels: bug

#4281 Add missing isSortable checks to the picker widget
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug

#4026 Fix multiple page controller routing issues
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/Routing/Candidates/PageCandidates.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/Page/PageRouteCompiler.php
  core-bundle/tests/Fixtures/Functional/PageController/page-with-alias.yml
  core-bundle/tests/Fixtures/Functional/PageController/page-without-alias.yml
  core-bundle/tests/Fixtures/Functional/PageController/root-with-suffix.yml
  core-bundle/tests/Fixtures/Functional/PageController/root-without-suffix.yml
  core-bundle/tests/Fixtures/Functional/PageController/theme.yml
  core-bundle/tests/Fixtures/src/Controller/Page/TestPageController.php
  core-bundle/tests/Functional/PageControllerTest.php
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#4282 Update the tools
  psalm.xml
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/psalm/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#4292 Ignore file symlinks when auto-mounting adapters
  core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php
  core-bundle/tests/DependencyInjection/Compiler/ConfigureFilesystemPassTest.php
Labels: bug

#4287 Fix the route sorting in the Route404Provider
  core-bundle/src/Routing/Route404Provider.php
Labels: bug

#4285 Fix DCA extractor wrongly assuming every DCA is database driven
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
Labels: bug

#4266 Forward IO to Composer filesystem in ScriptHandler
  manager-bundle/src/Composer/ScriptHandler.php
Labels: bug

#4300 Fix symlink tests on Windows
  core-bundle/tests/DependencyInjection/Compiler/ConfigureFilesystemPassTest.php
Labels: bug

#4298 Remove the internal CSS editor
  core-bundle/.tx/config
  core-bundle/src/Resources/contao/classes/StyleSheets.php
  core-bundle/src/Resources/contao/classes/Theme.php
  core-bundle/src/Resources/contao/config/config.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_style_sheet.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/languages/en/modules.xlf
  core-bundle/src/Resources/contao/languages/en/tl_layout.xlf
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/en/tl_style.xlf
  core-bundle/src/Resources/contao/languages/en/tl_style_sheet.xlf
  core-bundle/src/Resources/contao/languages/en/tl_theme.xlf
  core-bundle/src/Resources/contao/library/Contao/Automator.php
  core-bundle/src/Resources/contao/library/Contao/Database/Updater.php
  core-bundle/src/Resources/contao/models/LayoutModel.php
  core-bundle/src/Resources/contao/models/StyleModel.php
  core-bundle/src/Resources/contao/models/StyleSheetModel.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: feature

#4307 Drop the deprecated Encryption library
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/config/default.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/Config.php
  core-bundle/src/Resources/contao/library/Contao/Encryption.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: feature, BC break

#4190 Remove left-over url field in tl_module
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
Labels: bug

#4315 Remove the Contao 3 ModuleLoader
  DEPRECATED.md
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/library/Contao/ModuleLoader.php
Labels: feature

#4203 Add a HtmlAttributes class and Twig function
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/tests/String/HtmlAttributesTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: feature

#4306 Drop the initialize.php BC layer
  core-bundle/src/Controller/InitializeController.php
  core-bundle/src/EventListener/InitializeControllerListener.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Response/InitializeControllerResponse.php
  core-bundle/tests/Command/InstallCommandTest.php
  manager-bundle/src/EventListener/InstallCommandListener.php
  manager-bundle/src/Resources/config/services.yml
  manager-bundle/src/Resources/skeleton/system/initialize.php
Labels: feature

#4322 Use FQCN instead of aliased class name
  calendar-bundle/src/Resources/contao/dca/tl_calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments_notify.php
  core-bundle/src/Picker/TablePickerProvider.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_log.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_opt_in.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_settings.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_style_sheet.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
  core-bundle/src/Resources/contao/dca/tl_undo.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_File.php
  core-bundle/src/Resources/contao/library/Contao/Database/Updater.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/widgets/FileSelector.php
  core-bundle/src/Resources/contao/widgets/FileTree.php
  core-bundle/src/Resources/contao/widgets/PageSelector.php
  core-bundle/tests/Config/Loader/PhpFileLoaderTest.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare1.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare2.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare3.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare4.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare5.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare6.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_namespace1.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_namespace2.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  faq-bundle/src/Resources/contao/dca/tl_faq_category.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/dca/tl_news_archive.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_channel.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: bug

#4334 Merge branch '4.9' into 4.13
  calendar-bundle/src/Resources/contao/dca/tl_calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments_notify.php
  core-bundle/src/Picker/TablePickerProvider.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_log.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_opt_in.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_settings.php
  core-bundle/src/Resources/contao/dca/tl_style.php
  core-bundle/src/Resources/contao/dca/tl_style_sheet.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
  core-bundle/src/Resources/contao/dca/tl_undo.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_File.php
  core-bundle/src/Resources/contao/library/Contao/Database/Updater.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/widgets/FileSelector.php
  core-bundle/src/Resources/contao/widgets/FileTree.php
  core-bundle/src/Resources/contao/widgets/PageSelector.php
  core-bundle/tests/Config/Loader/PhpFileLoaderTest.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare1.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare2.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare3.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare4.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare5.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare6.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_namespace1.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_namespace2.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  faq-bundle/src/Resources/contao/dca/tl_faq_category.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/dca/tl_news_archive.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_channel.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: release

#4336 Merge branch '4.13' into 5.x
  calendar-bundle/src/Resources/contao/dca/tl_calendar.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  calendar-bundle/src/Resources/contao/templates/calendar/cal_default.html5
  calendar-bundle/src/Resources/contao/templates/calendar/cal_mini.html5
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments_notify.php
  core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php
  core-bundle/src/Picker/TablePickerProvider.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/dca/tl_form.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/contao/dca/tl_image_size.php
  core-bundle/src/Resources/contao/dca/tl_image_size_item.php
  core-bundle/src/Resources/contao/dca/tl_layout.php
  core-bundle/src/Resources/contao/dca/tl_log.php
  core-bundle/src/Resources/contao/dca/tl_member.php
  core-bundle/src/Resources/contao/dca/tl_member_group.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_opt_in.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/dca/tl_settings.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
  core-bundle/src/Resources/contao/dca/tl_undo.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/drivers/DC_File.php
  core-bundle/src/Resources/contao/library/Contao/Database/Updater.php
  core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php
  core-bundle/src/Resources/contao/widgets/FileTree.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/tests/Config/Loader/PhpFileLoaderTest.php
  core-bundle/tests/DependencyInjection/Compiler/ConfigureFilesystemPassTest.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare1.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare2.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare3.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare4.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare5.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_declare6.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_namespace1.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_namespace2.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  faq-bundle/src/Resources/contao/dca/tl_faq_category.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  news-bundle/src/Resources/contao/dca/tl_news_archive.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_channel.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: release

#4289 Add the missing type hints to our interfaces and abstract classes
  calendar-bundle/composer.json
  calendar-bundle/src/Picker/EventPickerProvider.php
  composer.json
  core-bundle/composer.json
  core-bundle/src/Config/Dumper/CombinedFileDumper.php
  core-bundle/src/Config/Dumper/DumperInterface.php
  core-bundle/src/Config/ResourceFinder.php
  core-bundle/src/Config/ResourceFinderInterface.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/Doctrine/Backup/Config/AbstractConfig.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemInterface.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Framework/FrameworkAwareInterface.php
  core-bundle/src/Image/ImageFactoryInterface.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Image/PictureFactoryInterface.php
  core-bundle/src/Image/Studio/ImageResult.php
  core-bundle/src/Picker/AbstractInsertTagPickerProvider.php
  core-bundle/src/Picker/AbstractPickerProvider.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/DcaPickerProviderInterface.php
  core-bundle/src/Picker/FilePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Picker/PickerBuilder.php
  core-bundle/src/Picker/PickerBuilderInterface.php
  core-bundle/src/Picker/PickerInterface.php
  core-bundle/src/Picker/PickerProviderInterface.php
  core-bundle/tests/Fixtures/Image/PictureFactoryWithRandomArgumentStub.php
  core-bundle/tests/Fixtures/Image/PictureFactoryWithResizeOptionsStub.php
  core-bundle/tests/Fixtures/Image/PictureFactoryWithoutResizeOptionsStub.php
  core-bundle/tests/Image/Studio/ImageResultTest.php
  core-bundle/tests/PhpunitExtension/DeprecatedClasses.php
  faq-bundle/composer.json
  faq-bundle/src/Picker/FaqPickerProvider.php
  installation-bundle/composer.json
  maker-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  news-bundle/src/Picker/NewsPickerProvider.php
  newsletter-bundle/composer.json
  phpstan.neon
Labels: feature

#4337 Use the FQCN in the newsletter DCA
  newsletter-bundle/src/Resources/contao/dca/tl_member.php
Labels: bug

#4332 Remove the article keywords
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/tests/Contao/TemplateTest.php
Labels: BC break

#4325 Don‘t prefix the DC driver anymore
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug, BC break

#4338 Remove the article keyword leftovers
  UPGRADE.md
  core-bundle/src/Resources/contao/classes/FrontendTemplate.php
  core-bundle/src/Resources/contao/classes/FrontendTemplateTrait.php
  core-bundle/src/Resources/contao/languages/en/tl_article.xlf
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/modules/ModuleArticle.php
Labels: bug

#4333 Removed deprecated TL_CSS_UNITS superglobal
  DEPRECATED.md
  core-bundle/src/Resources/contao/config/config.php
Labels: BC break

#4344 Handle VFS deprecations and remove BC layers
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemException.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/MountManagerTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
Labels: feature

#4018 Remove deprecated log_message()
  UPGRADE.md
  core-bundle/src/Resources/contao/helper/functions.php
Labels: feature, BC break

#4313 Update the meta files
  DEPRECATED.md
  LIMITATIONS.md
  UPGRADE.md
Labels: feature

#4335 Removed deprecated legacy simple token parsing
  core-bundle/src/String/SimpleTokenParser.php
  core-bundle/tests/String/SimpleTokenParserTest.php
Labels: feature, BC break

#4350 Merge branch '4.9' into 4.13
  .github/workflows/ci.yml
  calendar-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  manager-bundle/composer.json
  monorepo.yml
  news-bundle/composer.json
  newsletter-bundle/composer.json
  test-case/.gitignore
  test-case/README.md
  test-case/composer.json
  test-case/src/ContaoDatabaseTrait.php
  test-case/src/ContaoTestCase.php
  test-case/src/DeprecatedClassesPhpunitExtension.php
  test-case/src/FunctionalTestCase.php
  tools/require-checker/config.json
Labels: release

#4351 Merge branch '4.13' into 5.x
  .github/workflows/ci.yml
  calendar-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  manager-bundle/composer.json
  monorepo.yml
  news-bundle/composer.json
  newsletter-bundle/composer.json
  test-case/.gitignore
  test-case/README.md
  test-case/composer.json
  test-case/src/ContaoDatabaseTrait.php
  test-case/src/ContaoTestCase.php
  test-case/src/DeprecatedClassesPhpunitExtension.php
  test-case/src/FunctionalTestCase.php
Labels: release

#4356 Update the test case
  .github/workflows/ci.yml
  composer.json
  test-case/src/ContaoDatabaseTrait.php
  test-case/src/ContaoTestCase.php
  test-case/src/DeprecatedClassesPhpunitExtension.php
  test-case/src/FunctionalTestCase.php
Labels: CI

#4354 Use PHP8 attributes instead of annotations
  core-bundle/src/Entity/CrawlQueue.php
  core-bundle/src/Entity/CronJob.php
  core-bundle/src/Entity/RememberMe.php
  core-bundle/src/Entity/TrustedDevice.php
Labels: feature

#4360 Templates should end with an empty line
  core-bundle/src/Resources/contao/templates/backend/be_alerts.html5
  core-bundle/src/Resources/contao/templates/backend/be_confirm.html5
  core-bundle/src/Resources/contao/templates/backend/be_conflict.html5
  core-bundle/src/Resources/contao/templates/backend/be_diff.html5
  core-bundle/src/Resources/contao/templates/backend/be_help.html5
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/src/Resources/contao/templates/backend/be_login_two_factor.html5
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Resources/contao/templates/backend/be_password.html5
  core-bundle/src/Resources/contao/templates/backend/be_popup.html5
  core-bundle/src/Resources/contao/templates/frontend/fe_page.html5
  core-bundle/src/Resources/contao/templates/mail/mail_default.html5
Labels: bug

#4359 Fix code style for InsertTags::executeReplace
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#4362 Use gulp-uglify-es
  core-bundle/src/Resources/contao/themes/flexible/hover.min.js
  core-bundle/src/Resources/public/clipboard.min.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/mootao.min.js
  gulpfile.js
  package-lock.json
  package.json
Labels: feature

#4361 Documented missing UPGRADE.md entries
  UPGRADE.md
Labels: feature

#4374 Fix minor typo in InsertTags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#4373 Also clean textarea of caption for last metawizard
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#4377 Require Flysystem 3 only
  composer.json
  core-bundle/composer.json
Labels: bug

#4376 Increase the speed of the functional tests
  test-case/src/FunctionalTestCase.php
Labels: bug

#4236 Also create a new version if a checkbox is auto-submitted
  core-bundle/src/Resources/contao/classes/Ajax.php
Labels: bug

#4256 Allow fragment reference with fake model instance
  core-bundle/src/Fragment/Reference/ContentElementReference.php
  core-bundle/src/Fragment/Reference/FrontendModuleReference.php
  core-bundle/src/Resources/contao/elements/ContentProxy.php
  core-bundle/src/Resources/contao/modules/ModuleProxy.php
Labels: bug

#4263 Make the search accent insensitive
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/tests/Contao/SearchTest.php
  core-bundle/tests/Functional/SearchTest.php
Labels: bug

#4299 Fix invalid news content element ID
  news-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#4293 Revert 'Do not use the `.tl_confirm` CSS class in the front end'
  comments-bundle/src/Resources/contao/templates/modules/mod_comment_form.html5
  core-bundle/src/Resources/contao/templates/member/member_default.html5
  core-bundle/src/Resources/contao/templates/member/member_grouped.html5
  core-bundle/src/Resources/contao/templates/modules/mod_changePassword.html5
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
Labels: bug

#4331 Fix typos in Environment
  core-bundle/src/Resources/contao/library/Contao/Environment.php
Labels: bug

#4294 Rename the Controller::reset method
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#4391 Merge branch '4.9' into 4.13
  comments-bundle/src/Resources/contao/templates/modules/mod_comment_form.html5
  core-bundle/src/Fragment/Reference/ContentElementReference.php
  core-bundle/src/Fragment/Reference/FrontendModuleReference.php
  core-bundle/src/Framework/ContaoFramework.php
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/elements/ContentProxy.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/Environment.php
  core-bundle/src/Resources/contao/modules/ModuleProxy.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/src/Resources/contao/templates/member/member_default.html5
  core-bundle/src/Resources/contao/templates/member/member_grouped.html5
  core-bundle/src/Resources/contao/templates/modules/mod_changePassword.html5
  core-bundle/src/Resources/contao/templates/modules/mod_two_factor.html5
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/tests/Contao/ControllerTest.php
  news-bundle/src/Resources/contao/dca/tl_content.php
Labels: release

#4302 Always render protected pages in the pretty error screen listener
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/Fixtures/Functional/Routing/protected-root.yml
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#4353 Ensure the decorated access decision manager shows up in profiler
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Resources/config/services_debug.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#4311 Remove nullable response in controllers
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/src/Controller/ContentElement/TemplateController.php
  core-bundle/src/Controller/FrontendModule/TemplateController.php
  maker-bundle/src/Resources/skeleton/content-element/ContentElement.tpl.php
  maker-bundle/src/Resources/skeleton/frontend-module/FrontendModule.tpl.php
Labels: bug

#4398 Add missing annotations in ContentModel for showPreview
  core-bundle/src/Resources/contao/models/ContentModel.php
Labels: bug

#4357 Fix srcToInsertTag() for URL encoded paths
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
Labels: bug

#4402 Fixed nested http client options not supported
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#4397 Fix several VFS bugs
  core-bundle/src/EventListener/DbafsMetadataSubscriber.php
  core-bundle/src/Filesystem/Dbafs/AbstractDbafsMetadataEvent.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/Dbafs/RetrieveDbafsMetadataEvent.php
  core-bundle/src/Filesystem/Dbafs/StoreDbafsMetadataEvent.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemInterface.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
Labels: bug

#4346 Drop useless framework initialization
  core-bundle/src/Controller/ContentElement/TemplateController.php
Labels: bug

#4365 Removed deprecated FrontendCron controller
  core-bundle/src/Resources/contao/controllers/FrontendCron.php
Labels: feature, BC break

#4381 Allow to json-serialize the HtmlAttributes class
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/String/HtmlAttributesTest.php
Labels: feature

#4252 Fix the trigger_error() calls
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/pages/PageError401.php
  core-bundle/src/Resources/contao/pages/PageError403.php
  core-bundle/src/Resources/contao/pages/PageError404.php
  core-bundle/src/Resources/contao/pages/PageForward.php
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRegular.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#4297 Fix requireItem sorting
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/tests/Routing/AbstractPageRouteProviderTest.php
Labels: bug

#4411 Fix the CI chain
  test-case/src/ContaoDatabaseTrait.php
  test-case/src/ContaoTestCase.php
  test-case/src/DeprecatedClassesPhpunitExtension.php
  test-case/src/FunctionalTestCase.php
Labels: CI

#4179 Add a warning for too large database row sizes
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  comments-bundle/src/Resources/contao/dca/tl_content.php
  comments-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/src/Doctrine/Schema/MysqlInnodbRowSizeCalculator.php
  core-bundle/src/Resources/config/commands.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/tests/Command/MigrateCommandTest.php
  listing-bundle/src/Resources/contao/dca/tl_module.php
  news-bundle/src/Resources/contao/dca/tl_module.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
Labels: bug

#4410 Use symfony/polyfill-intl-idn instead of true/punycode
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/contao/library/Contao/Idna.php
  core-bundle/tests/Contao/IdnaTest.php
  core-bundle/tests/Contao/ValidatorTest.php
Labels: bug

#4219 Make the contao:install:lock command idempotent
  installation-bundle/src/Command/LockCommand.php
Labels: bug

#4416 Some small improvements for the HtmlAttribute class
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/String/HtmlAttributesTest.php
Labels: feature

#4342 Rewrite the Backend.limitPreviewHeight to vanilla JS
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/limit-height.js
  core-bundle/src/Resources/public/limit-height.min.js
Labels: feature

#4378 Fix global state in tests
  .github/workflows/ci.yml
  core-bundle/tests/Contao/ControllerTest.php
  test-case/src/ContaoTestCase.php
Labels: CI

#4423 Decode the folder name when checking for circular references
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#4424 Also hover over the parent records in "paste" mode
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#4425 Return the prefix-relative path when getting filesystem items from the VFS
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
Labels: bug

#4427 Handle long page titles and URLs in the search table
  core-bundle/src/Resources/contao/dca/tl_search.php
  core-bundle/src/Resources/contao/library/Contao/Search.php
Labels: bug

#4428 Update the changelog and the language files
  CHANGELOG.md
  calendar-bundle/src/Resources/contao/languages/pt/tl_calendar.xlf
  calendar-bundle/src/Resources/contao/languages/pt/tl_module.xlf
  comments-bundle/src/Resources/contao/languages/pt/tl_content.xlf
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/it/default.xlf
  core-bundle/src/Resources/contao/languages/it/exception.xlf
  core-bundle/src/Resources/contao/languages/it/explain.xlf
  core-bundle/src/Resources/contao/languages/lv/default.xlf
  core-bundle/src/Resources/contao/languages/lv/exception.xlf
  core-bundle/src/Resources/contao/languages/pt/default.xlf
  core-bundle/src/Resources/contao/languages/pt/exception.xlf
  core-bundle/src/Resources/contao/languages/pt/explain.xlf
  core-bundle/src/Resources/contao/languages/pt/modules.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_article.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_content.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_files.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_form.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_form_field.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_image_size.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_member.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_member_group.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_module.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_page.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_settings.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_style_sheet.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_theme.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_user.xlf
  core-bundle/src/Resources/contao/languages/pt/tl_user_group.xlf
  faq-bundle/src/Resources/contao/languages/pt/tl_faq_category.xlf
  installation-bundle/src/Resources/translations/ContaoInstallationBundle.pt.xlf
  listing-bundle/src/Resources/contao/languages/pt/tl_module.xlf
  manager-bundle/src/Resources/translations/ContaoManagerBundle.pt.xlf
  news-bundle/src/Resources/contao/languages/pt/tl_module.xlf
  news-bundle/src/Resources/contao/languages/pt/tl_news_archive.xlf
  newsletter-bundle/src/Resources/contao/languages/pt/tl_module.xlf
  newsletter-bundle/src/Resources/contao/languages/pt/tl_newsletter.xlf
  newsletter-bundle/src/Resources/contao/languages/pt/tl_newsletter_channel.xlf
Labels: release

#4429 Merge branch '4.9' into 4.13
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/Resources/contao/controllers/FrontendIndex.php
  core-bundle/src/Resources/contao/dca/tl_search.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  installation-bundle/src/Command/LockCommand.php
Labels: release

#4301 Remove file title from sources element
  core-bundle/src/Resources/contao/templates/elements/ce_player.html5
Labels: bug

#4303 Move the logic from LogoutHandler to LogoutSuccessListener
  core-bundle/README.md
  core-bundle/src/EventListener/Security/LogoutSuccessListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Security/Logout/LogoutHandler.php
  core-bundle/tests/EventListener/Security/LogoutSuccessListenerTest.php
  core-bundle/tests/Functional/app/config/security.yml
  core-bundle/tests/PhpunitExtension/DeprecatedClasses.php
  core-bundle/tests/Security/Logout/LogoutHandlerTest.php
  manager-bundle/src/Resources/skeleton/config/security.yml
  phpstan.neon
Labels: bug

#4426 Add the service subscriber tag to the correct controller
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/config/services.yml
Labels: bug

#4432 Use actions/checkout@v3 in the Github actions
  .github/workflows/ci.yml
Labels: CI

#4433 Always create an article if page has no layout
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
Labels: bug

#4431 Allow to purge the preview cache in the user profile
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/languages/en/tl_user.xlf
Labels: bug
