Repository contao/contao, pull requests merged in 2022-10, with the labels that each got.

#5329 Fix MySQL data too long error in search
  core-bundle/src/Resources/contao/library/Contao/Search.php
Labels: bug

#5332 Fix return type of FilterIterator
  core-bundle/src/Resources/contao/library/Contao/Filter/SqlFiles.php
  core-bundle/src/Resources/contao/library/Contao/Filter/SyncExclude.php
Labels: bug

#5331 Do not show errors twice in console
  manager-bundle/bin/contao-console
Labels: bug

#5338 Backport localconfig file check to Contao 4.9
  core-bundle/src/Resources/contao/drivers/DC_File.php
Labels: bug

#5337 Backport localconfig file check to Contao 4.13
  core-bundle/src/Resources/contao/drivers/DC_File.php
Labels: bug

#5345 Fix the version edit URL
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#5342 Hide the form field name if a widget does not submit input
  core-bundle/src/Resources/contao/dca/tl_form_field.php
Labels: bug

#5348 Correctly pick fallback root page with domain
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#5330 Add an exception for a missing administrator email address
  core-bundle/src/Resources/contao/library/Contao/Email.php
Labels: bug

#5336 Fix a potential error when trying to log the deleted record
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5352 Fix `DC_Folder` ID not being determined correctly due to special characters
  core-bundle/src/Resources/contao/classes/Ajax.php
Labels: bug

#5343 Backport the TinyMCE accesskey fix
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5
Labels: bug

#5350 Fix unknown system variable error
  core-bundle/src/Doctrine/Schema/MysqlInnodbRowSizeCalculator.php
Labels: bug

#5354 Merge branch '4.13' into 5.0
  calendar-bundle/contao/modules/ModuleEventlist.php
  comments-bundle/contao/classes/Comments.php
  core-bundle/contao/classes/Ajax.php
  core-bundle/contao/classes/Versions.php
  core-bundle/contao/controllers/BackendHelp.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/elements/ContentGallery.php
  core-bundle/contao/library/Contao/Email.php
  core-bundle/contao/library/Contao/Filter/SqlFiles.php
  core-bundle/contao/library/Contao/Filter/SyncExclude.php
  core-bundle/contao/library/Contao/Search.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/ModuleChangePassword.php
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/contao/modules/ModuleRssReader.php
  core-bundle/contao/modules/ModuleSearch.php
  core-bundle/src/Doctrine/Schema/MysqlInnodbRowSizeCalculator.php
  faq-bundle/contao/dca/tl_faq.php
  listing-bundle/contao/modules/ModuleListing.php
  manager-bundle/bin/contao-console
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/modules/ModuleNewsArchive.php
  news-bundle/contao/modules/ModuleNewsList.php
Labels: release

#5347 Add a markdown help text
  core-bundle/contao/languages/en/explain.xlf
Labels: feature

#5358 Update the tools
  .github/workflows/ci.yml
  composer.json
  core-bundle/contao/library/Contao/Template.php
  core-bundle/contao/models/PageModel.php
  core-bundle/src/Controller/ContentElement/ImagesController.php
  core-bundle/src/Controller/ContentElement/MarkdownController.php
  core-bundle/src/Controller/RobotsTxtController.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Filesystem/FilesystemUtil.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/Controller/FrontendModule/RootPageDependentModulesControllerTest.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/Filesystem/FilesystemUtilTest.php
  core-bundle/tests/Image/Studio/FigureBuilderStub.php
  core-bundle/tests/Routing/RouteProviderTest.php
  core-bundle/tests/Security/Authentication/AccessDecisionManagerTest.php
  news-bundle/src/EventListener/NewsFeedListener.php
  news-bundle/src/Migration/FeedMigration.php
  news-bundle/tests/EventListener/NewsFeedListenerTest.php
  phpunit.xml.dist
  tools/ecs/composer.lock
  tools/ecs/config/default.php
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/rector/config/rector.php
  tools/require-checker/composer.lock
  tools/require-checker/config/config.json
  tools/service-linter/composer.lock
Labels: CI

#5361 Fix the oncopy_callback
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5359 Change the default value for tl_layout.viewport
  core-bundle/contao/dca/tl_layout.php
Labels: feature

#5362 Merge branch '4.13' into 5.0
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/Command/MigrateCommand.php
Labels: release

#5363 Use Rector and ECS for the tools as well
  .github/workflows/ci.yml
  composer.json
  tools/ecs/config/default.php
  tools/ecs/config/legacy.php
  tools/ecs/config/template.php
  tools/isolated-tests/src/RunTestsIsolatedCommand.php
  tools/rector/config/rector.php
  tools/service-linter/src/LintServiceIdsCommand.php
Labels: CI

#5370 Fix the CSS reset in the back end
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
Labels: bug

#5379 Use sendfile for local files downloads
  core-bundle/src/Filesystem/FileDownloadHelper.php
  core-bundle/tests/Filesystem/FileDownloadHelperTest.php
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
Labels: feature

#5412 Fix the TL_ADMIN_MAIL usage
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  comments-bundle/src/Resources/contao/elements/ContentComments.php
  comments-bundle/src/Resources/contao/modules/ModuleComments.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: bug

#5408 Reintroduce missing locking mechanism
  core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php
Labels: bug

#5411 Use button element for metawizard
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
Labels: bug

#5403 Add the user option to not collapse content elements
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/languages/en/tl_user.xlf
  core-bundle/contao/library/Contao/User.php
  core-bundle/contao/models/UserModel.php
Labels: feature

#5364 Allow defining a default search field
  calendar-bundle/contao/dca/tl_calendar.php
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/contao/dca/tl_calendar_feed.php
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_form.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/dca/tl_layout.php
  core-bundle/contao/dca/tl_log.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_member_group.php
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/dca/tl_opt_in.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/contao/dca/tl_undo.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  core-bundle/contao/drivers/DC_Table.php
  faq-bundle/contao/dca/tl_faq.php
  faq-bundle/contao/dca/tl_faq_category.php
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/dca/tl_news_archive.php
  newsletter-bundle/contao/dca/tl_newsletter.php
  newsletter-bundle/contao/dca/tl_newsletter_channel.php
  newsletter-bundle/contao/dca/tl_newsletter_recipients.php
Labels: feature

#5410 Fix several VFS/UUID related issues
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
Labels: bug

#5366 Rename the internal route name for generating page routes
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Resources/contao/classes/Frontend.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/PageUrlGenerator.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/Routing/PageUrlGeneratorTest.php
Labels: bug

#5420 Fix the reverse toggle operation
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#5422 Fix more PHP8 issues
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/forms/FormTextField.php
Labels: bug

#5429 Use codecov-action@v3 and always send the token
  .github/workflows/ci.yml
Labels: bug, CI

#5409 Add icon alt text to file tree
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
Labels: bug

#5430 Merge branch '4.9' into 4.13
  .github/workflows/ci.yml
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  comments-bundle/src/Resources/contao/classes/Comments.php
  comments-bundle/src/Resources/contao/dca/tl_comments.php
  comments-bundle/src/Resources/contao/elements/ContentComments.php
  comments-bundle/src/Resources/contao/modules/ModuleComments.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/forms/Form.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: bug, release

#5431 Merge branch '4.13' into 5.0
  .github/workflows/ci.yml
  calendar-bundle/contao/modules/ModuleEventReader.php
  comments-bundle/contao/classes/Comments.php
  comments-bundle/contao/dca/tl_comments.php
  comments-bundle/contao/elements/ContentComments.php
  comments-bundle/contao/modules/ModuleComments.php
  core-bundle/contao/classes/Frontend.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/forms/Form.php
  core-bundle/contao/forms/FormText.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/contao/widgets/MetaWizard.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/PageUrlGenerator.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
  core-bundle/tests/Routing/PageUrlGeneratorTest.php
  faq-bundle/contao/modules/ModuleFaqReader.php
  news-bundle/contao/modules/ModuleNewsReader.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
Labels: CI

#5432 Merge branch '5.0' into 5.1
  .github/workflows/ci.yml
  calendar-bundle/contao/modules/ModuleEventReader.php
  comments-bundle/contao/classes/Comments.php
  comments-bundle/contao/dca/tl_comments.php
  comments-bundle/contao/elements/ContentComments.php
  comments-bundle/contao/modules/ModuleComments.php
  core-bundle/contao/classes/Frontend.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/forms/Form.php
  core-bundle/contao/forms/FormText.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/contao/widgets/MetaWizard.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Routing/PageUrlGenerator.php
  core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
  core-bundle/tests/Routing/PageUrlGeneratorTest.php
  faq-bundle/contao/modules/ModuleFaqReader.php
  listing-bundle/contao/modules/ModuleListing.php
  news-bundle/contao/modules/ModuleNewsReader.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
Labels: release

#5438 Don’t throw error for empty insert tag
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
Labels: bug

#5436 Fix reader modules when `auto_item` is empty
  calendar-bundle/contao/modules/ModuleEventReader.php
  faq-bundle/contao/modules/ModuleFaqReader.php
  news-bundle/contao/modules/ModuleNewsReader.php
  newsletter-bundle/contao/modules/ModuleNewsletterReader.php
Labels: bug

#5437 Fix error "toFixed is not a function"
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
Labels: bug

#5421 Handle errors with important parts
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#5435 Restore previous translations in `$GLOBALS['TL_LANG']`
  core-bundle/src/Translation/Translator.php
  core-bundle/tests/Translation/TranslatorTest.php
Labels: bug

#5439 Stop using `$GLOBALS['TL_LANG']` in templates
  core-bundle/src/Resources/contao/templates/backend/be_welcome.html5
  core-bundle/src/Resources/contao/templates/js/js_nocookie.html5
  core-bundle/src/Resources/contao/templates/mootools/moo_tablesort.html5
Labels: bug

#5441 Don’t replace insert tags in the backend
  core-bundle/contao/library/Contao/TemplateInheritance.php
Labels: bug

#5212 Write dotenv parameters to .env.local
  manager-bundle/src/ContaoManager/ApiCommand/GetDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/RemoveDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetDotEnvCommand.php
  manager-bundle/tests/ContaoManager/ApiCommand/GetDotEnvCommandTest.php
  manager-bundle/tests/ContaoManager/ApiCommand/RemoveDotEnvCommandTest.php
  manager-bundle/tests/ContaoManager/ApiCommand/SetDotEnvCommandTest.php
Labels: bug

#5444 Fix issues introduced by CSS reset changes in the back end
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
Labels: bug

#4840 Add class to back end login
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/src/Resources/contao/templates/backend/be_login_two_factor.html5
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
Labels: bug

#5440 Do not boot Contao framework in DefaultIndexer::delete()
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: bug

#5442 Do not boot Contao framework in DefaultIndexer::delete()
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/tests/Search/Indexer/DefaultIndexerTest.php
Labels: bug

#5450 Fix bug in Search::removeEntry()
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/tests/Functional/SearchTest.php
Labels: bug

#5447 Decode entities in the page title in the JSON-LD data
  core-bundle/src/Resources/contao/pages/PageRegular.php
Labels: bug

#5445 Fix the back end top navigation disappearing on mobile devices
  core-bundle/src/Resources/contao/themes/flexible/hover.js
  core-bundle/src/Resources/contao/themes/flexible/hover.min.js
Labels: bug

#5452 Merge branch '4.9' into 4.13
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/templates/backend/be_login.html5
  core-bundle/src/Resources/contao/templates/backend/be_login_two_factor.html5
  core-bundle/src/Resources/contao/templates/backend/be_main.html5
  core-bundle/src/Resources/contao/templates/backend/be_welcome.html5
  core-bundle/src/Resources/contao/templates/js/js_nocookie.html5
  core-bundle/src/Resources/contao/templates/mootools/moo_tablesort.html5
  core-bundle/src/Resources/contao/themes/flexible/hover.js
  core-bundle/src/Resources/contao/themes/flexible/hover.min.js
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  manager-bundle/src/ContaoManager/ApiCommand/GetDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/RemoveDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetDotEnvCommand.php
  manager-bundle/tests/ContaoManager/ApiCommand/GetDotEnvCommandTest.php
  manager-bundle/tests/ContaoManager/ApiCommand/RemoveDotEnvCommandTest.php
  manager-bundle/tests/ContaoManager/ApiCommand/SetDotEnvCommandTest.php
Labels: bug, release

#5451 Fix bug in Search::removeEntry()
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/tests/Functional/SearchTest.php
Labels: bug

#5455 Allow PNG favicons
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Fixtures/images/favicon.png
Labels: bug

#5446 Fix issues in images content element if no images are defined
  core-bundle/src/Controller/ContentElement/ImagesController.php
  core-bundle/tests/Controller/ContentElement/ImagesControllerTest.php
Labels: bug
