Repository contao/contao, pull requests merged in 2023-01, with the labels that each got.

#5620 Fix `{{date::Y}}` caching
  core-bundle/src/Controller/InsertTagsController.php
  core-bundle/tests/Controller/InsertTagsControllerTest.php
Labels: bug

#5603 Set $useLastModified in FilesystemConfiguration::addDefaultDbafs()
  core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php
  core-bundle/tests/DependencyInjection/Filesystem/FilesystemConfigurationTest.php
Labels: bug

#5371 Allow to set the locale in `Template::trans`
  core-bundle/contao/library/Contao/Template.php
  core-bundle/src/Twig/FragmentTemplate.php
Labels: feature

#5478 Add the `#[\SensitiveParameter]` attribute
  core-bundle/contao/forms/FormPassword.php
  core-bundle/contao/library/Contao/User.php
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Csrf/MemoryTokenStorage.php
  core-bundle/src/Image/Preview/PreviewFactory.php
  core-bundle/src/Security/Authentication/RememberMe/RememberMeTokenProvider.php
  manager-bundle/src/Command/ContaoSetupCommand.php
Labels: feature

#5116 Introduce MemberActivationMailEvent
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/src/Event/MemberActivationMailEvent.php
  newsletter-bundle/config/services.yaml
  newsletter-bundle/src/EventListener/MemberActivationMailListener.php
  newsletter-bundle/tests/EventListener/MemberActivationMailListenerTest.php
Labels: feature

#5602 Adjust the name of the default guests group
  core-bundle/contao/languages/en/default.xlf
Labels: feature

#5591 Remove localconfig.disableCron in favor of a new zero config approach
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/config/default.php
  core-bundle/contao/dca/tl_settings.php
  core-bundle/contao/languages/en/tl_settings.xlf
  core-bundle/contao/library/Contao/Config.php
  core-bundle/src/Cron/Cron.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/CommandSchedulerListener.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/CommandSchedulerListenerTest.php
  core-bundle/tests/Functional/app/config/config_test.yaml
Labels: feature

#5621 Update and run the tools
  core-bundle/src/DependencyInjection/Attribute/AsContentElement.php
  core-bundle/src/DependencyInjection/Attribute/AsFrontendModule.php
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/tests/Filesystem/FilesystemItemIteratorTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.json
  tools/rector/composer.lock
  tools/rector/config/rector.php
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#5622 Merge branch '4.9' into 4.13
  core-bundle/src/Resources/contao/dca/tl_undo.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/templates/modules/mod_navigation.html5
  core-bundle/src/Resources/contao/widgets/PageTree.php
  core-bundle/src/Resources/views/Backend/be_header_menu.html.twig
  core-bundle/src/Resources/views/Backend/be_menu.html.twig
  manager-bundle/src/ContaoManager/Plugin.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
  newsletter-bundle/src/Resources/contao/modules/ModuleUnsubscribe.php
Labels: bug, release

#5623 Merge branch '4.13' into 5.0
  core-bundle/contao/dca/tl_undo.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/templates/modules/mod_navigation.html5
  core-bundle/contao/widgets/PageTree.php
  core-bundle/src/Command/FilesyncCommand.php
  core-bundle/src/Controller/InsertTagsController.php
  core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ChangeSet.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ItemToCreate.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ItemToDelete.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ItemToUpdate.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/Dbafs/DbafsInterface.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/templates/Backend/be_filesync_report.html.twig
  core-bundle/templates/Backend/be_header_menu.html.twig
  core-bundle/templates/Backend/be_menu.html.twig
  core-bundle/tests/Command/FilesyncCommandTest.php
  core-bundle/tests/Controller/InsertTagsControllerTest.php
  core-bundle/tests/DependencyInjection/Filesystem/FilesystemConfigurationTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSet/ChangeSetTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSet/ItemToCreateTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSet/ItemToDeleteTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSet/ItemToUpdateTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSetTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  core-bundle/tests/Functional/DbafsTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  newsletter-bundle/contao/modules/ModuleSubscribe.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
Labels: release

#5624 Merge branch '5.0' into 5.x
  composer.json
  core-bundle/config/migrations.yaml
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_undo.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/templates/modules/mod_navigation.html5
  core-bundle/contao/widgets/PageTree.php
  core-bundle/src/Command/FilesyncCommand.php
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/src/Controller/InsertTagsController.php
  core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ChangeSet.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ItemToCreate.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ItemToDelete.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ItemToUpdate.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/Dbafs/DbafsInterface.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Migration/Version500/AccesskeyMigration.php
  core-bundle/templates/Backend/be_filesync_report.html.twig
  core-bundle/templates/Backend/be_header_menu.html.twig
  core-bundle/templates/Backend/be_menu.html.twig
  core-bundle/tests/Command/FilesyncCommandTest.php
  core-bundle/tests/Controller/InsertTagsControllerTest.php
  core-bundle/tests/DependencyInjection/Filesystem/FilesystemConfigurationTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSet/ChangeSetTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSet/ItemToCreateTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSet/ItemToDeleteTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSet/ItemToUpdateTest.php
  core-bundle/tests/Filesystem/Dbafs/ChangeSetTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  core-bundle/tests/Functional/DbafsTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  newsletter-bundle/contao/modules/ModuleSubscribe.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
Labels: release

#5417 Add a button to copy multiple records and paste them multiple times
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/languages/en/default.xlf
Labels: feature

#5425 Allow sorting DCA fields ascending and descending
  calendar-bundle/contao/dca/tl_calendar_events.php
  comments-bundle/contao/dca/tl_comments.php
  comments-bundle/contao/languages/en/tl_comments.xlf
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/drivers/DC_Table.php
  faq-bundle/contao/dca/tl_faq.php
  news-bundle/contao/dca/tl_news.php
  newsletter-bundle/contao/dca/tl_newsletter.php
Labels: feature

#4898 Add error handling for process form data
  core-bundle/contao/forms/Form.php
  core-bundle/contao/templates/forms/form_wrapper.html5
Labels: feature

#5307 Add a confirmation message to forms and provide Ajax out of the box
  core-bundle/assets/ajax-form.js
  core-bundle/contao/dca/tl_form.php
  core-bundle/contao/forms/Form.php
  core-bundle/contao/languages/en/tl_form.xlf
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/templates/forms/form_inline.html5
  core-bundle/contao/templates/forms/form_message.html5
  core-bundle/contao/templates/forms/form_wrapper.html5
  core-bundle/public/ajax-form.8d9f14a4.js
  core-bundle/public/ajax-form.8d9f14a4.js.map
  core-bundle/public/backend.c9c34f6e.js
  core-bundle/public/backend.c9c34f6e.js.map
  core-bundle/public/backend.deffe4ac.js
  core-bundle/public/backend.deffe4ac.js.map
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  webpack.config.js
Labels: feature

#4936 Support native date input type for text fields in the form generator
  core-bundle/contao/forms/FormText.php
Labels: feature

#5598 Also minify the core.js and mootao.js scripts with Webpack
  core-bundle/assets/backend.js
  core-bundle/assets/scripts/core.js
  core-bundle/assets/scripts/mootao.js
  core-bundle/contao/templates/backend/be_alerts.html5
  core-bundle/contao/templates/backend/be_confirm.html5
  core-bundle/contao/templates/backend/be_conflict.html5
  core-bundle/contao/templates/backend/be_help.html5
  core-bundle/contao/templates/backend/be_login.html5
  core-bundle/contao/templates/backend/be_login_two_factor.html5
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/contao/templates/backend/be_password.html5
  core-bundle/contao/templates/backend/be_popup.html5
  core-bundle/contao/themes/flexible/hover.js
  core-bundle/contao/themes/flexible/hover.min.js
  core-bundle/public/backend.25f3db11.js
  core-bundle/public/backend.25f3db11.js.map
  core-bundle/public/backend.deffe4ac.js
  core-bundle/public/backend.deffe4ac.js.map
  core-bundle/public/core.min.js
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/public/mootao.min.js
  gulpfile.js
  webpack.config.js
Labels: feature

#5368 Enable login rate limit
  composer.json
  core-bundle/README.md
  core-bundle/composer.json
  core-bundle/contao/controllers/BackendIndex.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/library/Contao/User.php
  core-bundle/contao/models/MemberModel.php
  core-bundle/contao/models/UserModel.php
  core-bundle/contao/modules/ModuleLogin.php
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/src/Command/UserPasswordCommand.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php
  core-bundle/src/Security/Exception/LockedException.php
  core-bundle/src/Security/User/UserChecker.php
  core-bundle/tests/Command/UserPasswordCommandTest.php
  core-bundle/tests/Functional/app/config/security.yaml
  core-bundle/tests/Security/Exception/LockedExceptionTest.php
  core-bundle/tests/Security/User/UserCheckerTest.php
  manager-bundle/skeleton/config/security.yaml
Labels: feature

#5597 Correctly open and close tree nodes if there is a filter
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#5630 Run the tools
  calendar-bundle/contao/modules/ModuleEventReader.php
  core-bundle/contao/elements/ContentAccordion.php
  core-bundle/contao/elements/ContentImage.php
  core-bundle/contao/elements/ContentText.php
  core-bundle/contao/library/Contao/Database/Result.php
  core-bundle/contao/library/Contao/Dbafs.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/src/Doctrine/Backup/Dumper.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Routing/Page/ContentCompositionInterface.php
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Finder/Finder.php
  core-bundle/src/Twig/Runtime/HighlightResult.php
  core-bundle/src/Util/CachingTraversable.php
  core-bundle/tests/Command/FilesyncCommandTest.php
  core-bundle/tests/Contao/WidgetTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Filesystem/MountManagerTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Util/CachingTraversableTest.php
  faq-bundle/contao/modules/ModuleFaqPage.php
  faq-bundle/contao/modules/ModuleFaqReader.php
Labels: CI

#5629 Fix PHP8 Warning picture_default
  core-bundle/src/Resources/contao/templates/picture/picture_default.html5
Labels: bug

#5633 Fix the @see annotations
  core-bundle/contao/classes/FrontendTemplate.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/DependencyInjection/Attribute/AsPage.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/FilesystemUtil.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Fragment/FragmentConfig.php
  core-bundle/src/Picker/FilePickerProvider.php
  core-bundle/src/ServiceAnnotation/Page.php
  core-bundle/src/Slug/Slug.php
  core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicUseTokenParser.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/src/Twig/Interop/ContextFactory.php
  core-bundle/src/Twig/Runtime/HighlightResult.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: CI

#5405 Introduce background workers
  composer.json
  core-bundle/composer.json
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/src/Cron/MessengerCron.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/DoctrineSchemaListener.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Messenger/AutoFallbackNotifier.php
  core-bundle/src/Messenger/EventListener/WorkerListener.php
  core-bundle/src/Messenger/Message/HighPriorityMessageInterface.php
  core-bundle/src/Messenger/Message/LowPriorityMessageInterface.php
  core-bundle/src/Messenger/Message/NormalPriorityMessageInterface.php
  core-bundle/src/Messenger/Message/SearchIndexMessage.php
  core-bundle/src/Messenger/MessageHandler/SearchIndexMessageHandler.php
  core-bundle/src/Messenger/Transport/AutoFallbackTransport.php
  core-bundle/src/Messenger/Transport/AutoFallbackTransportFactory.php
  core-bundle/src/Search/Document.php
  core-bundle/src/Util/ProcessUtil.php
  core-bundle/tests/Cron/MessengerCronTest.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/EventListener/DoctrineSchemaListenerTest.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
  core-bundle/tests/Messenger/AutoFallbackNotifierTest.php
  core-bundle/tests/Messenger/EventListener/WorkerListenerTest.php
  core-bundle/tests/Messenger/MessageHandler/SearchIndexMessageHandlerTest.php
  core-bundle/tests/Messenger/Transport/AutoFallbackTransportFactoryTest.php
  core-bundle/tests/Messenger/Transport/AutoFallbackTransportTest.php
  core-bundle/tests/Util/ProcessUtilTest.php
  manager-bundle/skeleton/config/config.yaml
Labels: feature

#5646 Use enumNode instead of custom validation
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: bug

#5647 Ensure Doctrine connections are closed after message handling
  manager-bundle/skeleton/config/config.yaml
Labels: bug

#5637 Correctly check for hidden content elements
  core-bundle/src/Resources/contao/elements/ContentAlias.php
  core-bundle/src/Resources/contao/elements/ContentArticle.php
  core-bundle/src/Resources/contao/elements/ContentDownload.php
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/elements/ContentProxy.php
Labels: bug

#5615 Fix the foreignKey handling when showColumns is enabled
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5641 Fix the z-index of the user menu
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#5643 Fix array index check in tl_calendar_events
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
Labels: bug

#5625 Correctly handle invalid size in TextArea widget
  core-bundle/src/Resources/contao/forms/FormTextArea.php
Labels: bug

#5427 Check administrator email address
  core-bundle/config/listener.yaml
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/src/EventListener/AdministratorEmailListener.php
  core-bundle/tests/EventListener/AdministratorEmailListenerTest.php
Labels: feature

#5652 Only hide the dark/light theme icons via CSS
  core-bundle/contao/library/Contao/Image.php
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
Labels: bug

#5653 Fix the tree indentation
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#5654 Allow cronjobs to be skipped
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Cron/CronJob.php
  core-bundle/src/Exception/CronExecutionSkippedException.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/Fixtures/src/Cron/TestCronJob.php
Labels: bug

#5664 Merge branch '4.9' into 4.13
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Cron/CronJob.php
  core-bundle/src/Exception/CronExecutionSkippedException.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/Fixtures/src/Cron/TestCronJob.php
Labels: bug, release

#5665 Merge branch '4.13' into 5.0
  composer.json
  core-bundle/composer.json
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Cron/CronJob.php
  core-bundle/src/Exception/CronExecutionSkippedException.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/Fixtures/src/Cron/TestCronJob.php
Labels: release

#5632 Reset the list wizard list-style
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
Labels: bug

#5666 Skip cron execution for minutely cron and messenger cron in web scope
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Cron/MessengerCron.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/Cron/MessengerCronTest.php
Labels: bug

#5662 Handle symlinked upload directories outside of the Contao root
  core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php
  core-bundle/tests/DependencyInjection/Compiler/ConfigureFilesystemPassTest.php
Labels: bug

#5668 Fix the URLs for the newsletter sending process
  newsletter-bundle/contao/classes/Newsletter.php
Labels: bug

#3694 Add the URI and page ID to log entries
  core-bundle/contao/dca/tl_log.php
  core-bundle/contao/languages/en/tl_log.xlf
  core-bundle/src/Monolog/ContaoContext.php
  core-bundle/src/Monolog/ContaoTableHandler.php
  core-bundle/src/Monolog/ContaoTableProcessor.php
  core-bundle/tests/Monolog/ContaoContextTest.php
  core-bundle/tests/Monolog/ContaoTableHandlerTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
Labels: feature

#5670 Do not add the request token to idempotent actions
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/Versions.php
  core-bundle/contao/controllers/BackendMain.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/library/Contao/System.php
  core-bundle/contao/modules/ModuleChangePassword.php
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/contao/widgets/ModuleWizard.php
  core-bundle/src/EventListener/Widget/RootPageDependentSelectListener.php
  core-bundle/tests/EventListener/Widget/RootPageDependentSelectListenerTest.php
Labels: bug

#5673 Add attributes_callback for DCA fields
  core-bundle/contao/library/Contao/Widget.php
Labels: feature

#5672 Add more back end grid classes
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_files.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/dca/tl_settings.php
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  newsletter-bundle/contao/dca/tl_newsletter.php
  newsletter-bundle/contao/dca/tl_newsletter_channel.php
Labels: feature

#5676 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/lv/default.xlf
  core-bundle/src/Resources/contao/languages/lv/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/explain.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_member.xlf
  core-bundle/src/Resources/contao/languages/tr/default.xlf
  newsletter-bundle/src/Resources/contao/languages/tr/tl_newsletter.xlf
Labels: bug, release

#5667 Correctly sort images and downloads by date
  core-bundle/src/Resources/contao/elements/ContentDownloads.php
  core-bundle/src/Resources/contao/elements/ContentGallery.php
Labels: bug

#5677 Update the changelog and the language files
  CHANGELOG.md
  CONTRIBUTORS.md
  core-bundle/src/Resources/contao/config/constants.php
  core-bundle/src/Resources/contao/languages/lv/default.xlf
  core-bundle/src/Resources/contao/languages/lv/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/sl/default.xlf
  core-bundle/src/Resources/contao/languages/sl/explain.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_content.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_maintenance.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_member.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_page.xlf
  core-bundle/src/Resources/contao/languages/sl/tl_preview_link.xlf
  core-bundle/src/Resources/contao/languages/tr/default.xlf
  core-bundle/src/Resources/contao/languages/tr/tl_preview_link.xlf
  newsletter-bundle/src/Resources/contao/languages/tr/tl_newsletter.xlf
Labels: bug, release

#5679 Add a default value for the worker "min" configuration
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: bug

#5566 Remove Basic Entities from SerpPreview
  core-bundle/assets/scripts/mootao.js
  core-bundle/contao/widgets/SerpPreview.php
Labels: bug

#5682 Allow to pass an array of allowed attributes to Input::stripTags()
  core-bundle/contao/library/Contao/Input.php
Labels: feature

#5683 Fix the skippable cronjobs
  core-bundle/src/Cron/Cron.php
  core-bundle/tests/Cron/CronTest.php
  core-bundle/tests/Fixtures/src/Cron/TestCronJob.php
Labels: bug

#4847 Add a new feed reader implementation
  composer.json
  core-bundle/composer.json
  core-bundle/config/controller.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/languages/en/modules.xlf
  core-bundle/contao/languages/en/tl_module.xlf
  core-bundle/contao/library/Contao/Pagination.php
  core-bundle/contao/modules/ModuleRssReader.php
  core-bundle/contao/templates/_new/frontend_module/_base.html.twig
  core-bundle/contao/templates/_new/frontend_module/feed_reader.html.twig
  core-bundle/src/Controller/FrontendModule/FeedReaderController.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/SanitizerRuntime.php
  core-bundle/tests/Contao/PaginationTest.php
  core-bundle/tests/Controller/FrontendModule/FeedReaderControllerTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
Labels: feature

#5690 Fix the icons when toggling structures in dark mode
  core-bundle/assets/scripts/core.js
  core-bundle/public/backend.9a54c06e.js
  core-bundle/public/backend.9a54c06e.js.map
  core-bundle/public/backend.ad44f617.js
  core-bundle/public/backend.ad44f617.js.map
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug

#5687 Move the dark mode toggle to the header bar
  core-bundle/assets/controllers/color-scheme-controller.js
  core-bundle/assets/scripts/tips.js
  core-bundle/config/listener.yaml
  core-bundle/contao/themes/flexible/icons-dark/color-scheme_small.svg
  core-bundle/contao/themes/flexible/icons/color-scheme_small.svg
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/public/backend.ad44f617.js
  core-bundle/public/backend.ad44f617.js.map
  core-bundle/public/backend.e4fd78c3.js
  core-bundle/public/backend.e4fd78c3.js.map
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/src/EventListener/Menu/BackendColorSchemeListener.php
  core-bundle/src/EventListener/Menu/BackendLogoutListener.php
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/src/EventListener/Menu/BackendPreviewListener.php
  core-bundle/tests/EventListener/Menu/BackendColorSchemeListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendFavoritesListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendPreviewListenerTest.php
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
Labels: bug

#5691 Correctly toggle the favorites menu group
  core-bundle/src/EventListener/Menu/BackendFavoritesListener.php
  core-bundle/tests/EventListener/Menu/BackendFavoritesListenerTest.php
Labels: bug

#5695 Use two different icons for light and dark mode
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/icons-dark/alert.svg
  core-bundle/contao/themes/flexible/icons-dark/color_scheme.svg
  core-bundle/contao/themes/flexible/icons-dark/favorite.svg
  core-bundle/contao/themes/flexible/icons-dark/favorite_active.svg
  core-bundle/contao/themes/flexible/icons-dark/manual.svg
  core-bundle/contao/themes/flexible/icons/color-scheme_small.svg
  core-bundle/contao/themes/flexible/icons/color_scheme.svg
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
Labels: bug

#5702 Make `$consolePath` a required argument
  core-bundle/src/Util/ProcessUtil.php
  core-bundle/tests/Cron/MessengerCronTest.php
  core-bundle/tests/Util/ProcessUtilTest.php
Labels: bug

#5703 Fix the Gulp watch task
  gulpfile.js
Labels: bug

#5698 Fix wrong page alias when changing the title of a page
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
Labels: bug

#5705 Observe document instead of document.documentElement
  core-bundle/contao/templates/_new/component/_table.html.twig
Labels: bug

#5715 Fix component detection in template skeleton
  core-bundle/contao/dca/tl_templates.php
Labels: bug

#5714 Use the HTML sanitizer component as Twig filter
  composer.json
  core-bundle/composer.json
  core-bundle/config/services.yaml
  core-bundle/src/Twig/Runtime/SanitizerRuntime.php
  core-bundle/tests/Functional/TwigTest.php
Labels: bug

#5721 Correctly describe our breadcrumbs with WAI-ARIA tags
  core-bundle/src/Resources/contao/templates/modules/mod_breadcrumb.html5
Labels: bug

#5669 Skip pages in sitemap.xml if URL cannot be generated
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: bug

#5709 Check for trail page before rendering the navigation
  core-bundle/src/Resources/contao/modules/ModuleNavigation.php
Labels: bug

#5606 Use the request language to match `iflng` tags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#5708 Add the missing null check for button_callback
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#5726 Merge branch '4.13' into 5.0
  .github/workflows/assign-pr.yml
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/modules/ModuleNavigation.php
  core-bundle/contao/templates/modules/mod_breadcrumb.html5
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: release

#5724 Fix the number of bound variables in the MemberModel class
  core-bundle/contao/models/MemberModel.php
Labels: bug

#5720 List the default template first in the template selection drop-down
  core-bundle/src/Twig/Finder/Finder.php
  core-bundle/tests/Twig/Finder/FinderTest.php
Labels: bug

#5716 Fix rendering article teasers when there is no text
  core-bundle/contao/templates/_new/content_element/teaser.html.twig
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/TeaserControllerTest.php
Labels: bug

#5725 Use the correct ID for URL parameters when saving and duplicating
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#5728 Handle inline styles in the HtmlAttributes class
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/String/HtmlAttributesTest.php
Labels: bug

#5730 Ignore empy layout selection
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#5733 Update the tools
  composer.json
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#5704 Do not require overwriting the console path
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/Util/ProcessUtilTest.php
  maker-bundle/README.md
  manager-bundle/config/services.yaml
  manager-bundle/skeleton/bin/console
  manager-bundle/skeleton/config/config.yaml
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/src/Command/InstallSkeletonCommand.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
  manager-bundle/tests/Command/InstallSkeletonCommandTest.php
Labels: bug

#5732 Do not overwrite the default vertical button alignment
  core-bundle/src/Resources/contao/themes/flexible/basic.css
  core-bundle/src/Resources/contao/themes/flexible/basic.min.css
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#5737 Update and run the tools
  core-bundle/src/EventListener/BackendRebuildCacheMessageListener.php
  core-bundle/src/EventListener/ExceptionConverterListener.php
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  maker-bundle/src/Reflection/MethodDefinition.php
  manager-bundle/src/Command/ContaoSetupCommand.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#5735 gsw_Hans_AT does not add native language suffix
  core-bundle/tests/Intl/LocalesTest.php
Labels: CI

#5746 Adjust the blocks in the table component template
  core-bundle/contao/templates/_new/component/_table.html.twig
Labels: bug

#5748 Preserve safe HTML in the Twig insert tag filters
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: bug
