Repository contao/contao, pull requests merged in 2023-03, with the labels that each got.

#5841 Backport 'Fix PHPUnit deprecation warnings'
  core-bundle/src/Resources/contao/library/Contao/Database/Result.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Security/Authentication/ContaoLoginAuthenticationListenerTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: CI

#5815 Make the captcha widget cacheable
  core-bundle/src/Controller/CaptchaController.php
  core-bundle/src/Resources/config/controller.yml
  core-bundle/src/Resources/contao/forms/FormCaptcha.php
  core-bundle/src/Resources/contao/templates/forms/form_captcha.html5
Labels: bug

#5842 Fix a PHP8 issue with the back end breadcrumb menu
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
Labels: bug

#5844 Update and run the tools
  core-bundle/src/Controller/CaptchaController.php
  core-bundle/src/Controller/FrontendModule/RootPageDependentModulesController.php
  core-bundle/src/Cron/CronJob.php
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Routing/Page/ContentCompositionInterface.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
  core-bundle/tests/Security/Authentication/Token/FrontendPreviewTokenTest.php
  package-lock.json
  package.json
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#5821 Remove tl_settings.doNotCollapse
  core-bundle/contao/dca/tl_settings.php
  core-bundle/contao/languages/en/tl_settings.xlf
Labels: bug

#5838 Add missing type hints to translation classes
  core-bundle/src/Translation/DataCollectorTranslator.php
  core-bundle/src/Translation/MessageCatalogue.php
  core-bundle/src/Translation/Translator.php
Labels: bug

#5843 Fix possible undefined headline data
  core-bundle/src/Controller/AbstractFragmentController.php
Labels: bug

#5850 Fix a possible CSRF cookie race condition
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
Labels: bug

#5840 Fix deleting multiple records
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#5819 Surround the `togglePassword` images with a button
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
Labels: bug

#5855 Add the `FigureBuilder::fromUrl()` method
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#5856 Add the `multiple` attribute to the list and table wizards
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#5857 Fix the split button alignment
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
Labels: bug

#5861 Split the CI files
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/pr.yml
  .github/workflows/schedule.yml
  .github/workflows/split.yml
Labels: CI

#5866 Split the CI files
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/pr.yml
  .github/workflows/schedule.yml
  .github/workflows/split.yml
Labels: CI

#5870 Explicitly set the legacy template in the TwoFactorController
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
Labels: bug

#5863 Correctly handle sub-subpalettes in editAll mode
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5788 Add the TokenDeauthenticatedListener
  core-bundle/config/listener.yaml
  core-bundle/src/EventListener/Security/TokenDeauthenticatedListener.php
  core-bundle/src/Repository/RememberMeRepository.php
  core-bundle/tests/EventListener/Security/TokenDeauthenticatedListenerTest.php
Labels: bug

#5868 Always redirect ajax requests when session expired
  core-bundle/src/Resources/public/mootao.js
  core-bundle/src/Resources/public/mootao.min.js
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/tests/Security/Authentication/AuthenticationEntryPointTest.php
Labels: bug

#5830 Handle invalid back end confirm requests
  core-bundle/src/Resources/contao/controllers/BackendConfirm.php
Labels: bug

#5820 Throw an exception if a model relation is incomplete
  core-bundle/src/Resources/contao/library/Contao/Model.php
Labels: bug

#5864 Fix subpalette toggling
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5877 Merge branch '4.13' into 5.1
  core-bundle/contao/classes/Ajax.php
  core-bundle/contao/drivers/DC_Table.php
Labels: release

#5878 Update and run the tools
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  yarn.lock
Labels: CI

#5879 Remove the `q` shortcut from `contao:crawl`
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/tests/Command/CrawlCommandTest.php
Labels: bug

#5887 Fix urlencoded paths in DC_Folder
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#5884 Prevent foreign key check errors when deleting a parent record with children
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5881 Remove the inconsistent form field wrapper
  core-bundle/contao/templates/member/member_default.html5
  core-bundle/contao/templates/modules/mod_changePassword.html5
  core-bundle/contao/templates/modules/mod_password.html5
Labels: bug

#5888 Remove the @internal hints at constructor level
  calendar-bundle/src/Picker/EventPickerProvider.php
  core-bundle/src/Cache/ContaoCacheClearer.php
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/Cors/WebsiteRootsConfigProvider.php
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  core-bundle/src/Fragment/FragmentHandler.php
  core-bundle/src/HttpKernel/ControllerResolver.php
  core-bundle/src/HttpKernel/ModelArgumentResolver.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/ImageSizes.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/Menu/BackendMenuBuilder.php
  core-bundle/src/Monolog/ContaoTableProcessor.php
  core-bundle/src/OptIn/OptIn.php
  core-bundle/src/Picker/ArticlePickerProvider.php
  core-bundle/src/Picker/FilePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Picker/PickerBuilder.php
  core-bundle/src/Routing/Candidates/LegacyCandidates.php
  core-bundle/src/Routing/Enhancer/InputEnhancer.php
  core-bundle/src/Routing/FrontendLoader.php
  core-bundle/src/Routing/ImagesLoader.php
  core-bundle/src/Routing/LegacyRouteProvider.php
  core-bundle/src/Routing/Matcher/LanguageFilter.php
  core-bundle/src/Routing/Matcher/LegacyMatcher.php
  core-bundle/src/Routing/Matcher/PublishedFilter.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/src/Routing/ScopeMatcher.php
  core-bundle/src/Routing/UrlGenerator.php
  core-bundle/src/Search/Indexer/DefaultIndexer.php
  core-bundle/src/Security/Authentication/AccessDecisionManager.php
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/src/Security/Authentication/Provider/AuthenticationProvider.php
  core-bundle/src/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServices.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/src/Security/Logout/LogoutHandler.php
  core-bundle/src/Security/Logout/LogoutSuccessHandler.php
  core-bundle/src/Security/TwoFactor/Provider.php
  core-bundle/src/Security/User/UserChecker.php
  core-bundle/src/Slug/Slug.php
  core-bundle/src/Slug/ValidCharacters.php
  core-bundle/src/Translation/Translator.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  installation-bundle/src/Database/Installer.php
  installation-bundle/src/InstallTool.php
  installation-bundle/src/InstallToolUser.php
  manager-bundle/src/Cache/BundleCacheClearer.php
  manager-bundle/src/Controller/DebugController.php
  manager-bundle/src/Routing/RouteLoader.php
  manager-bundle/src/Security/Logout/LogoutHandler.php
  manager-bundle/src/Twig/FileExtensionFilterIterator.php
  news-bundle/src/Picker/NewsPickerProvider.php
Labels: bug

#5717 Make the template selection translatable in the back end
  core-bundle/src/Translation/Translator.php
  core-bundle/src/Twig/Finder/Finder.php
  core-bundle/src/Twig/Finder/FinderFactory.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
  core-bundle/tests/Twig/Finder/FinderTest.php
Labels: feature

#5894 Try to fix the Codecov upload
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/schedule.yml
  .github/workflows/split.yml
Labels: bug, CI

#5892 Normalize the line endings in the file editor
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#5804 Add the missing data container permission checks
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
Labels: bug

#5895 Allow using basic entities in headlines
  calendar-bundle/contao/dca/tl_calendar.php
  core-bundle/contao/dca/tl_content.php
  faq-bundle/contao/dca/tl_faq.php
  news-bundle/contao/dca/tl_news.php
Labels: bug

#5900 Allow using basic entities in texts
  calendar-bundle/contao/dca/tl_calendar_events.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_form_field.php
  news-bundle/contao/dca/tl_news.php
Labels: bug

#5904 Update and run the tools
  calendar-bundle/src/EventListener/InsertTagsListener.php
  core-bundle/src/Filesystem/FilesystemItemIterator.php
  core-bundle/src/Image/Preview/PreviewFactory.php
  core-bundle/src/Translation/DataCollectorTranslator.php
  core-bundle/templates/Backend/be_route_conflicts.html.twig
  core-bundle/tests/Command/Backup/BackupListCommandTest.php
  core-bundle/tests/EventListener/DataContainer/BackendFavoritesListenerTest.php
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
  core-bundle/tests/Image/Studio/FigureBuilderStub.php
  core-bundle/tests/Image/Studio/ImageResultStub.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  faq-bundle/src/EventListener/InsertTagsListener.php
  news-bundle/src/EventListener/InsertTagsListener.php
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: CI

#5905 Get rid of deprecations as much as possible
  core-bundle/contao/library/Contao/Model.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Command/DebugPagesCommandTest.php
  core-bundle/tests/Contao/ModelTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Functional/app/config/config_test.yaml
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
Labels: CI

#5915 Fix the CI chain
  .github/workflows/ci.yml
Labels: CI

#5913 Fix a PHP 8 issue in the `mod_breadcrumb.html5` template
  core-bundle/src/Resources/contao/templates/modules/mod_breadcrumb.html5
Labels: bug

#5914 Regenerate the symlinks when moving or duplicating folders
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#5916 Filter non-image files in the ImagesController
  core-bundle/config/controller.yaml
  core-bundle/src/Controller/ContentElement/ImagesController.php
  core-bundle/tests/Controller/ContentElement/ImagesControllerTest.php
Labels: bug

#5919 Add a unit test for invalid files to the images controller
  core-bundle/tests/Controller/ContentElement/ImagesControllerTest.php
Labels: bug
