Repository contao/contao, pull requests merged in 2023-07, with the labels that each got.

#6177 Remove field permissions on favorites table
  core-bundle/contao/dca/tl_favorites.php
  core-bundle/src/Security/Voter/DataContainer/FavoritesVoter.php
Labels: bug

#6148 Correctly encode URLs in the sitemap
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: bug

#6188 Merge branch '4.13' into 5.1
  composer.json
  core-bundle/contao/library/Contao/Search.php
  core-bundle/contao/modules/ModuleSearch.php
  core-bundle/contao/widgets/Picker.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/Picker/TablePickerProvider.php
  core-bundle/tests/Contao/SearchTest.php
  manager-bundle/composer.json
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetDotEnvCommand.php
Labels: release

#6173 Increase Symfony filesystem dependency version
  composer.json
  manager-bundle/composer.json
Labels: bug

#6187 Make the template module more flexible
  core-bundle/src/Controller/FrontendModule/TemplateController.php
  core-bundle/src/Resources/contao/templates/modules/mod_template.html5
Labels: bug

#6153 Rotate the chevron icon instead of replacing it
  core-bundle/assets/scripts/core.js
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/Image.php
  core-bundle/contao/themes/flexible/backend.6b338b01.css
  core-bundle/contao/themes/flexible/backend.6b338b01.css.map
  core-bundle/contao/themes/flexible/backend.a17f1d3f.css
  core-bundle/contao/themes/flexible/backend.a17f1d3f.css.map
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/icons/chevron-right--dark.svg
  core-bundle/contao/themes/flexible/icons/chevron-right.svg
  core-bundle/contao/themes/flexible/icons/header--disabled.svg
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/main.css
  core-bundle/contao/widgets/CheckBox.php
  core-bundle/public/backend.291cbfb9.js
  core-bundle/public/backend.291cbfb9.js.map
  core-bundle/public/backend.ebe0b709.js
  core-bundle/public/backend.ebe0b709.js.map
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: feature

#6190 Update and run the tools
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  test-case/src/ContaoTestCase.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#6124 Implement visible root trails for DC_Folder
  core-bundle/contao/dca/tl_files.php
  core-bundle/contao/drivers/DC_Folder.php
Labels: feature, up for discussion

#6192 Update and run the tools
  core-bundle/tests/InsertTag/Flag/PhpFunctionFlagTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: CI

#6195 New insert tags system
  core-bundle/src/DependencyInjection/Attribute/AsBlockInsertTag.php
  core-bundle/src/DependencyInjection/Attribute/AsInsertTag.php
  core-bundle/src/DependencyInjection/Compiler/AddInsertTagsPass.php
  core-bundle/src/InsertTag/Flag/PhpFunctionFlag.php
  core-bundle/src/InsertTag/Flag/StringUtilFlag.php
  core-bundle/src/InsertTag/InsertTag.php
  core-bundle/src/InsertTag/InsertTagParameters.php
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/InsertTag/InsertTagSubscription.php
  core-bundle/tests/DependencyInjection/Compiler/AddInsertTagsPassTest.php
  core-bundle/tests/InsertTag/Flag/PhpFunctionFlagTest.php
Labels: feature

#6194 Improve caching of the "date" insert tag
  core-bundle/config/services.yaml
  core-bundle/src/InsertTag/Resolver/DateInsertTag.php
  core-bundle/tests/InsertTag/Resolver/DateInsertTagTest.php
  core-bundle/tests/String/HtmlDecoderTest.php
Labels: feature

#6178 Correctly encode URLs in the sitemap
  core-bundle/src/Event/SitemapEvent.php
  core-bundle/tests/Event/SitemapEventTest.php
Labels: bug

#6197 Handle empty label fields in the picker
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug

#6203 Revert 'Allow multiple label callbacks'
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_log.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_member_group.php
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/EventListener/DataContainerCallbackListener.php
Labels: bug

#6202 Correctly set the APP_SECRET environment variable in the manager plugin
  manager-bundle/src/ContaoManager/Plugin.php
Labels: bug

#6221 Improve UrlUtil::makeAbsolute()
  core-bundle/src/Util/UrlUtil.php
  core-bundle/tests/Util/UrlUtilTest.php
Labels: bug

#6217 Fix relative redirects
  core-bundle/src/Resources/contao/pages/PageRedirect.php
  core-bundle/src/Resources/contao/pages/PageRoot.php
Labels: bug

#6231 Fix ReflectionProperty::setValue() method signature
  core-bundle/tests/Contao/EnvironmentTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  test-case/src/ContaoTestCase.php
Labels: bug

#6222 Fix StringUtil::insertTagToSrc() for missing files
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug

#6229 Fix PHP8 issues in database installer
  core-bundle/src/Resources/contao/library/Contao/Database/Installer.php
Labels: bug

#6159 Include the category data in the FAQ list template
  faq-bundle/src/Resources/contao/modules/ModuleFaqList.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
Labels: bug

#5829 Make the RegisterFragmentType fragment type agnostic
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
Labels: bug

#6226 Replace the token in the storage for preview link authentication
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
Labels: bug

#5465 Add end-to-end tests with Cypress
  README.md
  cypress.config.dev.js
  tests/cypress/e2e/core-bundle/backend-login.cy.js
  tests/cypress/fixtures/app.json
  tests/cypress/fixtures/users/admin.json
  tests/cypress/support/commands.js
  tests/cypress/support/e2e.js
Labels: CI

#6237 Fix ReflectionProperty::setValue() method signature
  core-bundle/tests/Contao/EnvironmentTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  test-case/src/ContaoTestCase.php
Labels: CI

#6224 Allow to pass options to the Handorgel initializer
  core-bundle/contao/templates/js/js_accordion.html5
Labels: bug

#6196 Add more Cypress tests
  .github/workflows/schedule.yml
  .gitignore
  README.md
  composer.json
  cypress.config.dev.js
  manager-bundle/bin/contao-console
  package.json
  tests/cypress/e2e/core-bundle/backend-login.cy.js
  tests/cypress/fixtures/app.json
  tests/cypress/support/commands.js
  tests/cypress/support/e2e.js
  tools/cypress/composer.json
  tools/cypress/composer.lock
  tools/cypress/cypress.config.js
  tools/cypress/e2e/core-bundle/backend-login.cy.js
  tools/cypress/e2e/core-bundle/create-minimal-website.cy.js
  tools/cypress/fixtures/users/admin.json
  tools/cypress/support/commands.js
  tools/cypress/support/e2e.js
  tools/cypress/webspace/.env
  tools/cypress/webspace/composer.json
  yarn.lock
Labels: CI

#6241 Merge branch '4.13' into 5.1
  core-bundle/contao/library/Contao/Database/Installer.php
  core-bundle/contao/library/Contao/StringUtil.php
  core-bundle/contao/pages/PageRedirect.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/src/Util/UrlUtil.php
  core-bundle/tests/Contao/EnvironmentTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Util/UrlUtilTest.php
  faq-bundle/contao/modules/ModuleFaqList.php
  faq-bundle/contao/modules/ModuleFaqPage.php
  test-case/src/ContaoTestCase.php
Labels: release

#6238 Correctly generate the file tree for admin users
  core-bundle/contao/drivers/DC_Folder.php
Labels: bug

#6244 Fix the "folder ID … is not mounted" error
  core-bundle/contao/drivers/DC_Folder.php
Labels: bug

#6234 Fix the variable naming in the DCA schema provider
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: bug

#6240 Do not set the unsubscribe header for test newsletters
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#6225 Skip type error when trying to assign DCA label to string
  core-bundle/contao/library/Contao/DcaLoader.php
Labels: bug

#6230 Set the correct type on model ID
  core-bundle/contao/library/Contao/Model.php
Labels: bug

#6183 Unset PID for copy button callbacks
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
Labels: bug

#6210 Decode HTML entities in feed item titles
  news-bundle/config/services.yaml
  news-bundle/src/Controller/Page/NewsFeedController.php
  news-bundle/src/EventListener/NewsFeedListener.php
  news-bundle/tests/Controller/Page/NewsFeedControllerTest.php
  news-bundle/tests/EventListener/NewsFeedListenerTest.php
Labels: bug

#6250 Correctly show options with the same label in the filter menu
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#6127 Recursively implode fields when generating record labels
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#6252 Set the correct PIDs when copying folders recursively
  core-bundle/src/Resources/contao/library/Contao/Dbafs.php
  core-bundle/src/Resources/contao/models/FilesModel.php
Labels: bug

#6201 Favorites voter must not grant access
  core-bundle/src/Security/Voter/DataContainer/FavoritesVoter.php
  core-bundle/tests/Security/Voter/DataContainer/FavoritesVoterTest.php
Labels: bug

#6254 Ensure the PID in the favorites listener is an integer
  core-bundle/src/EventListener/Menu/BackendFavoritesListener.php
Labels: bug

#6246 Manage the Cypress tests entirely with Yarn
  .github/workflows/schedule.yml
  .gitignore
  README.md
  cypress.config.js
  cypress/e2e/core-bundle/backend-login.cy.js
  cypress/e2e/core-bundle/create-minimal-website.cy.js
  cypress/fixtures/users/admin.json
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/webspace/.env
  cypress/webspace/composer.json
  package.json
  tools/cypress/composer.json
  tools/cypress/composer.lock
  tools/cypress/cypress.config.js
  tools/cypress/e2e/core-bundle/backend-login.cy.js
  tools/cypress/e2e/core-bundle/create-minimal-website.cy.js
  tools/cypress/support/commands.js
  tools/cypress/support/e2e.js
  yarn.lock
Labels: CI

#6255 Run the scheduled jobs with every branch
  .github/workflows/cypress.yml
  .github/workflows/isolated-tests.yml
  .github/workflows/schedule.yml
  .github/workflows/windows.yml
Labels: CI

#6258 Merge branch '4.13' into 5.1
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/Dbafs.php
  core-bundle/contao/models/FilesModel.php
  core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php
  newsletter-bundle/contao/classes/Newsletter.php
Labels: release

#6253 Correctly set the link title in the hyperlink controller
  core-bundle/src/Controller/ContentElement/HyperlinkController.php
  core-bundle/tests/Controller/ContentElement/HyperlinkControllerTest.php
Labels: bug

#6251 Handle insert tags in news and event URLs
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  news-bundle/src/Resources/contao/modules/ModuleNewsReader.php
Labels: bug, up for discussion
