Repository contao/contao, pull requests merged in 2023-09, with the labels that each got.

#6386 Deprecate the `System::setCookie()` method
  core-bundle/contao/library/Contao/System.php
Labels: feature

#6390 Do not allow route parameters for redirect pages
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
Labels: bug

#6393 Generate the file tree preview images with a 1x, 2x source set
  core-bundle/src/Resources/contao/widgets/FileTree.php
Labels: bug

#6391 Do not forward pages with parameters by default
  core-bundle/src/Migration/Version413/AlwaysForwardMigration.php
  core-bundle/src/Resources/config/migrations.yml
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/languages/en/tl_page.xlf
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Routing/Page/PageRegistry.php
Labels: bug

#6395 Add the missing page registry tests
  core-bundle/tests/Routing/Page/PageRegistryTest.php
Labels: CI

#6396 Merge branch '4.13' into 5.2
  core-bundle/config/migrations.yaml
  core-bundle/contao/classes/BackendTemplate.php
  core-bundle/contao/controllers/BackendHelp.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/languages/en/tl_page.xlf
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/widgets/FileTree.php
  core-bundle/src/Migration/Version502/AlwaysForwardMigration.php
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
Labels: release

#6398 Update and run the tools
  calendar-bundle/tests/EventListener/SitemapListenerTest.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/DependencyInjection/Compiler/AddInsertTagsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/DependencyInjection/Compiler/RegisterPagesPass.php
  core-bundle/src/EventListener/DataContainer/PageRoutingListener.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/FileDownloadHelper.php
  core-bundle/src/Framework/Adapter.php
  core-bundle/src/Image/ImageSizes.php
  core-bundle/src/Picker/AbstractPickerProvider.php
  core-bundle/src/Security/TwoFactor/BackupCodeManager.php
  core-bundle/src/Security/TwoFactor/Provider.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/src/Twig/Interop/PhpTemplateProxyNode.php
  core-bundle/tests/Controller/ContentElement/DownloadsControllerTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddCronJobsPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/DataContainerCallbackPassTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterHookListenersPassTest.php
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
  core-bundle/tests/EventListener/PageAccessListenerTest.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Intl/LocalesTest.php
  core-bundle/tests/Routing/Enhancer/InputEnhancerTest.php
  core-bundle/tests/Routing/Page/PageRouteTest.php
  core-bundle/tests/Routing/Route404ProviderTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
  faq-bundle/tests/EventListener/SitemapListenerTest.php
  maker-bundle/tests/Reflection/ImportExtractorTest.php
  news-bundle/src/Migration/FeedMigration.php
  news-bundle/tests/Controller/Page/NewsFeedControllerTest.php
  news-bundle/tests/EventListener/NewsFeedListenerTest.php
  news-bundle/tests/EventListener/SitemapListenerTest.php
  news-bundle/tests/Migration/FeedMigrationTest.php
  newsletter-bundle/tests/EventListener/SitemapListenerTest.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/rector/src/SimplifyObjectOrNullCheckRector.php
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#6399 Only notify about rejected recipients if there are any
  newsletter-bundle/contao/classes/Newsletter.php
Labels: bug

#6401 Create one `<script>` block per JSON-LD context
  core-bundle/src/Routing/ResponseContext/JsonLd/JsonLdManager.php
  core-bundle/tests/Routing/ResponseContext/JsonLd/JsonLdManagerTest.php
Labels: bug

#6407 Fix the LintServiceIdsCommand
  .gitignore
  core-bundle/config/listener.yaml
  core-bundle/config/migrations.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/languages/de/tl_style.xlf
  core-bundle/contao/languages/de/tl_style_sheet.xlf
  news-bundle/contao/languages/en/tl_page.xlf
  phpstan.neon
  tools/ecs/config/default.php
  tools/rector/config/rector.php
  tools/service-linter/src/LintServiceIdsCommand.php
Labels: CI

#6410 Update the tools
  calendar-bundle/src/Resources/contao/languages/en/tl_module.xlf
  tools/ecs/composer.lock
  tools/ecs/config/default.php
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/bin/lint-service-ids
  tools/service-linter/composer.json
  tools/service-linter/composer.lock
  tools/service-linter/src/LintServiceIdsCommand.php
Labels: CI

#6411 Update and run the tools
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/EventListener/UnwrapTwigExceptionListener.php
  tools/ecs/composer.json
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
  tools/service-linter/src/LintServiceIdsCommand.php
Labels: CI

#6413 Use contao/rector instead of rector/rector
  tools/rector/composer.json
  tools/rector/composer.lock
  tools/rector/config/phpstan.neon
  tools/rector/config/rector.php
  tools/rector/src/ReturnTypeVisitor.php
  tools/rector/src/SimplifyObjectOrNullCheckRector.php
Labels: CI
