Repository contao/contao, pull requests merged in 2023-05, with the labels that each got.

#6002 Fix a type error in the meta wizard
  core-bundle/src/Resources/contao/widgets/MetaWizard.php
Labels: bug

#6000 Add a double encoding setting to the HtmlAttributes class
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/String/HtmlAttributesTest.php
Labels: bug

#6003 Add a method to retrieve the original route path
  core-bundle/src/Routing/Page/PageRoute.php
Labels: bug

#6005 Merge branch '4.13' into 5.1
  core-bundle/contao/widgets/MetaWizard.php
  core-bundle/src/Routing/Page/PageRoute.php
Labels: release

#6007 Merge branch '5.1' into 5.x
  core-bundle/config/listener.yaml
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/templates/backend/be_popup.html5
  core-bundle/contao/templates/backend/be_purge_data.html5
  core-bundle/contao/themes/flexible/backend.184f7434.css
  core-bundle/contao/themes/flexible/backend.bd360e27.css
  core-bundle/contao/themes/flexible/backend.bd360e27.css.map
  core-bundle/contao/themes/flexible/confirm.b5e263dd.css
  core-bundle/contao/themes/flexible/confirm.e9cc363b.css
  core-bundle/contao/themes/flexible/confirm.e9cc363b.css.map
  core-bundle/contao/themes/flexible/conflict.069ac036.css
  core-bundle/contao/themes/flexible/conflict.069ac036.css.map
  core-bundle/contao/themes/flexible/conflict.5a877f67.css
  core-bundle/contao/themes/flexible/diff.4509668a.css
  core-bundle/contao/themes/flexible/diff.8d2de1ec.css
  core-bundle/contao/themes/flexible/diff.8d2de1ec.css.map
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/help.c43f24b1.css
  core-bundle/contao/themes/flexible/help.ccc7e7c3.css
  core-bundle/contao/themes/flexible/help.ccc7e7c3.css.map
  core-bundle/contao/themes/flexible/login.af1352d9.css
  core-bundle/contao/themes/flexible/login.f1c29e7f.css
  core-bundle/contao/themes/flexible/login.f1c29e7f.css.map
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/popup.48eb7606.css
  core-bundle/contao/themes/flexible/popup.48eb7606.css.map
  core-bundle/contao/themes/flexible/popup.b15fbd55.css
  core-bundle/contao/themes/flexible/styles/basic.css
  core-bundle/contao/themes/flexible/styles/main.css
  core-bundle/contao/themes/flexible/styles/popup.css
  core-bundle/contao/widgets/MetaWizard.php
  core-bundle/src/EventListener/UnwrapTwigExceptionListener.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/EventListener/UnwrapTwigExceptionListenerTest.php
  core-bundle/tests/String/HtmlAttributesTest.php
Labels: release

#5989 Hide fields that are not to be displayed in the undo details
  core-bundle/contao/dca/tl_undo.php
Labels: bug

#5979 Check for the `debug.stopwatch` service
  core-bundle/src/Resources/contao/elements/ContentModule.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
Labels: bug

#6009 Merge branch '4.9' into 4.13
  core-bundle/src/EventListener/InsecureInstallationListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/InsecureInstallationListenerTest.php
Labels: release

#6010 Merge branch '4.13' into 5.1
  core-bundle/config/listener.yaml
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/src/EventListener/InsecureInstallationListener.php
  core-bundle/tests/EventListener/InsecureInstallationListenerTest.php
Labels: release

#5966 Ensure that root pages are always shown in the correct order
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#6008 Add the `USER_CAN_ACCESS_PAGE` permission
  core-bundle/contao/classes/BackendUser.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/tests/Security/Voter/BackendAccessVoterTest.php
Labels: feature

#6006 Prepend the base path to the Contao Manager URL in the back end
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
Labels: bug

#5998 Fix the list and table wizards in news and events
  calendar-bundle/contao/config/config.php
  news-bundle/contao/config/config.php
Labels: bug

#6014 Fix backtracking in insert tags regular expressions
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#5930 Correctly detect empty HTML when generating DCA labels
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#5808 Render modules and elements from templates
  core-bundle/config/services.yaml
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/FragmentRuntime.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Runtime/FragmentRuntimeTest.php
Labels: feature

#6040 Add missing space after page icon
  core-bundle/src/Resources/contao/classes/Backend.php
Labels: bug

#6047 Pass the ID to `getCurrentRecord()` in "override all" mode
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#6041 Fix a PHP 8 error if the label insert tag does not match
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#6038 Load the page details before manipulating root page data
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
Labels: bug

#6051 Run the code inspector
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Fragment/FragmentHandler.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/EventListener/Security/TwoFactorFrontendListenerTest.php
Labels: CI

#6052 Fix a PHP8 warning in the PageSelector class
  core-bundle/src/Resources/contao/widgets/PageSelector.php
Labels: bug

#6062 Do not mark as copy more than once
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#6063 Do not filter folders named `0` in the file manager
  core-bundle/src/Resources/contao/dca/tl_files.php
  core-bundle/src/Resources/contao/library/Contao/Dbafs.php
Labels: bug

#5985 Support readonly in TinyMCE and ACE editor
  core-bundle/src/Resources/contao/classes/DataContainer.php
  core-bundle/src/Resources/contao/templates/backend/be_ace.html5
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
Labels: bug

#6071 Make the support link language-agnostic
  README.md
  calendar-bundle/README.md
  comments-bundle/README.md
  core-bundle/README.md
  core-bundle/src/Resources/views/Collector/contao.html.twig
  faq-bundle/README.md
  installation-bundle/README.md
  listing-bundle/README.md
  maker-bundle/README.md
  manager-bundle/README.md
  news-bundle/README.md
  newsletter-bundle/README.md
Labels: bug

#6075 Fix root page dependent module when there is no module for a root page
  core-bundle/src/Controller/FrontendModule/RootPageDependentModulesController.php
Labels: bug

#6077 Also handle transport exceptions when sending newsletters
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#6079 Upgrade and run the tools
  core-bundle/src/Mailer/ContaoMailer.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#6080 Fix randomImage caption bug
  core-bundle/src/Resources/contao/modules/ModuleRandomImage.php
Labels: bug

#6064 Merge the "overwrite metadata" with the default metadata
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Resources/contao/elements/ContentAccordion.php
  core-bundle/src/Resources/contao/elements/ContentHyperlink.php
  core-bundle/src/Resources/contao/elements/ContentImage.php
  core-bundle/src/Resources/contao/elements/ContentText.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqReader.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#6046 Improve the main navigation hover style
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
Labels: bug

#6084 Compare start and stop dates as numbers instead of strings
  calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Resources/contao/classes/BackendUser.php
  core-bundle/src/Resources/contao/classes/Crawl.php
  core-bundle/src/Resources/contao/classes/Messages.php
  core-bundle/src/Resources/contao/models/ArticleModel.php
  core-bundle/src/Resources/contao/models/ContentModel.php
  core-bundle/src/Resources/contao/models/MemberGroupModel.php
  core-bundle/src/Resources/contao/models/MemberModel.php
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/src/Resources/contao/modules/Module.php
  news-bundle/src/Resources/contao/models/NewsModel.php
  news-bundle/src/Resources/contao/modules/ModuleNewsMenu.php
Labels: bug

#6087 Make named parameter matching in routing non-possessive
  core-bundle/src/Routing/Page/PageRouteCompiler.php
Labels: bug

#5610 Add a an "edit image size" popup link
  core-bundle/assets/controllers/image-size-controller.js
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/themes/flexible/backend.0c374b6e.css
  core-bundle/contao/themes/flexible/backend.0c374b6e.css.map
  core-bundle/contao/themes/flexible/backend.6de2ed1d.css
  core-bundle/contao/themes/flexible/backend.6de2ed1d.css.map
  core-bundle/contao/themes/flexible/confirm.db87f830.css
  core-bundle/contao/themes/flexible/confirm.db87f830.css.map
  core-bundle/contao/themes/flexible/confirm.df2be012.css
  core-bundle/contao/themes/flexible/confirm.df2be012.css.map
  core-bundle/contao/themes/flexible/conflict.b505718e.css
  core-bundle/contao/themes/flexible/conflict.b505718e.css.map
  core-bundle/contao/themes/flexible/conflict.bdd0ad73.css
  core-bundle/contao/themes/flexible/conflict.bdd0ad73.css.map
  core-bundle/contao/themes/flexible/diff.71a07c96.css
  core-bundle/contao/themes/flexible/diff.71a07c96.css.map
  core-bundle/contao/themes/flexible/diff.8458d88d.css
  core-bundle/contao/themes/flexible/diff.8458d88d.css.map
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/help.51035033.css
  core-bundle/contao/themes/flexible/help.51035033.css.map
  core-bundle/contao/themes/flexible/help.9e70b126.css
  core-bundle/contao/themes/flexible/help.9e70b126.css.map
  core-bundle/contao/themes/flexible/login.074d5c37.css
  core-bundle/contao/themes/flexible/login.074d5c37.css.map
  core-bundle/contao/themes/flexible/login.54c4a33d.css
  core-bundle/contao/themes/flexible/login.54c4a33d.css.map
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/popup.56518a36.css
  core-bundle/contao/themes/flexible/popup.56518a36.css.map
  core-bundle/contao/themes/flexible/popup.915ea82c.css
  core-bundle/contao/themes/flexible/popup.915ea82c.css.map
  core-bundle/contao/themes/flexible/styles/basic.css
  core-bundle/contao/themes/flexible/styles/main.css
  core-bundle/contao/widgets/ImageSize.php
  core-bundle/public/backend.53a22055.js
  core-bundle/public/backend.53a22055.js.map
  core-bundle/public/backend.5859b9cf.js
  core-bundle/public/backend.5859b9cf.js.map
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: feature

#6092 Ignore Doctrine class in global state watcher
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
Labels: CI

#6096 Fix the CI chain
  core-bundle/tests/Functional/app/config/config_test.yaml
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
  phpstan.neon
Labels: CI

#5794 Always show the 404 page
  core-bundle/config/controller.yaml
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Controller/RobotsTxtController.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/src/Routing/Enhancer/InputEnhancer.php
  core-bundle/src/Routing/PageFinder.php
  core-bundle/tests/Controller/FaviconControllerTest.php
  core-bundle/tests/Controller/RobotsTxtControllerTest.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  core-bundle/tests/Routing/Enhancer/InputEnhancerTest.php
  core-bundle/tests/Routing/PageFinderTest.php
Labels: bug

#6099 Update the Rector configuration
  core-bundle/src/Config/Loader/XliffFileLoader.php
  core-bundle/src/EventListener/UserSessionListener.php
  core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/ResponseContext/AddTokenParser.php
  core-bundle/tests/Fragment/FragmentHandlerTest.php
  maker-bundle/src/Maker/AbstractFragmentMaker.php
  maker-bundle/src/Maker/MakeDcaCallback.php
  maker-bundle/src/Maker/MakeHook.php
  test-case/src/ContaoTestCase.php
  tools/rector/config/rector.php
Labels: CI

#6097 Fix PHPStan generics
  core-bundle/tests/Fragment/FragmentHandlerTest.php
  phpstan.neon
Labels: CI
