Repository contao/contao, pull requests merged in 2023-12, with the labels that each got.

#6598 Do not smooth-scroll on devices with reduced motion
  core-bundle/contao/themes/flexible/backend.cb9fdcd6.css
  core-bundle/contao/themes/flexible/backend.cb9fdcd6.css.map
  core-bundle/contao/themes/flexible/backend.fb1eae6c.css
  core-bundle/contao/themes/flexible/backend.fb1eae6c.css.map
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/main.css
Labels: bug

#6590 Move the `ModelMetadataTrait` to the correct namespace
  calendar-bundle/contao/models/CalendarEventsModel.php
  core-bundle/contao/library/Contao/Model/MetadataTrait.php
  core-bundle/contao/models/ContentModel.php
  core-bundle/src/File/ModelMetadataTrait.php
  faq-bundle/contao/models/FaqModel.php
  news-bundle/contao/models/NewsModel.php
  tools/phpstan/config/contao.neon
Labels: bug

#6602 Update the insert tags doc link
  core-bundle/src/Resources/contao/languages/en/explain.xlf
Labels: bug

#6595 Deprecate the `PageModel::getPreviewUrl()` method
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/models/PageModel.php
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
Labels: bug

#6593 Add a data container setting to hide the `orderBy` column in the back end listing
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#6603 Unify the deprecation messages
  DEPRECATED.md
  comments-bundle/contao/classes/Comments.php
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/library/Contao/Automator.php
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/library/Contao/Database.php
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/contao/library/Contao/Environment.php
  core-bundle/contao/library/Contao/Input.php
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/library/Contao/Model.php
  core-bundle/contao/library/Contao/System.php
  core-bundle/contao/models/PageModel.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
  core-bundle/src/Routing/PageUrlGenerator.php
  core-bundle/src/Twig/Extension/DeprecationsNodeVisitor.php
  core-bundle/src/Twig/Runtime/FigureRuntime.php
  manager-bundle/src/Api/ManagerConfig.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/src/Routing/RouteLoader.php
  newsletter-bundle/contao/classes/Newsletter.php
Labels: feature

#6614 Sort the tables in the database backup
  core-bundle/src/Doctrine/Backup/Dumper.php
  core-bundle/tests/Doctrine/Backup/DumperTest.php
Labels: feature

#6571 Fix relative asset paths in feeds
  calendar-bundle/src/Resources/contao/classes/Calendar.php
  news-bundle/src/Resources/contao/classes/News.php
Labels: bug

#6625 Do not show the end time of open-ended events
  calendar-bundle/src/Resources/contao/classes/Events.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
Labels: bug

#6624 Remove `UriSigner` ignore for PHPStan
  phpstan.neon
Labels: CI

#6623 Do no process the form data if there are errors
  core-bundle/contao/forms/Form.php
Labels: bug

#6549 Update page registry when generating multiple page aliases
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#6521 Nested content elements
  core-bundle/config/services.yaml
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/elements/ContentProxy.php
  core-bundle/contao/languages/en/tl_content.xlf
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/src/Controller/ContentElement/AbstractContentElementController.php
  core-bundle/src/DependencyInjection/Attribute/AsContentElement.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/Fragment/FragmentCompositor.php
  core-bundle/src/Fragment/Reference/ContentElementReference.php
  core-bundle/src/Twig/Runtime/FragmentRuntime.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Twig/Runtime/FragmentRuntimeTest.php
  test-case/src/ContaoTestCase.php
Labels: feature, up for discussion

#6627 Fix favorites voter not voting on current record
  core-bundle/config/services.yaml
  core-bundle/src/Security/Voter/DataContainer/FavoritesVoter.php
  core-bundle/tests/Security/Voter/DataContainer/FavoritesVoterTest.php
Labels: bug

#6628 Fix DCA voters not checking module and parent update access
  calendar-bundle/src/Security/ContaoCalendarPermissions.php
  calendar-bundle/src/Security/Voter/CalendarAccessVoter.php
  calendar-bundle/src/Security/Voter/CalendarEventsAccessVoter.php
  calendar-bundle/tests/Security/Voter/CalendarAccessVoterTest.php
  calendar-bundle/tests/Security/Voter/CalendarEventsAccessVoterTest.php
  core-bundle/src/Security/Voter/DataContainer/FormAccessVoter.php
  core-bundle/src/Security/Voter/DataContainer/FormFieldAccessVoter.php
  core-bundle/src/Security/Voter/DataContainer/ParentAccessTrait.php
  core-bundle/tests/Security/Voter/DataContainer/FormAccessVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/FormFieldAccessVoterTest.php
  faq-bundle/src/Security/ContaoFaqPermissions.php
  faq-bundle/src/Security/Voter/FaqAccessVoter.php
  faq-bundle/src/Security/Voter/FaqCategoryAccessVoter.php
  faq-bundle/tests/Security/Voter/FaqAccessVoterTest.php
  faq-bundle/tests/Security/Voter/FaqCategoryAccessVoterTest.php
  news-bundle/src/Security/ContaoNewsPermissions.php
  news-bundle/src/Security/Voter/NewsAccessVoter.php
  news-bundle/src/Security/Voter/NewsArchiveAccessVoter.php
  news-bundle/tests/Security/Voter/NewsAccessVoterTest.php
  news-bundle/tests/Security/Voter/NewsArchiveAccessVoterTest.php
  newsletter-bundle/src/Security/ContaoNewsletterPermissions.php
  newsletter-bundle/src/Security/Voter/NewsletterAccessVoter.php
  newsletter-bundle/src/Security/Voter/NewsletterChannelAccessVoter.php
  newsletter-bundle/tests/Security/Voter/NewsletterAccessVoterTest.php
  newsletter-bundle/tests/Security/Voter/NewsletterChannelAccessVoterTest.php
Labels: bug

#6632 Update and run the tools
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/phpstan/config/contao.neon
  tools/rector/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#6621 Add example content to .env
  manager-bundle/src/Command/ContaoSetupCommand.php
Labels: bug

#6634 Fix the unit tests
  core-bundle/contao/templates/twig/content_element/_base.html.twig
  core-bundle/contao/templates/twig/content_element/code.html.twig
  core-bundle/tests/Controller/ContentElement/CodeControllerTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
Labels: CI

#6620 Rename "childs" to "children"
  core-bundle/assets/scripts/core.js
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/languages/en/tl_page.xlf
  core-bundle/contao/library/Contao/Database.php
  core-bundle/contao/themes/flexible/icons/copychildren--dark.svg
  core-bundle/contao/themes/flexible/icons/copychildren--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/copychildren--disabled.svg
  core-bundle/contao/themes/flexible/icons/copychildren.svg
  core-bundle/public/backend.fc2e9b5c.js.map
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
Labels: feature

#6553 Automatically enable the Strict Transport Security (HSTS) header
  core-bundle/config/controller.yaml
  core-bundle/config/listener.yaml
  core-bundle/src/Controller/RedirectController.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/TransportSecurityHeaderListener.php
  core-bundle/src/Routing/Matcher/UrlMatcher.php
  core-bundle/tests/Controller/RedirectControllerTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/TransportSecurityHeaderListenerTest.php
Labels: feature

#6636 Vote on the current token in the voters
  calendar-bundle/config/services.yaml
  calendar-bundle/src/Security/Voter/CalendarAccessVoter.php
  calendar-bundle/src/Security/Voter/CalendarEventsAccessVoter.php
  calendar-bundle/tests/Security/Voter/CalendarAccessVoterTest.php
  calendar-bundle/tests/Security/Voter/CalendarEventsAccessVoterTest.php
  core-bundle/config/services.yaml
  core-bundle/src/Security/Voter/DataContainer/AbstractDataContainerVoter.php
  core-bundle/src/Security/Voter/DataContainer/FavoritesVoter.php
  core-bundle/src/Security/Voter/DataContainer/FormAccessVoter.php
  core-bundle/src/Security/Voter/DataContainer/FormFieldAccessVoter.php
  core-bundle/src/Security/Voter/DataContainer/ParentAccessTrait.php
  core-bundle/src/Security/Voter/DataContainer/TableAccessVoter.php
  core-bundle/tests/Security/Voter/DataContainer/FavoritesVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/FormAccessVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/FormFieldAccessVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/TableAccessVoterTest.php
  faq-bundle/config/services.yaml
  faq-bundle/src/Security/Voter/FaqAccessVoter.php
  faq-bundle/src/Security/Voter/FaqCategoryAccessVoter.php
  faq-bundle/tests/Security/Voter/FaqAccessVoterTest.php
  faq-bundle/tests/Security/Voter/FaqCategoryAccessVoterTest.php
  news-bundle/config/services.yaml
  news-bundle/src/Security/Voter/NewsAccessVoter.php
  news-bundle/src/Security/Voter/NewsArchiveAccessVoter.php
  news-bundle/tests/Security/Voter/NewsAccessVoterTest.php
  news-bundle/tests/Security/Voter/NewsArchiveAccessVoterTest.php
  newsletter-bundle/config/services.yaml
  newsletter-bundle/src/Security/Voter/NewsletterAccessVoter.php
  newsletter-bundle/src/Security/Voter/NewsletterChannelAccessVoter.php
  newsletter-bundle/tests/Security/Voter/NewsletterAccessVoterTest.php
  newsletter-bundle/tests/Security/Voter/NewsletterChannelAccessVoterTest.php
Labels: bug

#6641 Fix missing `ptabe` for `saveNcreate` and `saveNduplicate`
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#6638 Add the onpalette_callback
  core-bundle/contao/drivers/DC_File.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
Labels: feature

#6645 Move ptable logic from tl_content to DC_Table
  calendar-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/drivers/DC_Table.php
  news-bundle/contao/dca/tl_content.php
Labels: bug

#6643 Add a voter for tl_newsletter_recipients
  newsletter-bundle/config/services.yaml
  newsletter-bundle/contao/dca/tl_newsletter_recipients.php
  newsletter-bundle/src/Security/Voter/NewsletterRecipientsAccessVoter.php
  newsletter-bundle/tests/Security/Voter/NewsletterRecipientsAccessVoterTest.php
Labels: feature

#6644 Correctly check for theme export permissions
  core-bundle/src/Resources/contao/classes/Theme.php
  core-bundle/src/Resources/contao/dca/tl_theme.php
Labels: bug

#6615 Automatic login for cross-domain preview links
  core-bundle/README.md
  core-bundle/config/controller.yaml
  core-bundle/config/services.yaml
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/tests/Controller/BackendPreviewControllerTest.php
  core-bundle/tests/Functional/app/config/security.yaml
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  manager-bundle/skeleton/config/security.yaml
Labels: feature

#6648 Add a modern accordion element
  core-bundle/config/controller.yaml
  core-bundle/config/listener.yaml
  core-bundle/contao/config/config.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_content.xlf
  core-bundle/contao/models/ContentModel.php
  core-bundle/contao/templates/twig/content_element/_base.html.twig
  core-bundle/contao/templates/twig/content_element/accordion.html.twig
  core-bundle/contao/templates/twig/content_element/element_group.html.twig
  core-bundle/contao/templates/twig/frontend_module/_base.html.twig
  core-bundle/src/Controller/ContentElement/AccordionController.php
  core-bundle/src/Controller/ContentElement/ElementGroupController.php
  core-bundle/src/EventListener/DataContainer/AccordionListener.php
  core-bundle/tests/Controller/ContentElement/AccordionControllerTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/ElementGroupTest.php
  core-bundle/tests/EventListener/DataContainer/AccordionListenerTest.php
Labels: feature

#6651 Do not load style sheets lazily by default
  core-bundle/contao/templates/twig/component/_stylesheet.html.twig
  core-bundle/tests/Controller/ContentElement/CodeControllerTest.php
Labels: feature

#6516 Implement worker supervision
  composer.json
  core-bundle/composer.json
  core-bundle/config/commands.yaml
  core-bundle/config/services.yaml
  core-bundle/src/Command/SuperviseWorkersCommand.php
  core-bundle/src/Cron/MessengerCron.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/Command/SuperviseWorkersCommandTest.php
  core-bundle/tests/Cron/MessengerCronTest.php
Labels: feature

#6659 Fix toggle operation parameter check
  core-bundle/contao/classes/DataContainer.php
Labels: bug

#6668 Sync the logic to generate multiple aliases
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_page.php
Labels: feature

#6658 Fix clipboard permission checks
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#6671 Merge branch '5.2' into 5.x
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/forms/Form.php
  core-bundle/contao/languages/en/explain.xlf
Labels: release

#6665 Only check the first record to be restored
  core-bundle/src/EventListener/DataContainer/Undo/UndoOperationListener.php
  core-bundle/tests/EventListener/DataContainer/Undo/UndoOperationListenerTest.php
Labels: bug

#6670 Fetch visible root trail record from database
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#6669 Use the `attributes_callback` to make the logout redirect mandatory
  core-bundle/config/listener.yaml
  core-bundle/contao/dca/tl_page.php
  core-bundle/src/EventListener/DataContainer/LogoutPageRedirectListener.php
  core-bundle/tests/EventListener/DataContainer/LogoutPageRedirectListenerTest.php
Labels: feature

#6673 Properly name the worker supervision cron
  core-bundle/config/services.yaml
  core-bundle/src/Cron/SuperviseWorkersCron.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/Cron/SuperviseWorkersCronTest.php
Labels: feature

#6626 Add a modern content slider element
  composer.json
  core-bundle/composer.json
  core-bundle/config/controller.yaml
  core-bundle/contao/config/config.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/templates/twig/content_element/accordion.html.twig
  core-bundle/contao/templates/twig/content_element/swiper.html.twig
  core-bundle/src/Controller/ContentElement/SwiperController.php
  core-bundle/tests/Controller/ContentElement/AccordionControllerTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/ElementGroupTest.php
  core-bundle/tests/Controller/ContentElement/SwiperControllerTest.php
Labels: feature

#6676 Use the `_attributes` suffix in the accordion template
  core-bundle/contao/templates/twig/content_element/accordion.html.twig
Labels: bug
