Repository contao/contao, pull requests merged in 2023-02, with the labels that each got.

#5743 Render HTML in the table and list elements again
  core-bundle/contao/templates/_new/component/_table.html.twig
  core-bundle/contao/templates/_new/content_element/list.html.twig
  core-bundle/contao/templates/_new/content_element/table.html.twig
  core-bundle/tests/Controller/ContentElement/ListControllerTest.php
  core-bundle/tests/Controller/ContentElement/TableControllerTest.php
Labels: bug

#5747 Prevent "array to string conversion" errors when migrating basic entities
  core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php
Labels: bug

#5723 Validate the given month or day in the calendar module
  calendar-bundle/src/Resources/contao/modules/ModuleCalendar.php
Labels: bug

#5756 Fix "variable must be of type array, null given"
  core-bundle/src/Resources/contao/library/Contao/DcaLoader.php
Labels: bug

#5741 Fix reordering trees when the PID is null
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5696 Fix installer issue if SQL field has no precision
  core-bundle/src/Resources/contao/library/Contao/Database/Installer.php
Labels: bug

#5544 Merge CSS classes in the "root page dependent modules" module
  core-bundle/src/Controller/FrontendModule/RootPageDependentModulesController.php
  core-bundle/tests/Controller/FrontendModule/RootPageDependentModulesControllerTest.php
Labels: bug

#5740 Correctly handle numeric paths (part 2)
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/tests/Functional/DbafsTest.php
Labels: bug

#5753 Always set `currentRecord` when initializing widgets
  core-bundle/src/Resources/contao/controllers/BackendPassword.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
Labels: bug

#5757 Merge branch '4.13' into 5.0
  calendar-bundle/contao/modules/ModuleCalendar.php
  composer.json
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/controllers/BackendPassword.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/Database/Installer.php
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/ModuleChangePassword.php
  core-bundle/contao/modules/ModuleCloseAccount.php
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/src/Controller/FrontendModule/RootPageDependentModulesController.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/tests/Controller/FrontendModule/RootPageDependentModulesControllerTest.php
  core-bundle/tests/Functional/DbafsTest.php
Labels: release

#5758 Merge branch '5.0' into 5.1
  calendar-bundle/contao/modules/ModuleCalendar.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/controllers/BackendPassword.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/Database/Installer.php
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/ModuleChangePassword.php
  core-bundle/contao/modules/ModuleCloseAccount.php
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/templates/_new/component/_table.html.twig
  core-bundle/contao/templates/_new/content_element/list.html.twig
  core-bundle/contao/templates/_new/content_element/table.html.twig
  core-bundle/contao/themes/flexible/basic.css
  core-bundle/contao/themes/flexible/basic.min.css
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
  core-bundle/src/Controller/FrontendModule/RootPageDependentModulesController.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/tests/Controller/ContentElement/ListControllerTest.php
  core-bundle/tests/Controller/ContentElement/TableControllerTest.php
  core-bundle/tests/Controller/FrontendModule/RootPageDependentModulesControllerTest.php
  core-bundle/tests/Functional/DbafsTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: release

#5776 Disallow Composer plugin from `php-http/discovery`
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  installation-bundle/composer.json
  listing-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  newsletter-bundle/composer.json
  test-case/composer.json
Labels: bug

#5775 Only check for registration opt-in tokens when purging registrations
  core-bundle/src/Resources/contao/models/MemberModel.php
Labels: bug

#5768 Harden hyperlink controller against URLs that are null
  core-bundle/contao/models/ContentModel.php
  core-bundle/src/Controller/ContentElement/HyperlinkController.php
  core-bundle/tests/Controller/ContentElement/HyperlinkControllerTest.php
Labels: bug

#5759 Fix the image encoding in the RSS feeds
  core-bundle/src/Resources/contao/library/Contao/FeedItem.php
Labels: bug

#5762 Fix header notification color
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
Labels: bug

#5760 Do not deep merge messenger workers
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: bug

#5742 Prevent division by zero in gallery element
  core-bundle/src/Resources/contao/elements/ContentGallery.php
Labels: bug

#5706 Do not add `target="_blank"` to the `{{link}}` insert tag for non-redirect pages
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#5778 Merge branch '4.13' into 5.0
  core-bundle/contao/elements/ContentGallery.php
  core-bundle/contao/forms/FormTextarea.php
  core-bundle/contao/library/Contao/FeedItem.php
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/models/MemberModel.php
  core-bundle/contao/widgets/TextArea.php
Labels: release

#5777 Do not URL-decode file paths in FigureBuilder
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#5619 Allow using both modern fragments and Twig templates in extensions
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Twig/ContaoTwigUtil.php
  core-bundle/src/Twig/Finder/Finder.php
  core-bundle/src/Twig/Finder/FinderFactory.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Contao/TemplateLoaderTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
  core-bundle/tests/Fixtures/Twig/inheritance/vendor-bundles/InvalidBundle1/templates/foo.html.twig
  core-bundle/tests/Fixtures/Twig/inheritance/vendor-bundles/InvalidBundle1/templates/sub/foo.html.twig
  core-bundle/tests/Fixtures/Twig/inheritance/vendor-bundles/InvalidBundle2/templates/text.json.twig
  core-bundle/tests/Twig/ContaoTwigUtilTest.php
  core-bundle/tests/Twig/Finder/FinderTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
Labels: bug

#5781 Merge branch '5.0' into 5.1
  core-bundle/contao/elements/ContentGallery.php
  core-bundle/contao/forms/FormTextarea.php
  core-bundle/contao/library/Contao/FeedItem.php
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/models/ContentModel.php
  core-bundle/contao/models/MemberModel.php
  core-bundle/contao/widgets/TextArea.php
  core-bundle/src/Controller/ContentElement/HyperlinkController.php
  core-bundle/tests/Controller/ContentElement/HyperlinkControllerTest.php
  maker-bundle/composer.json
Labels: release

#5782 Fix the remaining opt-in token validation queries
  comments-bundle/src/Resources/contao/models/CommentsNotifyModel.php
  core-bundle/src/Resources/contao/models/MemberModel.php
  newsletter-bundle/src/Resources/contao/models/NewsletterRecipientsModel.php
Labels: bug

#5674 Dynamically change the "expand/collapse all" label
  core-bundle/src/EventListener/DataContainer/ToggleNodesLabelListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/tests/EventListener/DataContainer/ToggleNodesLabelListenerTest.php
Labels: bug

#5783 Update the tools
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/tests/EventListener/DataContainer/PreviewLinkListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Intl/LocalesTest.php
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#5786 Handle negative PHP ini precision in StringUtil
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug

#5785 Fix file uploads erroneously overwriting existing files
  core-bundle/src/Resources/contao/forms/FormFileUpload.php
Labels: bug

#5787 Disable `ToggleNodesLabelListener` if not in back end
  core-bundle/src/EventListener/DataContainer/ToggleNodesLabelListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/DataContainer/ToggleNodesLabelListenerTest.php
Labels: bug

#5799 Define line endings for templates
  tools/ecs/config/template.php
Labels: bug

#5797 Revise the revision of reviseTable
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5792 Skip invalid article links if URL cannot be generated
  core-bundle/src/Resources/contao/modules/ModuleArticleList.php
Labels: bug

#5802 Fix public folder renaming on Windows
  core-bundle/src/Resources/contao/library/Contao/Files.php
Labels: bug

#5803 Move the favorites voter to the correct namespace
  core-bundle/config/services.yaml
  core-bundle/src/Security/Voter/DataContainer/FavoritesVoter.php
  core-bundle/tests/Security/Voter/DataContainer/DefaultDataContainerVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/FavoritesVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/TableAccessVoterTest.php
Labels: bug

#5780 Fix PHPUnit deprecation warnings
  core-bundle/contao/library/Contao/Database/Result.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Contao/Database/ResultTest.php
  core-bundle/tests/Filesystem/FilesystemItemIteratorTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: bug

#5805 Allow checking whether any field is allowed in the BackendAccessVoter
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/tests/Security/Voter/BackendAccessVoterTest.php
Labels: feature

#5811 Clear the session value when toggle is closed
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5790 Load app routes before everything else
  manager-bundle/src/Routing/RouteLoader.php
Labels: bug

#5809 Fix the "root page dependent modules" module
  core-bundle/src/Controller/FrontendModule/RootPageDependentModulesController.php
Labels: bug

#5795 Add the missing option to resume crawling from CLI
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/tests/Command/CrawlCommandTest.php
Labels: bug

#5817 Fix invalid HTML output of `DC_Table`
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5793 Do not rely on the current session IDs
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5774 Ignore if global_operation has no class
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#3540 Improve handling of pages with `tl_page.requireItem`
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
Labels: bug

#5828 Return BinaryFileResponse when handling downloads
  core-bundle/src/Controller/ContentElement/DownloadsController.php
Labels: bug
