Repository contao/contao, pull requests merged in 2023-06, with the labels that each got.

#6102 Fix the service linter namespace
  tools/service-linter/bin/lint-service-ids
  tools/service-linter/composer.json
  tools/service-linter/src/LintServiceIdsCommand.php
Labels: CI

#6108 Set the default class in the promoted constructor property
  core-bundle/src/Command/ResizeImagesCommand.php
  core-bundle/src/Controller/ImagesController.php
  core-bundle/src/Twig/Runtime/HighlighterRuntime.php
  manager-bundle/src/Command/MaintenanceModeCommand.php
  manager-bundle/src/Dotenv/DotenvDumper.php
Labels: CI

#5694 Parse back end URLs with Symfony assets
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
Labels: bug

#6110 Use only primary languages in the default locale list
  core-bundle/src/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPass.php
Labels: feature

#6111 Fix the reverse order unit tests
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
Labels: CI

#6035 Make sure login constants are set when rendering error page
  core-bundle/src/Resources/config/listener.yml
Labels: bug

#5968 Fix security and CSRF issues on the command line
  core-bundle/src/DependencyInjection/Security/ContaoLoginFactory.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/tests/DependencyInjection/Security/ContaoLoginFactoryTest.php
Labels: bug

#6114 Fix the CI chain
  core-bundle/tests/Fragment/FragmentHandlerTest.php
  core-bundle/tests/Functional/app/config/config_test.yaml
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
Labels: CI

#6113 Add recipient and channel ID to subject for List-Unsubscribe
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#6089 Add the missing annotation for the widget type field
  core-bundle/src/Resources/contao/forms/FormRange.php
  core-bundle/src/Resources/contao/forms/FormTextField.php
  core-bundle/src/Resources/contao/library/Contao/Widget.php
Labels: bug

#6115 Merge branch '4.13' into 5.1
  core-bundle/contao/classes/BackendTemplate.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/Routing/Page/PageRouteCompiler.php
Labels: release

#6085 Remove the parameters.yml file from the skeleton
  manager-bundle/skeleton/config/config.yaml
  manager-bundle/skeleton/config/parameters.yaml
  manager-bundle/src/ContaoManager/Plugin.php
Labels: bug

#6112 Allow saving serialized strings in DC_File again
  core-bundle/contao/drivers/DC_File.php
Labels: bug

#6117 Stop using the deprecated contao/image methods
  core-bundle/src/Image/PictureFactory.php
  core-bundle/tests/Image/PictureFactoryTest.php
  core-bundle/tests/Image/Preview/PreviewFactoryTest.php
  core-bundle/tests/Twig/Runtime/PictureConfigurationRuntimeTest.php
Labels: bug

#6119 Stop using Symfony‘s deprecated RequestMatcher class
  core-bundle/config/services.yaml
  core-bundle/src/Routing/Matcher/BackendMatcher.php
  core-bundle/src/Routing/Matcher/FrontendMatcher.php
  core-bundle/tests/TestCase.php
Labels: bug

#6093 Fix a typo in the `_download` component
  core-bundle/contao/templates/_new/component/_download.html.twig
Labels: bug

#6121 Do not generate a secret in the install tool anymore
  installation-bundle/src/Config/ParameterDumper.php
Labels: bug

#6109 Correctly track whether config files exist
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
Labels: bug

#6132 Require version `^2.15.1` of `friendsofsymfony/http-cache`
  composer.json
  core-bundle/composer.json
Labels: bug

#6135 Merge branch '4.13' into 5.1
  calendar-bundle/contao/classes/Calendar.php
  composer.json
  core-bundle/composer.json
  core-bundle/contao/forms/FormRange.php
  core-bundle/contao/forms/FormText.php
  core-bundle/contao/library/Contao/Widget.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
  newsletter-bundle/contao/classes/Newsletter.php
Labels: release

#6118 Only prepend the protocol in the page finder if the hostname is not empty
  core-bundle/src/Routing/PageFinder.php
  core-bundle/tests/Routing/PageFinderTest.php
Labels: bug

#6138 Fix book navigation in PHP 8
  core-bundle/src/Resources/contao/modules/ModuleBooknav.php
Labels: bug

#6128 Image quality setting for image sizes
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/languages/en/tl_image_size.xlf
  core-bundle/contao/models/ImageSizeModel.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: feature

#6137 Upgrade the Handorgel implementation
  composer.json
  core-bundle/composer.json
  core-bundle/contao/templates/js/js_accordion.html5
Labels: bug

#6142 Fix force language in `PageModel::getFrontendUrl()`
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#6139 Support relative URLs as canonical URLs
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Util/UrlUtil.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/HtmlHeadBag/HtmlHeadBagTest.php
  core-bundle/tests/Util/UrlUtilTest.php
Labels: bug

#6140 Always define a reference type in `PageModel::getFrontendUrl()`
  core-bundle/src/Resources/contao/models/PageModel.php
  core-bundle/tests/Contao/PageModelTest.php
Labels: bug

#6141 Remove entity mapping type for app bundle
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#6123 Prepend the web dir in `FigureBuilder::fromUrl()`
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Image/Studio/Studio.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Fixtures/public/images/dummy_public.jpg
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#6152 Fix undefined array key 0 in stylesheet
  core-bundle/src/Resources/contao/classes/StyleSheets.php
Labels: bug

#6144 Support vimeo unlisted video privacy hash
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/elements/ContentVimeo.php
Labels: bug

#6147 Support vimeo unlisted video privacy hash
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/elements/ContentVimeo.php
  core-bundle/src/Controller/ContentElement/VideoController.php
  core-bundle/tests/Controller/ContentElement/VideoControllerTest.php
Labels: bug

#6145 Add `authorModel` to the news templates
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#6130 Use `setMetadata()` in the `addImageToTemplate()` method
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/tests/Contao/ControllerTest.php
Labels: bug

#6073 Check string length for short hex color
  core-bundle/src/Resources/contao/classes/StyleSheets.php
Labels: bug

#6160 Ensure `multiSRC` is not mandatory when `useHomeDir` is selected
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#6161 Accumulate several PHP8 fixes
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  news-bundle/src/Resources/contao/dca/tl_news.php
Labels: bug

#6151 Fix a PHP8 issue in the `be_help` template
  core-bundle/src/Resources/contao/templates/backend/be_help.html5
Labels: bug

#6162 Merge branch '4.13' into 5.1
  calendar-bundle/contao/dca/tl_calendar_events.php
  core-bundle/config/services.yaml
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/ModuleBooknav.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/contao/templates/backend/be_help.html5
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/Image/Studio/Studio.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Util/UrlUtil.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Fixtures/public/images/dummy_public.jpg
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/HtmlHeadBag/HtmlHeadBagTest.php
  core-bundle/tests/Util/UrlUtilTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/modules/ModuleNews.php
Labels: release

#6136 Log the bad credentials exception in the security channel
  core-bundle/config/services.yaml
  core-bundle/src/Security/Authentication/AuthenticationFailureHandler.php
  core-bundle/tests/Security/Authentication/AuthenticationFailureHandlerTest.php
Labels: bug

#6054 Allow multiple label callbacks
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_log.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_member_group.php
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/EventListener/DataContainerCallbackListener.php
  core-bundle/tests/DependencyInjection/Compiler/DataContainerCallbackPassTest.php
  core-bundle/tests/EventListener/DataContainerCallbackListenerTest.php
  core-bundle/tests/Fixtures/src/EventListener/TestListener.php
Labels: feature

#6163 Always use `System::importStatic()` for callbacks and hooks
  calendar-bundle/contao/classes/Events.php
  calendar-bundle/contao/modules/ModuleCalendar.php
  comments-bundle/contao/classes/Comments.php
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/contao/classes/Ajax.php
  core-bundle/contao/classes/BackendTemplate.php
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/classes/FrontendTemplate.php
  core-bundle/contao/classes/PurgeData.php
  core-bundle/contao/classes/Versions.php
  core-bundle/contao/controllers/BackendHelp.php
  core-bundle/contao/controllers/BackendPassword.php
  core-bundle/contao/dca/tl_log.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/drivers/DC_File.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/forms/Form.php
  core-bundle/contao/library/Contao/Automator.php
  core-bundle/contao/library/Contao/Combiner.php
  core-bundle/contao/library/Contao/Database/Installer.php
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/library/Contao/Template.php
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/contao/modules/ModuleArticle.php
  core-bundle/contao/modules/ModuleBreadcrumb.php
  core-bundle/contao/modules/ModuleChangePassword.php
  core-bundle/contao/modules/ModuleCloseAccount.php
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModuleMaintenance.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/contao/modules/ModuleSearch.php
  core-bundle/contao/pages/PageRegular.php
  core-bundle/contao/widgets/Picker.php
  news-bundle/contao/modules/ModuleNews.php
  newsletter-bundle/contao/modules/ModuleSubscribe.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
Labels: feature

#6164 Remove the leftover BC layer in `System::__get()`
  core-bundle/contao/library/Contao/System.php
Labels: feature

#6168 Fix highlighting for phrase searches
  core-bundle/src/Resources/contao/library/Contao/Search.php
  core-bundle/src/Resources/contao/modules/ModuleSearch.php
  core-bundle/tests/Contao/SearchTest.php
Labels: bug

#6171 Revert 'Use real path for `.env.local`'
  composer.json
  manager-bundle/composer.json
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetDotEnvCommand.php
Labels: bug

#6180 Fix rootNodes for table picker
  core-bundle/src/Picker/TablePickerProvider.php
  core-bundle/src/Resources/contao/widgets/Picker.php
Labels: bug
