Repository contao/contao, pull requests merged in 2023-08, with the labels that each got.

#6261 Fix the FAQ page and list modules
  faq-bundle/src/Resources/contao/modules/ModuleFaqList.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
Labels: bug

#6262 Merge branch '4.13' into 5.1
  calendar-bundle/contao/modules/ModuleEventReader.php
  faq-bundle/contao/modules/ModuleFaqList.php
  faq-bundle/contao/modules/ModuleFaqPage.php
  news-bundle/contao/modules/ModuleNewsReader.php
Labels: release

#6263 Ensure absolute URLs in the PageRedirect class
  core-bundle/contao/pages/PageRedirect.php
Labels: bug

#6267 Adjust the "preserve metadata" logic
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/languages/en/tl_image_size.xlf
  core-bundle/contao/models/ImageSizeModel.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/PictureFactory.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
Labels: bug

#6157 Use createElementNS for namespaced XML elements
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/Event/SitemapEvent.php
Labels: feature

#6278 Simplify three regular expressions
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/String/HtmlAttributesTest.php
Labels: bug

#6283 Adjust the model return types
  calendar-bundle/contao/models/CalendarEventsModel.php
  calendar-bundle/contao/models/CalendarFeedModel.php
  calendar-bundle/contao/models/CalendarModel.php
  comments-bundle/contao/models/CommentsModel.php
  comments-bundle/contao/models/CommentsNotifyModel.php
  core-bundle/contao/library/Contao/Model.php
  core-bundle/contao/library/Contao/Model/Collection.php
  core-bundle/contao/models/ArticleModel.php
  core-bundle/contao/models/ContentModel.php
  core-bundle/contao/models/FilesModel.php
  core-bundle/contao/models/FormFieldModel.php
  core-bundle/contao/models/FormModel.php
  core-bundle/contao/models/ImageSizeItemModel.php
  core-bundle/contao/models/ImageSizeModel.php
  core-bundle/contao/models/LayoutModel.php
  core-bundle/contao/models/MemberGroupModel.php
  core-bundle/contao/models/MemberModel.php
  core-bundle/contao/models/ModuleModel.php
  core-bundle/contao/models/OptInModel.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/models/ThemeModel.php
  core-bundle/contao/models/UserGroupModel.php
  core-bundle/contao/models/UserModel.php
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  faq-bundle/contao/models/FaqCategoryModel.php
  faq-bundle/contao/models/FaqModel.php
  news-bundle/contao/models/NewsArchiveModel.php
  news-bundle/contao/models/NewsModel.php
  news-bundle/src/EventListener/NewsFeedListener.php
  newsletter-bundle/contao/models/NewsletterChannelModel.php
  newsletter-bundle/contao/models/NewsletterDenyListModel.php
  newsletter-bundle/contao/models/NewsletterModel.php
  newsletter-bundle/contao/models/NewsletterRecipientsModel.php
Labels: CI

#6284 Convert another regular expression
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
Labels: CI

#6282 Fix labels for news and event feature operation
  calendar-bundle/contao/languages/en/tl_calendar_events.xlf
  news-bundle/contao/languages/en/tl_news.xlf
Labels: bug

#6285 Get rid of the 'Loading a non-existent DCA' deprecation
  core-bundle/tests/Contao/StringUtilTest.php
Labels: CI

#6288 Deprecate the option to return model collections as array
  core-bundle/contao/library/Contao/Model.php
Labels: up for discussion, CI

#6295 Add the missing expectDeprecation() calls
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
Labels: CI

#6276 Use PDF TrimBox when generating previews
  core-bundle/src/Image/Preview/ImaginePreviewProvider.php
Labels: bug

#6293 Add redirect for app.php to prevent duplicate content
  manager-bundle/src/Resources/skeleton/public/.htaccess
Labels: bug

#6296 Allow to set `field` and `inputName` on DataContainer
  core-bundle/src/Resources/contao/classes/DataContainer.php
Labels: bug

#6298 Clean up the code of the picture insert tag
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: CI

#6302 Generate the file manager preview images with a 1x, 2x source set
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#6304 Upgrade and run the tools
  composer.json
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  core-bundle/tests/Routing/Matcher/LegacyMatcherTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
Labels: CI

#6305 Merge branch '4.13' into 5.2
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/library/Contao/Database.php
  core-bundle/contao/library/Contao/Database/Statement.php
  core-bundle/src/Image/Preview/ImaginePreviewProvider.php
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
Labels: release

#6306 Correctly handle users without username in the registration module
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#6307 Fix the .htaccess rewrite rules
  manager-bundle/src/Resources/skeleton/public/.htaccess
Labels: bug

#6310 Allow storing large integers in the calendar bundle
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
Labels: bug

#6309 Fix warnings when using `Image::get`
  core-bundle/src/Resources/contao/library/Contao/Image.php
Labels: bug

#6311 Remove another left-over `errorInfo()` call
  core-bundle/src/Resources/contao/library/Contao/Database.php
Labels: bug

#6279 Fix bug with huge PDF files in the back end preview
  core-bundle/src/Resources/contao/controllers/BackendPopup.php
Labels: bug

#6317 Use primary language for slug generation
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#6319 Simplify the "object or null" checks
  calendar-bundle/src/EventListener/InsertTagsListener.php
  calendar-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/contao/library/Contao/TemplateInheritance.php
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Command/Backup/BackupStreamContentCommand.php
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/src/Controller/ContentElement/PlayerController.php
  core-bundle/src/Controller/ContentElement/TeaserController.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php
  core-bundle/src/EventListener/ExceptionConverterListener.php
  core-bundle/src/EventListener/InsertTags/DateListener.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/FileDownloadHelper.php
  core-bundle/src/Filesystem/FilesystemUtil.php
  core-bundle/src/Filesystem/MountManager.php
  core-bundle/src/Filesystem/PublicUri/SymlinkedLocalFilesProvider.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/Image/Studio/FigureRenderer.php
  core-bundle/src/Intl/Countries.php
  core-bundle/src/Intl/Locales.php
  core-bundle/src/Slug/Slug.php
  news-bundle/src/EventListener/PreviewUrlConvertListener.php
Labels: CI

#6320 Run the code inspector
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/src/Controller/ContentElement/ImagesController.php
  core-bundle/src/Doctrine/Backup/BackupManager.php
  core-bundle/src/EventListener/DataContainer/DisableCanonicalFieldsListener.php
  manager-bundle/skeleton/config/services.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
Labels: CI

#6321 Simplify assignments in conditions with instanceof checks
  calendar-bundle/src/EventListener/GeneratePageListener.php
  calendar-bundle/src/Picker/EventPickerProvider.php
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/src/Controller/ContentElement/ImagesController.php
  core-bundle/src/EventListener/InsertTags/DateListener.php
  core-bundle/src/EventListener/UnwrapTwigExceptionListener.php
  core-bundle/src/Picker/FilePickerProvider.php
  core-bundle/src/Routing/PageFinder.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/src/Twig/Extension/DeprecationsNodeVisitor.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/src/Twig/Runtime/LegacyTemplateFunctionsRuntime.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/Twig/FragmentTemplateTest.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  manager-bundle/src/HttpKernel/ContaoCache.php
  news-bundle/src/Picker/NewsPickerProvider.php
Labels: CI

#6326 Run the tools
  composer.json
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/src/InsertTag/Resolver/IfLanguageInsertTag.php
  core-bundle/tests/Doctrine/Backup/DumperTest.php
Labels: CI

#6325 Do not URL-encode insert tags in `specialcharsUrl()`
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/InputTest.php
Labels: bug

#6324 Always set the `JSON_THROW_ON_ERROR` flag
  core-bundle/src/Command/Backup/BackupCreateCommand.php
  core-bundle/src/Command/Backup/BackupListCommand.php
  core-bundle/src/Command/Backup/BackupRestoreCommand.php
  core-bundle/src/Command/CronListCommand.php
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/src/Monolog/ContaoContext.php
  core-bundle/src/Picker/PickerConfig.php
  core-bundle/src/Search/Document.php
  core-bundle/src/Security/TwoFactor/BackupCodeManager.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Command/UserListCommandTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementControllerTest.php
  core-bundle/tests/Controller/FrontendModule/FrontendModuleControllerTest.php
  core-bundle/tests/Security/TwoFactor/BackupCodeManagerTest.php
  manager-bundle/src/Api/Command/VersionCommand.php
  manager-bundle/src/Command/MaintenanceModeCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/GetConfigCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/GetDotEnvCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/ParseJwtCookieCommand.php
  manager-bundle/src/ContaoManager/ApiCommand/SetConfigCommand.php
  manager-bundle/tests/ContaoManager/ApiCommand/SetConfigCommandTest.php
  tools/rector/config/rector.php
Labels: feature

#6329 Add the missing autowiring alias for the new `ProcessUtil` service
  core-bundle/config/services.yaml
Labels: bug

#6331 Check the preview script before the firewall
  core-bundle/src/EventListener/PreviewToolbarListener.php
Labels: bug

#6332 Always allow unpublished pages in preview entry point
  core-bundle/src/Routing/Matcher/PublishedFilter.php
  core-bundle/tests/Routing/Matcher/PublishedFilterTest.php
Labels: bug

#6339 Upgrade doctrine/collections and doctrine/persistence
  composer.json
  core-bundle/composer.json
Labels: feature

#6336 Make doctrine/dbal 3.6 the minimum version
  composer.json
  core-bundle/composer.json
  core-bundle/contao/library/Contao/Model.php
  core-bundle/src/Migration/CommandCompiler.php
  core-bundle/tests/Asset/ContaoContextTest.php
  core-bundle/tests/Command/DebugPagesCommandTest.php
  core-bundle/tests/Contao/ModelTest.php
  core-bundle/tests/Contao/ModuleTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Migration/CommandCompilerTest.php
  manager-bundle/composer.json
  test-case/composer.json
Labels: feature

#6338 Remove the "roave/better-reflection" dependency
  composer.json
  core-bundle/composer.json
  test-case/composer.json
Labels: feature

#6337 Upgrade the Symfony contracts
  composer.json
  core-bundle/composer.json
  manager-bundle/composer.json
  test-case/composer.json
Labels: feature

#6236 Allow array for page parameters
  core-bundle/contao/models/PageModel.php
Labels: feature

#6348 URL-encode file paths for edit multiple
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#6333 Correctly add the schema.org data of multiple FAQ archives on the same page
  faq-bundle/src/Resources/contao/modules/ModuleFaq.php
  faq-bundle/src/Resources/contao/modules/ModuleFaqPage.php
Labels: bug

#6343 Fix warning if reference page of navigation module gets deleted
  core-bundle/src/Resources/contao/modules/ModuleNavigation.php
  core-bundle/src/Resources/contao/modules/ModuleQuicknav.php
Labels: bug, unconfirmed
