Repository contao/contao, pull requests merged in 2023-04, with the labels that each got.

#5920 Reintroduce the unknown symbols check for core-bundle
  .github/workflows/ci.yml
  tools/require-checker/config.json
Labels: CI

#5929 Merge branch '4.13' into 5.1
  .github/workflows/ci.yml
  core-bundle/contao/drivers/DC_Folder.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/tests/Fixtures/HttpKernel/WithConfigsPhp/config/services.php
  manager-bundle/tests/Fixtures/HttpKernel/WithConfigsXml/config/services.xml
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
  tools/require-checker/config/config.json
Labels: release

#5921 Fix bug in Hybrid::generate() with missing ID
  core-bundle/contao/classes/Hybrid.php
Labels: bug

#5927 Fix the version panel alignment
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#5935 CS and grammar fixes
  UPGRADE.md
  calendar-bundle/contao/classes/Calendar.php
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/contao/languages/en/tl_calendar_events.xlf
  core-bundle/contao/forms/Form.php
  core-bundle/contao/languages/en/tl_article.xlf
  core-bundle/contao/languages/en/tl_content.xlf
  core-bundle/contao/languages/en/tl_member.xlf
  core-bundle/contao/languages/en/tl_member_group.xlf
  core-bundle/contao/languages/en/tl_page.xlf
  core-bundle/contao/languages/en/tl_user.xlf
  core-bundle/contao/languages/en/tl_user_group.xlf
  core-bundle/contao/library/Contao/ArrayUtil.php
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/models/FilesModel.php
  core-bundle/src/Monolog/ContaoTableHandler.php
  core-bundle/src/Security/TwoFactor/Authenticator.php
  core-bundle/templates/Error/layout.html.twig
  manager-bundle/skeleton/public/.htaccess
  manager-bundle/tests/Fixtures/HttpKernel/WithConfigsXml/config/services.xml
  news-bundle/contao/languages/en/tl_news.xlf
  newsletter-bundle/contao/languages/en/tl_module.xlf
Labels: CI

#5917 Consider foreign keys when sorting the list view
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#5934 Fix the search query in DC_Folder
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#5938 Merge branch '4.13' into 5.1
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/themes/flexible/main.css
  core-bundle/contao/themes/flexible/main.min.css
Labels: release

#5922 Correctly pass null values in findBy queries
  calendar-bundle/contao/models/CalendarEventsModel.php
  core-bundle/contao/library/Contao/Model.php
  core-bundle/contao/models/ArticleModel.php
  core-bundle/contao/models/FormFieldModel.php
  core-bundle/contao/models/MemberGroupModel.php
  core-bundle/contao/models/PageModel.php
  faq-bundle/contao/models/FaqModel.php
  news-bundle/contao/models/NewsModel.php
  newsletter-bundle/contao/models/NewsletterModel.php
  newsletter-bundle/contao/models/NewsletterRecipientsModel.php
Labels: bug

#5908 Correctly handle response status codes from legacy entry points
  core-bundle/src/Controller/InitializeController.php
Labels: bug

#5942 Do not treat sub-directories of Twig namespace roots as template paths
  core-bundle/src/Twig/Loader/TemplateLocator.php
Labels: bug

#5949 Add the "adjustDca" load callback to tl_news_archive again
  news-bundle/contao/dca/tl_news_archive.php
Labels: bug

#5952 Ignore exceptions when adding trusted devices
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
Labels: bug

#5893 Correctly check the mounted pages in the `hasAccess()` method
  core-bundle/src/Resources/contao/classes/BackendUser.php
Labels: bug

#5955 Remove the "symfony/proxy-manager-bridge" dependency
  composer.json
  manager-bundle/composer.json
  manager-bundle/src/HttpKernel/ContaoKernel.php
Labels: bug

#5959 Remove unnecessary locale tags from languages
  core-bundle/src/Intl/Locales.php
  core-bundle/tests/Intl/LocalesTest.php
Labels: bug

#5960 Prevent double slashes in version URLs
  core-bundle/contao/classes/Versions.php
Labels: bug

#5961 Merge branch '4.13' into 5.1
  composer.json
  core-bundle/contao/classes/BackendUser.php
  core-bundle/src/Intl/Locales.php
  core-bundle/src/Security/TwoFactor/TrustedDeviceManager.php
  core-bundle/tests/Intl/LocalesTest.php
  manager-bundle/composer.json
  manager-bundle/src/HttpKernel/ContaoKernel.php
Labels: release

#5851 Do not auto-link images in the news reader
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#5946 Load the default language when generating the calendar feeds
  calendar-bundle/contao/classes/Calendar.php
  calendar-bundle/tests/Cron/GenerateFeedsCronTest.php
Labels: bug

#5964 Add the header.svg and settings.svg icons again
  core-bundle/contao/themes/flexible/icons/header.svg
  core-bundle/contao/themes/flexible/icons/header_.svg
  core-bundle/contao/themes/flexible/icons/settings.svg
Labels: bug

#5962 Fix an undefined array key warning when comparing versions with different fields
  core-bundle/src/Resources/contao/classes/Versions.php
  core-bundle/src/Resources/contao/themes/flexible/diff.css
  core-bundle/src/Resources/contao/themes/flexible/diff.min.css
Labels: bug

#5969 Merge branch '4.13' into 5.1
  core-bundle/contao/classes/Versions.php
  core-bundle/contao/themes/flexible/diff.css
  core-bundle/contao/themes/flexible/diff.min.css
  news-bundle/contao/modules/ModuleNews.php
Labels: release

#5988 Harden the file manager against directory traversal attacks
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/library/Contao/Database.php
Labels: bug

#5990 Run the workflows on ubuntu-latest
  .github/workflows/ci.yml
Labels: bug, CI

#5986 Allow flysystem-bundle ^3.0
  composer.json
  core-bundle/composer.json
Labels: bug

#5981 Use the title instead of the filename in the download component
  core-bundle/contao/templates/_new/component/_download.html.twig
  core-bundle/tests/Controller/ContentElement/DownloadsControllerTest.php
Labels: bug

#5974 Convert the language callbacks
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_user.php
Labels: CI

#5984 Make the `multiSRC` field mandatory for galleries and downloads
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#5996 Merge branch '4.13' into 5.1
  composer.json
  core-bundle/composer.json
  core-bundle/contao/classes/Hybrid.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/src/Image/Studio/Figure.php
Labels: release

#5980 Unwrap response exceptions thrown while rendering a template
  core-bundle/config/listener.yaml
  core-bundle/src/EventListener/UnwrapTwigExceptionListener.php
  core-bundle/tests/EventListener/UnwrapTwigExceptionListenerTest.php
Labels: bug

#6001 Update and run the tools
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ChangeSet.php
  core-bundle/src/Picker/AbstractPickerProvider.php
  manager-bundle/tests/ContaoManager/PluginTest.php
  tools/ecs/composer.lock
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI
