Repository contao/contao, pull requests merged in 2023-10, with the labels that each got.

#6422 Correctly tag cached responses with forms
  core-bundle/src/Resources/contao/classes/Hybrid.php
  core-bundle/src/Resources/contao/forms/Form.php
Labels: bug

#6419 Use `href` for lightbox resource
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#6414 Do not add default operations when loading a non-existent DCA
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
Labels: bug

#6400 Convert dates into the HTML5 format in the FormText widget
  core-bundle/contao/forms/FormText.php
  core-bundle/contao/templates/forms/form_text.html5
Labels: bug

#6416 Fix the newsletter "delete" permission constant
  newsletter-bundle/src/Security/ContaoNewsletterPermissions.php
Labels: bug

#6405 Increase the `UnwrapTwigExceptionListener` priority
  core-bundle/config/listener.yaml
Labels: bug

#6404 Remove the BC layers in the `ContaoCache` class
  manager-bundle/src/HttpKernel/ContaoCache.php
Labels: feature

#6425 Do not set `database_version` in the install tool
  installation-bundle/src/Config/ParameterDumper.php
  installation-bundle/src/Controller/InstallationController.php
Labels: bug

#6431 Make sure valid URLs start with a slash
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
Labels: bug

#6437 Support themes from ZIP file
  core-bundle/src/Resources/contao/classes/Theme.php
  core-bundle/src/Resources/contao/library/Contao/ZipReader.php
Labels: bug

#6438 Cache lower key values in `Model::convertToPhpValue()`
  core-bundle/contao/library/Contao/Model.php
Labels: bug

#6439 Merge branch '4.13' into 5.2
  core-bundle/contao/classes/Theme.php
  core-bundle/contao/library/Contao/ZipReader.php
  core-bundle/src/Routing/Route404Provider.php
  core-bundle/src/Routing/RouteProvider.php
Labels: release

#6443 Simplify whitespace control in headline component template
  core-bundle/contao/templates/_new/component/_headline.html.twig
Labels: bug

#6444 Enable code highlighting for Twig
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#6446 Rename the `templates/_new` folder to `templates/twig`
  core-bundle/contao/templates/twig/.twig-root
  core-bundle/contao/templates/twig/backend/module_wildcard.html.twig
  core-bundle/contao/templates/twig/backend/template_skeleton.html.twig
  core-bundle/contao/templates/twig/component/_download.html.twig
  core-bundle/contao/templates/twig/component/_figure.html.twig
  core-bundle/contao/templates/twig/component/_headline.html.twig
  core-bundle/contao/templates/twig/component/_list.html.twig
  core-bundle/contao/templates/twig/component/_picture.html.twig
  core-bundle/contao/templates/twig/component/_read_more.html.twig
  core-bundle/contao/templates/twig/component/_splash_screen.html.twig
  core-bundle/contao/templates/twig/component/_stylesheet.html.twig
  core-bundle/contao/templates/twig/component/_table.html.twig
  core-bundle/contao/templates/twig/content_element/_base.html.twig
  core-bundle/contao/templates/twig/content_element/_video.html.twig
  core-bundle/contao/templates/twig/content_element/code.html.twig
  core-bundle/contao/templates/twig/content_element/download.html.twig
  core-bundle/contao/templates/twig/content_element/downloads.html.twig
  core-bundle/contao/templates/twig/content_element/gallery.html.twig
  core-bundle/contao/templates/twig/content_element/headline.html.twig
  core-bundle/contao/templates/twig/content_element/html.html.twig
  core-bundle/contao/templates/twig/content_element/hyperlink.html.twig
  core-bundle/contao/templates/twig/content_element/image.html.twig
  core-bundle/contao/templates/twig/content_element/list.html.twig
  core-bundle/contao/templates/twig/content_element/markdown.html.twig
  core-bundle/contao/templates/twig/content_element/player.html.twig
  core-bundle/contao/templates/twig/content_element/table.html.twig
  core-bundle/contao/templates/twig/content_element/teaser.html.twig
  core-bundle/contao/templates/twig/content_element/template.html.twig
  core-bundle/contao/templates/twig/content_element/text.html.twig
  core-bundle/contao/templates/twig/content_element/toplink.html.twig
  core-bundle/contao/templates/twig/content_element/unfiltered_html.html.twig
  core-bundle/contao/templates/twig/content_element/vimeo.html.twig
  core-bundle/contao/templates/twig/content_element/youtube.html.twig
  core-bundle/contao/templates/twig/frontend_module/_base.html.twig
  core-bundle/contao/templates/twig/frontend_module/feed_reader.html.twig
  core-bundle/contao/templates/twig/frontend_module/template.html.twig
  core-bundle/contao/templates/twig/frontend_module/unfiltered_html.html.twig
Labels: feature

#6449 Do not lowercase table and column names in type cache
  core-bundle/contao/library/Contao/Model.php
  core-bundle/tests/Contao/ModelTest.php
Labels: bug

#6417 Change user commands to not use models
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Command/UserListCommand.php
  core-bundle/tests/Command/UserListCommandTest.php
Labels: bug

#6429 Deprecate the `MergeHttpHeadersListener` class
  core-bundle/src/EventListener/MergeHttpHeadersListener.php
  core-bundle/src/HttpKernel/Header/HeaderStorageInterface.php
  core-bundle/src/HttpKernel/Header/MemoryHeaderStorage.php
  core-bundle/src/HttpKernel/Header/NativeHeaderStorage.php
  core-bundle/tests/EventListener/MergeHttpHeadersListenerTest.php
Labels: feature

#6457 Add member login preview links to known limitations
  LIMITATIONS.md
Labels: bug

#6456 Fix unsetting uppercase attributes
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/String/HtmlAttributesTest.php
Labels: bug

#6462 Remove the kernel.reset tag
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/config/services.yml
Labels: bug

#6459 Correctly reset the context when generating preview URL fails
  core-bundle/src/Resources/contao/models/PageModel.php
Labels: bug

#6464 Do not grant access in the news archive access voter
  news-bundle/src/Security/Voter/NewsArchiveAccessVoter.php
  news-bundle/tests/Security/Voter/NewsArchiveAccessVoterTest.php
Labels: bug

#6467 Compare actual row format instead of create options
  installation-bundle/src/Database/Installer.php
  installation-bundle/tests/Database/InstallerTest.php
Labels: bug

#6468 Compare actual row format instead of create options
  core-bundle/src/Migration/CommandCompiler.php
  core-bundle/tests/Migration/CommandCompilerTest.php
Labels: bug
