Repository contao/contao, pull requests merged in 2024-09, with the labels that each got.

#7504 Fix the CI chain
  core-bundle/src/Twig/Extension/DeprecationsNodeVisitor.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7499 Disable Turbo in the 2FA backup codes form
  core-bundle/contao/templates/backend/be_two_factor.html5
Labels: bug

#7500 Switch to a stable ALTCHA version
  composer.json
  core-bundle/composer.json
Labels: bug

#7511 Fix the CI chain
  .github/workflows/ci.yml
  .gitignore
  .yamllint
  composer.json
  core-bundle/src/Resources/contao/drivers/DC_Table.php
  core-bundle/src/Twig/Extension/DeprecationsNodeVisitor.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  phpstan.neon
  vendor-bin/ecs/composer.json
  vendor-bin/ecs/composer.lock
  vendor-bin/ecs/config/default.php
  vendor-bin/ecs/config/legacy.php
  vendor-bin/ecs/config/template.php
  vendor-bin/isolated-tests/bin/run-tests-isolated
  vendor-bin/isolated-tests/composer.json
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/isolated-tests/src/RunTestsIsolatedCommand.php
  vendor-bin/monorepo-tools/composer.json
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.json
  vendor-bin/phpstan/composer.lock
  vendor-bin/phpstan/config/config.php
  vendor-bin/require-checker/composer.json
  vendor-bin/require-checker/composer.lock
  vendor-bin/require-checker/config.json
  vendor-bin/service-linter/bin/lint-service-ids
  vendor-bin/service-linter/composer.json
  vendor-bin/service-linter/composer.lock
  vendor-bin/service-linter/src/LintServiceIdsCommand.php
Labels: CI

#7503 Always break out of Turbo frames when missing
  core-bundle/assets/backend.js
  core-bundle/public/backend.15536700.js
  core-bundle/public/backend.15536700.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  package-lock.json
Labels: bug

#7505 Make Twig 3.12 the minimum version
  composer.json
  core-bundle/composer.json
  core-bundle/src/Twig/Extension/DeprecationsNodeVisitor.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
Labels: feature

#7506 Only get valid image extensions once
  core-bundle/src/Resources/contao/dca/tl_image_size.php
Labels: bug

#7512 Allow the `name` attribute for the `<details>` element
  core-bundle/src/Resources/contao/config/default.php
Labels: bug

#7513 Fix the parent record loading in the dynamic parent table voter
  calendar-bundle/tests/Security/Voter/CalendarContentVoterTest.php
  core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php
  core-bundle/tests/Security/Voter/DataContainer/ArticleContentVoterTest.php
  news-bundle/tests/Security/Voter/NewsContentVoterTest.php
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
Labels: bug

#7466 Do not show the template warnings if a user only has group permissions
  core-bundle/src/Resources/contao/dca/tl_user.php
Labels: bug

#7467 Correctly handle news feed URLs in the page routing listener
  core-bundle/src/EventListener/DataContainer/PageRoutingListener.php
  core-bundle/tests/EventListener/DataContainer/PageRoutingListenerTest.php
  news-bundle/src/Controller/Page/NewsFeedController.php
Labels: bug

#7497 Use `flex` for the back end gallery layout
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#7509 Handle string IDs in the article content voter
  core-bundle/src/Security/Voter/DataContainer/ArticleContentVoter.php
  core-bundle/tests/Security/Voter/DataContainer/ArticleContentVoterTest.php
Labels: bug

#7530 Merge branch '5.3' into 5.4
  calendar-bundle/tests/Security/Voter/CalendarContentVoterTest.php
  core-bundle/config/listener.yaml
  core-bundle/contao/config/default.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/themes/flexible/backend.190c4061.css
  core-bundle/contao/themes/flexible/backend.aec4876d.css
  core-bundle/contao/themes/flexible/confirm.19e92035.css
  core-bundle/contao/themes/flexible/confirm.c912bc49.css
  core-bundle/contao/themes/flexible/conflict.3af35934.css
  core-bundle/contao/themes/flexible/conflict.97902980.css
  core-bundle/contao/themes/flexible/diff.589c7881.css
  core-bundle/contao/themes/flexible/diff.c35a870c.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/help.469c839a.css
  core-bundle/contao/themes/flexible/help.d33074ae.css
  core-bundle/contao/themes/flexible/login.69e0d490.css
  core-bundle/contao/themes/flexible/login.7f0ef01b.css
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/popup.1b675e09.css
  core-bundle/contao/themes/flexible/popup.e3b8d046.css
  core-bundle/contao/themes/flexible/styles/basic.css
  core-bundle/contao/themes/flexible/styles/main.css
  core-bundle/src/EventListener/DataContainer/LegacyGalleryPaletteListener.php
  core-bundle/src/EventListener/DataContainer/PageRoutingListener.php
  core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php
  core-bundle/src/Security/Voter/DataContainer/ArticleContentVoter.php
  core-bundle/tests/EventListener/DataContainer/LegacyGalleryPaletteListenerTest.php
  core-bundle/tests/EventListener/DataContainer/PageRoutingListenerTest.php
  core-bundle/tests/Intl/CountriesTest.php
  core-bundle/tests/Intl/LocalesTest.php
  core-bundle/tests/Security/Voter/DataContainer/ArticleContentVoterTest.php
  news-bundle/src/Controller/Page/NewsFeedController.php
  news-bundle/tests/Security/Voter/NewsContentVoterTest.php
  package-lock.json
  package.json
Labels: release

#7537 Add a null check for a possible empty array
  core-bundle/src/EventListener/DataContainer/LegacyGalleryPaletteListener.php
  core-bundle/tests/EventListener/DataContainer/LegacyGalleryPaletteListenerTest.php
Labels: bug

#7533 Update `box-size` translation for image-size
  core-bundle/src/Resources/contao/languages/en/default.xlf
Labels: bug

#7535 Fix hardcoded limit to 30 in database statement
  core-bundle/src/Resources/contao/library/Contao/Database/Statement.php
Labels: bug

#7541 Fix the CI chain
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/require-checker/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7574 Use platform overrides for the tools so the CI chain doesn‘t break
  vendor-bin/ecs/composer.json
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/bin/run-tests-isolated
  vendor-bin/isolated-tests/composer.json
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/isolated-tests/src/RunTestsIsolatedCommand.php
  vendor-bin/monorepo-tools/composer.json
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.json
  vendor-bin/phpstan/composer.lock
  vendor-bin/require-checker/composer.json
  vendor-bin/require-checker/composer.lock
  vendor-bin/service-linter/composer.json
  vendor-bin/service-linter/composer.lock
Labels: CI

#7578 Merge branch '5.3' into 5.4
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/split.yml
  composer.json
  depcheck.php
  ecs.php
  monorepo.yml
  rector.php
  vendor-bin/depcheck/composer.json
  vendor-bin/depcheck/composer.lock
  vendor-bin/ecs/composer.json
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/bin/run-tests-isolated
  vendor-bin/isolated-tests/composer.json
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/isolated-tests/src/RunTestsIsolatedCommand.php
  vendor-bin/monorepo-tools/composer.json
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.json
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.json
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.json
  vendor-bin/service-linter/composer.lock
Labels: release

#7532 Rename `$buger` to `$burger` in the `BackendMenuListener`
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
Labels: bug

#7577 Fix global state constants
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
Labels: CI

#7557 Specify the dev tools how-to in the readme file
  README.md
Labels: feature

#7553 Remove PDF remnants
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/modules/ModuleArticle.php
  core-bundle/contao/templates/modules/mod_article.html5
Labels: bug

#7579 Make the Twig inspector understand the block hierarchy
  core-bundle/config/services.yaml
  core-bundle/contao/templates/twig/backend/template_skeleton.html.twig
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/Twig/Inspector/BlockInformation.php
  core-bundle/src/Twig/Inspector/BlockType.php
  core-bundle/src/Twig/Inspector/Inspector.php
  core-bundle/src/Twig/Inspector/InspectorNodeVisitor.php
  core-bundle/src/Twig/Inspector/TemplateInformation.php
  core-bundle/tests/Command/DebugContaoTwigCommandTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/DeprecationsNodeVisitorTest.php
  core-bundle/tests/Twig/Extension/InsertTagTest.php
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Inspector/ContaoInspectorNodeVisitorTest.php
  core-bundle/tests/Twig/Inspector/InspectorIntegrationTest.php
  core-bundle/tests/Twig/Inspector/InspectorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/ResponseContext/AddTokenParserTest.php
  core-bundle/tests/Twig/Slots/SlotTokenParserTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: feature

#7573 Add a user templates VFS storage
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: feature

#7555 Use the resource finder in the Twig template locator
  core-bundle/config/services.yaml
  core-bundle/src/Config/ResourceFinder.php
  core-bundle/src/DependencyInjection/Compiler/AddResourcesPathsPass.php
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/DependencyInjection/Compiler/AddResourcesPathsPassTest.php
  core-bundle/tests/Fixtures/Twig/inheritance/contao/templates/bar.html.twig
  core-bundle/tests/Fixtures/Twig/inheritance/system/modules/foo/templates/any/text.html.twig
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: bug

#7570 Do not save long file extensions during filesync
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
Labels: bug

#7566 Introduce a general cache tag invalidator service
  core-bundle/config/services.yaml
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/library/Contao/Automator.php
  core-bundle/src/Cache/CacheTagInvalidator.php
  core-bundle/src/Cache/EntityCacheTags.php
  core-bundle/src/Event/InvalidateCacheTagsEvent.php
  core-bundle/tests/Cache/CacheTagInvalidatorTest.php
  core-bundle/tests/Cache/EntityCacheTagsTest.php
Labels: feature

#7580 Add a basic PostCSS setup
  core-bundle/assets/backend.js
  core-bundle/assets/styles/backend.pcss
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/public/backend.31d6cfe0.css
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  package-lock.json
  package.json
  webpack.config.js
Labels: feature

#7582 Add PostCSS as described in Symfony Encore
  core-bundle/public/backend.9409a3c0.js
  core-bundle/public/backend.9409a3c0.js.LICENSE.txt
  core-bundle/public/backend.cc67ac78.js
  core-bundle/public/backend.cc67ac78.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  package-lock.json
  package.json
  postcss.config.js
  webpack.config.js
Labels: bug
