Repository contao/contao, pull requests merged in 2024-07, with the labels that each got.

#7301 Update the file icons in the file manager
  core-bundle/contao/config/mimetypes.php
  core-bundle/contao/library/Contao/File.php
  core-bundle/contao/themes/flexible/icons/archive--dark.svg
  core-bundle/contao/themes/flexible/icons/archive.svg
  core-bundle/contao/themes/flexible/icons/audio--dark.svg
  core-bundle/contao/themes/flexible/icons/audio.svg
  core-bundle/contao/themes/flexible/icons/binary--dark.svg
  core-bundle/contao/themes/flexible/icons/binary.svg
  core-bundle/contao/themes/flexible/icons/chart--dark.svg
  core-bundle/contao/themes/flexible/icons/chart.svg
  core-bundle/contao/themes/flexible/icons/code--dark.svg
  core-bundle/contao/themes/flexible/icons/code.svg
  core-bundle/contao/themes/flexible/icons/document--dark.svg
  core-bundle/contao/themes/flexible/icons/document.svg
  core-bundle/contao/themes/flexible/icons/font--dark.svg
  core-bundle/contao/themes/flexible/icons/font.svg
  core-bundle/contao/themes/flexible/icons/image--dark.svg
  core-bundle/contao/themes/flexible/icons/image.svg
  core-bundle/contao/themes/flexible/icons/json--dark.svg
  core-bundle/contao/themes/flexible/icons/json.svg
  core-bundle/contao/themes/flexible/icons/manifest.json
  core-bundle/contao/themes/flexible/icons/plain--dark.svg
  core-bundle/contao/themes/flexible/icons/plain.svg
  core-bundle/contao/themes/flexible/icons/spreadsheet--dark.svg
  core-bundle/contao/themes/flexible/icons/spreadsheet.svg
  core-bundle/contao/themes/flexible/icons/terminal--dark.svg
  core-bundle/contao/themes/flexible/icons/terminal.svg
  core-bundle/contao/themes/flexible/icons/video--dark.svg
  core-bundle/contao/themes/flexible/icons/video.svg
Labels: feature

#7054 Add an ALTCHA form field to the form generator
  composer.json
  core-bundle/composer.json
  core-bundle/config/controller.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/config/config.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/forms/FormAltcha.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_form_field.xlf
  core-bundle/contao/templates/forms/form_altcha.html5
  core-bundle/src/Altcha/Altcha.php
  core-bundle/src/Altcha/AltchaChallenge.php
  core-bundle/src/Altcha/Config/Algorithm.php
  core-bundle/src/Altcha/Exception/InvalidAlgorithmException.php
  core-bundle/src/Controller/AltchaController.php
  core-bundle/src/Cron/PurgeExpiredAltchaChallengesCron.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Entity/Altcha.php
  core-bundle/src/Repository/AltchaRepository.php
  core-bundle/tests/Altcha/AltchaTest.php
  depcheck.php
Labels: feature

#7094 Move the `assets` folder to `public/assets`
  core-bundle/README.md
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/PurgeData.php
  core-bundle/contao/config/config.php
  core-bundle/contao/library/Contao/Automator.php
  core-bundle/contao/library/Contao/Combiner.php
  core-bundle/contao/library/Contao/Image.php
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/Command/InstallCommandTest.php
  core-bundle/tests/Command/SymlinksCommandTest.php
  core-bundle/tests/Contao/CombinerTest.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Fixtures/assets/.gitkeep
  core-bundle/tests/Image/ImageFactoryTest.php
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
Labels: feature

#7320 Handle `.<ext>.twig` file extensions in DC_Folder
  core-bundle/contao/drivers/DC_Folder.php
Labels: bug

#7319 Generate public URIs for automatically mounted adapters replacing symlinks
  composer.json
  core-bundle/composer.json
  core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php
  core-bundle/src/Filesystem/PublicUri/SymlinkedLocalFilesProvider.php
  core-bundle/tests/DependencyInjection/Compiler/ConfigureFilesystemPassTest.php
  core-bundle/tests/Filesystem/PublicUri/SymlinkedLocalFilesProviderTest.php
Labels: bug

#6999 Add Twig slots
  core-bundle/config/services.yaml
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Inspector/InspectionException.php
  core-bundle/src/Twig/Inspector/Inspector.php
  core-bundle/src/Twig/Inspector/InspectorNodeVisitor.php
  core-bundle/src/Twig/Inspector/TemplateInformation.php
  core-bundle/src/Twig/Slots/SlotNode.php
  core-bundle/src/Twig/Slots/SlotTokenParser.php
  core-bundle/tests/Command/DebugContaoTwigCommandTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/DeprecationsNodeVisitorTest.php
  core-bundle/tests/Twig/Extension/InsertTagTest.php
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Inspector/ContaoInspectorNodeVisitorTest.php
  core-bundle/tests/Twig/Inspector/InspectorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/ResponseContext/AddTokenParserTest.php
  core-bundle/tests/Twig/Slots/SlotNodeTest.php
  core-bundle/tests/Twig/Slots/SlotTokenParserTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: feature

#7273 Store the back end popup session bag under a different storage key
  core-bundle/config/services.yaml
  core-bundle/src/EventListener/UserSessionListener.php
  core-bundle/src/Session/SessionFactory.php
  core-bundle/tests/EventListener/UserSessionListenerTest.php
  core-bundle/tests/Session/SessionFactoryTest.php
Labels: feature

#7011 Add basic support for `hotwired/turbo` in the back end
  core-bundle/assets/backend.js
  core-bundle/contao/controllers/BackendMain.php
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/contao/templates/backend/be_ace.html5
  core-bundle/contao/templates/backend/be_login.html5
  core-bundle/contao/templates/backend/be_login_two_factor.html5
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/contao/templates/backend/be_password.html5
  core-bundle/contao/widgets/SerpPreview.php
  core-bundle/public/backend.147aae9f.js
  core-bundle/public/backend.147aae9f.js.map
  core-bundle/public/backend.2029a2c6.js
  core-bundle/public/backend.2029a2c6.js.LICENSE.txt
  core-bundle/public/backend.2029a2c6.js.map
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/src/EventListener/Menu/BackendLogoutListener.php
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/tests/EventListener/Menu/BackendLogoutListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
  package.json
  yarn.lock
Labels: feature

#7325 Update and run the tools
  UPGRADE.md
  core-bundle/contao/library/Contao/Input.php
  core-bundle/public/backend.00ac4bbf.js
  core-bundle/public/backend.00ac4bbf.js.LICENSE.txt
  core-bundle/public/backend.00ac4bbf.js.map
  core-bundle/public/backend.2029a2c6.js
  core-bundle/public/backend.2029a2c6.js.map
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Controller/ContentElement/AbstractDownloadContentElementController.php
  core-bundle/src/Csp/CspParser.php
  core-bundle/src/EventListener/DataContainer/CteAliasListener.php
  core-bundle/src/EventListener/DataContainer/FrontendModulePermissionsListener.php
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/src/EventListener/PageAccessListener.php
  core-bundle/src/EventListener/RequestTokenListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/Routing/Candidates/PageCandidates.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/JsonLd/ContaoPageSchema.php
  core-bundle/src/Security/Voter/DataContainer/PageTypeAccessVoter.php
  core-bundle/src/Security/Voter/DataContainer/UserAccessVoter.php
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/Contao/ArrayUtilTest.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/EventListener/CspReportListenerTest.php
  core-bundle/tests/EventListener/HttpCache/StripQueryParametersSubscriberTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  manager-bundle/tests/ContaoManagerBundleTest.php
  package.json
  vendor-bin/depcheck/composer.lock
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
  vendor-bin/service-linter/src/LintServiceIdsCommand.php
  yarn.lock
Labels: CI

#7209 Add an "ARIA label" field to the navigation module
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_module.xlf
  core-bundle/contao/library/Contao/Pagination.php
  core-bundle/contao/models/ModuleModel.php
  core-bundle/contao/modules/Module.php
  core-bundle/contao/modules/ModuleNavigation.php
  core-bundle/contao/templates/backend/be_pagination.html5
  core-bundle/contao/templates/elements/ce_sliderStop.html5
  core-bundle/contao/templates/modules/mod_breadcrumb.html5
  core-bundle/contao/templates/modules/mod_navigation.html5
  core-bundle/contao/templates/pagination/pagination.html5
  core-bundle/tests/Controller/FrontendModule/FeedReaderControllerTest.php
Labels: feature

#7326 Use the minified version of the ALTCHA scripts
  composer.json
  core-bundle/composer.json
  core-bundle/contao/templates/forms/form_altcha.html5
Labels: bug

#7323 Fix the login state for two factor authentication
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/tests/Security/Voter/MemberGroupVoterTest.php
Labels: bug

#7330 Merge branch '4.13' into 5.3
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/tests/EventListener/CspReportListenerTest.php
  core-bundle/tests/Security/Voter/MemberGroupVoterTest.php
Labels: release

#7328 Add `@return never` to methods that never return
  core-bundle/src/Resources/contao/classes/Ajax.php
  core-bundle/src/Resources/contao/dca/tl_templates.php
  core-bundle/src/Resources/contao/library/Contao/Controller.php
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Resources/contao/library/Contao/User.php
Labels: CI

#7332 Handle routing errors when trying to render the error screen
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
Labels: bug

#7316 Introduce a `Template::once()` method
  calendar-bundle/src/Resources/contao/classes/Events.php
  calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  news-bundle/src/Resources/contao/modules/ModuleNews.php
Labels: bug

#7327 Add the `:never` return type to methods that never return
  core-bundle/contao/classes/Ajax.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/library/Contao/File.php
Labels: bug

#7334 Merge branch '4.13' into 5.3
  calendar-bundle/contao/classes/Events.php
  calendar-bundle/contao/modules/ModuleEventReader.php
  core-bundle/contao/library/Contao/Template.php
  core-bundle/tests/Twig/FragmentTemplateTest.php
  news-bundle/contao/modules/ModuleNews.php
Labels: release

#7340 Ignore duplicate opt-in submissions
  comments-bundle/src/Resources/contao/classes/Comments.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
  newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php
Labels: bug

#7345 Adjust the Cypress workflow
  .github/workflows/cypress.yml
Labels: CI

#7346 Update and run the tools
  README.md
  core-bundle/src/Resources/contao/library/Contao/File.php
  core-bundle/src/Resources/contao/library/Contao/Template.php
  core-bundle/tests/Contao/ControllerTest.php
  tools/isolated-tests/composer.lock
  tools/phpstan/composer.lock
  tools/require-checker/composer.lock
  tools/service-linter/composer.lock
Labels: CI

#7347 Update and run the tools
  core-bundle/contao/library/Contao/Input.php
  core-bundle/src/Command/UserCreateCommand.php
  core-bundle/src/Controller/ContentElement/AbstractDownloadContentElementController.php
  core-bundle/src/Csp/CspParser.php
  core-bundle/src/EventListener/DataContainer/CteAliasListener.php
  core-bundle/src/EventListener/DataContainer/FrontendModulePermissionsListener.php
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/src/EventListener/PageAccessListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/src/Picker/PagePickerProvider.php
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/src/Routing/Candidates/PageCandidates.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/JsonLd/ContaoPageSchema.php
  core-bundle/src/Security/Voter/DataContainer/PageTypeAccessVoter.php
  core-bundle/src/Security/Voter/DataContainer/UserAccessVoter.php
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/tests/Contao/ArrayUtilTest.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/EventListener/HttpCache/StripQueryParametersSubscriberTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  manager-bundle/tests/ContaoManagerBundleTest.php
  vendor-bin/depcheck/composer.lock
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
  vendor-bin/service-linter/src/LintServiceIdsCommand.php
Labels: CI

#7348 Cleanup a leftover service argument
  core-bundle/config/services.yaml
Labels: bug

#7356 Allow .ics file uploads and downloads
  core-bundle/src/Resources/contao/config/default.php
Labels: bug, unconfirmed

#7357 Skip database backups if the remaining migrations will not be executed
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: bug

#7358 Use the widget attributes to generate the DCA row
  core-bundle/contao/classes/DataContainer.php
Labels: bug

#7359 Fix a PHP8 error when sending newsletters
  newsletter-bundle/src/Resources/contao/classes/Newsletter.php
Labels: bug

#7364 Use the modified element when cloning
  core-bundle/contao/library/Contao/Controller.php
Labels: bug

#7371 Add the `playerColor` migration
  core-bundle/src/Migration/Version413/PlayerColorMigration.php
  core-bundle/src/Resources/config/migrations.yml
Labels: bug

#7350 Ignore deleted cookies in the `CsrfTokenCookieSubscriber`
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
Labels: bug

#7375 Merge branch '4.13' into 5.3
  comments-bundle/contao/classes/Comments.php
  core-bundle/contao/config/default.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
  newsletter-bundle/contao/modules/ModuleSubscribe.php
Labels: release

#7379 Fix a PHP8 error if a user has no groups
  core-bundle/src/Resources/contao/dca/tl_article.php
Labels: bug

#7378 Disable Turbo on `editAll` and `overrideAll` forms
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#7376 Skip database backups if the remaining migrations will not be executed
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/tests/Command/MigrateCommandTest.php
Labels: bug

#7373 Fix the `contao-setup` command
  core-bundle/config/commands.yaml
  core-bundle/src/Command/InstallCommand.php
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/tests/Command/InstallCommandTest.php
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
Labels: bug

#7384 Show a warning if ALTCHA is used with an insecure connection
  core-bundle/contao/forms/FormAltcha.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/templates/forms/form_altcha.html5
Labels: bug

#7387 Load the TinyMCE and ACE scripts within `be_main`
  core-bundle/contao/templates/backend/be_ace.html5
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/contao/templates/backend/be_tinyMCE.html5
Labels: bug
