Repository contao/contao, pull requests merged in 2024-02, with the labels that each got.

#6805 Correctly handle denied access in the firewall
  core-bundle/README.md
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/ModuleChangePassword.php
  core-bundle/contao/modules/ModuleLogin.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/templates/modules/mod_login.html5
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/EventListener/ExceptionConverterListener.php
  core-bundle/src/EventListener/PrettyErrorScreenListener.php
  core-bundle/src/EventListener/Security/TwoFactorFrontendListener.php
  core-bundle/src/Security/Authentication/AccessDeniedHandler.php
  core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/EventListener/ExceptionConverterListenerTest.php
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  core-bundle/tests/EventListener/Security/TwoFactorFrontendListenerTest.php
  core-bundle/tests/Functional/app/config/security.yaml
  core-bundle/tests/Security/Authenticator/ContaoLoginAuthenticatorTest.php
  manager-bundle/skeleton/config/security.yaml
Labels: bug

#6830 Fix the order of the content elements
  core-bundle/contao/config/config.php
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/src/EventListener/GlobalsMapListener.php
  core-bundle/tests/EventListener/GlobalsMapListenerTest.php
Labels: bug

#6825 Add a foreign key declaration for form and module fields
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#6828 Do not display deleted authors in news
  news-bundle/contao/modules/ModuleNews.php
Labels: bug, unconfirmed

#6837 Fix the Cypress tests
  core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php
  cypress/bin/run-e2e
Labels: CI

#6831 Correctly set the target path in the login module
  core-bundle/contao/modules/ModuleLogin.php
Labels: bug

#6803 Fix the referrer URL if elements are moved inside a nested element
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#6835 Do not require full authentication in the "change password" module
  core-bundle/contao/modules/ModuleChangePassword.php
Labels: bug

#6841 Remove obsolete hardcoded configuration in page registry
  core-bundle/src/Routing/Page/PageRegistry.php
Labels: bug

#6826 Randomize CSRF tokens once per request
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/tests/Csrf/ContaoCsrfTokenManagerTest.php
Labels: bug

#6840 Keep login module errors
  core-bundle/contao/modules/ModuleLogin.php
Labels: bug

#6845 Remove the `web_dir` node in the `Configuration` class
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: bug

#6843 Fix relative front end preview links
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/tests/Controller/BackendPreviewControllerTest.php
Labels: bug

#6848 Improve the `ConfigureFilesystemPass` performance
  core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php
Labels: bug

#6849 Add the missing use statement for `FormHidden`
  core-bundle/src/Resources/contao/dca/tl_form_field.php
Labels: bug

#6833 Handle dynamic parent tables in the `Controller::getParentEntries()` method
  core-bundle/contao/library/Contao/Controller.php
Labels: bug

#6832 Do not load the sitemap from cache for authenticated users
  core-bundle/src/Controller/SitemapController.php
  core-bundle/tests/Controller/SitemapControllerTest.php
Labels: bug

#6851 Rewrite `Controller::getParentEntries()`
  core-bundle/contao/library/Contao/Controller.php
Labels: bug

#6855 Cast the template identifier to string
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
Labels: bug

#6858 Remove the `@internal` flag from the backup manager
  core-bundle/src/Doctrine/Backup/BackupManager.php
Labels: feature

#6857 Fix the "remember me" migration
  core-bundle/src/Migration/Version503/RememberMeMigration.php
Labels: bug

#6856 Add the "toggle visibility" button for articles and content elements again
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
Labels: bug

#6867 Correctly initialize multiple accordions on the same page
  core-bundle/contao/templates/twig/content_element/accordion.html.twig
Labels: bug

#6868 Do not add duplicate paths in our own Twig filesystem loader
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: bug

#6852 Fix the `TemplateOptionsListener`
  core-bundle/config/listener.yaml
  core-bundle/src/ContaoCoreBundle.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
Labels: bug

#6879 Update and run the tools
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/EventListener/MergeHttpHeadersListenerTest.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  core-bundle/tests/Image/PictureFactoryTest.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
  core-bundle/tests/Routing/ContentUrlGeneratorTest.php
  tools/ecs/composer.lock
  tools/ecs/config/legacy.php
  tools/ecs/config/template.php
Labels: CI

#6872 Correctly update the file name when synchronizing the DBAFS
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
Labels: bug

#6870 Improve the CAPTCHA
  core-bundle/src/Controller/CaptchaController.php
  core-bundle/src/Resources/contao/forms/FormCaptcha.php
  core-bundle/src/Resources/contao/templates/forms/form_captcha.html5
Labels: bug

#6883 Merge branch '4.13' into 5.2
  core-bundle/contao/forms/FormCaptcha.php
  core-bundle/contao/templates/forms/form_captcha.html5
  core-bundle/src/Controller/CaptchaController.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: release

#6814 Allow adding a source to multiple CSP directives at once
  core-bundle/contao/library/Contao/TemplateTrait.php
  core-bundle/src/Twig/Runtime/CspRuntime.php
  core-bundle/tests/Twig/Runtime/CspRuntimeTest.php
Labels: feature

#6880 Correctly handle dark icons in `data-icon` and `data-icon-disabled`
  core-bundle/contao/library/Contao/Image.php
Labels: bug

#6892 Merge the `Cache-Control` header in `PageRegular`
  core-bundle/src/Resources/contao/pages/PageRegular.php
Labels: bug

#6890 Always allow the "read" action in the front end modules voter
  core-bundle/src/Security/Voter/DataContainer/FrontendModulesVoter.php
  core-bundle/tests/Security/Voter/DataContainer/FrontendModulesVoterTest.php
Labels: bug

#6889 Correctly cache Contao translations that only exist as Symfony translations
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
Labels: bug

#6893 Move adding the schema.org data to the `_download.html.twig` component
  core-bundle/contao/templates/twig/component/_download.html.twig
  core-bundle/contao/templates/twig/content_element/downloads.html.twig
Labels: bug

#6897 Fix table picker for tables without parents
  core-bundle/src/Picker/AbstractTablePickerProvider.php
  core-bundle/tests/Picker/TablePickerProviderTest.php
Labels: bug

#6895 Fix the column name in the "remember me" migration
  core-bundle/src/Migration/Version503/RememberMeMigration.php
Labels: bug

#6899 Add the missing CSP nonce in the `form_wrapper.html5` template
  core-bundle/contao/templates/forms/form_wrapper.html5
Labels: bug

#6898 Add `type="button"` to the accordion toggler
  core-bundle/contao/templates/twig/content_element/accordion.html.twig
  core-bundle/tests/Controller/ContentElement/AccordionControllerTest.php
Labels: bug

#6900 Improve logging of request parameters
  manager-bundle/config/services.yaml
  manager-bundle/src/Monolog/RequestProcessor.php
  manager-bundle/tests/Monolog/RequestProcessorTest.php
Labels: bug

#6854 Handle routing exceptions during news and event URL generation
  calendar-bundle/contao/classes/Events.php
  news-bundle/contao/classes/News.php
  news-bundle/contao/modules/ModuleNews.php
Labels: bug

#6909 Also strip query parameter from `QUERY_STRING` variable in `ServerBag`
  core-bundle/src/EventListener/HttpCache/StripQueryParametersSubscriber.php
  core-bundle/tests/EventListener/HttpCache/StripQueryParametersSubscriberTest.php
Labels: bug

#6906 Update the `tstamp` column only on `tl_files` in the DBAFS
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
Labels: bug

#6912 Inconsistent use of `findById()` and `findByPk()`
  calendar-bundle/contao/classes/Calendar.php
  calendar-bundle/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Picker/EventPickerProvider.php
  calendar-bundle/tests/Picker/EventPickerProviderTest.php
  core-bundle/contao/forms/Form.php
  core-bundle/src/EventListener/DataContainer/Undo/LabelListener.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/tests/EventListener/DataContainer/Undo/LabelListenerTest.php
  faq-bundle/contao/modules/ModuleFaqReader.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  faq-bundle/tests/Picker/FaqPickerProviderTest.php
  news-bundle/contao/modules/ModuleNewsReader.php
  news-bundle/src/Picker/NewsPickerProvider.php
  news-bundle/tests/Picker/NewsPickerProviderTest.php
  newsletter-bundle/contao/modules/ModuleNewsletterReader.php
Labels: CI

#6846 Allow to configure the components-dir
  core-bundle/config/commands.yaml
  core-bundle/src/Command/SymlinksCommand.php
  core-bundle/src/DependencyInjection/Compiler/AddAssetsPackagesPass.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/Command/SymlinksCommandTest.php
Labels: feature

#6918 Update and run the tools
  core-bundle/src/Intl/Countries.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
  tools/ecs/composer.lock
  tools/phpstan/composer.json
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: CI

#6917 Fix two CSS issues
  core-bundle/contao/themes/flexible/backend.51223d60.css
  core-bundle/contao/themes/flexible/backend.51223d60.css.map
  core-bundle/contao/themes/flexible/backend.bb890b0a.css
  core-bundle/contao/themes/flexible/backend.bb890b0a.css.map
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/main.css
Labels: bug

#6905 Camelize the file system service argument
  core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php
Labels: bug

#6936 Fix the Twig loader infrastructure
  core-bundle/config/commands.yaml
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/src/Command/DebugContaoTwigCommand.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/src/EventListener/DataContainer/ThemeTemplatesListener.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Finder/Finder.php
  core-bundle/src/Twig/Finder/FinderFactory.php
  core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicUseTokenParser.php
  core-bundle/src/Twig/Inheritance/TemplateHierarchyInterface.php
  core-bundle/src/Twig/Loader/AutoRefreshTemplateHierarchyListener.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php
  core-bundle/tests/Command/DebugContaoTwigCommandTest.php
  core-bundle/tests/Contao/TemplateLoaderTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/EventListener/DataContainer/TemplateOptionsListenerTest.php
  core-bundle/tests/EventListener/DataContainer/ThemeTemplatesListenerTest.php
  core-bundle/tests/Fixtures/Twig/default-project/.gitkeep
  core-bundle/tests/Fixtures/Twig/paths/1/templates/1.html.twig
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/DeprecationsNodeVisitorTest.php
  core-bundle/tests/Twig/Extension/InsertTagTest.php
  core-bundle/tests/Twig/Finder/FinderTest.php
  core-bundle/tests/Twig/Inheritance/DynamicExtendsTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/DynamicIncludeTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Loader/AutoRefreshTemplateHierarchyListenerTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderWarmerTest.php
  core-bundle/tests/Twig/ResponseContext/AddTokenParserTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: bug

#6939 Correctly implement the `ImageFactoryInterface`
  core-bundle/src/Image/ImageFactory.php
Labels: bug

#6938 Add a button to the "invalid request token" template
  core-bundle/contao/languages/en/exception.xlf
  core-bundle/templates/Error/invalid_request_token.html.twig
  core-bundle/templates/Error/layout.html.twig
Labels: bug

#6940 Handle unicode strings in insert tag flags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
  core-bundle/tests/Contao/InsertTagsTest.php
Labels: bug

#6919 Make full authentication optional in the personal data module
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/languages/en/tl_module.xlf
  core-bundle/contao/models/ModuleModel.php
  core-bundle/contao/modules/Module.php
  core-bundle/contao/modules/ModulePersonalData.php
Labels: bug

#6944 Correctly check if a "jump to" page is set when generating event feeds
  calendar-bundle/contao/classes/Calendar.php
Labels: bug

#6946 Improve the performance of the database dumper
  core-bundle/src/Doctrine/Backup/Dumper.php
Labels: bug

#6943 Correctly generate the URLs to subscribe to comments
  comments-bundle/contao/classes/Comments.php
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/tests/Util/UrlUtilTest.php
  newsletter-bundle/contao/classes/Newsletter.php
Labels: bug

#6951 Fix that the guests migration only migrates one field at a time
  core-bundle/src/Migration/Version500/AbstractGuestsMigration.php
Labels: bug

#6950 Correctly register the `AutoRefreshTemplateHierarchyListener`
  core-bundle/config/listener.yaml
Labels: bug

#6954 Register the `dotenv:dump` command by default in the Contao managed edition
  manager-bundle/config/services.yaml
Labels: feature
