Repository contao/contao, pull requests merged in 2024-11, with the labels that each got.

#7692 Fix typo for purge XML files
  core-bundle/src/Resources/contao/languages/en/tl_maintenance.xlf
Labels: bug

#7629 Use UTC in `BackupListCommandTest`
  core-bundle/tests/Command/Backup/BackupListCommandTest.php
Labels: bug

#7605 Fix login redirect and session usage
  core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php
  core-bundle/tests/Security/Authentication/AuthenticationEntryPointTest.php
Labels: bug

#7595 Add the `resampling-filter` Imagine option
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: bug

#7559 Fix warning in `ModuleRegistration` if editable field does not exist anymore
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug

#7545 Add `includeBlankOption` for `module` and `form` content element
  core-bundle/src/Resources/contao/dca/tl_content.php
Labels: bug

#7696 Fix the unit tests
  core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/require-checker/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7550 Delete related opt-in tokens after a password change
  core-bundle/src/Resources/contao/models/OptInModel.php
  core-bundle/src/Resources/contao/modules/ModuleChangePassword.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
Labels: bug

#7564 Decode entities in the `CustomRgxpListener`
  core-bundle/src/EventListener/Widget/CustomRgxpListener.php
  core-bundle/tests/EventListener/Widget/CustomRgxpListenerTest.php
Labels: bug

#7444 Use the service ID instead of the class name for cron jobs
  core-bundle/src/Cron/CronJob.php
  core-bundle/src/DependencyInjection/Compiler/AddCronJobsPass.php
  core-bundle/tests/DependencyInjection/Compiler/AddCronJobsPassTest.php
Labels: bug

#7480 Fix search results overwriting root limit
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#7701 Use the return value of the `InvalidateCacheTagsEvent`
  core-bundle/src/Cache/CacheTagInvalidator.php
Labels: bug

#7581 Add a rate limit for password resets
  core-bundle/src/Resources/contao/languages/en/default.xlf
  core-bundle/src/Resources/contao/models/OptInModel.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
Labels: bug

#7705 Merge branch '4.13' into 5.3
  README.md
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_maintenance.xlf
  core-bundle/contao/models/OptInModel.php
  core-bundle/contao/modules/ModuleChangePassword.php
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/src/Cron/CronJob.php
  core-bundle/src/DependencyInjection/Compiler/AddCronJobsPass.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/src/EventListener/Widget/CustomRgxpListener.php
  core-bundle/tests/DependencyInjection/Compiler/AddCronJobsPassTest.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/EventListener/Widget/CustomRgxpListenerTest.php
Labels: release

#7703 Backport the VFS interface adjustments
  core-bundle/src/EventListener/DbafsMetadataSubscriber.php
  core-bundle/src/Filesystem/Dbafs/AbstractDbafsMetadataEvent.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Filesystem/Dbafs/DbafsInterface.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Filesystem/Dbafs/RetrieveDbafsMetadataEvent.php
  core-bundle/src/Filesystem/ExtraMetadata.php
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/src/Filesystem/VirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemInterface.php
  core-bundle/tests/EventListener/DbafsMetadataSubscriberTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Filesystem/Dbafs/RetrieveDbafsMetadataEventTest.php
  core-bundle/tests/Filesystem/Dbafs/StoreDbafsMetadataEventTest.php
  core-bundle/tests/Filesystem/ExtraMetadataTest.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
Labels: bug

#7713 Use the `RateLimiter` component to limit password reset requests
  composer.json
  core-bundle/composer.json
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/models/OptInModel.php
  core-bundle/src/Resources/contao/modules/ModulePassword.php
Labels: bug

#7717 Use the `RateLimiter` component to limit password reset requests
  core-bundle/config/services.yaml
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/modules/ModuleLostPassword.php
Labels: bug

#7708 Decode entities for favorites labels
  core-bundle/src/EventListener/Menu/BackendFavoritesListener.php
  core-bundle/tests/EventListener/Menu/BackendFavoritesListenerTest.php
Labels: bug

#7712 Fix the permissions check for "save and duplicate"
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
Labels: bug

#7716 Fix login redirect and session usage
  core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php
  core-bundle/tests/Security/Authenticator/ContaoLoginAuthenticatorTest.php
Labels: bug

#7715 Consider the `doNotDeleteRecords` setting when deleting child records
  core-bundle/contao/drivers/DC_Table.php
Labels: bug, unconfirmed

#7720 Cache hot path in model
  core-bundle/contao/library/Contao/Model.php
Labels: bug

#7726 Fix the CI chain
  composer.json
  core-bundle/composer.json
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/Controller/BackendCsvImportController.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  depcheck.php
  newsletter-bundle/contao/classes/Newsletter.php
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7699 Do not load the CAPTCHA script in the back end preview
  core-bundle/contao/library/Contao/Template.php
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/contao/templates/forms/form_captcha.html5
Labels: bug

#7670 Prevent possible type error in `DC_Table::getClipboardPermission`
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#7727 Make the abstract entities migration case-sensitive
  core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php
Labels: bug

#7729 Allow basic entities in section headlines
  core-bundle/contao/dca/tl_content.php
Labels: bug

#7730 Show section headlines in the back end preview
  core-bundle/contao/dca/tl_content.php
Labels: bug

#7724 Canonicalize purge paths
  core-bundle/contao/classes/PurgeData.php
Labels: bug

#7723 Add an ALTCHA noscript warning message
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/templates/forms/form_altcha.html5
Labels: bug

#7725 Cache hot path in model
  core-bundle/src/Resources/contao/library/Contao/Model.php
Labels: bug

#7737 Revert 'Add the `turbo-root` meta tag to the back end'
  core-bundle/contao/controllers/BackendMain.php
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/tests/Controller/AbstractBackendControllerTest.php
Labels: bug

#7736 Disable Turbo in `MODE_PARENT` content section
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#7711 Upgrade to PHPStan 2
  .github/workflows/ci.yml
  core-bundle/src/Controller/AbstractBackendController.php
  core-bundle/src/Csp/WysiwygStyleProcessor.php
  core-bundle/src/DataContainer/PaletteManipulator.php
  core-bundle/src/Doctrine/ORM/FailTolerantProxyCacheWarmer.php
  core-bundle/src/Security/User/ContaoUserProvider.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/src/Security/Voter/BackendSearch/ProviderDelegatingVoter.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Csrf/MemoryTokenStorageTest.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  core-bundle/tests/EventListener/DataContainer/EnumOptionsListenerTest.php
  core-bundle/tests/EventListener/DataContainer/LayoutOptionsListenerTest.php
  core-bundle/tests/EventListener/DbafsMetadataSubscriberTest.php
  core-bundle/tests/EventListener/MergeHttpHeadersListenerTest.php
  core-bundle/tests/Filesystem/MountManagerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/ImageSizesTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Intl/CountriesTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Session/Attribute/ArrayAttributeBagTest.php
  core-bundle/tests/Translation/DataCollectorTranslatorTest.php
  core-bundle/tests/Twig/Interop/ContextFactoryTest.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
  vendor-bin/phpstan/composer.lock
Labels: CI

#7739 Fix a JS performance issue related to the registration of tooltips
  core-bundle/assets/controllers/tooltip-controller.js
  core-bundle/assets/controllers/tooltips-controller.js
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/public/backend.115fc204.js
  core-bundle/public/backend.115fc204.js.LICENSE.txt
  core-bundle/public/backend.3db086cc.js
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug

#7738 Allow events to format DC_Table search results
  core-bundle/config/backend_search.yaml
  core-bundle/src/Search/Backend/Event/FormatTableDataContainerDocumentEvent.php
  core-bundle/src/Search/Backend/EventListener/FormatCoreWidgetSearchResultsListener.php
  core-bundle/src/Search/Backend/Provider/TableDataContainerProvider.php
  core-bundle/tests/Search/Backend/Event/FormatTableDataContainerDocumentEventTest.php
  core-bundle/tests/Search/Backend/EventListener/FormatCoreWidgetSearchResultsListenerTest.php
  core-bundle/tests/Search/Backend/Provider/TableDataContainerProviderTest.php
Labels: feature

#7721 Fix the delete API of the back end search
  core-bundle/src/Messenger/Message/BackendSearch/DeleteDocumentsMessage.php
  core-bundle/src/Messenger/MessageHandler/BackendSearch/DeleteDocumentsMessageHandler.php
  core-bundle/src/Search/Backend/BackendSearch.php
  core-bundle/tests/Messenger/Message/BackendSearch/DeleteDocumentsMessageTest.php
  core-bundle/tests/Messenger/MessageHandler/BackendSearch/DeleteDocumentsMessageHandlerTest.php
  core-bundle/tests/Search/Backend/BackendSearchTest.php
Labels: feature

#7691 Fix the partials regex in the Twig template finder
  core-bundle/src/Twig/Finder/Finder.php
  core-bundle/tests/Twig/Finder/FinderTest.php
Labels: bug

#7681 Add IDE autocompletion for core templates
  core-bundle/contao/templates/twig/ide-twig.json
Labels: feature

#7744 Fix the "lost password" module
  core-bundle/contao/modules/ModuleLostPassword.php
Labels: bug

#7745 Add the isolated tests again
  vendor-bin/isolated-tests/bin/run-tests-isolated
  vendor-bin/isolated-tests/composer.json
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/isolated-tests/src/RunTestsIsolatedCommand.php
Labels: CI

#7604 Implement subtitles and CC functionality for videos
  core-bundle/config/listener.yaml
  core-bundle/contao/config/default.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_files.php
  core-bundle/contao/languages/en/tl_content.xlf
  core-bundle/contao/languages/en/tl_files.xlf
  core-bundle/contao/models/ContentModel.php
  core-bundle/contao/models/FilesModel.php
  core-bundle/contao/templates/twig/content_element/player.html.twig
  core-bundle/src/Controller/ContentElement/PlayerController.php
  core-bundle/src/EventListener/DataContainer/TrackFieldsListener.php
  core-bundle/src/EventListener/DbafsMetadataSubscriber.php
  core-bundle/src/File/TextTrack.php
  core-bundle/src/File/TextTrackType.php
  core-bundle/src/Filesystem/ExtraMetadata.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/PlayerControllerTest.php
  core-bundle/tests/EventListener/DataContainer/TrackFieldsListenerTest.php
  core-bundle/tests/EventListener/DbafsMetadataSubscriberTest.php
Labels: feature

#7749 Make Contao 5.3 compatible with PHP 8.4
  composer.json
  core-bundle/composer.json
Labels: bug

#7600 Fix prefetching of edit, children and select links
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/assets/backend.js
  core-bundle/assets/controllers/deeplink-controller.js
  core-bundle/assets/scripts/core.js
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/dca/tl_files.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/public/backend.13a53486.js
  core-bundle/public/backend.24438c49.js
  core-bundle/public/backend.24438c49.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/src/DataContainer/DataContainerOperationsBuilder.php
  core-bundle/src/EventListener/DataContainer/DefaultGlobalOperationsListener.php
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  newsletter-bundle/contao/dca/tl_newsletter.php
Labels: bug

#7750 Handle null result in 404 router provider
  core-bundle/src/Routing/Route404Provider.php
Labels: bug

#7556 Enable double encoding for JSON in Twig
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/src/Twig/Interop/ContaoEscaper.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/tests/String/HtmlAttributesTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperTest.php
Labels: bug

#7753 Replace insert tags in Twig surrogate parent templates
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: bug

#7752 Fix the sorting when copying multiple form fields as a non-admin user
  core-bundle/contao/dca/tl_form_field.php
Labels: bug
