Repository contao/contao, pull requests merged in 2024-06, with the labels that each got.

#7264 Replace non-routable URLs with an empty string for the `{{link*}}` insert tags
  core-bundle/src/Resources/contao/library/Contao/InsertTags.php
Labels: bug

#7266 Delete search index entries under more specific conditions
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
Labels: bug

#7263 Handle failed `preg_split()` return values for image sources
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
Labels: bug

#7262 Remove the process timeout in the `SuperviseWorkersCommand`
  core-bundle/src/Command/SuperviseWorkersCommand.php
  core-bundle/src/Cron/SuperviseWorkersCron.php
Labels: bug

#7259 Use `array_is_list()` instead of `ArrayUtil::isAssoc()` where possible
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
  core-bundle/tests/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPassTest.php
  core-bundle/tests/Intl/CountriesTest.php
  core-bundle/tests/Intl/LocalesTest.php
Labels: CI

#6731 Add sitemap information to the `tl_page.robots` help text
  core-bundle/contao/languages/en/tl_page.xlf
Labels: feature

#7268 Initialize the Contao framework when working with opt-in tokens
  core-bundle/src/OptIn/OptIn.php
Labels: bug

#7270 Replace non-routable URLs with an empty string for the `{{link*}}` insert tags
  core-bundle/src/InsertTag/Resolver/LinkInsertTag.php
Labels: bug

#7277 Improve the docs of `quoteIdentifier()` and `findInSet()`
  core-bundle/src/Resources/contao/library/Contao/Database.php
Labels: bug

#7282 Check CSRF and private response after the session
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/MakeResponsePrivateListenerTest.php
Labels: bug

#7281 Check CSRF and private response after the session
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/EventListener/MakeResponsePrivateListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/MakeResponsePrivateListenerTest.php
Labels: bug

#7283 Use the translator language instead of the request language for the `iflng` and `ifnlng` insert tags
  core-bundle/config/services.yaml
  core-bundle/src/InsertTag/Resolver/IfLanguageInsertTag.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddInsertTagsPassTest.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
Labels: bug

#7287 Fix missing query parameters in the file insert tag
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
Labels: bug

#7285 Decouple the locale subscriber test from the request implementation
  core-bundle/tests/EventListener/LocaleSubscriberTest.php
Labels: CI

#7289 Skip sleeping in messenger web worker
  core-bundle/src/Messenger/WebWorker.php
Labels: bug

#7296 Fix toggling nodes if there is no global operation
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#7275 Make ID always searchable in DC_Table
  core-bundle/src/Resources/contao/dca/tl_article.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_module.php
  core-bundle/src/Resources/contao/dca/tl_page.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#7292 Evaluate scripts in Ajax form responses
  core-bundle/contao/templates/forms/form_wrapper.html5
Labels: bug

#7302 Add the missing dark icons
  core-bundle/contao/themes/flexible/icons/article--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/children--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/copy--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/copychildren--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/cut--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/delete--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/diff--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/diffTemplate--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/edit--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/editor--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/error--dark.svg
  core-bundle/contao/themes/flexible/icons/error_401--dark.svg
  core-bundle/contao/themes/flexible/icons/error_403--dark.svg
  core-bundle/contao/themes/flexible/icons/error_404--dark.svg
  core-bundle/contao/themes/flexible/icons/error_503--dark.svg
  core-bundle/contao/themes/flexible/icons/featured--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/feed--dark.svg
  core-bundle/contao/themes/flexible/icons/feed_2--dark.svg
  core-bundle/contao/themes/flexible/icons/forward--dark.svg
  core-bundle/contao/themes/flexible/icons/forward_2--dark.svg
  core-bundle/contao/themes/flexible/icons/forward_4--dark.svg
  core-bundle/contao/themes/flexible/icons/forward_6--dark.svg
  core-bundle/contao/themes/flexible/icons/layout--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/logout--dark.svg
  core-bundle/contao/themes/flexible/icons/logout_2--dark.svg
  core-bundle/contao/themes/flexible/icons/logout_4--dark.svg
  core-bundle/contao/themes/flexible/icons/logout_6--dark.svg
  core-bundle/contao/themes/flexible/icons/modules--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/parent--dark.svg
  core-bundle/contao/themes/flexible/icons/parent--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/pasteafter--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/pasteinto--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/redirect--dark.svg
  core-bundle/contao/themes/flexible/icons/redirect_2--dark.svg
  core-bundle/contao/themes/flexible/icons/redirect_4--dark.svg
  core-bundle/contao/themes/flexible/icons/redirect_6--dark.svg
  core-bundle/contao/themes/flexible/icons/regular--dark.svg
  core-bundle/contao/themes/flexible/icons/regular_2--dark.svg
  core-bundle/contao/themes/flexible/icons/regular_4--dark.svg
  core-bundle/contao/themes/flexible/icons/regular_6--dark.svg
  core-bundle/contao/themes/flexible/icons/root--dark.svg
  core-bundle/contao/themes/flexible/icons/share--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/sizes--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/su--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/theme_export--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/undo--disabled--dark.svg
  core-bundle/contao/themes/flexible/icons/visible--disabled--dark.svg
Labels: bug

#7142 Update Monolog to version 3
  composer.json
  core-bundle/composer.json
  core-bundle/src/Command/CrawlCommand.php
  core-bundle/src/Crawl/Monolog/CrawlCsvLogHandler.php
  core-bundle/src/Monolog/ContaoTableHandler.php
  core-bundle/src/Monolog/ContaoTableProcessor.php
  core-bundle/tests/Crawl/Monolog/CrawlCsvLogHandlerTest.php
  core-bundle/tests/Monolog/ContaoTableHandlerTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
  manager-bundle/src/Monolog/RequestProcessor.php
  manager-bundle/tests/Monolog/RequestProcessorTest.php
Labels: feature

#7303 Merge branch '4.13' into 5.3
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_favorites.php
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/Database.php
  core-bundle/contao/library/Contao/StringUtil.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
Labels: release

#7294 Fix symlinked file not inside root directory
  core-bundle/config/services.yaml
  core-bundle/src/Image/Studio/FigureBuilder.php
Labels: bug

#7293 Prevent double form submission
  core-bundle/contao/templates/forms/form_wrapper.html5
Labels: bug

#7304 Update and run the tools
  core-bundle/contao/templates/forms/form_wrapper.html5
  core-bundle/src/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPass.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7300 Remove two leftover clearing DIVs
  core-bundle/contao/drivers/DC_Folder.php
Labels: bug

#7279 Allow Symfony 7
  .github/workflows/ci.yml
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  core-bundle/contao/library/Contao/User.php
  core-bundle/src/Config/Loader/PhpFileLoader.php
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/DoctrineSchemaListener.php
  core-bundle/src/Translation/DataCollectorTranslator.php
  core-bundle/tests/Controller/BackendPreviewSwitchControllerTest.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  core-bundle/tests/Translation/MessageCatalogueTest.php
  faq-bundle/composer.json
  listing-bundle/composer.json
  maker-bundle/composer.json
  manager-bundle/composer.json
  manager-bundle/skeleton/config/config.yaml
  news-bundle/composer.json
  newsletter-bundle/composer.json
  phpstan.neon
  test-case/composer.json
Labels: feature

#7180 Correctly show the file tree if the widget is restricted to a path
  core-bundle/src/Resources/contao/drivers/DC_Folder.php
Labels: bug

#7308 Merge branch '4.13' into 5.3
  .github/workflows/ci.yml
  core-bundle/contao/drivers/DC_Folder.php
Labels: release

#7309 Fix infinite loop in `encore dev --watch`
  webpack.config.js
Labels: bug

#7317 Fix missing submitter in form data
  core-bundle/contao/templates/forms/form_wrapper.html5
Labels: bug

#7315 Fix the priority of the web worker and improve memory handling
  core-bundle/src/Messenger/WebWorker.php
Labels: bug
