Repository contao/contao, pull requests merged in 2024-12, with the labels that each got.

#7761 Implement a re-index maintenance job for the back end search
  core-bundle/config/backend_search.yaml
  core-bundle/contao/classes/RebuildBackendSearchIndex.php
  core-bundle/contao/config/config.php
  core-bundle/contao/languages/en/tl_maintenance.xlf
  core-bundle/contao/templates/backend/be_rebuild_backend_search.html5
  core-bundle/src/Command/BackendSearch/IndexCommand.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Messenger/Message/BackendSearch/ReindexMessage.php
  core-bundle/src/Messenger/MessageHandler/BackendSearch/ReindexMessageHandler.php
  core-bundle/src/Messenger/WebWorker.php
  core-bundle/src/Search/Backend/BackendSearch.php
  core-bundle/src/Search/Backend/IndexUpdateConfig/IndexUpdateConfigInterface.php
  core-bundle/src/Search/Backend/IndexUpdateConfig/UpdateAllProvidersConfig.php
  core-bundle/src/Search/Backend/Provider/FilesStorageProvider.php
  core-bundle/src/Search/Backend/Provider/ProviderInterface.php
  core-bundle/src/Search/Backend/Provider/TableDataContainerProvider.php
  core-bundle/src/Search/Backend/ReindexConfig.php
  core-bundle/tests/Command/BackendSearch/IndexCommandTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Messenger/Message/BackendSearch/ReindexMessageTest.php
  core-bundle/tests/Messenger/MessageHandler/BackendSearch/ReindexMessageHandlerTest.php
  core-bundle/tests/Messenger/WebWorkerTest.php
  core-bundle/tests/Search/Backend/BackendSearchTest.php
  core-bundle/tests/Search/Backend/IndexUpdateConfig/UpdateAllProvidersConfigTest.php
  core-bundle/tests/Search/Backend/Provider/FilesStorageProviderTest.php
  core-bundle/tests/Search/Backend/Provider/TableDataContainerProviderTest.php
  core-bundle/tests/Search/Backend/ReindexConfigTest.php
Labels: feature

#7769 Implement search invalidation on DC_Table edits
  core-bundle/config/backend_search.yaml
  core-bundle/src/Command/BackendSearch/IndexCommand.php
  core-bundle/src/Messenger/Message/BackendSearch/DeleteDocumentsMessage.php
  core-bundle/src/Messenger/Message/BackendSearch/ReindexMessage.php
  core-bundle/src/Messenger/MessageHandler/BackendSearch/DeleteDocumentsMessageHandler.php
  core-bundle/src/Messenger/MessageHandler/BackendSearch/ReindexMessageHandler.php
  core-bundle/src/Search/Backend/BackendSearch.php
  core-bundle/src/Search/Backend/EventListener/TriggerReindexOnTableDataContainerInvalidationListener.php
  core-bundle/src/Search/Backend/GroupedDocumentIds.php
  core-bundle/src/Search/Backend/Provider/FilesStorageProvider.php
  core-bundle/src/Search/Backend/Provider/TableDataContainerProvider.php
  core-bundle/src/Search/Backend/ReindexConfig.php
  core-bundle/tests/Messenger/Message/BackendSearch/DeleteDocumentsMessageTest.php
  core-bundle/tests/Messenger/Message/BackendSearch/ReindexMessageTest.php
  core-bundle/tests/Messenger/MessageHandler/BackendSearch/DeleteDocumentsMessageHandlerTest.php
  core-bundle/tests/Messenger/MessageHandler/BackendSearch/ReindexMessageHandlerTest.php
  core-bundle/tests/Search/Backend/BackendSearchTest.php
  core-bundle/tests/Search/Backend/EventListener/FormatCoreWidgetSearchResultsListenerTest.php
  core-bundle/tests/Search/Backend/EventListener/TriggerReindexOnTableDataContainerInvalidationListenerTest.php
  core-bundle/tests/Search/Backend/GroupedDocumentIdsTest.php
  core-bundle/tests/Search/Backend/Provider/FilesStorageProviderTest.php
  core-bundle/tests/Search/Backend/ReindexConfigTest.php
Labels: feature

#7751 Make sure the correct test-case package is installed in Contao
  test-case/composer.json
Labels: bug

#7778 Do not normalize the `resampling-filter` array key
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: bug

#7767 Fix the base path for canonical URLs
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
Labels: bug

#7772 Use the correct session bag in the preview link listener
  calendar-bundle/contao/dca/tl_calendar_feed.php
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
Labels: bug

#7755 Handle ampersands in the alt attribute of the picture insert tag
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
Labels: bug, unconfirmed

#6493 Test the service arguments
  core-bundle/config/migrations.yaml
  core-bundle/config/services.yaml
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/String/SimpleTokenExpressionLanguage.php
  core-bundle/tests/Functional/ServiceArgumentsTest.php
Labels: CI

#7757 Disallow creating or updating elements with invalid parent record
  core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php
Labels: bug

#7773 Add the missing relations to the DCAs
  calendar-bundle/contao/dca/tl_calendar_feed.php
  calendar-bundle/contao/dca/tl_layout.php
  calendar-bundle/contao/dca/tl_module.php
  calendar-bundle/contao/dca/tl_user.php
  calendar-bundle/contao/dca/tl_user_group.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_preview_link.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  faq-bundle/contao/dca/tl_module.php
  faq-bundle/contao/dca/tl_user.php
  faq-bundle/contao/dca/tl_user_group.php
  news-bundle/contao/dca/tl_layout.php
  news-bundle/contao/dca/tl_module.php
  news-bundle/contao/dca/tl_user.php
  news-bundle/contao/dca/tl_user_group.php
  newsletter-bundle/contao/dca/tl_member.php
  newsletter-bundle/contao/dca/tl_module.php
  newsletter-bundle/contao/dca/tl_newsletter_deny_list.php
  newsletter-bundle/contao/dca/tl_user.php
  newsletter-bundle/contao/dca/tl_user_group.php
Labels: bug

#7684 Adjust the template studio layout
  core-bundle/assets/styles/component/tabs.pcss
  core-bundle/assets/styles/template-studio/common.pcss
  core-bundle/assets/styles/template-studio/layout.pcss
  core-bundle/contao/templates/twig/backend/template_studio/info/_block_info.html.twig
  core-bundle/public/backend.4d4f60d8.css
  core-bundle/public/backend.534c3f67.css
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: feature

#7785 Use `CAST(… AS BINARY)` instead of `BINARY`
  calendar-bundle/contao/models/CalendarEventsModel.php
  core-bundle/contao/library/Contao/Model.php
  core-bundle/contao/models/ArticleModel.php
  core-bundle/contao/models/PageModel.php
  core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php
  core-bundle/src/Migration/Version500/MemberCountryUppercaseMigration.php
  core-bundle/src/Migration/Version503/FileExtensionMigration.php
  faq-bundle/contao/models/FaqModel.php
  news-bundle/contao/models/NewsModel.php
  newsletter-bundle/contao/models/NewsletterModel.php
Labels: bug

#7788 Update and run the tools
  core-bundle/src/String/SimpleTokenExpressionLanguage.php
  test-case/composer.json
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7796 Use PHP CMS-IG SEAL for the back end search
  composer.json
  core-bundle/composer.json
  core-bundle/config/backend_search.yaml
  core-bundle/src/Search/Backend/BackendSearch.php
  core-bundle/tests/Search/Backend/BackendSearchTest.php
  depcheck.php
  manager-bundle/composer.json
  manager-bundle/src/Command/ContaoSetupCommand.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/Command/ContaoSetupCommandTest.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: feature

#7811 Switch to new SEAL ReindexProvider framework
  core-bundle/config/backend_search.yaml
  core-bundle/src/Command/BackendSearch/IndexCommand.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Search/Backend/BackendSearch.php
  core-bundle/src/Search/Backend/ReindexConfig.php
  core-bundle/src/Search/Backend/Seal/SealReindexProvider.php
  core-bundle/src/Search/Backend/Seal/SealUtil.php
  core-bundle/tests/Command/BackendSearch/IndexCommandTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Search/Backend/BackendSearchTest.php
  core-bundle/tests/Search/Backend/Seal/SealReindexProviderTest.php
  core-bundle/tests/Search/Backend/Seal/SealUtilTest.php
Labels: feature

#7819 Correctly show the record label if `showColumns` is enabled
  core-bundle/src/EventListener/DataContainer/FallbackRecordLabelListener.php
Labels: bug, feature

#7822 Backport the record labeler service
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/src/DataContainer/RecordLabeler.php
  core-bundle/src/Event/DataContainerRecordLabelEvent.php
  core-bundle/src/EventListener/DataContainer/ContentRecordLabelListener.php
  core-bundle/src/EventListener/DataContainer/FallbackRecordLabelListener.php
  core-bundle/tests/DataContainer/RecordLabelerTest.php
  core-bundle/tests/Event/DataContainerRecordLabelEventTest.php
  core-bundle/tests/EventListener/DataContainer/ContentRecordLabelListenerTest.php
  core-bundle/tests/EventListener/DataContainer/FallbackRecordLabelListenerTest.php
  core-bundle/tests/Fixtures/TranslatorStub.php
Labels: bug

#7683 Support themes in the template studio
  core-bundle/assets/controllers/tabs-controller.js
  core-bundle/assets/controllers/template-studio-controller.js
  core-bundle/config/template_studio.yaml
  core-bundle/contao/languages/en/template_studio.xlf
  core-bundle/contao/templates/twig/backend/template_studio/editor/_editor_tab.html.twig
  core-bundle/contao/templates/twig/backend/template_studio/index.html.twig
  core-bundle/contao/templates/twig/backend/template_studio/select_theme.stream.html.twig
  core-bundle/public/backend.612750ae.js
  core-bundle/public/backend.612750ae.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/src/Controller/AbstractBackendController.php
  core-bundle/src/Controller/BackendTemplateStudioController.php
  core-bundle/src/Twig/Loader/ThemeNamespace.php
  core-bundle/src/Twig/Studio/Operation/AbstractCreateVariantOperation.php
  core-bundle/src/Twig/Studio/Operation/AbstractOperation.php
  core-bundle/src/Twig/Studio/Operation/AbstractRenameVariantOperation.php
  core-bundle/src/Twig/Studio/Operation/CreateOperation.php
  core-bundle/src/Twig/Studio/Operation/DeleteOperation.php
  core-bundle/src/Twig/Studio/Operation/OperationContext.php
  core-bundle/src/Twig/Studio/Operation/OperationContextFactory.php
  core-bundle/src/Twig/Studio/Operation/OperationInterface.php
  core-bundle/src/Twig/Studio/Operation/SaveOperation.php
  core-bundle/tests/Command/DebugContaoTwigCommandTest.php
  core-bundle/tests/Controller/AbstractBackendControllerTest.php
  core-bundle/tests/Fixtures/Twig/inheritance/themes/templates/invalid.theme/.gitkeep
  core-bundle/tests/Twig/Loader/TemplateLocatorTest.php
  core-bundle/tests/Twig/Loader/ThemeTest.php
Labels: feature

#7010 Handle nested content elements in the back end breadcrumb menu
  core-bundle/config/services.yaml
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/library/Contao/Input.php
  core-bundle/contao/themes/flexible/backend.4da76d3d.css
  core-bundle/contao/themes/flexible/backend.61663d68.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/main.css
  core-bundle/src/DataContainer/DcaUrlAnalyzer.php
  core-bundle/src/EventListener/DataContainer/ContentRecordLabelListener.php
  core-bundle/tests/Fixtures/Functional/DcaUrlAnalyzer/default.yaml
  core-bundle/tests/Functional/DcaUrlAnalyzerTest.php
Labels: bug

#7792 Use the Stimulus color picker instead of the old MooTools one
  composer.json
  core-bundle/assets/controllers/color-picker-controller.js
  core-bundle/assets/styles/backend.pcss
  core-bundle/assets/styles/component/color-picker.pcss
  core-bundle/composer.json
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/public/backend.5b8f0c46.css
  core-bundle/public/backend.612750ae.js
  core-bundle/public/backend.7961ab38.js
  core-bundle/public/backend.7961ab38.js.LICENSE.txt
  core-bundle/public/backend.7f024f81.css
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  package-lock.json
  package.json
Labels: feature

#7821 Add `chosen` to `tl_form_field.type`
  core-bundle/contao/dca/tl_form_field.php
Labels: bug
