Repository contao/contao, pull requests merged in 2024-01, with the labels that each got.

#6679 Add a CONTRIBUTING.md file with the release cycle dates
  CONTRIBUTING.md
Labels: release

#6558 Inline the CSS from a newsletter template before sending
  composer.json
  core-bundle/contao/templates/mail/mail_responsive.html5
  newsletter-bundle/composer.json
  newsletter-bundle/contao/classes/Newsletter.php
  newsletter-bundle/contao/dca/tl_newsletter.php
  newsletter-bundle/contao/languages/en/tl_newsletter.xlf
  newsletter-bundle/contao/models/NewsletterModel.php
  newsletter-bundle/public/newsletter.min.css
Labels: feature

#6652 Sort options by key if they use language references
  core-bundle/contao/library/Contao/Widget.php
Labels: feature

#6605 Optimize the MySQL indexes
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_opt_in_related.php
  core-bundle/contao/dca/tl_search.php
  core-bundle/contao/dca/tl_undo.php
  core-bundle/contao/library/Contao/Search.php
  newsletter-bundle/contao/classes/Newsletter.php
Labels: feature

#5810 Add a VFS decorator that supports user permissions
  core-bundle/src/Filesystem/PermissionCheckingVirtualFilesystem.php
  core-bundle/src/Filesystem/VirtualFilesystemDecoratorTrait.php
  core-bundle/tests/Filesystem/PermissionCheckingVirtualFilesystemTest.php
Labels: feature

#6529 Add the DNS mapping migration
  core-bundle/config/migrations.yaml
  core-bundle/src/Migration/Environment/DnsMigration.php
  core-bundle/tests/Migration/Environment/DnsMigrationTest.php
  manager-bundle/src/ContaoManager/Plugin.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: feature

#6639 Allow adding a lost-password page to the login module
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_module.xlf
  core-bundle/contao/models/ModuleModel.php
  core-bundle/contao/modules/ModuleLogin.php
  core-bundle/contao/templates/modules/mod_login.html5
Labels: feature

#6650 Decouple the calendar, FAQ and news bundles from the comments bundle
  calendar-bundle/contao/dca/tl_calendar.php
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/contao/dca/tl_module.php
  calendar-bundle/contao/languages/en/tl_calendar.xlf
  calendar-bundle/contao/languages/en/tl_calendar_events.xlf
  comments-bundle/config/services.yaml
  comments-bundle/contao/languages/en/default.xlf
  comments-bundle/contao/languages/en/tl_calendar.xlf
  comments-bundle/contao/languages/en/tl_calendar_events.xlf
  comments-bundle/contao/languages/en/tl_faq.xlf
  comments-bundle/contao/languages/en/tl_faq_category.xlf
  comments-bundle/contao/languages/en/tl_news.xlf
  comments-bundle/contao/languages/en/tl_news_archive.xlf
  comments-bundle/src/ContaoManager/Plugin.php
  comments-bundle/src/EventListener/DataContainer/AddCommentFieldsListener.php
  comments-bundle/tests/ContaoManager/PluginTest.php
  comments-bundle/tests/EventListener/DataContainer/AddCommentFieldsListenerTest.php
  faq-bundle/contao/dca/tl_faq.php
  faq-bundle/contao/dca/tl_faq_category.php
  faq-bundle/contao/dca/tl_module.php
  faq-bundle/contao/languages/en/tl_faq.xlf
  faq-bundle/contao/languages/en/tl_faq_category.xlf
  news-bundle/contao/dca/tl_module.php
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/dca/tl_news_archive.php
  news-bundle/contao/languages/en/default.xlf
  news-bundle/contao/languages/en/tl_news.xlf
  news-bundle/contao/languages/en/tl_news_archive.xlf
Labels: feature

#6169 Support the template_from_string() Twig function
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
Labels: bug

#6434 Cache the `cteAlias` references
  core-bundle/src/EventListener/DataContainer/CteAliasListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/tests/EventListener/DataContainer/CteAliasListenerTest.php
Labels: bug

#6554 Fix NULL handling in the `SerpPreview` widget
  core-bundle/src/Resources/contao/widgets/SerpPreview.php
Labels: bug

#6599 Disallow the web profiler in the `robots.txt` file
  core-bundle/composer.json
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  tools/require-checker/config.json
Labels: bug

#6687 Merge branch '4.13' into 5.2
  calendar-bundle/contao/classes/Calendar.php
  calendar-bundle/contao/classes/Events.php
  calendar-bundle/contao/modules/ModuleEventlist.php
  core-bundle/composer.json
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/Theme.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/languages/en/explain.xlf
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/contao/widgets/SerpPreview.php
  core-bundle/src/EventListener/DataContainer/CteAliasListener.php
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
  core-bundle/tests/EventListener/DataContainer/CteAliasListenerTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  manager-bundle/src/Command/ContaoSetupCommand.php
  tools/require-checker/config/config.json
Labels: release

#6689 Fix the description of the "template data" field
  core-bundle/src/Resources/contao/languages/en/tl_content.xlf
Labels: bug

#6342 Fix a PHP 8 error in the `Form` class
  core-bundle/src/Resources/contao/forms/Form.php
Labels: bug

#6463 Fix a PHP8 error in the `Frontend::addToUrl()` method
  core-bundle/src/Resources/contao/classes/Frontend.php
Labels: bug

#6690 Merge branch '5.2' into 5.x
  calendar-bundle/contao/classes/Calendar.php
  calendar-bundle/contao/classes/Events.php
  calendar-bundle/contao/modules/ModuleEventlist.php
  composer.json
  core-bundle/composer.json
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/Theme.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/languages/en/explain.xlf
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/contao/widgets/SerpPreview.php
  core-bundle/src/EventListener/DataContainer/CteAliasListener.php
  core-bundle/src/EventListener/RobotsTxtListener.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/tests/EventListener/DataContainer/CteAliasListenerTest.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  manager-bundle/src/Command/ContaoSetupCommand.php
  tools/require-checker/config/config.json
Labels: release

#6684 Do not overwrite `id`, `pid`, `ptable` and `sorting` when restoring a version
  core-bundle/src/Resources/contao/classes/Versions.php
Labels: bug

#6683 Add more database indexes
  calendar-bundle/contao/dca/tl_calendar.php
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/contao/dca/tl_calendar_feed.php
  comments-bundle/contao/dca/tl_comments_notify.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_favorites.php
  core-bundle/contao/dca/tl_files.php
  core-bundle/contao/dca/tl_form.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/dca/tl_image_size_item.php
  core-bundle/contao/dca/tl_layout.php
  core-bundle/contao/dca/tl_log.php
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_member_group.php
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/dca/tl_opt_in.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_preview_link.php
  core-bundle/contao/dca/tl_search.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/contao/dca/tl_undo.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  core-bundle/contao/dca/tl_version.php
  core-bundle/contao/models/PageModel.php
  faq-bundle/contao/dca/tl_faq.php
  faq-bundle/contao/dca/tl_faq_category.php
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/dca/tl_news_archive.php
  newsletter-bundle/contao/dca/tl_newsletter.php
  newsletter-bundle/contao/dca/tl_newsletter_channel.php
  newsletter-bundle/contao/dca/tl_newsletter_recipients.php
Labels: feature

#6695 Fix undefined method `checkPermission`
  core-bundle/contao/dca/tl_theme.php
Labels: bug

#6696 Add PHP 8.4 as nightly version to the CI chain
  .github/workflows/ci.yml
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/phpstan/config/contao.neon
  tools/rector/composer.lock
Labels: CI

#6584 Add enum support for DCAs and models
  core-bundle/config/listener.yaml
  core-bundle/contao/library/Contao/DcaExtractor.php
  core-bundle/contao/library/Contao/Model.php
  core-bundle/src/EventListener/DataContainer/EnumOptionsListener.php
  core-bundle/src/Translation/TranslatableLabelInterface.php
  core-bundle/tests/Contao/DcaExtractorTest.php
  core-bundle/tests/Contao/ModelTest.php
  core-bundle/tests/EventListener/DataContainer/EnumOptionsListenerTest.php
  core-bundle/tests/Fixtures/Enum/IntBackedEnum.php
  core-bundle/tests/Fixtures/Enum/StringBackedEnum.php
  core-bundle/tests/Fixtures/Enum/TranslatableEnum.php
  core-bundle/tests/Fixtures/vendor/contao/test-bundle/Resources/contao/dca/tl_test_with_enums.php
Labels: feature

#6646 Add an image size voter
  core-bundle/config/services.yaml
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/dca/tl_image_size_item.php
  core-bundle/src/Security/Voter/DataContainer/ImageSizeAccessVoter.php
  core-bundle/src/Security/Voter/DataContainer/ImageSizeItemAccessVoter.php
  core-bundle/tests/Security/Voter/DataContainer/ImageSizeAccessVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/ImageSizeItemAccessVoterTest.php
Labels: feature

#6700 Fix tests when `MAILER_DSN` env var is defined
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: bug

#6232 Implement front end module permissions
  core-bundle/config/listener.yaml
  core-bundle/config/migrations.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  core-bundle/contao/languages/en/tl_user.xlf
  core-bundle/src/EventListener/DataContainer/FrontendModulePermissionsListener.php
  core-bundle/src/Migration/Version503/FrontendModulesMigration.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/Voter/DataContainer/FrontendModulesVoter.php
  core-bundle/tests/EventListener/DataContainer/FrontendModulePermissionsListenerTest.php
  core-bundle/tests/Security/Voter/BackendAccessVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/FrontendModulesVoterTest.php
Labels: feature

#6699 Fix the compression in the `contao:backup:create` command
  core-bundle/src/Command/Backup/AbstractBackupCommand.php
  core-bundle/tests/Command/Backup/BackupCreateCommandTest.php
Labels: bug

#6675 Add the page permission voters
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/Event/FilterPageTypeEvent.php
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  core-bundle/src/EventListener/DataContainer/PageTypeOptionsListener.php
  core-bundle/src/EventListener/FilterPageTypeListener.php
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/src/Security/Voter/DataContainer/ArticleContentVoter.php
  core-bundle/src/Security/Voter/DataContainer/ContentCompositionVoter.php
  core-bundle/src/Security/Voter/DataContainer/PagePermissionVoter.php
  core-bundle/src/Security/Voter/DataContainer/PageTypeAccessVoter.php
  core-bundle/tests/Event/FilterPageTypeEventTest.php
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
  core-bundle/tests/EventListener/FilterPageTypeListenerTest.php
  core-bundle/tests/Security/Voter/DataContainer/ArticleContentVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/ContentCompositionVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/PagePermissionVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/PageTypeAccessVoterTest.php
Labels: feature

#6692 Make method `getTemplate` in `FrontendTemplateTrait` static
  core-bundle/src/Resources/contao/classes/FrontendTemplateTrait.php
Labels: bug

#6215 Add canonical links to news and events
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/contao/dca/tl_module.php
  calendar-bundle/contao/languages/en/tl_calendar_events.xlf
  calendar-bundle/contao/languages/en/tl_module.xlf
  calendar-bundle/contao/models/CalendarEventsModel.php
  calendar-bundle/contao/modules/ModuleEventReader.php
  calendar-bundle/src/Migration/KeepCanonicalMigration.php
  news-bundle/contao/dca/tl_module.php
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/languages/en/tl_module.xlf
  news-bundle/contao/languages/en/tl_news.xlf
  news-bundle/contao/models/NewsModel.php
  news-bundle/contao/modules/ModuleNewsReader.php
  news-bundle/src/Migration/KeepCanonicalMigration.php
Labels: feature, up for discussion

#6707 Correctly set the ptable for copy and cut actions
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#6474 Retrieve the `PageModel` correctly in `ContaoMailer`
  core-bundle/src/Mailer/ContaoMailer.php
  core-bundle/src/Resources/config/services.yml
  core-bundle/tests/Mailer/ContaoMailerTest.php
Labels: bug

#5424 Add a description list content element
  core-bundle/config/controller.yaml
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_content.xlf
  core-bundle/contao/templates/twig/content_element/description_list.html.twig
  core-bundle/contao/widgets/KeyValueWizard.php
  core-bundle/src/Controller/ContentElement/DescriptionListController.php
  core-bundle/src/EventListener/DataContainer/DescriptionListLabelListener.php
  core-bundle/tests/EventListener/DataContainer/DescriptionListLabelListenerTest.php
Labels: feature

#6392 Implement the redirect page as page controller
  core-bundle/config/controller.yaml
  core-bundle/contao/pages/PageRedirect.php
  core-bundle/src/Controller/Page/RedirectPageController.php
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/tests/Controller/Page/RedirectPageControllerTest.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
Labels: feature

#6672 Add a Stimulus controller to handle scrolling in the back end
  calendar-bundle/contao/dca/tl_calendar.php
  calendar-bundle/contao/dca/tl_calendar_feed.php
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/assets/backend.js
  core-bundle/assets/controllers/scroll-offset-controller.js
  core-bundle/assets/scripts/autofocus.js
  core-bundle/assets/scripts/core.js
  core-bundle/assets/scripts/modulewizard.js
  core-bundle/assets/scripts/sectionwizard.js
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/classes/DropZone.php
  core-bundle/contao/classes/FileUpload.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_files.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/drivers/DC_File.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/templates/backend/be_ace.html5
  core-bundle/contao/templates/backend/be_csv_import.html5
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/contao/templates/backend/be_purge_data.html5
  core-bundle/contao/templates/backend/be_tinyMCE.html5
  core-bundle/contao/widgets/CheckBox.php
  core-bundle/contao/widgets/CheckBoxWizard.php
  core-bundle/contao/widgets/ChmodTable.php
  core-bundle/contao/widgets/ImageSize.php
  core-bundle/contao/widgets/InputUnit.php
  core-bundle/contao/widgets/ModuleWizard.php
  core-bundle/contao/widgets/Password.php
  core-bundle/contao/widgets/RadioButton.php
  core-bundle/contao/widgets/RadioTable.php
  core-bundle/contao/widgets/RootPageDependentSelect.php
  core-bundle/contao/widgets/SectionWizard.php
  core-bundle/contao/widgets/SelectMenu.php
  core-bundle/contao/widgets/TextArea.php
  core-bundle/contao/widgets/TextField.php
  core-bundle/contao/widgets/TimePeriod.php
  core-bundle/contao/widgets/TrblField.php
  core-bundle/public/backend.42df1514.js
  core-bundle/public/backend.42df1514.js.map
  core-bundle/public/backend.fc2e9b5c.js
  core-bundle/public/backend.fc2e9b5c.js.map
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/src/EventListener/DataContainer/DefaultGlobalOperationsListener.php
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  core-bundle/templates/Backend/be_filesync_report.html.twig
  core-bundle/tests/Contao/RootPageDependentSelectTest.php
  newsletter-bundle/contao/classes/Newsletter.php
  newsletter-bundle/contao/dca/tl_newsletter.php
  newsletter-bundle/contao/dca/tl_newsletter_recipients.php
Labels: feature

#6710 Update and run the tools
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/BackendPreviewController.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Controller/CaptchaController.php
  core-bundle/src/Controller/FaviconController.php
  core-bundle/src/Controller/FrontendController.php
  core-bundle/src/Controller/PreviewLinkController.php
  core-bundle/src/Controller/RobotsTxtController.php
  core-bundle/src/Controller/SitemapController.php
  manager-bundle/tests/Fixtures/Routing/WithAppController/src/Controller/BarController.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/rector/config/rector.php
Labels: CI

#6714 Re-fix missing icon for dca operation
  core-bundle/contao/dca/tl_page.php
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
Labels: bug

#6697 Fix an error if a gallery image does not exist
  core-bundle/src/Resources/contao/elements/ContentGallery.php
Labels: bug

#6631 Add the ability to set Content Security Policies
  composer.json
  core-bundle/composer.json
  core-bundle/config/controller.yaml
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/languages/en/tl_page.xlf
  core-bundle/contao/library/Contao/Template.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/pages/PageRegular.php
  core-bundle/contao/templates/analytics/analytics_google.html5
  core-bundle/contao/templates/analytics/analytics_matomo.html5
  core-bundle/contao/templates/elements/ce_player.html5
  core-bundle/contao/templates/elements/ce_vimeo.html5
  core-bundle/contao/templates/elements/ce_youtube.html5
  core-bundle/contao/templates/forms/form_captcha.html5
  core-bundle/contao/templates/jquery/j_accordion.html5
  core-bundle/contao/templates/jquery/j_colorbox.html5
  core-bundle/contao/templates/jquery/j_tablesort.html5
  core-bundle/contao/templates/js/js_accordion.html5
  core-bundle/contao/templates/js/js_autofocus.html5
  core-bundle/contao/templates/js/js_nocookie.html5
  core-bundle/contao/templates/js/js_slider.html5
  core-bundle/contao/templates/mootools/moo_accordion.html5
  core-bundle/contao/templates/mootools/moo_chosen.html5
  core-bundle/contao/templates/mootools/moo_mediabox.html5
  core-bundle/contao/templates/mootools/moo_tablesort.html5
  core-bundle/contao/templates/twig/component/_list.html.twig
  core-bundle/contao/templates/twig/component/_splash_screen.html.twig
  core-bundle/contao/templates/twig/component/_table.html.twig
  core-bundle/contao/templates/twig/content_element/_video.html.twig
  core-bundle/contao/templates/twig/content_element/player.html.twig
  core-bundle/contao/templates/twig/content_element/toplink.html.twig
  core-bundle/src/Controller/CspReporterController.php
  core-bundle/src/Csp/CspParser.php
  core-bundle/src/EventListener/CspReportListener.php
  core-bundle/src/EventListener/DataContainer/CspSaveCallbackListener.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/Monolog/ContaoTableProcessor.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/Csp/CspHandler.php
  core-bundle/src/Routing/ResponseContext/ResponseContextAccessor.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/CspRuntime.php
  core-bundle/templates/Frontend/preview_toolbar_base.html.twig
  core-bundle/templates/Frontend/preview_toolbar_base_js.html.twig
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/CspReporterControllerTest.php
  core-bundle/tests/Csp/CspParserTest.php
  core-bundle/tests/EventListener/CspReportListenerTest.php
  core-bundle/tests/EventListener/DataContainer/CspSaveCallbackListenerTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/Csp/CspHandlerTest.php
  core-bundle/tests/Routing/ResponseContext/ResponseContextAccessorTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/FragmentTemplateTest.php
  core-bundle/tests/Twig/Runtime/CspRuntimeTest.php
  manager-bundle/composer.json
Labels: feature

#6721 Revert "Allow data-lightbox in TinyMCE by default"
  core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5
Labels: bug

#6725 Merge branch '4.13' into 5.2
  core-bundle/contao/classes/Versions.php
  core-bundle/contao/elements/ContentGallery.php
  core-bundle/contao/forms/Form.php
  core-bundle/contao/languages/en/tl_content.xlf
  core-bundle/contao/templates/backend/be_tinyMCE.html5
  core-bundle/src/Command/Backup/AbstractBackupCommand.php
  core-bundle/tests/Command/Backup/BackupCreateCommandTest.php
  manager-bundle/tests/ContaoManager/PluginTest.php
Labels: release

#6596 Implement the content URL generator
  core-bundle/config/controller.yaml
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/classes/Frontend.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/elements/ContentTeaser.php
  core-bundle/contao/forms/Form.php
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/modules/Module.php
  core-bundle/contao/modules/ModuleArticleList.php
  core-bundle/contao/modules/ModuleArticlenav.php
  core-bundle/contao/modules/ModuleBreadcrumb.php
  core-bundle/contao/modules/ModuleCustomnav.php
  core-bundle/contao/modules/ModuleLogin.php
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModuleQuicklink.php
  core-bundle/contao/modules/ModuleQuicknav.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/contao/modules/ModuleSearch.php
  core-bundle/contao/widgets/SerpPreview.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/ContentElement/TeaserController.php
  core-bundle/src/Controller/FrontendModule/TwoFactorController.php
  core-bundle/src/Controller/Page/RootPageController.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/Crawl/Escargot/Factory.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/PreviewUrlConvertListener.php
  core-bundle/src/EventListener/Security/TwoFactorFrontendListener.php
  core-bundle/src/Exception/ForwardPageNotFoundException.php
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
  core-bundle/src/InsertTag/Resolver/LinkInsertTag.php
  core-bundle/src/Routing/Content/ArticleResolver.php
  core-bundle/src/Routing/Content/ContentUrlResolverInterface.php
  core-bundle/src/Routing/Content/ContentUrlResult.php
  core-bundle/src/Routing/Content/PageResolver.php
  core-bundle/src/Routing/Content/StringResolver.php
  core-bundle/src/Routing/Content/StringUrl.php
  core-bundle/src/Routing/ContentUrlGenerator.php
  core-bundle/src/Routing/Page/ContentCompositionInterface.php
  core-bundle/src/Routing/Page/PageRoute.php
  core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/FrontendModule/TwoFactorControllerTest.php
  core-bundle/tests/Controller/Page/RootPageControllerTest.php
  core-bundle/tests/Controller/SitemapControllerTest.php
  core-bundle/tests/Crawl/Escargot/FactoryTest.php
  core-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  core-bundle/tests/EventListener/Security/TwoFactorFrontendListenerTest.php
  core-bundle/tests/Routing/Content/ArticleResolverTest.php
  core-bundle/tests/Routing/Content/PageResolverTest.php
  core-bundle/tests/Routing/Content/StringResolverTest.php
  core-bundle/tests/Routing/ContentUrlGeneratorTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
Labels: feature

#6607 Generate event URLs using the content URL generator
  calendar-bundle/config/services.yaml
  calendar-bundle/contao/classes/Calendar.php
  calendar-bundle/contao/classes/Events.php
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/contao/modules/ModuleCalendar.php
  calendar-bundle/contao/modules/ModuleEventReader.php
  calendar-bundle/src/EventListener/InsertTagsListener.php
  calendar-bundle/src/EventListener/PreviewUrlConvertListener.php
  calendar-bundle/src/EventListener/SitemapListener.php
  calendar-bundle/src/Routing/CalendarEventsResolver.php
  calendar-bundle/tests/EventListener/InsertTagsListenerTest.php
  calendar-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  calendar-bundle/tests/EventListener/SitemapListenerTest.php
  calendar-bundle/tests/Routing/CalendarEventsResolverTest.php
Labels: feature

#6604 Generate news URLs using the content URL generator
  news-bundle/config/services.yaml
  news-bundle/contao/classes/News.php
  news-bundle/contao/dca/tl_news.php
  news-bundle/contao/modules/ModuleNews.php
  news-bundle/contao/modules/ModuleNewsMenu.php
  news-bundle/contao/modules/ModuleNewsReader.php
  news-bundle/src/EventListener/GeneratePageListener.php
  news-bundle/src/EventListener/InsertTagsListener.php
  news-bundle/src/EventListener/NewsFeedListener.php
  news-bundle/src/EventListener/PreviewUrlConvertListener.php
  news-bundle/src/EventListener/SitemapListener.php
  news-bundle/src/Routing/NewsResolver.php
  news-bundle/tests/EventListener/GeneratePageListenerTest.php
  news-bundle/tests/EventListener/InsertTagsListenerTest.php
  news-bundle/tests/EventListener/NewsFeedListenerTest.php
  news-bundle/tests/EventListener/PreviewUrlConverterListenerTest.php
  news-bundle/tests/EventListener/SitemapListenerTest.php
  news-bundle/tests/Routing/NewsResolverTest.php
Labels: feature

#6597 Generate FAQ URLs using the content URL generator
  faq-bundle/config/services.yaml
  faq-bundle/contao/dca/tl_faq.php
  faq-bundle/contao/modules/ModuleFaqList.php
  faq-bundle/contao/modules/ModuleFaqReader.php
  faq-bundle/src/EventListener/InsertTagsListener.php
  faq-bundle/src/EventListener/SitemapListener.php
  faq-bundle/src/Routing/FaqResolver.php
  faq-bundle/tests/EventListener/InsertTagsListenerTest.php
  faq-bundle/tests/EventListener/SitemapListenerTest.php
  faq-bundle/tests/Routing/FaqResolverTest.php
Labels: feature

#6606 Generate newsletter URLs using the content URL generator
  newsletter-bundle/config/services.yaml
  newsletter-bundle/contao/modules/ModuleNewsletterList.php
  newsletter-bundle/contao/modules/ModuleNewsletterReader.php
  newsletter-bundle/contao/modules/ModuleSubscribe.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
  newsletter-bundle/src/EventListener/SitemapListener.php
  newsletter-bundle/src/Routing/NewsletterResolver.php
  newsletter-bundle/tests/EventListener/SitemapListenerTest.php
  newsletter-bundle/tests/Routing/NewsletterResolverTest.php
Labels: feature

#6723 Introduce `TemplateTrait` to fix missing method in `Widget`
  core-bundle/contao/library/Contao/Template.php
  core-bundle/contao/library/Contao/TemplateTrait.php
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/contao/templates/forms/form_captcha.html5
  core-bundle/contao/templates/modules/mod_two_factor.html5
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/CspRuntime.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/FragmentTemplateTest.php
  core-bundle/tests/Twig/Runtime/CspRuntimeTest.php
Labels: bug

#6730 Run the tools
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/src/Picker/EventPickerProvider.php
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/library/Contao/TemplateTrait.php
  core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php
  core-bundle/src/Image/ImageFactory.php
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
  core-bundle/src/Monolog/ContaoTableProcessor.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/Csp/CspHandler.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/src/Twig/Runtime/CspRuntime.php
  core-bundle/src/Twig/Runtime/SchemaOrgRuntime.php
  core-bundle/tests/Contao/PageModelTest.php
  faq-bundle/src/Picker/FaqPickerProvider.php
  news-bundle/src/Picker/NewsPickerProvider.php
Labels: CI

#6734 Get rid of most deprecations
  composer.json
  core-bundle/composer.json
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
  core-bundle/src/Migration/Environment/DnsMigration.php
  core-bundle/tests/Migration/Environment/DnsMigrationTest.php
Labels: CI

#6736 Unify the deprecation messages
  comments-bundle/contao/classes/Comments.php
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/Automator.php
  core-bundle/contao/library/Contao/Config.php
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/library/Contao/Input.php
  core-bundle/contao/library/Contao/Template.php
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Twig/Runtime/FigureRuntime.php
  core-bundle/tests/EventListener/RobotsTxtListenerTest.php
  newsletter-bundle/contao/classes/Newsletter.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: bug

#6737 Properly assign parameters to `contao.crawl.escargot.factory`
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
Labels: bug

#6744 Fix the "delete files" button in the file manager
  core-bundle/contao/dca/tl_files.php
Labels: bug

#6724 Redirect in the `BackendConfirm` controller if there is no `INVALID_TOKEN_URL` in the session
  core-bundle/src/Resources/contao/controllers/BackendConfirm.php
Labels: bug

#6688 Add the `encode_email` Twig filter
  core-bundle/config/services.yaml
  core-bundle/contao/templates/_new/content_element/text.html.twig
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/StringRuntime.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Runtime/StringRuntimeTest.php
Labels: bug

#6720 Allow insert tags in link titles
  core-bundle/contao/templates/_new/content_element/hyperlink.html.twig
Labels: bug

#6759 Normalize the Twig CSP method names
  composer.json
  core-bundle/composer.json
  core-bundle/config/services.yaml
  core-bundle/contao/templates/twig/component/_list.html.twig
  core-bundle/contao/templates/twig/component/_splash_screen.html.twig
  core-bundle/contao/templates/twig/component/_table.html.twig
  core-bundle/contao/templates/twig/content_element/_video.html.twig
  core-bundle/contao/templates/twig/content_element/player.html.twig
  core-bundle/contao/templates/twig/content_element/toplink.html.twig
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/CspRuntime.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
Labels: bug

#6760 Correctly set the link title and text in the downloads controller
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/tests/Controller/ContentElement/DownloadsControllerTest.php
Labels: bug

#6719 Support CSP on WYSIWYG editors like TinyMCE
  calendar-bundle/contao/templates/events/event_full.html5
  calendar-bundle/contao/templates/events/event_list.html5
  calendar-bundle/contao/templates/events/event_teaser.html5
  comments-bundle/contao/templates/comments/com_default.html5
  core-bundle/config/services.yaml
  core-bundle/contao/library/Contao/TemplateTrait.php
  core-bundle/contao/templates/elements/ce_text.html5
  core-bundle/contao/templates/forms/form_captcha.html5
  core-bundle/contao/templates/forms/form_explanation.html5
  core-bundle/contao/templates/forms/form_message.html5
  core-bundle/contao/templates/modules/mod_article.html5
  core-bundle/contao/templates/modules/mod_two_factor.html5
  core-bundle/contao/templates/twig/content_element/text.html.twig
  core-bundle/src/Csp/WysiwygStyleProcessor.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/CspRuntime.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Csp/WysiwygStyleProcessorTest.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/FragmentTemplateTest.php
  core-bundle/tests/Twig/Runtime/CspRuntimeTest.php
  faq-bundle/contao/templates/modules/mod_faqpage.html5
  faq-bundle/contao/templates/modules/mod_faqreader.html5
  news-bundle/contao/templates/news/news_full.html5
  news-bundle/contao/templates/news/news_latest.html5
  news-bundle/contao/templates/news/news_short.html5
Labels: feature

#6726 Correctly handle arrays in the Ajax confirmation message
  core-bundle/contao/forms/Form.php
  core-bundle/contao/library/Contao/ArrayUtil.php
Labels: bug

#6762 Fix mov mime type
  core-bundle/src/Resources/contao/config/mimetypes.php
Labels: bug

#6764 Prevent argument errors on malicious login attempts
  core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php
Labels: bug

#6761 Limit the CSP header size to avoid server errors
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/Csp/CspHandler.php
  core-bundle/src/Routing/ResponseContext/Csp/CspHandlerFactory.php
  core-bundle/src/Twig/Runtime/CspRuntime.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/Csp/CspHandlerTest.php
Labels: bug

#6758 Improve how headlines can be adjusted in Twig
  core-bundle/contao/templates/twig/content_element/_base.html.twig
  core-bundle/contao/templates/twig/content_element/headline.html.twig
Labels: bug

#6787 Fix the DNS migration test
  core-bundle/tests/Migration/Environment/DnsMigrationTest.php
Labels: CI

#6738 Add a Twig function to generate content URLs
  core-bundle/config/services.yaml
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Runtime/ContentUrlRuntime.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
Labels: feature

#6778 Correctly check the "show" permission in the site structure
  core-bundle/src/Resources/contao/dca/tl_page.php
Labels: bug

#6788 Use the content URL generator in the redirect page controller
  core-bundle/config/controller.yaml
  core-bundle/src/Controller/Page/RedirectPageController.php
  core-bundle/tests/Controller/Page/RedirectPageControllerTest.php
Labels: bug

#6777 Ensure absolute paths in the `ImageObject` schema.org data
  core-bundle/src/Image/Studio/Figure.php
Labels: bug

#6796 Prevent errors in the images controller if images are missing
  core-bundle/src/Controller/ContentElement/ImagesController.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/ImagesControllerTest.php
  core-bundle/tests/Image/Studio/FigureBuilderStub.php
Labels: bug

#6794 Fix ptable for copyAll and cutAll
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#6436 Add a global Twig variable with Contao state
  core-bundle/config/services.yaml
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Global/ContaoVariable.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/DeprecationsNodeVisitorTest.php
  core-bundle/tests/Twig/Extension/InsertTagTest.php
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/ResponseContext/AddTokenParserTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: feature

#6806 Update and run the tools
  calendar-bundle/contao/modules/ModuleEventReader.php
  calendar-bundle/contao/modules/ModuleEventlist.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/library/Contao/Combiner.php
  core-bundle/contao/library/Contao/Input.php
  core-bundle/contao/library/Contao/TemplateTrait.php
  core-bundle/src/Filesystem/Dbafs/ChangeSet/ChangeSet.php
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  news-bundle/contao/modules/ModuleNews.php
  tools/ecs/composer.lock
  tools/phpstan/composer.lock
  tools/rector/composer.lock
Labels: CI

#6808 Support HTML5 entities with `double_encode: false`
  core-bundle/src/Resources/contao/helper/functions.php
  core-bundle/src/Resources/contao/library/Contao/StringUtil.php
  core-bundle/src/Twig/Interop/ContaoEscaper.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperTest.php
Labels: bug

#6809 Mark `$secret` as sensitive parameter
  core-bundle/src/EventListener/InsecureInstallationListener.php
Labels: bug

#6801 Handle empty sessions in the CSRF cookie subscriber
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
Labels: bug

#6798 Correctly show past events if "hide running events" is active
  calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php
Labels: bug

#6813 Merge branch '4.13' into 5.2
  calendar-bundle/contao/modules/ModuleEventlist.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/library/Contao/StringUtil.php
  core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php
  core-bundle/src/Twig/Interop/ContaoEscaper.php
  core-bundle/tests/Contao/InputTest.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/EventListener/CsrfTokenCookieSubscriberTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperTest.php
Labels: release

#6791 Correctly generate the enclosure URLs in news feeds
  news-bundle/src/Controller/Page/NewsFeedController.php
Labels: bug

#6807 Improve the debug message for `FigureBuilder` link attributes
  core-bundle/src/Image/Studio/FigureBuilder.php
Labels: bug

#6815 Drop the custom "remember me" implementation
  core-bundle/README.md
  core-bundle/config/listener.yaml
  core-bundle/config/migrations.yaml
  core-bundle/config/services.yaml
  core-bundle/phpunit.xml.dist
  core-bundle/src/Entity/RememberMe.php
  core-bundle/src/EventListener/Security/TokenDeauthenticatedListener.php
  core-bundle/src/Migration/Version503/RememberMeMigration.php
  core-bundle/src/Repository/RememberMeRepository.php
  core-bundle/src/Security/Authentication/RememberMe/RememberMeTokenProvider.php
  core-bundle/tests/EventListener/Security/TokenDeauthenticatedListenerTest.php
  core-bundle/tests/Security/Authentication/RememberMe/RememberMeTokenProviderTest.php
  manager-bundle/skeleton/config/security.yaml
Labels: bug

#6820 Fix the CI chain
  core-bundle/src/Cache/ContaoCacheWarmer.php
Labels: CI
