Repository contao/contao, pull requests merged in 2024-04, with the labels that each got.

#7036 Handle CSV fields in the registration and personal data module
  core-bundle/src/Resources/contao/modules/ModulePersonalData.php
  core-bundle/src/Resources/contao/modules/ModuleRegistration.php
Labels: bug, unconfirmed

#7096 Fix the CI chain
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  codecov.yml
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
Labels: CI

#7033 Register theme templates in the global namespace, too
  core-bundle/src/Twig/Loader/TemplateLocator.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: bug

#7052 Skip token validation if the session is empty and new
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/tests/Csrf/ContaoCsrfTokenManagerTest.php
Labels: bug

#7069 Correctly run the file extension migration on Windows
  core-bundle/src/Migration/Version413/FileExtensionMigration.php
Labels: bug

#7078 Fix a PHP 8 error if there is no default palette
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#7092 Remove the `feViewable` configuration
  core-bundle/src/Resources/contao/dca/tl_member.php
Labels: bug

#7072 Use `display: grid` in the image gallery preview
  core-bundle/src/Resources/contao/themes/flexible/main.css
  core-bundle/src/Resources/contao/themes/flexible/main.min.css
Labels: bug

#7097 Merge branch '4.13' into 5.3
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  codecov.yml
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/modules/ModulePersonalData.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/src/Csrf/ContaoCsrfTokenManager.php
  core-bundle/src/Migration/Version503/FileExtensionMigration.php
  core-bundle/tests/Csrf/ContaoCsrfTokenManagerTest.php
  core-bundle/tests/EventListener/RequestTokenListenerTest.php
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
Labels: release

#7046 Fix some edge cases when parsing HTML style attributes
  core-bundle/src/String/HtmlAttributes.php
  core-bundle/tests/String/HtmlAttributesTest.php
  core-bundle/tests/Twig/Runtime/CspRuntimeTest.php
Labels: bug

#7057 Cache SQL queries in the page type voter
  core-bundle/src/Security/Voter/DataContainer/PageTypeAccessVoter.php
  core-bundle/tests/Security/Voter/DataContainer/PageTypeAccessVoterTest.php
Labels: bug

#7064 Also unset the `disable`, `start` and `stop` fields when an admin edits themselves
  core-bundle/src/EventListener/DataContainer/UserAdminFieldListener.php
  core-bundle/tests/EventListener/DataContainer/UserAdminFieldListenerTest.php
Labels: bug

#7081 Add the missing `WysiwygStyleProcessor ` autowiring alias
  core-bundle/config/services.yaml
Labels: bug

#7074 Initialize Handorgel on the element
  core-bundle/contao/templates/js/js_accordion.html5
Labels: bug

#7098 Rename `tools` to `vendor-bin`
  .github/workflows/ci.yml
  .gitignore
  .yamllint
  composer.json
  tools/monorepo/composer.json
  vendor-bin/ecs/composer.json
  vendor-bin/ecs/composer.lock
  vendor-bin/ecs/config/default.php
  vendor-bin/ecs/config/legacy.php
  vendor-bin/ecs/config/template.php
  vendor-bin/isolated-tests/bin/run-tests-isolated
  vendor-bin/isolated-tests/composer.json
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/isolated-tests/src/RunTestsIsolatedCommand.php
  vendor-bin/monorepo/composer.json
  vendor-bin/monorepo/composer.lock
  vendor-bin/phpstan/composer.json
  vendor-bin/phpstan/composer.lock
  vendor-bin/phpstan/config/contao.neon
  vendor-bin/phpstan/src/ExtensionReturnTypeExtension.php
  vendor-bin/phpstan/src/GraphReturnTypeExtension.php
  vendor-bin/phpstan/src/HelperReturnTypeExtension.php
  vendor-bin/rector/composer.json
  vendor-bin/rector/composer.lock
  vendor-bin/rector/config/rector.php
  vendor-bin/require-checker/composer.json
  vendor-bin/require-checker/composer.lock
  vendor-bin/require-checker/config/config.json
  vendor-bin/service-linter/bin/lint-service-ids
  vendor-bin/service-linter/composer.json
  vendor-bin/service-linter/composer.lock
  vendor-bin/service-linter/src/LintServiceIdsCommand.php
Labels: CI

#7071 Add the missing styles to the new table element
  composer.json
  core-bundle/composer.json
  core-bundle/contao/templates/twig/component/_table.html.twig
  core-bundle/tests/Controller/ContentElement/TableControllerTest.php
Labels: bug

#7104 Use `shipmonk/composer-dependency-analyser` to check the Composer dependencies
  .github/workflows/ci.yml
  composer.json
  core-bundle/composer.json
  core-bundle/tests/EventListener/DataContainer/FrontendModulePermissionsListenerTest.php
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
  core-bundle/tests/Security/TwoFactor/AuthenticatorTest.php
  depcheck.php
  maker-bundle/composer.json
  rector.php
  test-case/composer.json
  vendor-bin/depcheck/composer.json
  vendor-bin/depcheck/composer.lock
  vendor-bin/require-checker/composer.json
  vendor-bin/require-checker/composer.lock
  vendor-bin/require-checker/config/config.json
Labels: CI

#7109 Add the missing `FilesystemItem::getName()` method
  core-bundle/src/Filesystem/FilesystemItem.php
  core-bundle/tests/Filesystem/FilesystemItemTest.php
Labels: bug

#7113 Fix the order of the media block in the text element markup
  core-bundle/contao/templates/twig/content_element/text.html.twig
  core-bundle/tests/Controller/ContentElement/TextControllerTest.php
Labels: bug

#7076 Fix the markup of the trusted device checkbox in the login template
  core-bundle/src/Resources/contao/templates/modules/mod_login.html5
Labels: bug

#7112 Handle empty strings in the `StringResolver` class
  core-bundle/src/Routing/Content/StringResolver.php
  core-bundle/tests/Routing/Content/StringResolverTest.php
Labels: bug

#7122 Ensure compatibility with Twig 3.9
  composer.json
  core-bundle/composer.json
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Extension/DeprecationsNodeVisitor.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/src/Twig/Interop/PhpTemplateProxyNodeVisitor.php
  core-bundle/src/Twig/ResponseContext/AddNode.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/ResponseContext/AddNodeTest.php
  core-bundle/tests/Twig/ResponseContext/AddTokenParserTest.php
Labels: bug

#7123 Ensure compatibility with Twig 3.9
  composer.json
  core-bundle/composer.json
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Extension/DeprecationsNodeVisitor.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/src/Twig/Interop/PhpTemplateProxyNodeVisitor.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
Labels: bug

#7125 Fix the require checker
  .github/workflows/ci.yml
  tools/monorepo/composer.json
  tools/require-checker/config.json
Labels: CI

#7128 Merge branch '4.13' into 5.3
  .github/workflows/ci.yml
Labels: release

#7127 Use `PhpSubprocess` instead of `Process` if available
  core-bundle/src/Util/ProcessUtil.php
  core-bundle/tests/Util/ProcessUtilTest.php
Labels: bug

#7130 Fix the elements check in the `sectionwizard.js` script
  core-bundle/assets/scripts/sectionwizard.js
  core-bundle/public/backend.50c79c9f.js
  core-bundle/public/backend.50c79c9f.js.map
  core-bundle/public/backend.69d856f0.js
  core-bundle/public/backend.69d856f0.js.map
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug

#7129 Make the `PhpTemplateProxyNode` class compatible with Twig 3.9
  core-bundle/src/Twig/Interop/PhpTemplateParentReferenceNode.php
  core-bundle/src/Twig/Interop/PhpTemplateProxyNode.php
  core-bundle/src/Twig/ResponseContext/AddNode.php
  core-bundle/tests/Twig/Interop/PhpTemplateParentReferenceNodeTest.php
  core-bundle/tests/Twig/Interop/PhpTemplateProxyNodeTest.php
  core-bundle/tests/Twig/ResponseContext/AddNodeTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: feature

#7134 Remove a useless if condition
  core-bundle/src/Util/ProcessUtil.php
Labels: CI

#7089 Make the member group voter cacheable
  core-bundle/src/Security/Voter/MemberGroupVoter.php
Labels: bug

#7138 Fix the CI chain
  core-bundle/tests/Twig/TwigIntegrationTest.php
  depcheck.php
Labels: CI

#7139 Add a `deserialize` Twig filter
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
Labels: bug

#7146 Test the `deserialize` Twig filter
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: bug

#7147 Catch the URL generator exception in the news insert tag
  news-bundle/src/EventListener/InsertTagsListener.php
  news-bundle/tests/EventListener/InsertTagsListenerTest.php
Labels: bug

#7144 Fix the PHP subprocess call once again
  core-bundle/src/Util/ProcessUtil.php
Labels: bug

#7148 Disable the search index listener in the back end
  core-bundle/config/listener.yaml
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
Labels: bug

#7156 PHP 8.4 compatibility
  calendar-bundle/contao/classes/Calendar.php
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/BackendModule.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/library/Contao/Pagination.php
  core-bundle/contao/library/Contao/Search.php
  core-bundle/contao/library/Contao/TemplateInheritance.php
  core-bundle/contao/library/Contao/TemplateTrait.php
  core-bundle/contao/library/Contao/Widget.php
  core-bundle/contao/pages/PageError401.php
  core-bundle/contao/pages/PageError403.php
  faq-bundle/contao/modules/ModuleFaq.php
  newsletter-bundle/contao/modules/ModuleSubscribe.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
  test-case/src/DeprecatedClassesPhpunitExtension.php
  vendor-bin/ecs/config/legacy.php
Labels: CI

#7155 Backport 'Fix non-existent "contao.image.image_factory" in FeedItem.php'
  core-bundle/src/Resources/contao/library/Contao/FeedItem.php
Labels: bug

#7153 Fix non-existent "contao.image.image_factory" in FeedItem.php
  core-bundle/contao/library/Contao/FeedItem.php
Labels: bug

#7126 Automatically set `ParameterType::BOOLEAN` for booleans
  core-bundle/src/Resources/contao/library/Contao/Database/Statement.php
Labels: bug

#7161 Send an `X-Robots-Tag: noindex` header in the back end
  core-bundle/src/EventListener/BackendNoindexListener.php
  core-bundle/src/Resources/config/listener.yml
  core-bundle/tests/EventListener/BackendNoindexListenerTest.php
Labels: bug

#7086 Add a fallback route for the back end
  core-bundle/src/Resources/config/routes.yml
Labels: bug

#7160 Restore the time period back end settings
  core-bundle/src/Resources/contao/dca/tl_settings.php
  core-bundle/src/Resources/contao/languages/en/tl_settings.xlf
Labels: bug

#7169 Correctly resolve child definitions for callback tags
  core-bundle/src/DependencyInjection/Compiler/DataContainerCallbackPass.php
  core-bundle/tests/DependencyInjection/Compiler/DataContainerCallbackPassTest.php
  core-bundle/tests/Fixtures/src/EventListener/TestListener.php
Labels: bug

#7165 Fix invalid HTML markup in splash screens
  core-bundle/contao/templates/twig/content_element/_video.html.twig
  core-bundle/contao/templates/twig/content_element/vimeo.html.twig
  core-bundle/contao/templates/twig/content_element/youtube.html.twig
  core-bundle/tests/Controller/ContentElement/VideoControllerTest.php
Labels: bug
