Repository contao/contao, pull requests merged in 2025-09, with the labels that each got.

#8752 Backup the response context
  core-bundle/contao/controllers/FrontendIndex.php
Labels: bug

#8754 Additionally check the `disablePermissionsChecks` flag for back end modules
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/tests/Security/Voter/BackendAccessVoterTest.php
Labels: bug

#8759 Restore the "empty event list" message
  calendar-bundle/contao/modules/ModuleEventlist.php
Labels: bug

#8766 Make a job optional for the back end search reindex
  core-bundle/contao/classes/RebuildBackendSearchIndex.php
  core-bundle/src/Search/Backend/BackendSearch.php
  core-bundle/src/Search/Backend/ReindexConfig.php
  core-bundle/tests/Search/Backend/BackendSearchTest.php
  core-bundle/tests/Search/Backend/ReindexConfigTest.php
Labels: bug

#8771 Update and run the tools
  core-bundle/public/backend.1dd82b2b.js
  core-bundle/public/backend.1dd82b2b.js.LICENSE.txt
  core-bundle/public/backend.f6d01fb8.js
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/src/Filesystem/PublicUri/SymlinkedLocalFilesProvider.php
  core-bundle/src/Fragment/FragmentHandler.php
  core-bundle/src/InsertTag/ParsedSequence.php
  core-bundle/src/Session/SessionFactory.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  package-lock.json
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#8772 Update and run the tools
  core-bundle/src/DataContainer/PaletteBuilder.php
  core-bundle/tests/EventListener/HttpCache/StripQueryParametersSubscriberTest.php
  package-lock.json
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#8779 Check if the `Content-Type` header exists before using it in the `PreviewToolbarListener`
  core-bundle/src/EventListener/PreviewToolbarListener.php
  core-bundle/tests/EventListener/PreviewToolbarListenerTest.php
Labels: bug

#8775 Also apply cache headers in Twig layouts
  core-bundle/src/Controller/Page/AbstractLayoutPageController.php
  core-bundle/tests/Controller/Page/AbstractLayoutPageControllerTest.php
Labels: bug

#8784 Only set the request format when rendering a Turbo stream template
  core-bundle/src/Controller/AbstractBackendController.php
  core-bundle/tests/Controller/AbstractBackendControllerTest.php
Labels: bug

#8630 Implemented searching by UUID in the file manager
  core-bundle/contao/dca/tl_files.php
  core-bundle/contao/drivers/DC_Folder.php
Labels: feature

#8085 Preload the reader modules
  calendar-bundle/contao/modules/ModuleEventReader.php
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/models/ContentModel.php
  core-bundle/contao/modules/Module.php
  core-bundle/contao/modules/ModuleArticle.php
  core-bundle/contao/modules/ModuleProxy.php
  core-bundle/contao/pages/PageRegular.php
  core-bundle/src/DependencyInjection/Attribute/AsFrontendModule.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/Fragment/FragmentCompositor.php
  core-bundle/src/Twig/FragmentTemplate.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  faq-bundle/contao/modules/ModuleFaqReader.php
  news-bundle/contao/modules/ModuleNewsReader.php
  newsletter-bundle/contao/modules/ModuleNewsletterReader.php
Labels: bug

#8786 Add new basic entities `[lsqb]` and `[rsqb]`
  core-bundle/contao/library/Contao/Input.php
  core-bundle/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Contao/WidgetTest.php
Labels: feature

#8785 Use the Imagine info provider for format detection
  composer.json
  core-bundle/composer.json
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/src/DataCollector/ContaoDataCollector.php
  core-bundle/src/Image/Preview/ImaginePreviewProvider.php
  core-bundle/tests/DataCollector/ContaoDataCollectorTest.php
  core-bundle/tests/Image/Preview/ImaginePreviewProviderTest.php
Labels: feature

#8812 Move the preview toolbar into the shadow DOM
  core-bundle/contao/templates/twig/frontend_preview/toolbar_js.html.twig
Labels: bug

#8814 Do not check the page type when adding child pages
  core-bundle/src/Security/Voter/DataContainer/PagePermissionVoter.php
  core-bundle/tests/Security/Voter/DataContainer/PagePermissionVoterTest.php
Labels: bug

#8751 Fix the template module class
  core-bundle/contao/templates/twig/frontend_module/template.html.twig
Labels: bug

#8819 Do not hardcode the file preview
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_files.php
  core-bundle/contao/languages/en/tl_files.xlf
  core-bundle/src/EventListener/DataContainer/FileImagePreviewListener.php
Labels: bug

#8820 Add operation list attributes to hide the limit height toggle by default
  core-bundle/contao/templates/twig/backend/data_container/operations.html.twig
  core-bundle/src/DataContainer/AbstractDataContainerOperationsBuilder.php
  core-bundle/src/DataContainer/DataContainerGlobalOperationsBuilder.php
  core-bundle/src/DataContainer/DataContainerOperation.php
  core-bundle/src/DataContainer/DataContainerOperationsBuilder.php
  core-bundle/src/EventListener/DataContainer/DefaultGlobalOperationsListener.php
Labels: bug

#8817 Switch to hierarchical back links in the back end
  UPGRADE.md
  comments-bundle/contao/dca/tl_comments.php
  core-bundle/assets/controllers/toggle-nodes-controller.js
  core-bundle/assets/scripts/core.js
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/BackendTemplateTrait.php
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/classes/Versions.php
  core-bundle/contao/controllers/BackendConfirm.php
  core-bundle/contao/controllers/BackendMain.php
  core-bundle/contao/drivers/DC_File.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/library/Contao/Controller.php
  core-bundle/contao/library/Contao/System.php
  core-bundle/contao/modules/ModuleTwoFactor.php
  core-bundle/contao/templates/backend/be_maintenance.html5
  core-bundle/contao/templates/backend/be_two_factor.html5
  core-bundle/contao/templates/backend/be_wildcard.html5
  core-bundle/src/DataContainer/DataContainerOperationsBuilder.php
  core-bundle/src/DataContainer/DcaUrlAnalyzer.php
  core-bundle/src/EventListener/AdministratorEmailListener.php
  core-bundle/src/EventListener/Menu/BackendFavoritesListener.php
  core-bundle/src/EventListener/Menu/BackendHeaderListener.php
  core-bundle/src/EventListener/Menu/BackendJobsListener.php
  core-bundle/src/EventListener/RefererIdListener.php
  core-bundle/src/EventListener/StoreRefererListener.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/EventListener/AdministratorEmailListenerTest.php
  core-bundle/tests/EventListener/DataContainer/BackendFavoritesListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendFavoritesListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendHeaderListenerTest.php
  core-bundle/tests/EventListener/RefererIdListenerTest.php
  core-bundle/tests/EventListener/StoreRefererListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Functional/DcaUrlAnalyzerTest.php
  manager-bundle/src/EventListener/BackendMenuListener.php
  manager-bundle/tests/EventListener/BackendJobsListenerTest.php
  manager-bundle/tests/EventListener/BackendMenuListenerTest.php
Labels: feature

#8835 Bump the minimum Symfony version to 7.3
  calendar-bundle/composer.json
  comments-bundle/composer.json
  composer.json
  core-bundle/composer.json
  faq-bundle/composer.json
  listing-bundle/composer.json
  maker-bundle/composer.json
  manager-bundle/composer.json
  news-bundle/composer.json
  newsletter-bundle/composer.json
Labels: feature

#8853 Use a pointer cursor for the preview toolbar toggle
  core-bundle/templates/Frontend/preview_toolbar_base_js.html.twig
Labels: bug

#8831 Add links to the back end breadcrumb for views with a `key` parameter
  core-bundle/contao/classes/Backend.php
Labels: feature

#8855 Display the form field label if the widget is missing
  core-bundle/contao/dca/tl_form_field.php
Labels: bug

#8892 Map the backup object to file names
  core-bundle/src/Command/Backup/BackupRestoreCommand.php
Labels: bug

#8760 Make the accessible navigation breakpoint adjustable
  core-bundle/assets/scripts/frontend/navigation.js
  core-bundle/assets/styles/frontend/navigation.pcss
  core-bundle/contao/templates/modules/mod_navigation_accessible.html.twig
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/public/navigation.742f2632.js
  core-bundle/public/navigation.8e9846cd.js
  core-bundle/public/navigation.bbf12939.css
  core-bundle/public/navigation.fb29ed99.css
Labels: bug

#8691 Use the locale switcher to set the user language
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/src/Controller/Page/AbstractLayoutPageController.php
  core-bundle/src/EventListener/BackendLocaleListener.php
  core-bundle/src/EventListener/LocaleSubscriber.php
  core-bundle/src/Translation/LegacyLocaleSwitcher.php
  core-bundle/tests/Controller/Page/AbstractLayoutPageControllerTest.php
  core-bundle/tests/EventListener/BackendLocaleListenerTest.php
  core-bundle/tests/EventListener/LocaleSubscriberTest.php
  core-bundle/tests/Translation/LegacyLocaleSwitcherTest.php
Labels: bug

#8896 Remove a superfluous `"` in the data-action attribute of the `be_main` template
  core-bundle/contao/templates/backend/be_main.html5
Labels: bug
