Repository contao/contao, pull requests merged in 2025-06, with the labels that each got.

#8385 Also embed SVG images in emails
  core-bundle/contao/library/Contao/Email.php
Labels: bug

#8398 Correctly close the `header_outlets` block
  core-bundle/contao/templates/backend/be_main.html5
Labels: bug, feature

#8392 Always tag the news archives in the news feed controller
  news-bundle/src/Controller/Page/NewsFeedController.php
  news-bundle/tests/Controller/Page/NewsFeedControllerTest.php
Labels: bug

#8389 Handle empty news feed items in the news feed controller
  news-bundle/src/Controller/Page/NewsFeedController.php
Labels: bug

#8406 Fix the permission check when copying elements
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#8412 Do not use `MooTools.getElements()` in the `toggle-nodes-controller`
  core-bundle/assets/controllers/toggle-nodes-controller.js
  core-bundle/public/backend.4ad6842e.js
  core-bundle/public/backend.ab6b5b20.js
  core-bundle/public/backend.ab6b5b20.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug

#8417 Add the fieldset legend IDs again
  core-bundle/contao/drivers/DC_File.php
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#7825 Add a help text to form fields in the form generator
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/languages/en/tl_form_field.xlf
  core-bundle/contao/templates/forms/form_checkbox.html5
  core-bundle/contao/templates/forms/form_password.html5
  core-bundle/contao/templates/forms/form_radio.html5
  core-bundle/contao/templates/forms/form_range.html5
  core-bundle/contao/templates/forms/form_select.html5
  core-bundle/contao/templates/forms/form_text.html5
  core-bundle/contao/templates/forms/form_textarea.html5
  core-bundle/contao/templates/forms/form_upload.html5
Labels: feature

#8245 Implement a "store in session" setting for forms
  core-bundle/config/migrations.yaml
  core-bundle/contao/dca/tl_form.php
  core-bundle/contao/forms/Form.php
  core-bundle/contao/languages/en/tl_form.xlf
  core-bundle/contao/models/FormModel.php
  core-bundle/src/Migration/Version505/FormStoreSessionMigration.php
Labels: feature

#8393 Add a shortcut to get the `HtmlHeadBag`
  core-bundle/src/Controller/AbstractController.php
Labels: feature

#8410 Use listeners to set the dynamic parent table and the default labels
  core-bundle/config/listener.yaml
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/src/EventListener/DataContainer/DefaultLabelsListener.php
  core-bundle/src/EventListener/DataContainer/DynamicPtableListener.php
Labels: feature

#8404 Add the current member groups to the schema.org output
  core-bundle/config/services.yaml
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
  core-bundle/src/Routing/ResponseContext/JsonLd/ContaoPageSchema.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Routing/ResponseContext/JsonLd/ContaoPageSchemaTest.php
  core-bundle/tests/Routing/ResponseContext/JsonLd/JsonLdManagerTest.php
Labels: feature

#8424 Make the subscribed services optional in the abstract controllers
  core-bundle/src/Controller/AbstractBackendController.php
  core-bundle/src/Controller/AbstractController.php
  core-bundle/src/Controller/AbstractFragmentController.php
  core-bundle/src/Controller/ContentElement/AbstractDownloadContentElementController.php
  core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php
  core-bundle/src/Controller/Page/AbstractLayoutPageController.php
  core-bundle/src/Twig/Studio/Operation/AbstractOperation.php
  core-bundle/src/Twig/Studio/Operation/AbstractRenameVariantOperation.php
Labels: feature

#8433 Do not override `error_reporting` in `contao-api`
  manager-bundle/bin/contao-api
Labels: bug

#8439 Remove the `title` attribute from the breadcrumb elements
  core-bundle/contao/templates/modules/mod_breadcrumb.html5
Labels: bug

#8443 Add test for the `LinkInsertTag` class
  core-bundle/tests/InsertTag/Resolver/LinkInsertTagTest.php
Labels: CI

#8405 Fix multiple issues with referrers in the back end
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#8455 Fix side-effects in `Document::getContentCrawler()`
  core-bundle/src/Search/Document.php
  core-bundle/tests/Search/DocumentTest.php
Labels: bug

#8465 Allow selecting the backup within the `backup:restore` command
  core-bundle/src/Command/Backup/BackupRestoreCommand.php
  core-bundle/tests/Command/Backup/BackupRestoreCommandTest.php
Labels: feature

#8468 Fix a merge error in the guests migration
  core-bundle/src/Migration/Version500/AbstractGuestsMigration.php
Labels: bug

#8379 Fix absolute path URLs not enabling the lightbox
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#8476 Add `HtmlAttributes` to `be_main` and meta tags to the `HtmlHeadBag`
  core-bundle/contao/pages/PageRegular.php
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/contao/templates/frontend/fe_page.html5
  core-bundle/src/Routing/ResponseContext/HtmlHeadBag/HtmlHeadBag.php
  core-bundle/tests/Routing/ResponseContext/HtmlHeadBag/HtmlHeadBagTest.php
Labels: feature

#8373 Correctly resolve the preview URL inside content elements
  calendar-bundle/config/services.yaml
  calendar-bundle/src/EventListener/PreviewUrlCreateListener.php
  calendar-bundle/tests/EventListener/PreviewUrlCreateListenerTest.php
  core-bundle/config/listener.yaml
  core-bundle/src/DataContainer/DynamicPtableTrait.php
  core-bundle/src/EventListener/PreviewUrlCreateListener.php
  core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php
  core-bundle/tests/EventListener/PreviewUrlCreateListenerTest.php
  news-bundle/config/services.yaml
  news-bundle/src/EventListener/PreviewUrlCreateListener.php
  news-bundle/tests/EventListener/PreviewUrlCreateListenerTest.php
Labels: bug

#8499 Remove `noSearch` from `news_feed` and use permission for `newsArchives` options
  news-bundle/config/services.yaml
  news-bundle/contao/dca/tl_page.php
  news-bundle/src/EventListener/DataContainer/PageListener.php
  news-bundle/tests/EventListener/DataContainer/PageListenerTest.php
Labels: bug

#8490 Switch the DCA request on `kernel.request` and `kernel.finish_request`
  core-bundle/config/listener.yaml
  core-bundle/contao/library/Contao/DcaLoader.php
  core-bundle/src/EventListener/DcaSwitchRequestListener.php
Labels: bug
