Repository contao/contao, pull requests merged in 2025-02, with the labels that each got.

#7975 Add breadcrumb separators to the back end title
  core-bundle/contao/controllers/BackendMain.php
Labels: bug

#7995 Allow using basic entities in TinyMCE fields
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_form.php
  faq-bundle/contao/dca/tl_faq.php
  newsletter-bundle/contao/dca/tl_module.php
  newsletter-bundle/contao/dca/tl_newsletter.php
Labels: bug

#7990 Unset the default `UriSigner` parameters when generating download URLs
  core-bundle/src/Filesystem/FileDownloadHelper.php
Labels: bug

#7991 Sort the news feed in descending order
  core-bundle/src/Controller/FrontendModule/FeedReaderController.php
Labels: bug

#7998 Enable format conversion for more image formats
  core-bundle/contao/dca/tl_image_size.php
  core-bundle/src/Image/PictureFactory.php
Labels: feature

#7999 Add support for content elements in page layouts
  core-bundle/contao/config/config.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_content.xlf
  core-bundle/contao/languages/en/tl_layout.xlf
  core-bundle/contao/languages/en/tl_theme.xlf
  core-bundle/contao/pages/PageRegular.php
  core-bundle/contao/widgets/ModuleWizard.php
  core-bundle/src/EventListener/DataContainer/ContentRecordLabelListener.php
  core-bundle/tests/EventListener/DataContainer/ContentRecordLabelListenerTest.php
Labels: feature

#8001 Use Symfony locks instead of DB locks for the `Cron` service
  composer.json
  core-bundle/composer.json
  core-bundle/config/services.yaml
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/tests/Cron/CronTest.php
Labels: bug, also affects 4.13

#8002 Metadata overwriting via empty insert tag
  core-bundle/config/services.yaml
  core-bundle/contao/library/Contao/Model/MetadataTrait.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  core-bundle/src/InsertTag/Resolver/EmptyInsertTag.php
Labels: feature

#8008 Test empty metadata overwrite
  core-bundle/tests/File/MetadataTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
Labels: bug

#8015 Backport the `MSC.edit` translation
  core-bundle/contao/languages/en/default.xlf
Labels: bug

#8016 Enable `enableKeyboardAccessibility` for the ace editor
  core-bundle/contao/templates/backend/be_ace.html5
Labels: bug, also affects 4.13

#8019 Close the search bar on the input `blur` event
  core-bundle/contao/templates/twig/backend/search/_container.html.twig
Labels: bug

#8018 Remove `<turbo-frame>` in the DC drivers
  core-bundle/contao/drivers/DC_File.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/src/DataContainer/ButtonsBuilder.php
Labels: bug

#8017 Enable `enableKeyboardAccessibility` for the ACE editor
  core-bundle/assets/controllers/ace-controller.js
  core-bundle/contao/templates/backend/be_ace.html5
  core-bundle/public/backend.0d446f87.js
  core-bundle/public/backend.7e6ce7bf.js
  core-bundle/public/backend.7e6ce7bf.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug

#8021 Use a prefix for the passkey user handle
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/classes/FrontendUser.php
  core-bundle/contao/library/Contao/User.php
  core-bundle/contao/modules/ModuleTwoFactor.php
  core-bundle/src/Entity/WebauthnCredential.php
  core-bundle/src/EventListener/WebauthnRouteListener.php
  core-bundle/src/Repository/WebauthnCredentialRepository.php
  core-bundle/src/Repository/WebauthnUserEntityRepository.php
  core-bundle/tests/EventListener/WebauthnRouteListenerTest.php
  manager-bundle/skeleton/config/security.yaml
Labels: bug

#8026 Replace the deprecated global variable `request_token`
  core-bundle/templates/Backend/be_menu.html.twig
  core-bundle/templates/Frontend/preview_toolbar_base.html.twig
Labels: bug

#8039 Fix `Undefined variable: $this` in tests
  core-bundle/tests/Command/Backup/BackupCreateCommandTest.php
  core-bundle/tests/Command/Backup/BackupRestoreCommandTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriberTest.php
  core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php
  core-bundle/tests/Doctrine/Schema/DcaSchemaProviderTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Fixtures/Helper/HookHelper.php
  core-bundle/tests/Image/Studio/FigureTest.php
  core-bundle/tests/Image/Studio/ImageResultTest.php
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
  core-bundle/tests/Monolog/ContaoTableProcessorTest.php
  phpstan.neon
  test-case/src/ContaoTestCase.php
Labels: feature

#8041 Use `eval()` to generate the dynamic test classes
  test-case/src/ContaoTestCase.php
Labels: CI

#8035 Change the ACE editor theme on the color change event
  core-bundle/assets/controllers/ace-controller.js
  core-bundle/assets/controllers/color-scheme-controller.js
  core-bundle/contao/templates/backend/be_ace.html5
  core-bundle/public/backend.7e6ce7bf.js
  core-bundle/public/backend.bd8e2243.js
  core-bundle/public/backend.bd8e2243.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug

#8053 Use table lock for `contao.cron` service again
  composer.json
  core-bundle/composer.json
  core-bundle/config/services.yaml
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/tests/Cron/CronTest.php
Labels: bug, also affects 4.13

#8058 Update and run the tools
  core-bundle/contao/templates/backend/be_ace.html5
  core-bundle/src/EventListener/DataContainer/FallbackRecordLabelListener.php
  core-bundle/src/Image/Studio/FigureBuilder.php
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#8059 Update and run the tools
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Twig/Inspector/Inspector.php
  core-bundle/tests/Controller/BackendTemplateStudioControllerTest.php
  core-bundle/tests/Controller/PreviewLinkControllerTest.php
  core-bundle/tests/DependencyInjection/Compiler/AddAvailableTransportsPassTest.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Image/ImageFactoryTest.php
  core-bundle/tests/Messenger/WebWorkerTest.php
  core-bundle/tests/Translation/MessageCatalogueTest.php
  core-bundle/tests/Translation/TranslatorTest.php
  core-bundle/tests/Twig/Studio/Operation/SaveOperationTest.php
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#8067 Do not unset the default operation options
  calendar-bundle/contao/dca/tl_calendar_events.php
  calendar-bundle/contao/dca/tl_calendar_feed.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/dca/tl_theme.php
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  core-bundle/tests/EventListener/DataContainer/DefaultOperationsListenerTest.php
  news-bundle/contao/dca/tl_news.php
  newsletter-bundle/contao/dca/tl_newsletter.php
Labels: bug

#8073 Make the back end tabs "turbo-temporary"
  core-bundle/contao/templates/twig/backend/component/tabs/_container.html.twig
Labels: bug

#8082 Add `data-turbo-prefetch="false"` to the favorites menu
  core-bundle/src/EventListener/Menu/BackendFavoritesListener.php
  core-bundle/tests/EventListener/Menu/BackendFavoritesListenerTest.php
Labels: bug

#8083 Use the correct icon in the favorites menu
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_favorites.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/themes/flexible/icons/plain--dark.svg
  core-bundle/contao/themes/flexible/icons/plain.svg
Labels: bug

#8092 Adjust the default location for Loupe
  manager-bundle/src/ContaoManager/Plugin.php
Labels: bug

#8088 Prevent useless messages in the search listener
  core-bundle/config/listener.yaml
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
Labels: bug

#8086 Log all sent and failed email messages
  core-bundle/config/listener.yaml
  core-bundle/contao/library/Contao/Email.php
  core-bundle/src/EventListener/LogEmailMessageListener.php
  core-bundle/tests/EventListener/LogEmailMessageListenerTest.php
Labels: bug

#8087 Generate the correct path when adding Contao components as assets
  core-bundle/src/DependencyInjection/Compiler/AddAssetsPackagesPass.php
Labels: bug

#8096 Update and run the tools
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#8098 Do not apply the `core.js` textarea resize script to the ACE editor
  core-bundle/contao/drivers/DC_Folder.php
Labels: bug

#8100 Update and run the tools
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/tests/Contao/ControllerTest.php
  core-bundle/tests/Contao/Database/StatementTest.php
  core-bundle/tests/Contao/EnvironmentTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Contao/TemplateLoaderTest.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/Security/LogoutListenerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Framework/ContaoFrameworkTest.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Intl/CountriesTest.php
  core-bundle/tests/Intl/LocalesTest.php
  core-bundle/tests/Picker/ArticlePickerProviderTest.php
  core-bundle/tests/Security/Authentication/AuthenticationSuccessHandlerTest.php
  core-bundle/tests/Security/User/ContaoUserProviderTest.php
  core-bundle/tests/String/SimpleTokenParserTest.php
  core-bundle/tests/Translation/MessageCatalogueTest.php
  core-bundle/tests/Translation/TranslatorTest.php
  manager-bundle/tests/Command/MaintenanceModeCommandTest.php
  manager-bundle/tests/ContaoManager/PluginTest.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
  vendor-bin/ecs/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
Labels: CI

#8056 Make VFS tests compatible with `league/flysystem-bundle` 3.4.0
  core-bundle/tests/DependencyInjection/Filesystem/FilesystemConfigurationTest.php
Labels: bug

#8055 Use a non-blocking table lock for `contao.cron`
  core-bundle/src/Cron/Cron.php
  core-bundle/src/Repository/CronJobRepository.php
  core-bundle/tests/Cron/CronTest.php
Labels: bug

#8104 Allow entire tables to be excluded from the back end search
  core-bundle/contao/dca/tl_favorites.php
  core-bundle/contao/dca/tl_log.php
  core-bundle/contao/dca/tl_opt_in.php
  core-bundle/contao/dca/tl_preview_link.php
  core-bundle/contao/dca/tl_undo.php
  core-bundle/src/Search/Backend/Provider/TableDataContainerProvider.php
  core-bundle/tests/Fixtures/table-data-container-provider/dca/tl_undo.php
  core-bundle/tests/Search/Backend/Provider/TableDataContainerProviderTest.php
Labels: bug

#8111 Only omit the request token for the edit operation in the form generator
  core-bundle/contao/dca/tl_form_field.php
Labels: bug

#8118 Allow passing children as `string` within the clipboard manager
  core-bundle/src/DataContainer/ClipboardManager.php
Labels: bug

#8123 Improve the language cache warmer performance
  core-bundle/src/Cache/ContaoCacheWarmer.php
  core-bundle/tests/Cache/ContaoCacheWarmerTest.php
Labels: bug

#8093 Change `Template` to `FragmentTemplate` in the maker bundle
  maker-bundle/skeleton/content-element/ContentElement.tpl.php
  maker-bundle/skeleton/dca-callback/Callback.tpl.php
  maker-bundle/skeleton/frontend-module/FrontendModule.tpl.php
Labels: bug

#8128 Modernize the maker bundle
  maker-bundle/config/services.yaml
  maker-bundle/skeleton/content-element/ContentElement.tpl.php
  maker-bundle/skeleton/content-element/content_element.tpl.html.twig
  maker-bundle/skeleton/content-element/content_element.tpl.php
  maker-bundle/skeleton/content-element/source.tpl.php
  maker-bundle/skeleton/content-element/target.tpl.php
  maker-bundle/skeleton/frontend-module/FrontendModule.tpl.php
  maker-bundle/skeleton/frontend-module/frontend_module.tpl.html.twig
  maker-bundle/skeleton/frontend-module/frontend_module.tpl.php
  maker-bundle/skeleton/frontend-module/source.tpl.php
  maker-bundle/skeleton/frontend-module/target.tpl.php
  maker-bundle/src/Config/XliffMerger.php
  maker-bundle/src/Generator/LanguageFileGenerator.php
  maker-bundle/src/Maker/AbstractFragmentMaker.php
  maker-bundle/src/Maker/MakeContentElement.php
  maker-bundle/src/Maker/MakeFrontendModule.php
  maker-bundle/tests/Config/XliffMergerTest.php
Labels: bug

#8131 Add `spellcheck="false"` to the search input field
  core-bundle/contao/templates/modules/mod_search.html5
Labels: bug

#8130 Add body template and attributes callback to the maker bundle
  maker-bundle/config/callbacks.yaml
  maker-bundle/src/Maker/MakeDcaCallback.php
  maker-bundle/src/Maker/MakeEventListener.php
  maker-bundle/src/Maker/MakeHook.php
  maker-bundle/src/Reflection/MethodDefinition.php
  maker-bundle/tests/Reflection/MethodDefinitionTest.php
Labels: bug

#8139 Only assume a self-referencing table in mode 5 when deleting records
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#8138 Fix the phpDoc of the `ImageFactoryInterface::create()` method
  core-bundle/src/Image/ImageFactoryInterface.php
Labels: bug, unconfirmed

#8143 Fix row size too large error
  core-bundle/config/commands.yaml
  core-bundle/src/Command/MigrateCommand.php
  core-bundle/src/Migration/CommandCompiler.php
  core-bundle/tests/Command/MigrateCommandTest.php
  core-bundle/tests/Functional/MigrateCommandTest.php
Labels: bug

#8133 Fix the module wizard and section wizard scripts
  core-bundle/assets/backend.js
  core-bundle/assets/controllers/row-wizard-controller.js
  core-bundle/assets/scripts/modulewizard.js
  core-bundle/assets/scripts/sectionwizard.js
  core-bundle/contao/templates/twig/backend/widget/module_wizard.html.twig
  core-bundle/contao/templates/twig/backend/widget/section_wizard.html.twig
  core-bundle/contao/widgets/ModuleWizard.php
  core-bundle/contao/widgets/SectionWizard.php
  core-bundle/public/backend.2f841948.js
  core-bundle/public/backend.2f841948.js.LICENSE.txt
  core-bundle/public/backend.8fe96e32.js
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug
