Repository contao/contao, pull requests merged in 2025-07, with the labels that each got.

#8506 Update the `flexible` theme - clean up utilities and miscellaneous styles
  core-bundle/contao/themes/flexible/backend.879947de.css
  core-bundle/contao/themes/flexible/backend.f01551ea.css
  core-bundle/contao/themes/flexible/confirm.7d070fd2.css
  core-bundle/contao/themes/flexible/confirm.c8ccd613.css
  core-bundle/contao/themes/flexible/conflict.427d693c.css
  core-bundle/contao/themes/flexible/conflict.9bf22d8f.css
  core-bundle/contao/themes/flexible/diff.005c877c.css
  core-bundle/contao/themes/flexible/diff.43f8d9db.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/help.41a3a8ed.css
  core-bundle/contao/themes/flexible/help.5dcac4ec.css
  core-bundle/contao/themes/flexible/login.85b9ff8c.css
  core-bundle/contao/themes/flexible/login.a3044328.css
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/popup.36464127.css
  core-bundle/contao/themes/flexible/popup.a49aa6b7.css
  core-bundle/contao/themes/flexible/styles/abstracts/a11y.pcss
  core-bundle/contao/themes/flexible/styles/abstracts/clear.pcss
  core-bundle/contao/themes/flexible/styles/abstracts/helpers.pcss
  core-bundle/contao/themes/flexible/styles/base/default.pcss
  core-bundle/contao/themes/flexible/styles/base/utilities.pcss
  core-bundle/contao/themes/flexible/styles/components/overview.pcss
  core-bundle/contao/themes/flexible/styles/main.pcss
  core-bundle/contao/themes/flexible/styles/styles/misc.pcss
Labels: feature

#8507 Update the `flexible` theme - cleanup the variables
  core-bundle/contao/themes/flexible/backend.591e6a5a.css
  core-bundle/contao/themes/flexible/confirm.93939319.css
  core-bundle/contao/themes/flexible/conflict.63b8370d.css
  core-bundle/contao/themes/flexible/diff.816ef69d.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/help.f9348280.css
  core-bundle/contao/themes/flexible/login.c512bc0b.css
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/popup.60bd7be3.css
  core-bundle/contao/themes/flexible/styles/base/default.pcss
  core-bundle/contao/themes/flexible/styles/base/icons.pcss
  core-bundle/contao/themes/flexible/styles/base/variables.pcss
Labels: feature

#8456 Implement rate limiting on the search indexer
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/EventListener/SearchIndexListener.php
  core-bundle/src/Search/Document.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/EventListener/SearchIndexListenerTest.php
Labels: feature

#8462 Support ISO 3166-2 country subdivision codes
  core-bundle/contao/dca/tl_member.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
  core-bundle/src/Intl/Countries.php
  core-bundle/tests/Intl/CountriesTest.php
Labels: feature

#8418 Deprecate legacy content elements with fragment replacements
  core-bundle/contao/elements/ContentAccordion.php
  core-bundle/contao/elements/ContentAccordionStart.php
  core-bundle/contao/elements/ContentAccordionStop.php
  core-bundle/contao/elements/ContentCode.php
  core-bundle/contao/elements/ContentDownload.php
  core-bundle/contao/elements/ContentDownloads.php
  core-bundle/contao/elements/ContentGallery.php
  core-bundle/contao/elements/ContentHeadline.php
  core-bundle/contao/elements/ContentHtml.php
  core-bundle/contao/elements/ContentHyperlink.php
  core-bundle/contao/elements/ContentImage.php
  core-bundle/contao/elements/ContentList.php
  core-bundle/contao/elements/ContentPlayer.php
  core-bundle/contao/elements/ContentSliderStart.php
  core-bundle/contao/elements/ContentSliderStop.php
  core-bundle/contao/elements/ContentTable.php
  core-bundle/contao/elements/ContentTeaser.php
  core-bundle/contao/elements/ContentText.php
  core-bundle/contao/elements/ContentToplink.php
  core-bundle/contao/elements/ContentVimeo.php
  core-bundle/contao/elements/ContentYouTube.php
Labels: feature

#8495 Add a general `From` override for the `ContaoMailer`
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Mailer/ContaoMailer.php
  core-bundle/tests/Mailer/ContaoMailerTest.php
Labels: feature

#8479 Enable `postcss-preset-env` for the `flexible` theme
  core-bundle/contao/themes/flexible/backend.494527c6.css
  core-bundle/contao/themes/flexible/backend.b2ec6a20.css
  core-bundle/contao/themes/flexible/confirm.2c3ea490.css
  core-bundle/contao/themes/flexible/confirm.c02396c1.css
  core-bundle/contao/themes/flexible/conflict.73455bba.css
  core-bundle/contao/themes/flexible/conflict.7aa816cd.css
  core-bundle/contao/themes/flexible/diff.78a01936.css
  core-bundle/contao/themes/flexible/diff.cd77ca08.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/help.530bc3fa.css
  core-bundle/contao/themes/flexible/help.ee665ff2.css
  core-bundle/contao/themes/flexible/login.082e0a12.css
  core-bundle/contao/themes/flexible/login.16e14580.css
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/popup.0c270a36.css
  core-bundle/contao/themes/flexible/popup.ff34b412.css
  core-bundle/contao/themes/flexible/tinymce-dark.b8510851.css
  core-bundle/contao/themes/flexible/tinymce-dark.c3737507.css
  core-bundle/contao/themes/flexible/tinymce.3c7bc5e0.css
  core-bundle/contao/themes/flexible/tinymce.808c0ed4.css
  postcss.config.js
  webpack.config.js
Labels: feature

#8466 Use `::` to reference fragment methods
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
Labels: bug

#8526 Add number format validation for slider settings
  core-bundle/contao/dca/tl_content.php
Labels: bug

#8524 Fix the CI chain
  core-bundle/src/InsertTag/ParsedSequence.php
Labels: CI

#8522 Make the table dynamic in the `DisableAppConfiguredSettingsListener`
  core-bundle/src/EventListener/DataContainer/DisableAppConfiguredSettingsListener.php
  core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php
Labels: feature

#8372 Simplify the operations menu labels
  .editorconfig
  calendar-bundle/contao/languages/en/tl_calendar.xlf
  calendar-bundle/contao/languages/en/tl_calendar_events.xlf
  calendar-bundle/contao/languages/en/tl_calendar_feed.xlf
  comments-bundle/contao/languages/en/tl_comments.xlf
  core-bundle/assets/controllers/limit-height-controller.js
  core-bundle/assets/controllers/sortable-controller.js
  core-bundle/assets/controllers/toggle-nodes-controller.js
  core-bundle/assets/scripts/core.js
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_article.xlf
  core-bundle/contao/languages/en/tl_content.xlf
  core-bundle/contao/languages/en/tl_favorites.xlf
  core-bundle/contao/languages/en/tl_files.xlf
  core-bundle/contao/languages/en/tl_form.xlf
  core-bundle/contao/languages/en/tl_form_field.xlf
  core-bundle/contao/languages/en/tl_image_size.xlf
  core-bundle/contao/languages/en/tl_image_size_item.xlf
  core-bundle/contao/languages/en/tl_layout.xlf
  core-bundle/contao/languages/en/tl_member.xlf
  core-bundle/contao/languages/en/tl_member_group.xlf
  core-bundle/contao/languages/en/tl_module.xlf
  core-bundle/contao/languages/en/tl_opt_in.xlf
  core-bundle/contao/languages/en/tl_page.xlf
  core-bundle/contao/languages/en/tl_templates.xlf
  core-bundle/contao/languages/en/tl_theme.xlf
  core-bundle/contao/languages/en/tl_undo.xlf
  core-bundle/contao/languages/en/tl_user.xlf
  core-bundle/contao/languages/en/tl_user_group.xlf
  core-bundle/contao/templates/twig/backend/data_container/operations.html.twig
  core-bundle/public/backend.4bb6aee7.js
  core-bundle/public/backend.c9d60e74.js
  core-bundle/public/backend.c9d60e74.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/src/DataContainer/AbstractDataContainerOperationsBuilder.php
  core-bundle/src/DataContainer/DataContainerOperationsBuilder.php
  core-bundle/src/EventListener/DataContainer/DefaultGlobalOperationsListener.php
  core-bundle/src/EventListener/DataContainer/DefaultLabelsListener.php
  core-bundle/tests/DataContainer/DataContainerOperationBuilderTest.php
  faq-bundle/contao/languages/en/tl_faq.xlf
  faq-bundle/contao/languages/en/tl_faq_category.xlf
  news-bundle/contao/languages/en/tl_news.xlf
  news-bundle/contao/languages/en/tl_news_archive.xlf
  newsletter-bundle/contao/dca/tl_newsletter_recipients.php
  newsletter-bundle/contao/languages/en/tl_newsletter.xlf
  newsletter-bundle/contao/languages/en/tl_newsletter_channel.xlf
  newsletter-bundle/contao/languages/en/tl_newsletter_recipients.xlf
Labels: bug

#8483 Always add a close button to messages
  core-bundle/assets/controllers/message-outlet-controller.js
  core-bundle/assets/styles/component/message.pcss
  core-bundle/config/services.yaml
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/templates/twig/backend/component/message/_message.html.twig
  core-bundle/public/backend.02736499.css
  core-bundle/public/backend.7040c497.css
  core-bundle/public/backend.aa972234.js
  core-bundle/public/backend.d44585d4.js
  core-bundle/public/backend.d44585d4.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/src/Twig/Global/ContaoVariable.php
  core-bundle/tests/Twig/Global/ContaoVariableTest.php
Labels: bug

#8533 Refactor the "switch user" operations
  core-bundle/config/listener.yaml
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/languages/en/tl_user.xlf
  core-bundle/src/EventListener/DataContainer/SwitchMemberOperationListener.php
  core-bundle/src/EventListener/DataContainer/SwitchUserOperationListener.php
  core-bundle/tests/EventListener/DataContainer/SwitchMemberOperationTest.php
  core-bundle/tests/EventListener/DataContainer/SwitchUserOperationTest.php
Labels: bug

#8511 Make the registration expiration time configurable
  core-bundle/contao/models/MemberModel.php
  core-bundle/contao/modules/ModuleRegistration.php
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/OptIn/OptIn.php
  core-bundle/src/OptIn/OptInInterface.php
Labels: feature

#8011 Implement passkey support for the front end
  core-bundle/assets/passkey_create.js
  core-bundle/assets/passkey_login.js
  core-bundle/config/controller.yaml
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/config/config.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/languages/en/tl_content.xlf
  core-bundle/contao/modules/ModuleLogin.php
  core-bundle/contao/modules/ModuleTwoFactor.php
  core-bundle/contao/templates/twig/content_element/login.html.twig
  core-bundle/contao/templates/twig/content_element/manage_passkeys.html.twig
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/public/passkey_create.1d33d033.js
  core-bundle/public/passkey_login.6dc9446a.js
  core-bundle/src/Controller/ContentElement/LoginController.php
  core-bundle/src/Controller/ContentElement/ManagePasskeysController.php
  core-bundle/src/EventListener/WebauthnRouteListener.php
  core-bundle/src/Repository/WebauthnCredentialRepository.php
  core-bundle/src/Repository/WebauthnUserEntityRepository.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/Voter/WebauthnCredentialVoter.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/LoginControllerTest.php
  core-bundle/tests/Controller/ContentElement/ManagePasskeysControllerTest.php
  core-bundle/tests/EventListener/WebauthnRouteListenerTest.php
  core-bundle/tests/Functional/app/config/config_test.yaml
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
  core-bundle/tests/Security/Voter/WebauthnCredentialVoterTest.php
  manager-bundle/skeleton/config/config.yaml
  manager-bundle/skeleton/config/security.yaml
  package-lock.json
  package.json
  webpack.config.js
Labels: feature

#8541 Update and run the tools
  calendar-bundle/contao/classes/Events.php
  calendar-bundle/contao/dca/tl_page.php
  calendar-bundle/tests/InsertTag/EventInsertTagTest.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/forms/FormAltcha.php
  core-bundle/src/Filesystem/PublicUri/SymlinkedLocalFilesProvider.php
  core-bundle/src/Job/Job.php
  core-bundle/src/Search/Document.php
  core-bundle/src/Session/SessionFactory.php
  core-bundle/tests/DataContainer/DataContainerGlobalOperationBuilderTest.php
  core-bundle/tests/DataContainer/PaletteBuilderTest.php
  core-bundle/tests/EventListener/RequestTokenListenerTest.php
  core-bundle/tests/Filesystem/DirectoryFilterVirtualFilesystemTest.php
  core-bundle/tests/Job/JobsTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/Security/Voter/DataContainer/AbstractAccessVoterTestCase.php
  core-bundle/tests/Security/Voter/DataContainer/ContentAliasDeleteVoterTest.php
  faq-bundle/tests/InsertTag/FaqInsertTagTest.php
  news-bundle/tests/InsertTag/NewsInsertTagTest.php
  package-lock.json
  vendor-bin/ecs/composer.lock
Labels: CI

#8542 Fix the clickable area of the operation buttons
  core-bundle/contao/themes/flexible/backend.5224c800.css
  core-bundle/contao/themes/flexible/backend.94ca56ac.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/layout/list-view.pcss
Labels: bug

#8242 Deprecate `Backend.enableImageSizeWidgets()`
  core-bundle/assets/controllers/image-size-controller.js
  core-bundle/assets/scripts/core.js
  core-bundle/contao/widgets/ImageSize.php
  core-bundle/public/backend.926b9b31.js
  core-bundle/public/backend.e1bf5ff9.js
  core-bundle/public/backend.e1bf5ff9.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: feature

#8549 Correctly hide disabled operations
  core-bundle/contao/templates/twig/backend/data_container/operations.html.twig
Labels: bug

#8559 Merge branch '5.3' into 5.5
  core-bundle/config/controller.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/templates/twig/component/_rich_text.html.twig
  core-bundle/contao/templates/twig/content_element/html.html.twig
  core-bundle/contao/templates/twig/content_element/list.html.twig
  core-bundle/contao/templates/twig/content_element/table.html.twig
  core-bundle/contao/templates/twig/content_element/teaser.html.twig
  core-bundle/src/Controller/InsertTagsController.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/SubrequestCacheSubscriber.php
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/InsertTag/Resolver/DateInsertTag.php
  core-bundle/src/InsertTag/Resolver/FormInsertTag.php
  core-bundle/src/InsertTag/Resolver/FragmentInsertTag.php
  core-bundle/src/Util/ProcessUtil.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Controller/InsertTagsControllerTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/File/MetadataTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/FigureRendererTest.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
  core-bundle/tests/InsertTag/Resolver/FormatDateInsertTagTest.php
  core-bundle/tests/InsertTag/Resolver/LinkInsertTagTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/String/HtmlDecoderTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/InsertTagTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: release

#8563 Merge branch '5.5' into 5.6
  core-bundle/config/controller.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_content.php
  core-bundle/contao/library/Contao/InsertTags.php
  core-bundle/contao/templates/backend/be_two_factor.html5
  core-bundle/contao/templates/twig/component/_rich_text.html.twig
  core-bundle/contao/templates/twig/content_element/html.html.twig
  core-bundle/contao/templates/twig/content_element/list.html.twig
  core-bundle/contao/templates/twig/content_element/table.html.twig
  core-bundle/contao/templates/twig/content_element/teaser.html.twig
  core-bundle/contao/templates/twig/content_element/toplink.html.twig
  core-bundle/src/Controller/InsertTagsController.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/SubrequestCacheSubscriber.php
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/src/InsertTag/Resolver/DateInsertTag.php
  core-bundle/src/InsertTag/Resolver/FormInsertTag.php
  core-bundle/src/InsertTag/Resolver/FragmentInsertTag.php
  core-bundle/src/Util/ProcessUtil.php
  core-bundle/tests/Contao/InsertTagsTest.php
  core-bundle/tests/Contao/StringUtilTest.php
  core-bundle/tests/Contao/TemplateTest.php
  core-bundle/tests/Controller/BackendCsvImportControllerTest.php
  core-bundle/tests/Controller/ContentElement/ToplinkControllerTest.php
  core-bundle/tests/Controller/InsertTagsControllerTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/File/MetadataTest.php
  core-bundle/tests/Image/Studio/FigureBuilderTest.php
  core-bundle/tests/Image/Studio/FigureRendererTest.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
  core-bundle/tests/InsertTag/Resolver/FormatDateInsertTagTest.php
  core-bundle/tests/InsertTag/Resolver/LinkInsertTagTest.php
  core-bundle/tests/Routing/ResponseContext/CoreResponseContextFactoryTest.php
  core-bundle/tests/String/HtmlDecoderTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/InsertTagTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: release

#8564 Run the nightly build with PHP 8.5
  .github/workflows/ci.yml
Labels: CI

#8593 Switch to `php-feed-io/feed-io`
  calendar-bundle/composer.json
  composer.json
  core-bundle/composer.json
  news-bundle/composer.json
Labels: bug

#8590 Deprecate `Contao\Feed` and `Contao\FeedItem`
  core-bundle/contao/library/Contao/Feed.php
  core-bundle/contao/library/Contao/FeedItem.php
Labels: bug

#8583 Use the page finder in the fragment insert tag
  core-bundle/config/services.yaml
  core-bundle/src/InsertTag/Resolver/FragmentInsertTag.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
Labels: bug

#8586 Remove the close button from non-gallery `fileTree` widgets
  core-bundle/contao/widgets/FileTree.php
Labels: bug

#8600 Add `aria-current="page"` to the active navigation item
  core-bundle/contao/templates/navigation/nav_default.html5
Labels: bug
