Repository contao/contao, pull requests merged in 2025-05, with the labels that each got.

#8329 Fix Twig CI failures
  core-bundle/tests/Twig/Inheritance/DynamicExtendsTokenParserTest.php
Labels: CI

#8328 Add `alwaysSave` to `tl_calendar_feed.feedBase`
  calendar-bundle/contao/dca/tl_calendar_feed.php
Labels: bug

#8344 Remove `error_reporting` from `contao-setup`
  manager-bundle/bin/contao-setup
Labels: bug

#8341 Strip more irrelevant query parameters
  core-bundle/src/EventListener/HttpCache/StripQueryParametersSubscriber.php
Labels: bug

#8334 Correctly support the `:collapsed` keyword in the palette manipulator
  core-bundle/src/DataContainer/PaletteManipulator.php
Labels: bug

#8327 Make `tl_newsletter_subscriptions.email` nullable
  newsletter-bundle/contao/dca/tl_newsletter_recipients.php
Labels: bug

#8324 Remove the `tableless` leftovers
  core-bundle/contao/models/FormModel.php
  core-bundle/contao/models/ModuleModel.php
Labels: bug

#8269 Fix the back end layout for mobile devices
  core-bundle/contao/themes/flexible/backend.2798f777.css
  core-bundle/contao/themes/flexible/backend.c7915ff5.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/main.css
Labels: bug

#8323 Allow absolute URLs in DCA backlinks
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#8347 Return the correct object instance in the `DataContainerOperationsBuilder`
  core-bundle/src/DataContainer/DataContainerOperationsBuilder.php
Labels: bug

#8297 Use the app cache instead of the system cache for the Template Studio
  core-bundle/config/services.yaml
  core-bundle/src/Twig/Inspector/Inspector.php
  core-bundle/src/Twig/Inspector/InspectorNodeVisitor.php
  core-bundle/src/Twig/Inspector/Storage.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Image/Studio/TwigMacrosTest.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Extension/DeprecationsNodeVisitorTest.php
  core-bundle/tests/Twig/Extension/InsertTagTest.php
  core-bundle/tests/Twig/Inheritance/DynamicIncludeTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/InheritanceTest.php
  core-bundle/tests/Twig/Inspector/InspectorNodeVisitorTest.php
  core-bundle/tests/Twig/Inspector/InspectorTest.php
  core-bundle/tests/Twig/Inspector/StorageTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/ResponseContext/AddTokenParserTest.php
  core-bundle/tests/Twig/Slots/SlotTokenParserTest.php
  core-bundle/tests/Twig/TwigIntegrationTest.php
Labels: bug

#8342 Catch exceptions in the `DelegatingIndexer`
  core-bundle/src/Search/Indexer/DelegatingIndexer.php
  core-bundle/src/Search/Indexer/IndexerException.php
  core-bundle/tests/Search/Indexer/DelegatingIndexerTest.php
Labels: bug

#8221 Add workers to the functional tests
  core-bundle/config/commands.yaml
  core-bundle/config/services.yaml
  core-bundle/tests/Functional/ServiceArgumentsTest.php
  core-bundle/tests/Functional/app/config/config_test.yaml
Labels: bug

#8274 Add search listeners for news, events and FAQs
  calendar-bundle/config/services.yaml
  calendar-bundle/src/EventListener/DataContainer/EventSearchListener.php
  calendar-bundle/tests/EventListener/DataContainer/EventSearchListenerTest.php
  faq-bundle/config/services.yaml
  faq-bundle/src/EventListener/DataContainer/FaqSearchListener.php
  faq-bundle/tests/EventListener/DataContainer/FaqSearchListenerTest.php
  news-bundle/config/services.yaml
  news-bundle/src/EventListener/DataContainer/NewsSearchListener.php
  news-bundle/tests/EventListener/DataContainer/NewsSearchListenerTest.php
Labels: bug

#8319 Recursively run `StringUtil::decodeEntities()` on arrays
  core-bundle/contao/library/Contao/StringUtil.php
  core-bundle/tests/Contao/StringUtilTest.php
Labels: bug

#8352 Update and run the tools
  comments-bundle/tests/ContaoManager/PluginTest.php
  comments-bundle/tests/Util/BbCodeTest.php
  comments-bundle/tests/Util/NodeTest.php
  core-bundle/src/File/ModelMetadataTrait.php
  core-bundle/src/InsertTag/ParsedSequence.php
  core-bundle/src/Picker/AbstractPickerProvider.php
  core-bundle/src/Security/User/ContaoUserProvider.php
  core-bundle/tests/DependencyInjection/Compiler/ConfigureFilesystemPassTest.php
  core-bundle/tests/EventListener/BackendLocaleListenerTest.php
  core-bundle/tests/EventListener/DataContainer/PreviewLinkListenerTest.php
  newsletter-bundle/src/DependencyInjection/ContaoNewsletterExtension.php
  newsletter-bundle/src/Event/SendNewsletterEvent.php
  package-lock.json
  phpstan.neon
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#8350 Add the missing "Template Studio" translation
  core-bundle/contao/languages/en/modules.xlf
  core-bundle/src/EventListener/Menu/BackendTemplateStudioListener.php
  core-bundle/tests/EventListener/Menu/BackendTemplateStudioListenerTest.php
Labels: bug

#8296 Add the lost commit of #8207 again
  core-bundle/assets/controllers/backend-search-controller.js
  core-bundle/public/backend.e6de7ff8.js
  core-bundle/public/backend.e6de7ff8.js.LICENSE.txt
  core-bundle/public/backend.f5c44e33.js
  core-bundle/public/backend.f5c44e33.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug

#8362 Use Biome instead of Prettier
  .github/workflows/ci.yml
  .prettierignore
  .prettierrc
  biome.json
  core-bundle/assets/backend.js
  core-bundle/assets/controllers/ace-controller.js
  core-bundle/assets/controllers/backend-search-controller.js
  core-bundle/assets/controllers/choices-controller.js
  core-bundle/assets/controllers/clipboard-controller.js
  core-bundle/assets/controllers/deeplink-controller.js
  core-bundle/assets/controllers/image-size-controller.js
  core-bundle/assets/controllers/jump-targets-controller.js
  core-bundle/assets/controllers/limit-height-controller.js
  core-bundle/assets/controllers/metawizard-controller.js
  core-bundle/assets/controllers/operations-menu-controller.js
  core-bundle/assets/controllers/row-wizard-controller.js
  core-bundle/assets/controllers/scroll-offset-controller.js
  core-bundle/assets/controllers/serp-preview-controller.js
  core-bundle/assets/controllers/tabs-controller.js
  core-bundle/assets/controllers/template-studio-controller.js
  core-bundle/assets/controllers/tinymce-controller.js
  core-bundle/assets/controllers/toggle-fieldset-controller.js
  core-bundle/assets/controllers/toggle-nodes-controller.js
  core-bundle/assets/controllers/tooltips-controller.js
  core-bundle/assets/controllers/webauthn-error-controller.js
  core-bundle/assets/modules/turbo-stream-connection.js
  core-bundle/assets/modules/twig-editor.js
  core-bundle/public/backend.2359b448.js
  core-bundle/public/backend.2359b448.js.LICENSE.txt
  core-bundle/public/backend.e6de7ff8.js
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  package-lock.json
  package.json
Labels: CI

#8331 Deprecate the messenger priority interfaces in favor of the new `#[AsMessage]` attribute
  composer.json
  core-bundle/composer.json
  core-bundle/src/Messenger/Message/BackendSearch/DeleteDocumentsMessage.php
  core-bundle/src/Messenger/Message/BackendSearch/ReindexMessage.php
  core-bundle/src/Messenger/Message/HighPriorityMessageInterface.php
  core-bundle/src/Messenger/Message/LowPriorityMessageInterface.php
  core-bundle/src/Messenger/Message/NormalPriorityMessageInterface.php
  core-bundle/src/Messenger/Message/SearchIndexMessage.php
  manager-bundle/skeleton/config/config.yaml
Labels: feature

#8367 Handle union and intersection types when autoloading app services
  depcheck.php
  manager-bundle/skeleton/config/services.php
  manager-bundle/tests/Fixtures/HttpKernel/AutowireSrc/src/Entity/FooEntity.php
  manager-bundle/tests/Fixtures/HttpKernel/AutowireSrc/src/EventListener/InvalidListener.php
  manager-bundle/tests/Fixtures/HttpKernel/AutowireSrc/src/EventListener/ValidListener.php
  manager-bundle/tests/Fixtures/HttpKernel/AutowireSrc/src/FrontendModule/LegacyModule.php
  manager-bundle/tests/Fixtures/HttpKernel/AutowireSrc/src/Messenger/UnionTypeMessage.php
  manager-bundle/tests/Fixtures/HttpKernel/AutowireSrc/src/Model/FooModel.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
Labels: bug

#8369 Update the `template_name` color within the Template Studio
  core-bundle/assets/styles/template-studio/common.pcss
  core-bundle/public/backend.2aca84cf.css
  core-bundle/public/backend.53322f30.css
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug

#8375 Fix the unit tests on Windows
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
Labels: CI

#8365 Drop the `guests` column after migration
  core-bundle/src/Migration/Version500/AbstractGuestsMigration.php
Labels: bug

#8363 Check the member groups before excluding content from indexing
  core-bundle/contao/library/Contao/Controller.php
Labels: bug

#8376 Use `Path::join` instead of `Path::makeAbsolute`
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
Labels: bug

#8381 Add the missing autowiring alias for the `DcaUrlAnalyzer`
  core-bundle/config/services.yaml
Labels: bug

#8384 Fix the unit tests
  core-bundle/src/Security/Voter/BackendAccessVoter.php
  core-bundle/src/Security/Voter/BackendSearch/ProviderDelegatingVoter.php
  core-bundle/src/Security/Voter/DataContainer/AbstractDataContainerVoter.php
  core-bundle/src/Security/Voter/DataContainer/ContentCompositionVoter.php
  core-bundle/src/Security/Voter/DataContainer/DefaultDataContainerVoter.php
  core-bundle/src/Security/Voter/DataContainer/PagePermissionVoter.php
  core-bundle/src/Security/Voter/DataContainer/TableAccessVoter.php
  core-bundle/src/Security/Voter/MemberGroupVoter.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Filesystem/FileDownloadHelperTest.php
  core-bundle/tests/PhpunitExtension/GlobalStateWatcher.php
  core-bundle/tests/Search/Backend/Provider/FilesStorageProviderTest.php
  core-bundle/tests/Security/Authentication/FrontendPreviewAuthenticatorTest.php
Labels: CI

#8371 Always add the operations menu
  core-bundle/contao/templates/twig/backend/data_container/operations.html.twig
Labels: bug

#8366 Update to SEAL 0.9
  composer.json
  core-bundle/composer.json
  core-bundle/contao/classes/RebuildBackendSearchIndex.php
  core-bundle/src/Search/Backend/BackendSearch.php
  manager-bundle/composer.json
Labels: feature
