Repository contao/contao, pull requests merged in 2025-01, with the labels that each got.

#7789 Consider the `addImage` checkbox when collecting RSS enclosures
  news-bundle/src/EventListener/NewsFeedListener.php
  news-bundle/tests/EventListener/NewsFeedListenerTest.php
Labels: bug

#7798 Do not force HTTP method parameter override
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
Labels: bug, also affects 4.13

#7799 Introduce constants for paste into/after
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#7797 Ignore pages in maintenance mode when generating the sitemap
  core-bundle/src/Controller/SitemapController.php
Labels: bug, also affects 4.13

#7795 Remove empty locales in the meta wizard and add the primary language
  core-bundle/contao/widgets/MetaWizard.php
Labels: bug

#7827 Do not overwrite the current referrer with the table referrer
  core-bundle/contao/library/Contao/System.php
Labels: bug

#7832 Use the correct `_store_referrer` request attribute
  core-bundle/src/Controller/BackendController.php
Labels: bug

#7844 Update and run the tools
  core-bundle/tests/Functional/DcaUrlAnalyzerTest.php
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7845 Merge branch '5.3' into 5.4
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/Input.php
  core-bundle/contao/library/Contao/System.php
  core-bundle/contao/themes/flexible/backend.07c2aad1.css
  core-bundle/contao/themes/flexible/backend.5d714015.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/main.css
  core-bundle/contao/widgets/MetaWizard.php
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/DataContainer/DcaUrlAnalyzer.php
  core-bundle/src/DataContainer/RecordLabeler.php
  core-bundle/src/Event/DataContainerRecordLabelEvent.php
  core-bundle/src/EventListener/DataContainer/ContentRecordLabelListener.php
  core-bundle/src/EventListener/DataContainer/FallbackRecordLabelListener.php
  core-bundle/tests/DataContainer/RecordLabelerTest.php
  core-bundle/tests/Event/DataContainerRecordLabelEventTest.php
  core-bundle/tests/EventListener/DataContainer/ContentRecordLabelListenerTest.php
  core-bundle/tests/EventListener/DataContainer/FallbackRecordLabelListenerTest.php
  core-bundle/tests/Fixtures/Functional/DcaUrlAnalyzer/default.yaml
  core-bundle/tests/Fixtures/TranslatorStub.php
  core-bundle/tests/Functional/DcaUrlAnalyzerTest.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
  news-bundle/src/EventListener/NewsFeedListener.php
  news-bundle/tests/EventListener/NewsFeedListenerTest.php
  package-lock.json
Labels: release

#7841 Register folders, pages and nodes as tooltip targets
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/drivers/DC_Folder.php
Labels: bug

#7846 Update and run the tools
  core-bundle/tests/Functional/ServiceArgumentsTest.php
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7847 Merge branch '5.4' into 5.x
  core-bundle/config/services.yaml
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/dca/tl_article.php
  core-bundle/contao/dca/tl_form_field.php
  core-bundle/contao/dca/tl_page.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/library/Contao/Input.php
  core-bundle/contao/library/Contao/System.php
  core-bundle/contao/themes/flexible/backend.c3df78d6.css
  core-bundle/contao/themes/flexible/backend.cebd42dc.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/main.css
  core-bundle/contao/widgets/MetaWizard.php
  core-bundle/src/Controller/BackendController.php
  core-bundle/src/Controller/SitemapController.php
  core-bundle/src/DataContainer/DcaUrlAnalyzer.php
  core-bundle/src/EventListener/DataContainer/ContentRecordLabelListener.php
  core-bundle/tests/EventListener/DataContainer/FallbackRecordLabelListenerTest.php
  core-bundle/tests/Fixtures/Functional/DcaUrlAnalyzer/default.yaml
  core-bundle/tests/Functional/DcaUrlAnalyzerTest.php
  core-bundle/tests/Functional/ServiceArgumentsTest.php
  manager-bundle/src/HttpKernel/ContaoKernel.php
  manager-bundle/tests/HttpKernel/ContaoKernelTest.php
  news-bundle/src/EventListener/NewsFeedListener.php
  news-bundle/tests/EventListener/NewsFeedListenerTest.php
  package-lock.json
Labels: release

#7848 Update and run the tools
  core-bundle/contao/controllers/BackendMain.php
  core-bundle/src/Controller/BackendTemplateStudioController.php
  core-bundle/src/InsertTag/Resolver/LinkInsertTag.php
  core-bundle/src/Messenger/Message/BackendSearch/DeleteDocumentsMessage.php
  core-bundle/src/Messenger/Message/BackendSearch/ReindexMessage.php
  core-bundle/tests/Search/Backend/Seal/SealUtilTest.php
  package.json
  vendor-bin/ecs/composer.lock
  vendor-bin/isolated-tests/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7828 Remove `contao-components/colorpicker` from the dependency check
  depcheck.php
Labels: CI

#7830 Fix `$models` within `ContaoDataCollector` being `null`
  core-bundle/src/DataCollector/ContaoDataCollector.php
Labels: bug

#7829 Allow installing `scssphp/scssphp` version 2
  composer.json
  core-bundle/composer.json
Labels: feature

#7814 Pass on the information if a message has been triggered via the WebWorker
  core-bundle/src/Messenger/Message/BackendSearch/DeleteDocumentsMessage.php
  core-bundle/src/Messenger/Message/BackendSearch/ReindexMessage.php
  core-bundle/src/Messenger/Message/ScopeAwareMessageInterface.php
  core-bundle/src/Messenger/Message/ScopeAwareMessageTrait.php
  core-bundle/src/Messenger/MessageHandler/BackendSearch/DeleteDocumentsMessageHandler.php
  core-bundle/src/Messenger/MessageHandler/BackendSearch/ReindexMessageHandler.php
  core-bundle/src/Messenger/WebWorker.php
  core-bundle/tests/Messenger/MessageHandler/BackendSearch/DeleteDocumentsMessageHandlerTest.php
  core-bundle/tests/Messenger/MessageHandler/BackendSearch/ReindexMessageHandlerTest.php
  core-bundle/tests/Messenger/WebWorkerTest.php
Labels: feature

#7831 Use the `#[IsGranted]` PHP attribute in template studio controller
  core-bundle/src/Controller/BackendTemplateStudioController.php
Labels: feature

#7834 Allow setting a custom redirect route when unauthenticated
  core-bundle/src/Controller/BackendTemplateStudioController.php
  core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php
  core-bundle/tests/Security/Authenticator/ContaoLoginAuthenticatorTest.php
Labels: bug

#7837 Use stable SEAL versions
  composer.json
  core-bundle/composer.json
  manager-bundle/composer.json
Labels: feature

#7838 Make sure back end search related messages are never too big
  core-bundle/src/Search/Backend/BackendSearch.php
  core-bundle/src/Search/Backend/GroupedDocumentIds.php
  core-bundle/tests/Search/Backend/GroupedDocumentIdsTest.php
Labels: feature

#7850 Fix the SEAL index name
  core-bundle/src/DependencyInjection/ContaoCoreExtension.php
  core-bundle/src/Search/Backend/BackendSearch.php
  core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php
  core-bundle/tests/Search/Backend/BackendSearchTest.php
Labels: bug

#7851 Implement Flysystem default public URI support
  core-bundle/config/services.yaml
  core-bundle/src/Filesystem/PublicUri/FlysystemDefaultProvider.php
  core-bundle/tests/Filesystem/PublicUri/FlysystemDefaultProviderTest.php
  core-bundle/tests/Fixtures/FilesystemAdapterAndPublicUrlGeneratorInterface.php
Labels: feature

#7826 Split the `BackendMenuListener` class into two separate classes
  core-bundle/config/listener.yaml
  core-bundle/src/EventListener/Menu/BackendHeaderListener.php
  core-bundle/src/EventListener/Menu/BackendMainListener.php
  core-bundle/tests/EventListener/Menu/BackendHeaderListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendMainListenerTest.php
Labels: feature

#7855 Use the DBAFS manager in `DC_Folder`
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/src/Filesystem/ExtraMetadata.php
  core-bundle/tests/Filesystem/ExtraMetadataTest.php
Labels: bug

#7857 Remove an unnecessary line of code
  core-bundle/contao/drivers/DC_Folder.php
Labels: bug

#7835 Implement search invalidation on file storage DBAFS updates
  core-bundle/config/backend_search.yaml
  core-bundle/config/services.yaml
  core-bundle/src/Filesystem/Dbafs/DbafsChangeEvent.php
  core-bundle/src/Filesystem/Dbafs/DbafsManager.php
  core-bundle/src/Search/Backend/EventListener/TriggerReindexOnFilesStorageUpdateListener.php
  core-bundle/tests/Filesystem/Dbafs/DbafsChangeEventTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsManagerTest.php
  core-bundle/tests/Filesystem/VirtualFilesystemTest.php
  core-bundle/tests/Functional/DbafsTest.php
  core-bundle/tests/Search/Backend/EventListener/TriggerReindexOnFilesStorageUpdateListenerTest.php
  core-bundle/tests/Search/Backend/Provider/FilesStorageProviderTest.php
Labels: feature

#7860 Set `$dc->table` and `$dc->id` in the `FallbackRecordLabelListener`
  core-bundle/src/EventListener/DataContainer/FallbackRecordLabelListener.php
Labels: bug

#7867 Adjust the `ClipboardManager::set()` method signature
  core-bundle/src/DataContainer/ClipboardManager.php
Labels: bug

#7866 Vote on the document instead of the hit in the back end search
  core-bundle/src/Search/Backend/BackendSearch.php
  core-bundle/src/Search/Backend/Provider/FilesStorageProvider.php
  core-bundle/src/Search/Backend/Provider/ProviderInterface.php
  core-bundle/src/Search/Backend/Provider/TableDataContainerProvider.php
  core-bundle/src/Security/ContaoCorePermissions.php
  core-bundle/src/Security/Voter/BackendSearch/ProviderDelegatingVoter.php
  core-bundle/tests/Search/Backend/BackendSearchTest.php
  core-bundle/tests/Search/Backend/Provider/FilesStorageProviderTest.php
  core-bundle/tests/Security/Voter/BackendSearch/ProviderDelegatingVoterTest.php
Labels: bug

#7842 Add edit and view URLs for the back end search
  core-bundle/config/backend_search.yaml
  core-bundle/src/DataContainer/DcaUrlAnalyzer.php
  core-bundle/src/EventListener/DataContainer/ContentRecordLabelListener.php
  core-bundle/src/Search/Backend/Provider/FilesStorageProvider.php
  core-bundle/src/Search/Backend/Provider/TableDataContainerProvider.php
  core-bundle/tests/Search/Backend/Provider/FilesStorageProviderTest.php
  core-bundle/tests/Search/Backend/Provider/TableDataContainerProviderTest.php
Labels: feature

#7594 Rewrite `tl_panel` and `tl_subpanel` to `display: flex`
  core-bundle/contao/classes/DataContainer.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/themes/flexible/backend.196f7294.css
  core-bundle/contao/themes/flexible/backend.c3571a33.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/main.css
Labels: feature

#7824 Replace `Chosen` with `Choices.js`
  composer.json
  core-bundle/assets/backend.js
  core-bundle/assets/controllers/chosen-controller.js
  core-bundle/assets/scripts/choices.js
  core-bundle/assets/scripts/modulewizard.js
  core-bundle/composer.json
  core-bundle/contao/classes/BackendTemplateTrait.php
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/forms/FormSelect.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/templates/backend/be_main.html5
  core-bundle/contao/templates/twig/backend/template_studio/index.html.twig
  core-bundle/contao/widgets/ModuleWizard.php
  core-bundle/contao/widgets/RootPageDependentSelect.php
  core-bundle/contao/widgets/SelectMenu.php
  core-bundle/public/backend.37a12671.js
  core-bundle/public/backend.37a12671.js.LICENSE.txt
  core-bundle/public/backend.e09163f8.js
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/tests/Contao/RootPageDependentSelectTest.php
  depcheck.php
Labels: feature

#7853 Remove the ability to edit Twig templates in the old template editor
  core-bundle/config/listener.yaml
  core-bundle/config/services.yaml
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/languages/en/tl_templates.xlf
  core-bundle/src/EventListener/DataContainer/LegacyTemplatesListener.php
  core-bundle/src/Security/Voter/DataContainer/LegacyTemplatesVoter.php
  core-bundle/tests/EventListener/DataContainer/LegacyTemplatesListenerTest.php
Labels: bug

#7879 Update and run the tools
  .editorconfig
  core-bundle/src/DataContainer/DcaUrlAnalyzer.php
  vendor-bin/ecs/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
Labels: CI

#7815 Correctly handle fragment priority
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/GlobalsMapListener.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/EventListener/GlobalsMapListenerTest.php
Labels: bug

#7800 Increase blob size for `tl_user.session`
  core-bundle/contao/dca/tl_user.php
Labels: bug, also affects 4.13

#7865 Add `no-store` to back end responses
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/BackendTemplate.php
  core-bundle/src/EventListener/MakeBackendResponseUncacheableListener.php
  core-bundle/tests/EventListener/MakeBackendResponseUncacheableListenerTest.php
Labels: bug, also affects 4.13

#7415 Fix an error if a record in the clipboard is deleted before pasting
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#7874 Handle query parameters when generating download URLs
  core-bundle/src/Controller/ContentElement/AbstractDownloadContentElementController.php
  core-bundle/src/Filesystem/FileDownloadHelper.php
  core-bundle/tests/Filesystem/FileDownloadHelperTest.php
Labels: bug

#7801 Correctly render nested fragments with the `allowedTypes` option in the debug view
  core-bundle/src/Command/DebugFragmentsCommand.php
  core-bundle/tests/Command/DebugFragmentsCommandTest.php
Labels: bug

#7880 Ensure that `Widget::$arrOptions` is always an array
  core-bundle/contao/forms/FormCheckbox.php
  core-bundle/contao/forms/FormRadio.php
  core-bundle/contao/forms/FormSelect.php
  core-bundle/contao/widgets/CheckBox.php
  core-bundle/contao/widgets/CheckBoxWizard.php
  core-bundle/contao/widgets/ImageSize.php
  core-bundle/contao/widgets/InputUnit.php
  core-bundle/contao/widgets/RadioButton.php
  core-bundle/contao/widgets/RadioTable.php
  core-bundle/contao/widgets/SelectMenu.php
  core-bundle/contao/widgets/TimePeriod.php
  core-bundle/contao/widgets/TrblField.php
Labels: bug

#7793 Unwrap Twig exceptions
  core-bundle/src/EventListener/ExceptionConverterListener.php
  core-bundle/src/EventListener/UnwrapTwigExceptionListener.php
  core-bundle/src/Exception/InternalServerErrorHttpException.php
  core-bundle/tests/EventListener/UnwrapTwigExceptionListenerTest.php
Labels: bug

#7843 Fix dynamic Twig inheritance when in a theme context
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicUseTokenParser.php
  core-bundle/src/Twig/Inheritance/RuntimeThemeDependentExpression.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Fixtures/Twig/use/templates/theme/component/fruit_shake.html.twig
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Inheritance/DynamicExtendsTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/DynamicIncludeTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/RuntimeThemeDependentExpressionTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: bug

#7762 Show an error message when copying newsletter recipient records
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/languages/en/default.xlf
  newsletter-bundle/config/services.yaml
  newsletter-bundle/src/EventListener/NewsletterRecipientsEditButtonsListener.php
  newsletter-bundle/tests/EventListener/NewsletterRecipientsEditButtonsListenerTest.php
Labels: bug

#7889 Also persist theme slugs in the Twig hierarchy cache
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
Labels: bug

#7747 Enable double encoding for JSON in Twig
  core-bundle/src/Twig/Interop/ContaoEscaper.php
  core-bundle/src/Twig/Interop/ContaoEscaperNodeVisitor.php
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperNodeVisitorTest.php
  core-bundle/tests/Twig/Interop/ContaoEscaperTest.php
Labels: bug

#7756 Handle null result in 404 router provider
  core-bundle/src/Routing/Route404Provider.php
Labels: bug

#7766 Fix the sorting when copying multiple form fields as a non-admin user
  core-bundle/src/Resources/contao/dca/tl_form_field.php
Labels: bug

#7779 Do not normalize the `resampling-filter` array key
  core-bundle/src/DependencyInjection/Configuration.php
  core-bundle/tests/DependencyInjection/ConfigurationTest.php
Labels: bug

#7768 Fix the base path for canonical URLs
  core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php
Labels: bug

#7551 Handle DCAs without fields in `tl_user_group`
  core-bundle/src/Resources/contao/dca/tl_user_group.php
Labels: bug, unconfirmed

#7820 Add the domain to the "root page dependent module" configuration
  core-bundle/src/Resources/contao/languages/en/tl_module.xlf
  core-bundle/src/Resources/contao/widgets/RootPageDependentSelect.php
Labels: bug

#7563 Add the missing relations to the DCAs
  calendar-bundle/src/Resources/contao/dca/tl_calendar_feed.php
  calendar-bundle/src/Resources/contao/dca/tl_layout.php
  calendar-bundle/src/Resources/contao/dca/tl_module.php
  calendar-bundle/src/Resources/contao/dca/tl_user.php
  calendar-bundle/src/Resources/contao/dca/tl_user_group.php
  core-bundle/src/Resources/contao/dca/tl_content.php
  core-bundle/src/Resources/contao/dca/tl_user.php
  core-bundle/src/Resources/contao/dca/tl_user_group.php
  faq-bundle/src/Resources/contao/dca/tl_module.php
  faq-bundle/src/Resources/contao/dca/tl_user.php
  faq-bundle/src/Resources/contao/dca/tl_user_group.php
  news-bundle/src/Resources/contao/dca/tl_layout.php
  news-bundle/src/Resources/contao/dca/tl_module.php
  news-bundle/src/Resources/contao/dca/tl_news_feed.php
  news-bundle/src/Resources/contao/dca/tl_user.php
  news-bundle/src/Resources/contao/dca/tl_user_group.php
  newsletter-bundle/src/Resources/contao/dca/tl_member.php
  newsletter-bundle/src/Resources/contao/dca/tl_module.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_deny_list.php
  newsletter-bundle/src/Resources/contao/dca/tl_user.php
  newsletter-bundle/src/Resources/contao/dca/tl_user_group.php
Labels: bug

#7770 Disable `overlayClick` for SimpleModal
  core-bundle/src/Resources/public/core.js
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/mootao.min.js
Labels: bug

#7809 Make sure the correct test-case package is installed in Contao
  test-case/composer.json
Labels: bug

#7876 Ignore pages in maintenance mode when generating the sitemap
  core-bundle/src/Controller/SitemapController.php
Labels: bug

#7883 Increase blob size for `tl_user.session`
  core-bundle/src/Resources/contao/dca/tl_user.php
Labels: bug

#7891 Merge branch '5.3' into 5.4
  core-bundle/config/listener.yaml
  core-bundle/contao/classes/BackendTemplate.php
  core-bundle/contao/dca/tl_user.php
  core-bundle/contao/dca/tl_user_group.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/forms/FormCheckbox.php
  core-bundle/contao/forms/FormRadio.php
  core-bundle/contao/forms/FormSelect.php
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/widgets/CheckBox.php
  core-bundle/contao/widgets/CheckBoxWizard.php
  core-bundle/contao/widgets/ImageSize.php
  core-bundle/contao/widgets/InputUnit.php
  core-bundle/contao/widgets/RadioButton.php
  core-bundle/contao/widgets/RadioTable.php
  core-bundle/contao/widgets/SelectMenu.php
  core-bundle/contao/widgets/TimePeriod.php
  core-bundle/contao/widgets/TrblField.php
  core-bundle/src/Command/DebugFragmentsCommand.php
  core-bundle/src/Controller/ContentElement/AbstractDownloadContentElementController.php
  core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php
  core-bundle/src/EventListener/DataContainer/FallbackRecordLabelListener.php
  core-bundle/src/EventListener/GlobalsMapListener.php
  core-bundle/src/EventListener/MakeBackendResponseUncacheableListener.php
  core-bundle/src/Filesystem/FileDownloadHelper.php
  core-bundle/src/Migration/Version503/FileExtensionMigration.php
  core-bundle/src/Twig/Extension/ContaoExtension.php
  core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php
  core-bundle/src/Twig/Inheritance/DynamicUseTokenParser.php
  core-bundle/src/Twig/Inheritance/RuntimeThemeDependentExpression.php
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Command/DebugFragmentsCommandTest.php
  core-bundle/tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php
  core-bundle/tests/EventListener/GlobalsMapListenerTest.php
  core-bundle/tests/EventListener/MakeBackendResponseUncacheableListenerTest.php
  core-bundle/tests/Filesystem/FileDownloadHelperTest.php
  core-bundle/tests/Fixtures/Twig/use/templates/theme/component/fruit_shake.html.twig
  core-bundle/tests/Twig/Extension/ContaoExtensionTest.php
  core-bundle/tests/Twig/Inheritance/DynamicExtendsTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/DynamicIncludeTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/DynamicUseTokenParserTest.php
  core-bundle/tests/Twig/Inheritance/RuntimeThemeDependentExpressionTest.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
  newsletter-bundle/config/services.yaml
  newsletter-bundle/src/EventListener/NewsletterRecipientsEditButtonsListener.php
  newsletter-bundle/tests/EventListener/NewsletterRecipientsEditButtonsListenerTest.php
Labels: release

#7886 Improve handling of Turbo stream requests when unauthenticated
  core-bundle/config/services.yaml
  core-bundle/contao/templates/twig/backend/reload.stream.html.twig
  core-bundle/src/Controller/BackendTemplateStudioController.php
  core-bundle/src/EventListener/ExceptionConverterListener.php
  core-bundle/src/EventListener/UnwrapTwigExceptionListener.php
  core-bundle/src/Exception/InternalServerErrorHttpException.php
  core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php
  core-bundle/tests/EventListener/UnwrapTwigExceptionListenerTest.php
  core-bundle/tests/Security/Authenticator/ContaoLoginAuthenticatorTest.php
Labels: bug

#7460 Check if `CURRENT_ID` is defined in the DCA permission checks
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
Labels: bug

#7781 Allow page controllers to create the response context
  core-bundle/src/Resources/config/services.yml
  core-bundle/src/Resources/contao/pages/PageRegular.php
Labels: bug

#7894 Run the tools and rebuild the assets
  calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php
  core-bundle/src/Resources/contao/classes/BackendTemplate.php
  core-bundle/src/Resources/contao/dca/tl_form_field.php
  core-bundle/src/Resources/public/core.min.js
  core-bundle/src/Resources/public/mootao.min.js
  faq-bundle/src/Resources/contao/dca/tl_faq.php
  news-bundle/src/Resources/contao/dca/tl_news.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php
  newsletter-bundle/src/Resources/contao/dca/tl_newsletter_recipients.php
  package-lock.json
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/require-checker/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#7898 Fix variadic parameters with string keys
  core-bundle/src/EventListener/GlobalsMapListener.php
  core-bundle/src/Framework/ContaoFramework.php
Labels: bug

#7904 Add custom template settings for the feed reader module
  core-bundle/contao/dca/tl_module.php
Labels: bug

#7899 Fix tree rendering with filters and trails
  core-bundle/contao/classes/Backend.php
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#7872 Fix tree rendering with filters and trails
  core-bundle/src/Resources/contao/classes/Backend.php
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#7903 Fix a small formatting issue in the Template Studio
  core-bundle/contao/templates/twig/backend/template_studio/operation/save_result.stream.html.twig
Labels: bug

#7909 Revert the changes to `FormSelect` regarding `Chosen`
  core-bundle/contao/forms/FormSelect.php
Labels: bug

#7914 Make the Twig inspector aware of the `RuntimeThemeExpression`
  core-bundle/src/Twig/Inspector/InspectorNodeVisitor.php
  core-bundle/tests/Twig/Inspector/ContaoInspectorNodeVisitorTest.php
  core-bundle/tests/Twig/Inspector/InspectorNodeVisitorTest.php
Labels: bug

#7916 Inline the operations and picker
  core-bundle/contao/themes/flexible/backend.c10bed19.css
  core-bundle/contao/themes/flexible/entrypoints.json
  core-bundle/contao/themes/flexible/manifest.json
  core-bundle/contao/themes/flexible/styles/main.css
Labels: bug

#7901 Fix the Choices.js initialization
  core-bundle/assets/backend.js
  core-bundle/assets/controllers/choices-controller.js
  core-bundle/contao/dca/tl_templates.php
  core-bundle/contao/drivers/DC_Folder.php
  core-bundle/contao/drivers/DC_Table.php
  core-bundle/contao/templates/twig/backend/template_studio/index.html.twig
  core-bundle/contao/widgets/ModuleWizard.php
  core-bundle/contao/widgets/RootPageDependentSelect.php
  core-bundle/contao/widgets/SelectMenu.php
  core-bundle/public/backend.57d411c6.js
  core-bundle/public/backend.57d411c6.js.LICENSE.txt
  core-bundle/public/backend.ccfd910f.js
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
  core-bundle/tests/Contao/RootPageDependentSelectTest.php
  package-lock.json
Labels: bug

#7922 Do not prefetch the "switch user" URLs
  core-bundle/contao/dca/tl_member.php
  core-bundle/contao/dca/tl_user.php
Labels: bug

#7929 Fix permission error in non-tree views
  core-bundle/src/Resources/contao/drivers/DC_Table.php
Labels: bug

#7939 Do not use `DC_Table::generateRecordLabel()` for breadcrumbs
  core-bundle/src/EventListener/DataContainer/FallbackRecordLabelListener.php
  core-bundle/tests/EventListener/DataContainer/FallbackRecordLabelListenerTest.php
  core-bundle/tests/Fixtures/Functional/DcaUrlAnalyzer/default.yaml
  core-bundle/tests/Functional/DcaUrlAnalyzerTest.php
Labels: bug

#7943 Fix a bug with unknown insert tag end names
  core-bundle/src/InsertTag/InsertTagParser.php
  core-bundle/tests/InsertTag/InsertTagParserTest.php
Labels: bug

#7945 Fix the download mime type
  core-bundle/src/Filesystem/FileDownloadHelper.php
  core-bundle/tests/Filesystem/FileDownloadHelperTest.php
Labels: bug

#7950 Update the language key for the confirm action
  core-bundle/contao/languages/en/default.xlf
  core-bundle/contao/templates/twig/backend/template_studio/_dialog.html.twig
Labels: bug

#7920 Improve the `TemplateLocator` performance
  core-bundle/src/Twig/Loader/TemplateLocator.php
Labels: bug

#7970 Correctly add the Template Studio menu item
  core-bundle/config/listener.yaml
  core-bundle/contao/languages/en/modules.xlf
  core-bundle/src/EventListener/Menu/BackendMainListener.php
  core-bundle/src/EventListener/Menu/BackendTemplateStudioListener.php
  core-bundle/tests/EventListener/Menu/BackendMainListenerTest.php
  core-bundle/tests/EventListener/Menu/BackendTemplateStudioListenerTest.php
Labels: bug

#7982 Prevent useless DB queries in the `CommandSchedulerListener`
  core-bundle/src/EventListener/CommandSchedulerListener.php
Labels: bug

#7977 Fix using numeric theme/identifier names in the `ContaoFilesystemLoader`
  core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php
  core-bundle/tests/Twig/Loader/ContaoFilesystemLoaderTest.php
Labels: bug

#7974 Hide the context menu when empty
  core-bundle/contao/templates/twig/backend/data_container/operations.html.twig
Labels: bug

#7966 Fix adding new articles after an existing article
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#7988 Set `defaultSearchField` for `tl_page` to `title`
  core-bundle/contao/dca/tl_page.php
Labels: bug

#7986 Add missing `ref` for edit profile redirect
  core-bundle/contao/controllers/BackendMain.php
  core-bundle/src/EventListener/Menu/BackendMenuListener.php
  core-bundle/tests/EventListener/Menu/BackendMenuListenerTest.php
Labels: bug, also affects 4.13
