Repository contao/contao, pull requests merged in 2025-04, with the labels that each got.

#8254 Correctly initialize the CAPTCHA widget
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModuleRegistration.php
  newsletter-bundle/contao/modules/ModuleSubscribe.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
Labels: bug

#8256 Fix the fallback `FormCaptcha` namespace
  core-bundle/contao/modules/ModuleLostPassword.php
  core-bundle/contao/modules/ModuleRegistration.php
Labels: bug

#8257 Rewrite the SERP widget to a Stimulus controller
  core-bundle/assets/controllers/serp-preview-controller.js
  core-bundle/assets/controllers/tinymce-controller.js
  core-bundle/assets/scripts/mootao.js
  core-bundle/contao/templates/twig/backend/widget/serp_preview.html.twig
  core-bundle/contao/widgets/SerpPreview.php
  core-bundle/public/backend.232edeb1.js
  core-bundle/public/backend.232edeb1.js.LICENSE.txt
  core-bundle/public/backend.8a843a04.js
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: feature

#7678 Unify the autoloader in CLI scripts
  manager-bundle/bin/contao-api
  manager-bundle/bin/contao-setup
Labels: bug

#8233 Make the `OrderFieldMigration` available for third-party developers
  core-bundle/src/Migration/Version500/AbstractOrderFieldMigration.php
  core-bundle/src/Migration/Version500/OrderFieldMigration.php
Labels: bug

#8263 Do not override page requirements and defaults
  core-bundle/src/Routing/Page/PageRegistry.php
Labels: bug

#8240 Do not use the title attribute in the download content elements
  core-bundle/contao/templates/twig/component/_download.html.twig
  core-bundle/src/Controller/ContentElement/DownloadsController.php
  core-bundle/tests/Controller/ContentElement/ContentElementTestCase.php
  core-bundle/tests/Controller/ContentElement/DownloadsControllerTest.php
Labels: bug

#8265 Show all search results in tree mode
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#8275 Remove redundant code
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#8270 Fix page sorting with same languages across domains
  core-bundle/src/Routing/AbstractPageRouteProvider.php
  core-bundle/tests/Fixtures/Functional/Routing/multidomain-languages.yaml
  core-bundle/tests/Functional/RoutingTest.php
Labels: bug

#8278 Update and run the tools
  core-bundle/contao/modules/ModuleBreadcrumb.php
  package-lock.json
  vendor-bin/ecs/composer.lock
  vendor-bin/monorepo-tools/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/service-linter/composer.lock
Labels: CI

#8282 Fix the model phpDocs
  calendar-bundle/contao/models/CalendarEventsModel.php
  calendar-bundle/contao/models/CalendarFeedModel.php
  calendar-bundle/contao/models/CalendarModel.php
  comments-bundle/contao/models/CommentsModel.php
  comments-bundle/contao/models/CommentsNotifyModel.php
  core-bundle/contao/library/Contao/Model/Collection.php
  core-bundle/contao/models/ArticleModel.php
  core-bundle/contao/models/ContentModel.php
  core-bundle/contao/models/FilesModel.php
  core-bundle/contao/models/FormFieldModel.php
  core-bundle/contao/models/FormModel.php
  core-bundle/contao/models/ImageSizeItemModel.php
  core-bundle/contao/models/ImageSizeModel.php
  core-bundle/contao/models/LayoutModel.php
  core-bundle/contao/models/MemberGroupModel.php
  core-bundle/contao/models/MemberModel.php
  core-bundle/contao/models/ModuleModel.php
  core-bundle/contao/models/OptInModel.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/models/ThemeModel.php
  core-bundle/contao/models/UserGroupModel.php
  core-bundle/contao/models/UserModel.php
  faq-bundle/contao/models/FaqCategoryModel.php
  faq-bundle/contao/models/FaqModel.php
  news-bundle/contao/models/NewsArchiveModel.php
  news-bundle/contao/models/NewsModel.php
  newsletter-bundle/contao/models/NewsletterChannelModel.php
  newsletter-bundle/contao/models/NewsletterDenyListModel.php
  newsletter-bundle/contao/models/NewsletterModel.php
  newsletter-bundle/contao/models/NewsletterRecipientsModel.php
Labels: bug

#8311 Remove `@internal` from services that are not internal
  core-bundle/contao/library/Contao/Database.php
  core-bundle/src/Asset/ContaoContext.php
  core-bundle/src/Framework/Adapter.php
  core-bundle/src/Framework/ContaoFramework.php
  vendor-bin/ecs/composer.lock
  vendor-bin/phpstan/composer.lock
  vendor-bin/rector/composer.lock
Labels: CI

#8305 Fix binary UUIDs in the back end search results
  core-bundle/config/backend_search.yaml
  core-bundle/src/Search/Backend/EventListener/FormatBinaryUuidSearchResultsListener.php
  core-bundle/tests/Search/Backend/EventListener/FormatBinaryUuidSearchResultsListenerTest.php
Labels: bug, feature

#8309 Use the module ID for flash bag variables in the newsletter modules
  newsletter-bundle/contao/modules/ModuleSubscribe.php
  newsletter-bundle/contao/modules/ModuleUnsubscribe.php
Labels: bug

#8307 Throw an exception on backup errors
  core-bundle/src/Doctrine/Backup/BackupManager.php
Labels: bug

#8292 Set status code 422 for widget errors in `AbstractBackendController::render()`
  core-bundle/contao/controllers/BackendMain.php
  core-bundle/src/Controller/AbstractBackendController.php
  core-bundle/tests/Controller/AbstractBackendControllerTest.php
Labels: bug

#8321 Adjust the SQL formatting
  calendar-bundle/src/Migration/KeepCanonicalMigration.php
  calendar-bundle/src/Security/Voter/CalendarContentVoter.php
  calendar-bundle/tests/Security/Voter/CalendarContentVoterTest.php
  core-bundle/contao/library/Contao/Database.php
  core-bundle/contao/library/Contao/Database/Statement.php
  core-bundle/contao/library/Contao/Model.php
  core-bundle/contao/library/Contao/Model/QueryBuilder.php
  core-bundle/contao/models/PageModel.php
  core-bundle/src/Controller/BackendPreviewSwitchController.php
  core-bundle/src/Controller/PreviewLinkController.php
  core-bundle/src/Cors/WebsiteRootsConfigProvider.php
  core-bundle/src/EventListener/DataContainer/BackendFavoritesListener.php
  core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php
  core-bundle/src/EventListener/DataContainer/CteAliasListener.php
  core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php
  core-bundle/src/EventListener/DataContainer/FrontendModulePermissionsListener.php
  core-bundle/src/EventListener/DataContainer/LayoutOptionsListener.php
  core-bundle/src/EventListener/DataContainer/MemberGroupsListener.php
  core-bundle/src/EventListener/DataContainer/PageSearchListener.php
  core-bundle/src/EventListener/DataContainer/PageUrlListener.php
  core-bundle/src/EventListener/DataContainer/PreviewLinkListener.php
  core-bundle/src/EventListener/DataContainer/Undo/JumpToParentOperationListener.php
  core-bundle/src/EventListener/LanguageFallbackWarningListener.php
  core-bundle/src/EventListener/Widget/RootPageDependentSelectListener.php
  core-bundle/src/Filesystem/Dbafs/Dbafs.php
  core-bundle/src/Image/ImageSizes.php
  core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php
  core-bundle/src/Migration/Version500/AbstractGuestsMigration.php
  core-bundle/src/Migration/Version500/AbstractOrderFieldMigration.php
  core-bundle/src/Migration/Version500/EmptyPtableMigration.php
  core-bundle/src/Migration/Version502/AlwaysForwardMigration.php
  core-bundle/src/Migration/Version503/FrontendModulesMigration.php
  core-bundle/src/Migration/Version503/RememberMeMigration.php
  core-bundle/src/Routing/Candidates/PageCandidates.php
  core-bundle/src/Routing/Page/PageRegistry.php
  core-bundle/src/Routing/RouteProvider.php
  core-bundle/src/Security/Authentication/Token/TokenChecker.php
  core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php
  core-bundle/src/Security/Voter/DataContainer/ArticleContentVoter.php
  core-bundle/src/Security/Voter/DataContainer/ContentElementNestingVoter.php
  core-bundle/src/Security/Voter/DataContainer/PageTypeAccessVoter.php
  core-bundle/tests/Contao/Database/StatementTest.php
  core-bundle/tests/Contao/PageModelTest.php
  core-bundle/tests/Controller/PreviewLinkControllerTest.php
  core-bundle/tests/EventListener/DataContainer/BackendFavoritesListenerTest.php
  core-bundle/tests/EventListener/DataContainer/ContentCompositionListenerTest.php
  core-bundle/tests/EventListener/DataContainer/LayoutOptionsListenerTest.php
  core-bundle/tests/EventListener/DataContainer/MemberGroupsListenerTest.php
  core-bundle/tests/EventListener/DataContainer/PageSearchListenerTest.php
  core-bundle/tests/EventListener/DataContainer/PageUrlListenerTest.php
  core-bundle/tests/Filesystem/Dbafs/DbafsTest.php
  core-bundle/tests/Functional/RoutingTest.php
  core-bundle/tests/Routing/Page/PageRegistryTest.php
  core-bundle/tests/Security/Voter/DataContainer/ArticleContentVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/ContentElementNestingVoterTest.php
  news-bundle/src/Migration/KeepCanonicalMigration.php
  news-bundle/src/Security/Voter/NewsContentVoter.php
  news-bundle/tests/Security/Voter/NewsContentVoterTest.php
  test-case/src/FunctionalTestCase.php
Labels: CI
