Repository contao/contao, pull requests merged in 2025-08, with the labels that each got.

#8612 Remove a superfluous `"` in the `data-action` attribute of the `be_main` template
  core-bundle/contao/templates/backend/be_main.html5
Labels: bug

#8648 Fix an SQL error when disabling subscribed members
  newsletter-bundle/contao/classes/Newsletter.php
Labels: bug

#8611 Fix a type error in the `tinymce-controller.js`
  core-bundle/assets/controllers/tinymce-controller.js
  core-bundle/public/backend.29cf27ea.js
  core-bundle/public/backend.5bd5a208.js
  core-bundle/public/backend.5bd5a208.js.LICENSE.txt
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: feature

#8609 Remove the `ClipboardManager` class constant
  core-bundle/contao/drivers/DC_Table.php
Labels: bug

#8358 Fix an undefined index error for `href` in the news menu template
  news-bundle/contao/templates/modules/mod_newsmenu.html5
Labels: bug

#8654 Allow version 2 of `guzzlehttp/promises`
  composer.json
  core-bundle/composer.json
Labels: bug

#8655 Merge branch '5.3' into 5.5
  calendar-bundle/contao/dca/tl_calendar_feed.php
  composer.json
  core-bundle/composer.json
  core-bundle/contao/dca/tl_module.php
  core-bundle/contao/library/Contao/TemplateTrait.php
  core-bundle/contao/models/PageModel.php
  core-bundle/contao/templates/analytics/analytics_google.html5
  core-bundle/contao/templates/analytics/analytics_matomo.html5
  core-bundle/contao/templates/elements/ce_vimeo.html5
  core-bundle/contao/templates/elements/ce_youtube.html5
  core-bundle/contao/templates/forms/form_wrapper.html5
  core-bundle/contao/templates/jquery/j_accordion.html5
  core-bundle/contao/templates/jquery/j_colorbox.html5
  core-bundle/contao/templates/jquery/j_tablesort.html5
  core-bundle/contao/templates/js/js_accordion.html5
  core-bundle/contao/templates/js/js_autofocus.html5
  core-bundle/contao/templates/js/js_nocookie.html5
  core-bundle/contao/templates/js/js_slider.html5
  core-bundle/contao/templates/mootools/moo_accordion.html5
  core-bundle/contao/templates/mootools/moo_chosen.html5
  core-bundle/contao/templates/mootools/moo_mediabox.html5
  core-bundle/contao/templates/mootools/moo_tablesort.html5
  core-bundle/src/Security/User/UserChecker.php
  core-bundle/tests/Twig/FragmentTemplateTest.php
  news-bundle/contao/templates/modules/mod_newsmenu.html5
  newsletter-bundle/contao/classes/Newsletter.php
  newsletter-bundle/contao/dca/tl_module.php
  newsletter-bundle/contao/dca/tl_newsletter_recipients.php
Labels: release

#8607 Fix a wrong Swiper option
  core-bundle/src/Controller/ContentElement/SwiperController.php
  core-bundle/tests/Controller/ContentElement/SwiperControllerTest.php
Labels: bug

#8660 Bump `enshrined/svg-sanitize` to version 0.22
  composer.json
  core-bundle/composer.json
Labels: bug

#8662 Update `enshrined/svg-sanitize` to version 0.22
  composer.json
  core-bundle/composer.json
Labels: bug

#8661 Fix a typo in `page/regular.html.twig`
  core-bundle/contao/templates/twig/page/regular.html.twig
Labels: feature

#8663 Do not make the new Twig layouts the default
  core-bundle/contao/dca/tl_layout.php
  core-bundle/contao/languages/en/tl_layout.xlf
Labels: bug

#8664 Fix an undefined array key warning in the `AbstractLayoutPageController`
  core-bundle/src/Controller/Page/AbstractLayoutPageController.php
Labels: bug

#8636 Fix the record fallback label
  core-bundle/src/EventListener/DataContainer/FallbackRecordLabelListener.php
  core-bundle/tests/EventListener/DataContainer/FallbackRecordLabelListenerTest.php
Labels: bug

#8666 Add the page class to the body element
  core-bundle/contao/templates/twig/page/regular.html.twig
Labels: bug

#8675 Check for main request in the `PreviewToolbarListener`
  core-bundle/src/EventListener/PreviewToolbarListener.php
Labels: bug

#8698 Fix the invalid permission check in `tl_content`
  core-bundle/src/DataContainer/DynamicPtableTrait.php
Labels: bug

#8701 Check undefined global `objPage`
  core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php
Labels: bug

#8700 A completed job must always be set to 100% progress
  core-bundle/src/Job/Job.php
  core-bundle/tests/Job/JobTest.php
Labels: bug

#8715 Restore the previous `autoFocus` when navigating with Turbo Drive
  core-bundle/assets/controllers/scroll-offset-controller.js
  core-bundle/public/backend.608cae71.js
  core-bundle/public/backend.62f4a1fe.js
  core-bundle/public/backend.62f4a1fe.js.LICENSE.txt
  core-bundle/public/backend.7bfa2107.css
  core-bundle/public/entrypoints.json
  core-bundle/public/manifest.json
Labels: bug

#8580 Add the group index and count to events
  calendar-bundle/contao/modules/ModuleEventlist.php
Labels: bug

#8726 Allow to create a user without a request
  core-bundle/contao/library/Contao/User.php
Labels: bug

#8729 Do not use the request locale in the `Countries` and `Locales` classes
  core-bundle/config/services.yaml
  core-bundle/src/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPass.php
  core-bundle/src/Intl/Countries.php
  core-bundle/src/Intl/Locales.php
  core-bundle/tests/DependencyInjection/Compiler/IntlInstalledLocalesAndCountriesPassTest.php
  core-bundle/tests/Intl/CountriesTest.php
  core-bundle/tests/Intl/LocalesTest.php
Labels: bug

#8727 Deprecate some user variables
  core-bundle/contao/classes/BackendUser.php
  core-bundle/contao/classes/FrontendUser.php
  core-bundle/contao/library/Contao/User.php
Labels: bug

#8741 Add an ID to the CAPTCHA in the registration form
  core-bundle/contao/modules/ModuleRegistration.php
Labels: bug

#8747 Correctly handle non-array DCA operation labels
  core-bundle/src/DataContainer/AbstractDataContainerOperationsBuilder.php
Labels: bug

#8749 Fix the CI chain
  core-bundle/src/Security/Voter/DataContainer/ArticleContentVoter.php
  core-bundle/src/Security/Voter/DataContainer/PageTypeAccessVoter.php
  core-bundle/tests/Security/Voter/DataContainer/ArticleContentVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/PagePermissionVoterTest.php
  core-bundle/tests/Security/Voter/DataContainer/TableAccessVoterTest.php
Labels: CI
